Repository planetarium/libplanet, pull requests merged in 2019-02, with the labels that each got.

#54 Make Hashcash to generate nonces using System.Random
  Libplanet.Tests/Blocks/BlockFixture.cs
  Libplanet.Tests/TestUtils.cs
  Libplanet/Hashcash.cs
Labels: enhancement

#52 Overall build/release automation
  .travis.yml
  Docs/api/.gitignore
  Docs/build.ps1
  Docs/publish.sh
  Libplanet/Libplanet.csproj
  README.md
  azure-pipelines.yml
  publish.sh
Labels: enhancement

#56 More NuGet metadata
  Libplanet/Libplanet.csproj
  publish.sh
Labels: enhancement

#55 Pass a context including Random object to IAction.Execute() method
  Libplanet.Tests/Action/ActionContextTest.cs
  Libplanet.Tests/Common/Action/Attack.cs
  Libplanet.Tests/Common/Action/BaseAction.cs
  Libplanet.Tests/Common/Action/DummyAction.cs
  Libplanet.Tests/Common/Action/Sleep.cs
  Libplanet.Tests/TestUtils.cs
  Libplanet/Action/ActionContext.cs
  Libplanet/Action/IAction.cs
  Libplanet/Action/IActionContext.cs
  Libplanet/Action/IRandom.cs
  Libplanet/Action/Random.cs
  Libplanet/Blockchain.cs
Labels: enhancement

#57 Move all parameters of IAction.Execute to IActionContext
  Libplanet.Tests/Action/ActionContextTest.cs
  Libplanet.Tests/Common/Action/Attack.cs
  Libplanet.Tests/Common/Action/BaseAction.cs
  Libplanet.Tests/Common/Action/DummyAction.cs
  Libplanet.Tests/Common/Action/Sleep.cs
  Libplanet/Action/ActionContext.cs
  Libplanet/Action/IAction.cs
  Libplanet/Action/IActionContext.cs
  Libplanet/Blockchain.cs
Labels: enhancement

#62 Turn packages only for development into private assets
  Libplanet/Libplanet.csproj
Labels: enhancement

#68 PrivateKey docs: disambiguate words and provide more helpful links
  Libplanet/Crypto/PrivateKey.cs
Labels: bug

#59 Add Swarm.BroadcastBlocksAsync()
  Libplanet.Tests/BlockchainTest.cs
  Libplanet.Tests/Net/SwarmTest.cs
  Libplanet.Tests/Store/FileStoreTest.cs
  Libplanet/Blockchain.cs
  Libplanet/Net/Swarm.cs
  Libplanet/Store/BaseStore.cs
  Libplanet/Store/FileStore.cs
  Libplanet/Store/IStore.cs
Labels: suggestion

#80 API docs for Libplanet.Tx namespace and some adjustments
  Libplanet.Tests/Tx/TransactionTest.cs
  Libplanet.Tests/Tx/TxIdTest.cs
  Libplanet/Store/FileStore.cs
  Libplanet/Tx/InvalidTxException.cs
  Libplanet/Tx/InvalidTxIdException.cs
  Libplanet/Tx/InvalidTxPublicKeyException.cs
  Libplanet/Tx/InvalidTxSignatureException.cs
  Libplanet/Tx/Transaction.cs
  Libplanet/Tx/TxId.cs
Labels: bug

#90 Awaiting method to ensure a Swarm instance is running
  Libplanet.Tests/Net/SwarmTest.cs
  Libplanet/Net/Swarm.cs
Labels: bug

#92 Prevent AppDomain to workaround Xunit's fatal error on Mono
  Libplanet.Tests/Libplanet.Tests.csproj
  Libplanet.Tests/xunit.runner.mono.json
Labels: bug
