Repository planetarium/libplanet, pull requests merged in 2020-10, with the labels that each got.

#1016 Do not store null state
  Libplanet.Tests/Store/Trie/TrieTest.cs
  Libplanet/Store/Trie/ITrie.cs
  Libplanet/Store/Trie/MerkleTrie.cs
Labels: bug, storage

#1023 Collect different nodes between two state root hashes
  CHANGES.md
  Libplanet.Tests/Store/Trie/MerkleTrieExtensionsTest.cs
  Libplanet.Tests/Store/Trie/MerkleTrieTest.cs
  Libplanet.Tools/Configuration/MptConfiguration.cs
  Libplanet.Tools/Configuration/ToolConfiguration.cs
  Libplanet.Tools/ICoconaLiteServiceCollectionExtensions.cs
  Libplanet.Tools/IConfigurationService.cs
  Libplanet.Tools/JsonConfigurationService.cs
  Libplanet.Tools/Libplanet.Tools.csproj
  Libplanet.Tools/Mpt.cs
  Libplanet.Tools/Program.cs
  Libplanet/Store/Trie/ITrie.cs
  Libplanet/Store/Trie/MerkleTrie.cs
  Libplanet/Store/Trie/MerkleTrieExtensions.cs
  Libplanet/Store/Trie/Nodes/INode.cs
Labels: storage, tools

#1026 Export all states as JSON
  CHANGES.md
  Libplanet.Tests/ImmutableArrayEqualityComparer.cs
  Libplanet.Tests/Store/Trie/MerkleTrieExtensionsTest.cs
  Libplanet.Tools/Mpt.cs
  Libplanet/Store/Trie/MerkleTrieExtensions.cs
Labels: storage, tools

#1033 test: fix TestUtils.GetRandomBytes
  Libplanet.Tests/TestUtils.cs
Labels: bug

#1036 fix(cli): fix an issue from deserialization
  Libplanet.Tools/Configuration/MptConfiguration.cs
  Libplanet.Tools/Configuration/ToolConfiguration.cs
  Libplanet.Tools/JsonConfigurationService.cs
Labels: bug

#1038 Fix broken unittests on ar_SA
  Libplanet.Tests/Blocks/BlockTest.cs
Labels: bug

#1040 Fix preloading bug
  Libplanet.Tests/Blockchain/BlockChainTest.ValidateNextBlock.cs
  Libplanet/Blockchain/BlockChain.cs
Labels: bug, consensus

#1024 Remove sonar analyzer surpressions
  Libplanet.Tests.ruleset
  Libplanet.Tests/Common/Action/BattleResult.cs
  Libplanet.Tests/HashDigestTest.cs
  Libplanet.Tests/Store/StoreFixture.cs
  Libplanet.ruleset
  Libplanet/Assets/FungibleAssetValue.cs
  Libplanet/Blocks/InvalidBlockException.cs
  Libplanet/HashDigest.cs
  Libplanet/KeyStore/KeyStoreException.cs
  Libplanet/Net/Protocols/RoutingTable.cs
  Libplanet/Store/DefaultStore.cs
  Libplanet/Store/Trie/Nodes/BaseNode.cs
  Libplanet/Tx/Transaction.cs
Labels: hacktoberfest-accepted

#1044 docs: improve arguments' description of `mpt` subcommand
  Libplanet.Tools/Mpt.cs
Labels: tools

#1049 Releasing guide
  .azure-pipelines/dotnet-core.yml
  .azure-pipelines/mono.yml
  .github/workflows/check-build.yaml
  .vscode/settings.json
  CHANGES.md
  CONTRIBUTING.md
  Docs/docfx.json
  Docs/theme/styles/main.css
  Libplanet.sln.DotSettings
  RELEASE.md
  hooks/check-changelog
  hooks/check-projects
Labels: docs

#1032 feat(mpt): log state root hash also when an action throws exception
  CHANGES.md
  Libplanet.Tests/Action/UnexpectedlyTerminatedActionExceptionTest.cs
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet/Action/ActionEvaluation.cs
  Libplanet/Action/UnexpectedlyTerminatedActionException.cs
  Libplanet/Blockchain/BlockEvaluator.cs
  Libplanet/Blocks/Block.cs
  Libplanet/Tx/Transaction.cs
Labels: bug

#1057 9C hotfix: Multiplex the order of staged transactions
  Libplanet.Tests/Blockchain/BlockChainTest.Internals.cs
  Libplanet/Blockchain/BlockChain.cs
Labels: bug
