Repository planetarium/libplanet, pull requests merged in 2020-01, with the labels that each got.

#759 Fix a bug to have invalid state references cache
  CHANGES.md
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet/Store/DefaultStore.cs
Labels: bug

#762 Compress serialization keys
  CHANGES.md
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet.Tests/Blocks/BlockTest.cs
  Libplanet.Tests/Common/Action/BattleResult.cs
  Libplanet.Tests/Libplanet.Tests.csproj
  Libplanet.Tests/Net/SwarmTest.cs
  Libplanet.Tests/Tx/TransactionTest.cs
  Libplanet/Action/AccountStateDeltaImpl.cs
  Libplanet/Action/PolymorphicAction.cs
  Libplanet/Blocks/Block.cs
  Libplanet/Blocks/BlockDigest.cs
  Libplanet/Blocks/BlockHeader.cs
  Libplanet/Blocks/RawBlock.cs
  Libplanet/Libplanet.csproj
  Libplanet/Tx/RawTransaction.cs
Labels: storage

#764 Broadcast single block header instead of block hashes
  CHANGES.md
  Libplanet.Benchmarks/SwarmBenchmark.cs
  Libplanet.Tests/Net/SwarmTest.cs
  Libplanet/Blocks/BlockHeader.cs
  Libplanet/Net/Messages/BlockHashes.cs
  Libplanet/Net/Messages/BlockHeaderMessage.cs
  Libplanet/Net/Messages/Message.cs
  Libplanet/Net/Swarm.cs
Labels: network

#767 Guarantee at least 10 peers to broadcast
  CHANGES.md
  Libplanet.Tests/Net/Protocols/ProtocolTest.cs
  Libplanet.Tests/Net/Protocols/TestTransport.cs
  Libplanet/Net/Protocols/RoutingTable.cs
Labels: network

#774 Make IStore to represent state keys as string (was Address)
  CHANGES.md
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet.Tests/Store/DefaultStoreTest.cs
  Libplanet.Tests/Store/StoreTest.cs
  Libplanet.Tests/Store/StoreTracker.cs
  Libplanet/Blockchain/BlockChain.cs
  Libplanet/Net/Swarm.cs
  Libplanet/Store/BaseStore.cs
  Libplanet/Store/DefaultStore.cs
  Libplanet/Store/IStore.cs
  Libplanet/Store/StoreExtension.cs
Labels: storage, suggestion

#777 Store states as files in DefaultStore
  Libplanet/Store/DefaultStore.cs
Labels: storage

#776 Fork state references included the genesis block
  Libplanet.Tests/Store/StoreTest.cs
  Libplanet/Store/DefaultStore.cs
Labels: bug

#772 Enrich routing table
  CHANGES.md
  Libplanet.Tests/Net/Protocols/ProtocolTest.cs
  Libplanet.Tests/Net/Protocols/RoutingTableTest.cs
  Libplanet/Net/NetMQTransport.cs
  Libplanet/Net/PeerState.cs
  Libplanet/Net/Protocols/KBucket.cs
  Libplanet/Net/Protocols/KademliaProtocol.cs
  Libplanet/Net/Protocols/RoutingTable.cs
  Libplanet/Net/Swarm.cs
Labels: network
