Repository planetarium/libplanet, pull requests merged in 2020-07, with the labels that each got.

#916 Fixed TurnClient's cancellation bug
  CHANGES.md
  Libplanet.Stun/Stun/TurnClient.cs
Labels: bug, network

#926 Separate timeouts in Swarm<T> to SwarmOptions
  CHANGES.md
  Libplanet/Net/Swarm.cs
  Libplanet/Net/SwarmOptions.cs
Labels: network

#923 Make CLI tools installable through npm
  .github/bin/constants.sh
  .github/bin/dist-npm.sh
  .github/bin/dist-nuget.sh
  .github/bin/dist-pack.sh
  .github/workflows/main.yml
  CHANGES.md
  Libplanet.Tools/.gitignore
  Libplanet.Tools/README.md
  Libplanet.Tools/bin/planet
  Libplanet.Tools/download.js
  Libplanet.Tools/install.js
  Libplanet.Tools/package.json
Labels: tools

#940 Serializable InsufficientBalanceException
  CHANGES.md
  Libplanet.Tests/Action/InsufficientBalanceExceptionTest.cs
  Libplanet.Tests/Action/UnexpectedlyTerminatedActionExceptionTest.cs
  Libplanet.Tests/CurrencyTest.cs
  Libplanet/Action/InsufficientBalanceException.cs
  Libplanet/Action/UnexpectedlyTerminatedActionException.cs
  Libplanet/Currency.cs
  Libplanet/Serialization/SerializationInfoExtensions.cs
Labels: bug
