Repository planetarium/libplanet, pull requests merged in 2020-04, with the labels that each got.

#838 Remove/hide unused public interfaces
  CHANGES.md
  Libplanet/Net/DifferentAppProtocolVersionException.cs
  Libplanet/Net/Swarm.cs
Labels: network

#841 Apply NuGet's readme field
  Libplanet.Tools/Libplanet.Tools.csproj
  Libplanet.Tools/README.md
  Libplanet/Libplanet.csproj
Labels: docs

#839 Fix Swarm<T>.Preload()
  CHANGES.md
  Libplanet.Tests/Net/BlockCompletionTest.cs
  Libplanet/Net/BlockCompletion.cs
Labels: bug, network

#845 Fix unexpected error on non-ASCII passphrases
  CHANGES.md
  Libplanet.Tests/KeyStore/Kdfs/KdfTest.cs
  Libplanet.Tests/KeyStore/ProtectedPrivateKeyTest.cs
  Libplanet/KeyStore/Kdfs/Pbkdf2.cs
  Libplanet/Libplanet.csproj
Labels: bug

#846 Parallelizing Swarm<T>.PreloadAsync()
  CHANGES.md
  Libplanet/Net/Swarm.cs
Labels: network

#848 Fix a missing link in the changelog
  CHANGES.md
Labels: bug, docs

#849 Improve reply throughput of `Swarm<T>`
  CHANGES.md
  Libplanet/Net/NetMQTransport.cs
Labels: network

#850 Compressed RecentStates message
  CHANGES.md
  Libplanet.Tests/Net/Messages/RecentStatesTest.cs
  Libplanet/Net/Messages/Message.cs
  Libplanet/Net/Messages/RecentStates.cs
Labels: network

#851 Fix two bugs from GitHub Actions scripts
  .github/bin/dist-pack.sh
  .github/workflows/main.yml
Labels: bug

#853 planet apv verify command
  Libplanet.Tools/Apv.cs
  Libplanet.Tools/Key.cs
Labels: keytool
