Repository planetarium/libplanet, pull requests merged in 2020-12, with the labels that each got.

#1118 Port changes from lib9c's ValidatingActionRenderer
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet.Tests/Blockchain/Renderers/DelayedActionRendererTest.cs
  Libplanet.Tests/Common/ValidatingActionRenderer.cs
  Libplanet.Tests/TestUtils.cs
Labels: bug

#1117 feat(state): deprecate `IBlockStatesStore`
  CHANGES.md
  Libplanet.Benchmarks/SwarmBenchmark.cs
  Libplanet.RocksDBStore.Tests/RocksDBStoreFixture.cs
  Libplanet.RocksDBStore.Tests/RocksDBStoreTest.cs
  Libplanet.RocksDBStore/RocksDBStore.cs
  Libplanet.Tests/Blockchain/BlockChainTest.ValidateNextBlock.cs
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet.Tests/Blockchain/BlockEvaluatorTest.cs
  Libplanet.Tests/Blockchain/Policies/BlockPolicyTest.cs
  Libplanet.Tests/Blockchain/Renderers/DelayedActionRendererTest.cs
  Libplanet.Tests/Blocks/BlockTest.cs
  Libplanet.Tests/Net/Messages/BlockStatesTest.cs
  Libplanet.Tests/Net/Messages/RecentStatesTest.cs
  Libplanet.Tests/Net/SwarmTest.Fixtures.cs
  Libplanet.Tests/Net/SwarmTest.Preload.cs
  Libplanet.Tests/Net/SwarmTest.TrustedStateCompleter.cs
  Libplanet.Tests/Net/SwarmTest.cs
  Libplanet.Tests/Store/DefaultStoreFixture.cs
  Libplanet.Tests/Store/DefaultStoreTest.cs
  Libplanet.Tests/Store/StateStoreTrackerTest.cs
  Libplanet.Tests/Store/StoreFixture.cs
  Libplanet.Tests/Store/StoreTest.cs
  Libplanet.Tests/TestUtils.cs
  Libplanet/Blockchain/BlockChain.cs
  Libplanet/Net/Messages/BlockStates.cs
  Libplanet/Net/Messages/GetBlockStates.cs
  Libplanet/Net/Messages/GetRecentStates.cs
  Libplanet/Net/Messages/Message.cs
  Libplanet/Net/Messages/RecentStates.cs
  Libplanet/Net/Swarm.MessageHandlers.cs
  Libplanet/Net/Swarm.TrustedStateCompleter.cs
  Libplanet/Net/Swarm.cs
  Libplanet/Store/BaseBlockStatesStore.cs
  Libplanet/Store/DefaultStore.cs
  Libplanet/Store/IBlockStatesStore.cs
  Libplanet/Store/StoreExtensions.cs
Labels: bug, network, storage

#1127 docs: correct document
  Libplanet/Blockchain/Policies/BlockPolicy.cs
Labels: docs

#1129 feat(cli): support multiple kv-store in diff
  CHANGES.md
  Libplanet.Tools/Mpt.cs
Labels: tools
