Repository planetarium/libplanet, pull requests merged in 2020-06, with the labels that each got.

#891 Make RocksDBStore.DeleteChainId() idempotent
  CHANGES.md
  Libplanet.RocksDBStore/RocksDBStore.cs
  Libplanet.Tests/Store/StoreTest.cs
Labels: bug

#890 Fix message dropping
  CHANGES.md
  Libplanet.Stun/Stun/NetworkStreamProxy.cs
  Libplanet.Stun/Stun/TurnClient.cs
  Libplanet/Net/NetMQTransport.cs
Labels: bug, network

#897 Fix a infinite timeout when remote peer had been gone
  Libplanet/Net/NetMQTransport.cs
Labels: bug, network

#899 Merge a behind patch from 9c-beta to master
  Libplanet/Net/NetMQTransport.cs
Labels: bug

#898 Ignore invalid header immediately
  CHANGES.md
  Libplanet.Tests/Blocks/BlockHeaderTest.cs
  Libplanet/Blocks/Block.cs
  Libplanet/Blocks/BlockHeader.cs
  Libplanet/Net/Swarm.cs
  Libplanet/Store/BaseStore.cs
Labels: network

#902 Clean up only temporary chains only
  CHANGES.md
  Libplanet.Tests/Net/SwarmTest.Preload.cs
  Libplanet/Net/Swarm.cs
Labels: network

#913 Fix serialization bug on UnexpectedlyTerminatedActionException
  CHANGES.md
  Libplanet.Tests/Action/UnexpectedlyTerminatedActionExceptionTest.cs
  Libplanet/Action/UnexpectedlyTerminatedActionException.cs
Labels: bug
