Repository planetarium/libplanet, pull requests merged in 2020-03, with the labels that each got.

#809 Fix release script bugs
  .github/bin/dist-github-release.sh
  .github/bin/dist-nuget.sh
  .github/bin/dist-pack.sh
  .github/workflows/main.yml
  hooks/validate-release
Labels: bug

#812 Fix a bug where nupkg is not submitted to NuGet
  .github/bin/dist-nuget.sh
Labels: bug

#790 Prune state after sync state from trusted peers
  CHANGES.md
  Libplanet.RocksDBStore/RocksDBStore.cs
  Libplanet.Tests/Net/SwarmTest.cs
  Libplanet.Tests/Store/StoreTest.cs
  Libplanet.Tests/Store/StoreTracker.cs
  Libplanet/Store/BaseStore.cs
  Libplanet/Store/DefaultStore.cs
  Libplanet/Store/IStore.cs
Labels: storage

#816 Open all ColumnFamilies when opening DB
  Libplanet.RocksDBStore.Tests/RocksDBStoreTest.cs
  Libplanet.RocksDBStore/RocksDBStore.cs
Labels: storage

#815 Signed app protocol version & new callback interface to negotiate versions
  CHANGES.md
  Libplanet.Benchmarks/SwarmBenchmark.cs
  Libplanet.Tests/Net/AppProtocolVersionTest.cs
  Libplanet.Tests/Net/Messages/BlockHashesTest.cs
  Libplanet.Tests/Net/Messages/RecentStatesTest.cs
  Libplanet.Tests/Net/PeerTest.cs
  Libplanet.Tests/Net/Protocols/RoutingTableTest.cs
  Libplanet.Tests/Net/Protocols/TestTransport.cs
  Libplanet.Tests/Net/SwarmTest.AppProtocolVersion.cs
  Libplanet.Tests/Net/SwarmTest.Fixtures.cs
  Libplanet.Tests/Net/SwarmTest.cs
  Libplanet/Net/AppProtocolVersion.cs
  Libplanet/Net/BoundPeer.cs
  Libplanet/Net/DifferentAppProtocolVersionEncountered.cs
  Libplanet/Net/DifferentAppProtocolVersionException.cs
  Libplanet/Net/DifferentProtocolVersionEventArgs.cs
  Libplanet/Net/NetMQTransport.cs
  Libplanet/Net/Peer.cs
  Libplanet/Net/Protocols/KademliaProtocol.cs
  Libplanet/Net/Swarm.cs
  Menees.Analyzers.Settings.xml
Labels: network

#820 Fix `Swarm<T>` halting
  CHANGES.md
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet.Tests/Net/SwarmTest.cs
  Libplanet.Tests/Store/StoreTest.cs
  Libplanet/Blockchain/BlockChain.cs
  Libplanet/Net/Swarm.cs
Labels: bug

#821 Fix RocksDBStore ForkBlockIndex
  Libplanet.RocksDBStore/RocksDBStore.cs
  Libplanet.Tests/Store/StoreTest.cs
  Libplanet/Store/DefaultStore.cs
Labels: bug

#824 Sticky footer using flexbox
  Docs/theme/styles/main.css
Labels: bug, docs

#829 Make default(AppProtocolVersion) to have an empty Signature
  Libplanet.Tests/Net/AppProtocolVersionTest.cs
  Libplanet.Tests/Net/PeerTest.cs
  Libplanet/Net/AppProtocolVersion.cs
  Libplanet/Net/Peer.cs
Labels: bug

#822 Do not run upstream specific workfolows in forks
  .github/workflows/main.yml
Labels: bug

#830 Disallow null from AppProtocolVersion.FromToken()
  Libplanet.Tests/Net/AppProtocolVersionTest.cs
  Libplanet/Net/AppProtocolVersion.cs
Labels: bug
