Repository planetarium/libplanet, pull requests merged in 2020-02, with the labels that each got.

#775 Stage transactions not included in swapped chain
  CHANGES.md
  Libplanet.Tests/Net/SwarmTest.cs
  Libplanet/Blockchain/BlockChain.cs
  Menees.Analyzers.Settings.xml
Labels: bug

#707 Preload blocks from multiple peers at a time
  CHANGES.md
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet.Tests/Blockchain/BlockLocatorTest.cs
  Libplanet.Tests/Net/BlockCompletionTest.cs
  Libplanet.Tests/Net/Messages/BlockHashesTest.cs
  Libplanet.Tests/Net/SwarmTest.cs
  Libplanet/Blockchain/BlockChain.cs
  Libplanet/Blockchain/BlockLocator.cs
  Libplanet/Net/BlockCompletion.cs
  Libplanet/Net/BlockDownloadState.cs
  Libplanet/Net/BlockHashDownloadState.cs
  Libplanet/Net/Messages/BlockHashes.cs
  Libplanet/Net/Messages/Message.cs
  Libplanet/Net/StateDownloadState.cs
  Libplanet/Net/Swarm.cs
  Menees.Analyzers.Settings.xml
Labels: network

#788 Fixed a bug when broadcasting
  CHANGES.md
  Libplanet.Benchmarks/SwarmBenchmark.cs
  Libplanet.Tests/Net/Protocols/ProtocolTest.cs
  Libplanet.Tests/Net/Protocols/TestTransport.cs
  Libplanet.Tests/TestUtils.cs
  Libplanet/Net/Protocols/RoutingTable.cs
Labels: bug, network

#784 Poll blocks and txs
  CHANGES.md
  Libplanet.Tests/Net/SwarmTest.cs
  Libplanet/Net/NetMQTransport.cs
  Libplanet/Net/Swarm.cs
  Menees.Analyzers.Settings.xml
Labels: network

#791 Mine block without txs having lower nonce
  CHANGES.md
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet/Blockchain/BlockChain.cs
Labels: bug

#794 Upgrade C# to 8.0 with maintaining .NET Standard 2.0
  .azure-pipelines/dotnet-core.yml
  .github/workflows/benchmarks.yml
  .github/workflows/main.yml
  CONTRIBUTING.md
  Libplanet.Stun/Libplanet.Stun.csproj
  Libplanet/Libplanet.csproj
  README.md
  azure-pipelines.yml
Labels: suggestion

#798 Restore BlockCompletion<T> (#707) and more
  CHANGES.md
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet.Tests/Blockchain/BlockLocatorTest.cs
  Libplanet.Tests/Libplanet.Tests.csproj
  Libplanet.Tests/LoggerExtensions.cs
  Libplanet.Tests/Net/BlockCompletionTest.cs
  Libplanet.Tests/Net/Messages/BlockHashesTest.cs
  Libplanet.Tests/Net/SwarmTest.cs
  Libplanet/Blockchain/BlockChain.cs
  Libplanet/Blockchain/BlockLocator.cs
  Libplanet/Libplanet.csproj
  Libplanet/Net/ActionExecutionState.cs
  Libplanet/Net/BlockCompletion.cs
  Libplanet/Net/BlockDownloadState.cs
  Libplanet/Net/BlockHashDownloadState.cs
  Libplanet/Net/BlockVerificationState.cs
  Libplanet/Net/Messages/BlockHashes.cs
  Libplanet/Net/Messages/Message.cs
  Libplanet/Net/NetMQTransport.cs
  Libplanet/Net/PreloadState.cs
  Libplanet/Net/StateDownloadState.cs
  Libplanet/Net/Swarm.cs
  Menees.Analyzers.Settings.xml
Labels: bug, network, suggestion
