Repository planetarium/libplanet, pull requests merged in 2020-09, with the labels that each got.

#982 Refactor CLI Install Script
  Libplanet.Tools/download.js
Labels: bug, tools

#975 Set auto assign by github bot
  .github/auto_assign.yml
Labels: suggestion

#985 Fix unit tests
  Libplanet.Tests/Net/SwarmTest.Preload.cs
  Libplanet.Tests/Net/SwarmTest.cs
Labels: bug

#988 Make BlockChain<T>.Swap() without reorg not to invoke IRenderer<T>.RenderReorg()
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet.Tests/Blockchain/Renderers/DelayedActionRendererTest.cs
  Libplanet.Tests/Net/SwarmTest.Preload.cs
  Libplanet/Blockchain/BlockChain.cs
  Libplanet/Blockchain/Renderers/DelayedActionRenderer.cs
  Libplanet/Blockchain/Renderers/IRenderer.cs
  Libplanet/Net/Swarm.cs
Labels: bug

#978 Do not request RecentStates if IBlockStateStore is unused
  Libplanet.RocksDBStore.Tests/RocksDBStoreFixture.cs
  Libplanet.Tests/Net/SwarmTest.Fixtures.cs
  Libplanet.Tests/Net/SwarmTest.Preload.cs
  Libplanet.Tests/Net/SwarmTest.cs
  Libplanet.Tests/Store/DefaultStoreFixture.cs
  Libplanet.Tests/Store/StoreFixture.cs
  Libplanet.Tests/TestUtils.cs
  Libplanet/Net/Swarm.MessageHandlers.cs
  Libplanet/Net/Swarm.cs
Labels: bug

#990 Fixed several bugs on DelayedRenderer<T> & BlockChain<T>.Swap()
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet/Blockchain/BlockChain.cs
  Libplanet/Blockchain/Renderers/DelayedRenderer.cs
Labels: bug

#989 Fix bug where BootstrapAsync throw PingTimeoutException when some FindPeer fails
  Libplanet.Tests/Net/Protocols/ProtocolTest.cs
  Libplanet/Net/Protocols/KademliaProtocol.cs
Labels: bug

#994 Even backward tip change shouldn't invoke RenderReorg
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet/Blockchain/BlockChain.cs
  Libplanet/Blockchain/Renderers/DelayedRenderer.cs
Labels: bug

#987 Fix FindSpecificPeerAsync's depth parameter did not worked properly
  Libplanet.Tests/Net/SwarmTest.cs
  Libplanet/Net/Protocols/KademliaProtocol.cs
Labels: bug

#996 Polishing Swarm<T>
  CHANGES.md
  Libplanet/Net/Swarm.cs
Labels: bug, network

#997 Make DelayedRenderer<T> to regard total difficulty
  .gitignore
  CONTRIBUTING.md
  Libplanet.RocksDBStore.Tests/Libplanet.RocksDBStore.Tests.csproj
  Libplanet.Stun.Tests/Libplanet.Stun.Tests.csproj
  Libplanet.Tests/Blockchain/Renderers/DelayedActionRendererTest.cs
  Libplanet.Tests/Blockchain/Renderers/DelayedRendererTest.cs
  Libplanet.Tests/Libplanet.Tests.csproj
  Libplanet/Blockchain/Renderers/DelayedRenderer.cs
  Libplanet/Blockchain/Renderers/IActionRenderer.cs
Labels: bug

#998 Make DelayedRenderer<T> to commit render buffers atomically
  .azure-pipelines/dotnet-core.yml
  .azure-pipelines/mono.yml
  .azure-pipelines/windows-net471.yml
  Libplanet/Blockchain/Renderers/DelayedActionRenderer.cs
Labels: bug

#986 Validate state root hash
  CHANGES.md
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet.Tests/Blockchain/Policies/BlockPolicyTest.cs
  Libplanet.Tests/Blocks/BlockHeaderTest.cs
  Libplanet.Tests/Blocks/BlockTest.cs
  Libplanet.Tests/Net/SwarmTest.Preload.cs
  Libplanet.Tests/Net/SwarmTest.cs
  Libplanet.Tests/Store/DefaultStoreFixture.cs
  Libplanet.Tests/Store/StoreFixture.cs
  Libplanet.Tests/Store/Trie/TrieTest.cs
  Libplanet.Tests/TestUtils.cs
  Libplanet/Action/ActionEvaluationsExtensions.cs
  Libplanet/Blockchain/BlockChain.cs
  Libplanet/Blockchain/BlockEvaluator.cs
  Libplanet/Blockchain/Policies/BlockPolicy.cs
  Libplanet/Blocks/Block.cs
  Libplanet/Blocks/BlockHeader.cs
  Libplanet/Blocks/InvalidBlockException.cs
  Libplanet/Blocks/InvalidBlockStateRootHashException.cs
  Libplanet/Store/BaseStore.cs
  Libplanet/Store/Trie/ITrie.cs
  Libplanet/Store/Trie/ITrieExtensions.cs
  Libplanet/Store/Trie/MerkleTrie.cs
  Libplanet/Store/TrieStateStore.cs
Labels: consensus

#995 Do not render genesis block during fork
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet.Tests/Net/SwarmTest.Preload.cs
  Libplanet.Tests/Net/SwarmTest.cs
  Libplanet/Blockchain/BlockChain.cs
  Libplanet/Net/Swarm.cs
Labels: bug

#993 Report progress synchronously in test
  Libplanet.Tests/Net/SwarmTest.Preload.cs
Labels: bug

#1004 Ignore messages from peer with different genesis block
  CHANGES.md
  Libplanet.Tests/Net/SwarmTest.Preload.cs
  Libplanet.Tests/Net/SwarmTest.cs
  Libplanet/Net/Messages/BlockHeaderMessage.cs
  Libplanet/Net/Messages/ChainStatus.cs
  Libplanet/Net/Messages/Message.cs
  Libplanet/Net/Swarm.MessageHandlers.cs
  Libplanet/Net/Swarm.TrustedStateCompleter.cs
  Libplanet/Net/Swarm.cs
Labels: network

#1005 Use PreEvaluationHash (instead of Hash) as random seed
  Libplanet/Blockchain/BlockEvaluator.cs
  Libplanet/Blocks/Block.cs
Labels: bug

#1009 Make delayed renderers more multithread-resistant
  Libplanet/Blockchain/Renderers/DelayedActionRenderer.cs
Labels: bug

#984 Fix Backspace not working in create new key in CLI.
  CHANGES.md
  Libplanet.Tools/ConsolePasswordReader.cs
  Libplanet.Tools/Key.cs
  Libplanet.Tools/Libplanet.Tools.csproj
Labels: bug, tools

#1011 Fix a bug the order of transactions was different in two steps (i.e., pre-evaluation and evaluation)
  Libplanet.Tests/Blocks/BlockTest.cs
  Libplanet/Blocks/Block.cs
Labels: bug

#1019 Fix inaccurate render events order according to documented automata
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet.Tests/Common/RecordingRenderer.cs
  Libplanet.Tests/Common/RenderRecord.cs
  Libplanet.Tests/Common/ValidatingActionRenderer.cs
  Libplanet.Tests/Menees.Analyzers.Settings.xml
  Libplanet.Tests/Net/SwarmTest.cs
  Libplanet.Tests/TestUtils.cs
  Libplanet/Blockchain/BlockChain.cs
  Libplanet/Blockchain/Renderers/DelayedActionRenderer.cs
  Libplanet/Net/Swarm.cs
Labels: bug
