Repository planetarium/libplanet, pull requests merged in 2020-05, with the labels that each got.

#859 Separate _poller in NetMQTransport
  CHANGES.md
  Libplanet/Net/NetMQTransport.cs
Labels: network

#864 Avoid overwrapped SetResult and SetException
  CHANGES.md
  Libplanet/Net/NetMQTransport.cs
Labels: bug, network

#865 Fix the release script (GitHub Actions)
  .github/bin/dist-github-release.sh
  .github/bin/dist-pack.sh
Labels: bug

#876 Fix a changelog typo
  CHANGES.md
Labels: bug

#879 Improve block propagation performance
  CHANGES.md
  Libplanet/Net/NetMQTransport.cs
  Libplanet/Net/Swarm.cs
Labels: network

#884 Prevent Swarm<T>.GetDemandBlockHashes() from being hanged when a peer's chain is during reorg
  CHANGES.md
  Libplanet.Tests/ActionProgress.cs
  Libplanet.Tests/Net/SwarmTest.Preload.cs
  Libplanet/Net/Swarm.cs
Labels: bug

#885 Fix NuGet distribution condition
  .github/bin/dist-nuget.sh
Labels: bug
