Repository planetarium/libplanet, pull requests merged in 2020-08, with the labels that each got.

#934 More flexible state complement
  .idea/.idea.Libplanet/.idea/vcs.xml
  CHANGES.md
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet.Tests/Net/SwarmTest.Preload.cs
  Libplanet.Tools/.gitignore
  Libplanet/Blockchain/BlockChain.cs
  Libplanet/Blockchain/FungibleAssetStateCompleter.cs
  Libplanet/Blockchain/FungibleAssetStateCompleters.cs
  Libplanet/Blockchain/StateCompleter.cs
  Libplanet/Blockchain/StateCompleterSet.cs
  Libplanet/Blockchain/StateCompleters.cs
Labels: storage, suggestion

#946 Trusted state completer
  CHANGES.md
  Libplanet.Benchmarks/SwarmBenchmark.cs
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet.Tests/Net/Messages/BlockStatesTest.cs
  Libplanet.Tests/Net/SwarmTest.Fixtures.cs
  Libplanet.Tests/Net/SwarmTest.TrustedStateCompleter.cs
  Libplanet.Tests/Net/SwarmTest.cs
  Libplanet.Tests/RandomExtensions.cs
  Libplanet.Tests/TestUtils.cs
  Libplanet/Blockchain/BlockChain.cs
  Libplanet/Blockchain/IncompleteBlockStatesException.cs
  Libplanet/Blocks/Block.cs
  Libplanet/Net/Messages/BlockStates.cs
  Libplanet/Net/Messages/GetBlockStates.cs
  Libplanet/Net/Messages/Message.cs
  Libplanet/Net/Swarm.MessageHandlers.cs
  Libplanet/Net/Swarm.TrustedStateCompleter.cs
  Libplanet/Net/Swarm.cs
Labels: network, storage

#950 Separate IStore into IStateStore
  CHANGES.md
  Libplanet.Benchmarks/BlockChain.cs
  Libplanet.Benchmarks/MineBlock.cs
  Libplanet.Benchmarks/SwarmBenchmark.cs
  Libplanet.RocksDBStore.Tests/RocksDBStoreTest.cs
  Libplanet.RocksDBStore/RocksDBStore.cs
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet.Tests/Blockchain/Policies/BlockPolicyTest.cs
  Libplanet.Tests/Menees.Analyzers.Settings.xml
  Libplanet.Tests/Net/SwarmTest.Preload.cs
  Libplanet.Tests/Net/SwarmTest.TrustedStateCompleter.cs
  Libplanet.Tests/Net/SwarmTest.cs
  Libplanet.Tests/Store/BaseTracker.cs
  Libplanet.Tests/Store/StateStoreTracker.cs
  Libplanet.Tests/Store/StateStoreTrackerTest.cs
  Libplanet.Tests/Store/StoreFixture.cs
  Libplanet.Tests/Store/StoreTest.cs
  Libplanet.Tests/Store/StoreTracker.cs
  Libplanet.Tests/TestUtils.cs
  Libplanet/Blockchain/BlockChain.cs
  Libplanet/Blockchain/FungibleAssetStateCompleters.cs
  Libplanet/Blockchain/StateCompleters.cs
  Libplanet/Net/Swarm.MessageHandlers.cs
  Libplanet/Net/Swarm.TrustedStateCompleter.cs
  Libplanet/Net/Swarm.cs
  Libplanet/Store/BaseBlockStatesStore.cs
  Libplanet/Store/BaseStore.cs
  Libplanet/Store/DefaultStore.cs
  Libplanet/Store/IBlockStatesStore.cs
  Libplanet/Store/IStateStore.cs
  Libplanet/Store/IStore.cs
  Libplanet/Store/StoreExtensions.cs
Labels: storage

#949 Introduce Version property to messages
  CHANGES.md
  Libplanet.Tests/Net/Messages/BlockHashesTest.cs
  Libplanet.Tests/Net/Messages/BlockStatesTest.cs
  Libplanet.Tests/Net/Messages/MessageTest.cs
  Libplanet.Tests/Net/Messages/RecentStatesTest.cs
  Libplanet.Tests/Net/PeerTest.cs
  Libplanet.Tests/Net/Protocols/RoutingTableTest.cs
  Libplanet.Tests/Net/Protocols/TestTransport.cs
  Libplanet.Tests/Net/SwarmTest.AppProtocolVersion.cs
  Libplanet.Tests/Net/SwarmTest.cs
  Libplanet/Net/BoundPeer.cs
  Libplanet/Net/DifferentAppProtocolVersionException.cs
  Libplanet/Net/Messages/DifferentVersion.cs
  Libplanet/Net/Messages/Message.cs
  Libplanet/Net/NetMQTransport.cs
  Libplanet/Net/Peer.cs
  Libplanet/Net/Protocols/KademliaProtocol.cs
  Libplanet/Net/Swarm.cs
Labels: network

#954 Represent fungible asset values as a distinct type and support minor units
  CHANGES.md
  Libplanet.Tests/Action/AccountStateDeltaExtensions.cs
  Libplanet.Tests/Action/AccountStateDeltaImplTest.cs
  Libplanet.Tests/Action/ActionContextTest.cs
  Libplanet.Tests/Action/ActionEvaluationExtensions.cs
  Libplanet.Tests/Action/ActionEvaluationTest.cs
  Libplanet.Tests/Action/InsufficientBalanceExceptionTest.cs
  Libplanet.Tests/Assets/CurrencyTest.cs
  Libplanet.Tests/Assets/FungibleAssetValueTest.cs
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet.Tests/Blocks/BlockTest.cs
  Libplanet.Tests/Common/Action/DumbAction.cs
  Libplanet.Tests/Tx/TransactionTest.cs
  Libplanet/Action/AccountBalanceGetter.cs
  Libplanet/Action/AccountStateDeltaImpl.cs
  Libplanet/Action/CurrencyPermissionException.cs
  Libplanet/Action/IAccountStateDelta.cs
  Libplanet/Action/InsufficientBalanceException.cs
  Libplanet/Assets/Currency.cs
  Libplanet/Assets/FungibleAssetValue.cs
  Libplanet/Blockchain/BlockChain.cs
  Libplanet/Blockchain/FungibleAssetStateCompleter.cs
  Libplanet/Blockchain/FungibleAssetStateCompleters.cs
  Libplanet/Blocks/Block.cs
  Libplanet/Tx/Transaction.cs
Labels: storage, suggestion

#961 Fix the outdated branch name in the docs build script
  CONTRIBUTING.md
  Docs/publish.sh
  Libplanet.Tools/package.json
  Libplanet/Libplanet.csproj
  README.md
Labels: bug, docs

#939 Introduce Merkle Patricia Trie
  CHANGES.md
  Libplanet.RocksDBStore.Tests/RocksDBKeyValueStoreTest.cs
  Libplanet.RocksDBStore/RocksDBKeyValueStore.cs
  Libplanet.RocksDBStore/RocksDBStore.cs
  Libplanet.RocksDBStore/RocksDBUtils.cs
  Libplanet.Tests/Store/Trie/BytesEqualityComparer.cs
  Libplanet.Tests/Store/Trie/CacheableKeyValueStoreTest.cs
  Libplanet.Tests/Store/Trie/DefaultKeyValueStoreTest.cs
  Libplanet.Tests/Store/Trie/KeyValueStoreTest.cs
  Libplanet.Tests/Store/Trie/MemoryKeyValueStore.cs
  Libplanet.Tests/Store/Trie/Nodes/FullNodeTest.cs
  Libplanet.Tests/Store/Trie/Nodes/HashNodeTest.cs
  Libplanet.Tests/Store/Trie/Nodes/NodeDecoderTest.cs
  Libplanet.Tests/Store/Trie/Nodes/ShortNodeTest.cs
  Libplanet.Tests/Store/Trie/Nodes/ValueNodeTest.cs
  Libplanet.Tests/Store/Trie/TrieTest.cs
  Libplanet.Tests/Store/TrieStateStoreTest.cs
  Libplanet/Libplanet.csproj
  Libplanet/Store/Trie/CacheableKeyValueStore.cs
  Libplanet/Store/Trie/DefaultKeyValueStore.cs
  Libplanet/Store/Trie/IKeyValueStore.cs
  Libplanet/Store/Trie/ITrie.cs
  Libplanet/Store/Trie/InvalidTrieNodeException.cs
  Libplanet/Store/Trie/MerkleTrie.cs
  Libplanet/Store/Trie/Nodes/BaseNode.cs
  Libplanet/Store/Trie/Nodes/FullNode.cs
  Libplanet/Store/Trie/Nodes/HashNode.cs
  Libplanet/Store/Trie/Nodes/INode.cs
  Libplanet/Store/Trie/Nodes/INodeExtensions.cs
  Libplanet/Store/Trie/Nodes/NodeDecoder.cs
  Libplanet/Store/Trie/Nodes/ShortNode.cs
  Libplanet/Store/Trie/Nodes/ValueNode.cs
  Libplanet/Store/TrieStateStore.cs
Labels: storage

#964 Add Swarm<T>.LastMessageTimestamp
  CHANGES.md
  Libplanet.Tests/Net/Protocols/TestTransport.cs
  Libplanet.Tests/Net/SwarmTest.cs
  Libplanet/Net/ITransport.cs
  Libplanet/Net/NetMQTransport.cs
  Libplanet/Net/Swarm.cs
Labels: network

#965 Restartable Swarm<T>
  CHANGES.md
  Libplanet.Tests/Net/FactOnlyTurnAvailableAttribute.cs
  Libplanet.Tests/Net/SwarmTest.cs
  Libplanet/Net/NetMQTransport.cs
  Libplanet/Net/Swarm.cs
Labels: network

#968 Fix a bug that TrieStateStore.SetStates(…) couldn't get previous hash successfully
  Libplanet.Tests/Store/StateStoreTracker.cs
  Libplanet.Tests/Store/TrieStateStoreTest.cs
  Libplanet/Blockchain/BlockChain.cs
  Libplanet/Store/BaseBlockStatesStore.cs
  Libplanet/Store/IStateStore.cs
  Libplanet/Store/TrieStateStore.cs
Labels: bug, storage

#972 Fix errors on TurnClient
  CHANGES.md
  Libplanet.Stun/Stun/TurnClient.cs
  Libplanet.Tests/Net/SwarmTest.cs
Labels: bug, network
