Repository planetarium/libplanet, pull requests merged in 2021-06, with the labels that each got.

#1330 [skip changelog] Use wget over curl if possible
  Docs/build.ps1
Labels: docs, invalid

#1338 Retry flaky tests using xRetry
  Libplanet.Tests/Libplanet.Tests.csproj
  Libplanet.Tests/Net/FactOnlyTurnAvailableAttribute.cs
  Libplanet.Tests/Net/SwarmTest.Broadcast.cs
  Libplanet.Tests/Net/SwarmTest.Preload.cs
  Libplanet.Tests/Net/SwarmTest.cs
Labels: ci/github-actions

#1343 Patch: Throw an unmanaged exception for critical failure during evaluation
  CHANGES.md
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
  Libplanet.Tests/Common/Action/ThrowException.cs
  Libplanet/Action/ActionEvaluator.cs
Labels: bug

#1334 Parallelize broadcast
  CHANGES.md
  Libplanet/Net/Transports/NetMQTransport.cs
Labels: network

#1348 Add `SwarmOptions.BranchpointThreshold`
  CHANGES.md
  Libplanet/Net/Swarm.BlockSync.cs
  Libplanet/Net/Swarm.cs
  Libplanet/Net/SwarmOptions.cs
Labels: network

#1355 lint: treat warning as error
  Libplanet.Extensions.Cocona.Tests/Commands/MptCommandTest.cs
  Libplanet.Extensions.Cocona.Tests/Libplanet.Extensions.Cocona.Tests.csproj
  Libplanet.Extensions.Cocona.Tests/Services/TestToolConfigurationService.cs
  Libplanet.Extensions.Cocona.Tests/UtilsTest.cs
Labels: analyzer

#1351 Introduce block broadcaster
  CHANGES.md
  Libplanet.Benchmarks/SwarmBenchmark.cs
  Libplanet.Tests/Net/SwarmTest.cs
  Libplanet/Net/Swarm.cs
Labels: network
