Repository planetarium/libplanet, pull requests merged in 2021-07, with the labels that each got.

#1360 Fix replying delay
  CHANGES.md
  Libplanet/Net/Transports/NetMQTransport.cs
Labels: network

#1369 Catch `ArgumentOutOfRangeException` & return `null` instead during block sync
  Libplanet/Net/Swarm.cs
Labels: bug

#1350 Fail-fast when block sync
  CHANGES.md
  Libplanet/Net/Swarm.BlockSync.cs
Labels: bug, network

#1353 New stats command added to planet cli
  CHANGES.md
  Libplanet.Extensions.Cocona.Tests/Commands/StatsCommandTest.cs
  Libplanet.Extensions.Cocona/AssemblyInfo.cs
  Libplanet.Extensions.Cocona/Commands/StatsCommand.cs
  Libplanet.Tools/Program.cs
Labels: tools

#1379 Configurable broadcast target number
  CHANGES.md
  Libplanet.Tests/Net/Transports/NetMQTransportTest.cs
  Libplanet.Tests/Net/Transports/TransportTest.cs
  Libplanet/Net/Swarm.cs
  Libplanet/Net/SwarmOptions.cs
  Libplanet/Net/Transports/NetMQTransport.cs
Labels: network

#1341 Miner is no longer nullable
  CHANGES.md
  Libplanet.Explorer.UnitTests/GraphTypes/BlockTypeTest.cs
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
  Libplanet.Tests/Blockchain/BlockChainTest.Internals.cs
  Libplanet.Tests/Blockchain/BlockChainTest.ValidateNextBlock.cs
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet.Tests/Blocks/BlockHeaderTest.cs
  Libplanet.Tests/Blocks/BlockTest.cs
  Libplanet.Tests/TestUtils.cs
  Libplanet/Action/ActionEvaluator.cs
  Libplanet/Blocks/Block.cs
  Libplanet/Blocks/BlockHeader.cs
Labels: suggestion

#1347 Refactor/header caching
  CHANGES.md
  Libplanet.Explorer.UnitTests/GraphTypes/BlockTypeTest.cs
  Libplanet.Tests/Blocks/BlockHeaderTest.cs
  Libplanet/Blocks/Block.cs
  Libplanet/Blocks/BlockHeader.cs
Labels: suggestion

#1367 Maintain static peers in `Swarm<T>`
  CHANGES.md
  Libplanet.Tests/Net/Protocols/RoutingTableTest.cs
  Libplanet.Tests/Net/SwarmTest.cs
  Libplanet/Net/Protocols/RoutingTable.cs
  Libplanet/Net/Swarm.cs
  Libplanet/Net/SwarmOptions.cs
Labels: network

#1326 Patch/transaction ordering update
  CHANGES.md
  Libplanet.Tests/Blocks/BlockTest.cs
  Libplanet/Blocks/Block.cs
Labels: bug

#1394 Release 0.12.0
  CHANGES.md
Labels: release

#1397 Fix error that dist-npm.sh makes on release
  .github/bin/dist-npm.sh
Labels: bug, ci/github-actions

#1405 Release 0.12.1
  CHANGES.md
Labels: release

#1365 Prevent ObjectDisposedException during NetMQTransport.DoBroadcast()
  CHANGES.md
  Libplanet/Net/Transports/NetMQTransport.cs
Labels: bug, network

#1411 Hotfix: Make `HashAlgorithmType.Digest()` thread-safe
  CHANGES.md
  Libplanet.Tests/HashAlgorithmTypeTest.cs
  Libplanet/HashAlgorithmType.cs
Labels: bug

#1412 Release 0.13.1
  CHANGES.md
Labels: release
