Repository planetarium/libplanet, pull requests merged in 2021-12, with the labels that each got.

#1639 Remove message history & release 0.22.1
  CHANGES.md
  Libplanet.Tests/Net/SwarmTest.Broadcast.cs
  Libplanet.Tests/Net/SwarmTest.cs
  Libplanet.Tests/Net/Transports/NetMQTransportTest.cs
  Libplanet/Net/Transports/ITransport.cs
  Libplanet/Net/Transports/NetMQTransport.cs
  Libplanet/Net/Transports/TcpTransport.cs
Labels: network

#1638 Remove ITransport.MessageHistory & Release 0.21.3
  CHANGES.md
  Libplanet.Tests/Net/SwarmTest.Broadcast.cs
  Libplanet.Tests/Net/SwarmTest.cs
  Libplanet.Tests/Net/Transports/NetMQTransportTest.cs
  Libplanet/Net/Transports/ITransport.cs
  Libplanet/Net/Transports/NetMQTransport.cs
  Libplanet/Net/Transports/TcpTransport.cs
Labels: network

#1636 Fragmented states on Merkle tree
  CHANGES.md
  Libplanet.Analyzers.Tests/ActionAnalyzerTest.cs
  Libplanet.Analyzers/ActionAnalyzer.cs
  Libplanet.Analyzers/rules/LAA1002.md
  Libplanet.Tests/Misc/ArrayEqualityComparerTest.cs
  Libplanet.Tests/Store/Trie/MerkleTrieTest.cs
  Libplanet/Blocks/PreEvaluationBlock.cs
  Libplanet/Libplanet.csproj
  Libplanet/Misc/ArrayEqualityComparer.cs
  Libplanet/Store/Trie/ITrieExtensions.cs
  Libplanet/Store/Trie/MerkleTrie.cs
  Libplanet/Store/Trie/Nodes/BaseNode.cs
  Libplanet/Store/Trie/Nodes/INodeExtensions.cs
  Libplanet/Store/Trie/Nodes/ValueNode.cs
  Libplanet/Store/TrieStateStore.cs
Labels: storage

#1651 Release 0.23.0
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: release

#1654 Release 0.23.1 & Fix `TrieStateStore.PruneStates()` throwing `ArgumentOutOfRangeException`
  CHANGES.md
  Libplanet.Tests/Store/TrieStateStoreTest.cs
  Libplanet/Store/TrieStateStore.cs
Labels: bug, storage

#1665 Virtually disable state fragmentation & release 0.23.3
  CHANGES.md
  Libplanet.Tests/Store/TrieStateStoreTest.cs
  Libplanet/Store/Trie/MerkleTrie.cs
Labels: bug, storage, release

#1667 Port 0.23.3 to main (0.24.x)
  CHANGES.md
  Libplanet.Tests/Store/TrieStateStoreTest.cs
  Libplanet/Store/Trie/MerkleTrie.cs
Labels: bug

#1661 Prevent broadcasting invalid transactions
  CHANGES.md
  Libplanet/Net/TxCompletion.cs
Labels: network

#1670 Release 0.24.0
  CHANGES.md
Labels: release

#1673 Release 0.24.1
  CHANGES.md
Labels: bug, release

#1676 Improve performance of `BlockChain<T>.FindNextHashes()`
  CHANGES.md
  Libplanet.RocksDBStore/RocksDBStore.cs
  Libplanet/Blockchain/BlockChain.cs
Labels: storage

#1678 Add multiget operation to `IKeyValueStore`
  CHANGES.md
  Libplanet.RocksDBStore/RocksDBKeyValueStore.cs
  Libplanet.Tests/Store/Trie/KeyBytesTest.cs
  Libplanet.Tests/Store/Trie/KeyValueStoreTest.cs
  Libplanet.Tests/TestUtils.cs
  Libplanet/HashDigest.cs
  Libplanet/Store/Trie/CacheableKeyValueStore.cs
  Libplanet/Store/Trie/DefaultKeyValueStore.cs
  Libplanet/Store/Trie/IKeyValueStore.cs
  Libplanet/Store/Trie/KeyBytes.cs
  Libplanet/Store/Trie/MemoryKeyValueStore.cs
  Libplanet/Store/Trie/MerkleTrie.cs
  Libplanet/Store/TrieStateStore.cs
Labels: storage

#1682 Hotfix on non-blocking renderers & release 0.23.4
  CHANGES.md
  Libplanet.Tests/Blockchain/Renderers/NonblockRendererTest.cs
  Libplanet/Blockchain/Renderers/NonblockRenderer.cs
Labels: bug, release

#1683 Port 0.23.4 & release 0.24.2
  CHANGES.md
  Libplanet.Tests/Blockchain/Renderers/NonblockRendererTest.cs
  Libplanet/Blockchain/Renderers/NonblockRenderer.cs
Labels: release
