Repository planetarium/libplanet, pull requests merged in 2021-09, with the labels that each got.

#1455 fix: avoid `BinaryFormatter`
  CHANGES.md
  Libplanet.Tests/Net/BoundPeerTest.cs
  Libplanet.Tests/Net/PeerTest.cs
  Libplanet/Net/BoundPeer.cs
  Libplanet/Net/Messages/Message.cs
  Libplanet/Net/Peer.cs
Labels: bug

#1463 Limit number of `Transaction<T>`s per signer per block
  CHANGES.md
  Libplanet.Explorer.Executable/Program.cs
  Libplanet.Tests/Blockchain/BlockChainTest.Internals.cs
  Libplanet.Tests/Blockchain/BlockChainTest.MineBlock.cs
  Libplanet.Tests/Blockchain/NullPolicy.cs
  Libplanet/Blockchain/BlockChain.MineBlock.cs
  Libplanet/Blockchain/BlockChain.cs
  Libplanet/Blockchain/Policies/BlockPolicy.cs
  Libplanet/Blockchain/Policies/IBlockPolicy.cs
Labels: consensus

#1461 Dealing the timeout of the request of multiple replies & Release 0.15.2
  CHANGES.md
  Libplanet.Tests/Net/Protocols/TestTransport.cs
  Libplanet.Tests/Net/SwarmTest.Broadcast.cs
  Libplanet/Net/Swarm.cs
  Libplanet/Net/Transports/ITransport.cs
  Libplanet/Net/Transports/NetMQTransport.cs
Labels: network

#1386 Introduce partial chain recalculation
  CHANGES.md
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet/Blockchain/BlockChain.Recalculate.cs
  Libplanet/Blockchain/BlockChain.cs
  Libplanet/Blockchain/FungibleAssetStateCompleters.cs
  Libplanet/Blockchain/IncompleteBlockStatesException.cs
  Libplanet/Blockchain/StateCompleterSet.cs
  Libplanet/Blockchain/StateCompleters.cs
Labels: storage

#1475 `PrivateKey.FromString()` method
  CHANGES.md
  Libplanet.Extensions.Cocona/Commands/Key/DerivationCommand.cs
  Libplanet.Extensions.Cocona/Commands/KeyCommand.cs
  Libplanet.Tests.ruleset
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
  Libplanet.Tests/Crypto/PrivateKeyTest.cs
  Libplanet.Tests/Net/SwarmTest.Broadcast.cs
  Libplanet.Tests/Net/SwarmTest.cs
  Libplanet.Tests/Tx/TransactionTest.cs
  Libplanet/Crypto/PrivateKey.cs
Labels: suggestion

#1447 Let maximum transactions vary depending on block index
  CHANGES.md
  Libplanet.Explorer.Executable/Program.cs
  Libplanet.Tests/Blockchain/BlockChainTest.Append.cs
  Libplanet.Tests/Blockchain/BlockChainTest.MineBlock.cs
  Libplanet.Tests/Blockchain/NullPolicy.cs
  Libplanet/Blockchain/BlockChain.MineBlock.cs
  Libplanet/Blockchain/BlockChain.cs
  Libplanet/Blockchain/Policies/BlockPolicy.cs
  Libplanet/Blockchain/Policies/IBlockPolicy.cs
  Libplanet/Blocks/BlockExceedingTransactionsException.cs
Labels: consensus

#1477 `txPriority` option for `BlockChain<T>.MineBlock()` method
  CHANGES.md
  Libplanet.Tests.ruleset
  Libplanet.Tests/Blockchain/BlockChainTest.Internals.cs
  Libplanet.Tests/Blockchain/BlockChainTest.MineBlock.cs
  Libplanet.Tests/RandomExtensions.cs
  Libplanet/Blockchain/BlockChain.MineBlock.cs
  Libplanet/Blockchain/BlockChain.cs
Labels: suggestion

#1480 Streamed hashing
  .github/auto_assign.yml
  CHANGES.md
  Libplanet.Tests/HashAlgorithmTypeTest.cs
  Libplanet/HashAlgorithmType.cs
Labels: suggestion

#1481 Prevent `KeyNotFoundException` during `TransferTxs()`
  CHANGES.md
  Libplanet/Net/Swarm.MessageHandlers.cs
Labels: bug

#1423 Remove CreatePermission in NetMQTransport
  CHANGES.md
  Libplanet/Net/Transports/NetMQTransport.cs
Labels: network

#1491 Fix BlockChain<T>.MineBlock() for dupped nonce & Release 0.15.4
  CHANGES.md
  Libplanet.Tests/Blockchain/BlockChainTest.MineBlock.cs
  Libplanet/Blockchain/BlockChain.cs
Labels: bug

#1493 Set session timeout of block completion into SwarmOptions.MaxTimeout
  Libplanet/Net/Swarm.BlockSync.cs
Labels: network

#1478 Fill transactions from multiple peers
  CHANGES.md
  Libplanet.Tests/Net/SwarmTest.Broadcast.cs
  Libplanet.Tests/Net/SwarmTest.cs
  Libplanet/Net/Swarm.MessageHandlers.cs
  Libplanet/Net/Swarm.cs
  Libplanet/Net/TxCompletion.cs
Labels: network

#1501 Release 0.17.0
  CHANGES.md
Labels: release
