Repository planetarium/libplanet, pull requests merged in 2021-01, with the labels that each got.

#1137 feat(cli): provide useful commands
  CHANGES.md
  Libplanet.Tools/Mpt.cs
Labels: tools

#1153 Fix broken crefs to System.* on docs.libplanet.io
  .github/workflows/benchmarks.yml
  .github/workflows/check-build.yaml
  .github/workflows/main.yml
  Docs/build.ps1
  Docs/docfx.json
Labels: bug, docs

#1162 fix: use protocol version of existing block
  CHANGES.md
  Libplanet.Tests/Store/StoreTest.cs
  Libplanet/Store/BaseStore.cs
Labels: bug

#1167 fix(net): reset block demand when not changed
  Libplanet.Tests/Menees.Analyzers.Settings.xml
  Libplanet.Tests/Net/SwarmTest.cs
  Libplanet/Net/Swarm.cs
Labels: bug

#1168 Add Hash validation to Block<T>.Validate()
  CHANGES.md
  Libplanet.Tests/Blocks/BlockHeaderTest.cs
  Libplanet/Blocks/Block.cs
  Libplanet/Blocks/BlockHeader.cs
Labels: bug

#1170 Motivate miners to upgrade protocol version
  CHANGES.md
  Libplanet.Tests/Blockchain/BlockChainTest.ValidateNextBlock.cs
  Libplanet.Tests/Blockchain/TotalDifficultyComparerTest.cs
  Libplanet.Tests/Blocks/BlockHeaderTest.cs
  Libplanet.Tests/Blocks/BlockTest.cs
  Libplanet/Blockchain/TotalDifficultyComparer.cs
  Libplanet/Blocks/Block.cs
  Libplanet/Blocks/BlockExcerpt.cs
  Libplanet/Blocks/BlockHeader.cs
  Libplanet/Blocks/IBlockExcerpt.cs
  Libplanet/Net/Messages/ChainStatus.cs
  Libplanet/Net/Swarm.MessageHandlers.cs
Labels: consensus

#1175 Port of #1168
  CHANGES.md
  Libplanet.Tests/Blocks/BlockHeaderTest.cs
  Libplanet/Blocks/Block.cs
  Libplanet/Blocks/BlockHeader.cs
Labels: bug

#1169 docs: add missing links
  CHANGES.md
Labels: docs

#1171 Add lifespan to messages
  CHANGES.md
  Libplanet.Tests/Net/Messages/BlockHashesTest.cs
  Libplanet.Tests/Net/Messages/MessageTest.cs
  Libplanet.Tests/Net/SwarmTest.cs
  Libplanet/Net/InvalidTimestampException.cs
  Libplanet/Net/Messages/Message.cs
  Libplanet/Net/NetMQTransport.cs
  Libplanet/Net/Protocols/KademliaProtocol.cs
  Libplanet/Net/Swarm.cs
  Libplanet/Net/SwarmOptions.cs
Labels: network
