Repository planetarium/libplanet, pull requests merged in 2021-08, with the labels that each got.

#1400 Explicit package reference to Microsoft.Bcl.AsyncInterfaces
  Libplanet.Tests/Libplanet.Tests.csproj
Labels: analyzer

#1415 Refactor/broadcast before rendering
  CHANGES.md
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet.Tests/Blockchain/Renderers/AtomicActionRendererTest.cs
  Libplanet.Tests/Blockchain/Renderers/DelayedActionRendererTest.cs
  Libplanet/Blockchain/BlockChain.Swap.cs
  Libplanet/Blockchain/BlockChain.cs
  Libplanet/Net/Swarm.BlockSync.cs
  Libplanet/Net/Swarm.cs
Labels: network

#1424 Release 0.13.2 & Fix TURN reconnection
  CHANGES.md
  Libplanet.Stun/Stun/TurnClient.cs
Labels: network

#1427 Release 0.14.0 (with 0.13.2 port)
  CHANGES.md
  Libplanet.Stun/Stun/TurnClient.cs
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet.Tests/Blockchain/Renderers/AtomicActionRendererTest.cs
  Libplanet.Tests/Blockchain/Renderers/DelayedActionRendererTest.cs
  Libplanet.Tests/Libplanet.Tests.csproj
  Libplanet/Blockchain/BlockChain.Swap.cs
  Libplanet/Blockchain/BlockChain.cs
  Libplanet/Net/Swarm.BlockSync.cs
  Libplanet/Net/Swarm.cs
Labels: release

#1437 Release 0.15.0 (with 0.14.1 port)
  CHANGES.md
  Libplanet/Blockchain/Renderers/LoggedRenderer.cs
  Libplanet/Net/Swarm.cs
  Libplanet/Net/Transports/NetMQTransport.cs
Labels: release

#1425 Sync recent blocks from multiple peers simultaneously
  CHANGES.md
  Libplanet.Tests/Net/SwarmTest.Broadcast.cs
  Libplanet.Tests/Net/SwarmTest.Preload.cs
  Libplanet.Tests/Net/SwarmTest.cs
  Libplanet/Blockchain/Renderers/Debug/ValidatingActionRenderer.cs
  Libplanet/Net/BlockDemand.cs
  Libplanet/Net/BlockDemandTable.cs
  Libplanet/Net/Swarm.BlockSync.cs
  Libplanet/Net/Swarm.MessageHandlers.cs
  Libplanet/Net/Swarm.cs
  Libplanet/Net/SwarmOptions.cs
Labels: network

#1439 Release 0.16.0
  CHANGES.md
Labels: release

#1456 Append Git commit hash to version suffix
  .github/bin/dist-pack.sh
  README.md
Labels: ci/github-actions
