Repository planetarium/libplanet, pull requests merged in 2021-11, with the labels that each got.

#1571 Disallow shorter/longer private keys than 32 bytes & release 0.18.4
  CHANGES.md
  Libplanet.Tests/Crypto/PrivateKeyTest.cs
  Libplanet/Crypto/PrivateKey.cs
  Libplanet/KeyStore/ProtectedPrivateKey.cs
  Libplanet/Libplanet.csproj
Labels: bug, release

#1572 Merge 0.18.4 into 0.19-maintenance (to be 0.19.2)
  CHANGES.md
  Libplanet.Tests/Crypto/PrivateKeyTest.cs
  Libplanet/Crypto/PrivateKey.cs
  Libplanet/KeyStore/ProtectedPrivateKey.cs
Labels: bug

#1575 Fix bug of streamed hash calculation & release 0.18.5
  CHANGES.md
  Libplanet.Tests/Blocks/HashAlgorithmTableTest.cs
  Libplanet.Tests/HashAlgorithmTypeTest.cs
  Libplanet/HashAlgorithmType.cs
  Libplanet/Libplanet.csproj
Labels: bug, release

#1574 Deprecate `MonoRocksDBStore`
  CHANGES.md
  Libplanet.Explorer.Executable/Program.cs
  Libplanet.Extensions.Cocona.Tests/Commands/StatsCommandTest.cs
  Libplanet.Extensions.Cocona.Tests/Commands/StoreCommandTest.cs
  Libplanet.Extensions.Cocona/Commands/StatsCommand.cs
  Libplanet.Extensions.Cocona/Commands/StoreCommand.cs
  Libplanet.RocksDBStore.Tests/MonoRocksDBStoreFixture.cs
  Libplanet.RocksDBStore.Tests/MonoRocksDBStoreTest.cs
  Libplanet.RocksDBStore/MonoRocksDBStore.cs
Labels: storage, api

#1576 Port 0.18.5 & release 0.19.2
  CHANGES.md
  Libplanet.Tests/Blocks/HashAlgorithmTableTest.cs
  Libplanet.Tests/HashAlgorithmTypeTest.cs
  Libplanet/HashAlgorithmType.cs
Labels: release

#1577 Port 0.19.2 & release 0.20.0
  CHANGES.md
  Libplanet.Tests/Blocks/HashAlgorithmTableTest.cs
  Libplanet.Tests/Crypto/PrivateKeyTest.cs
  Libplanet.Tests/HashAlgorithmTypeTest.cs
  Libplanet/Crypto/PrivateKey.cs
  Libplanet/HashAlgorithmType.cs
  Libplanet/KeyStore/ProtectedPrivateKey.cs
Labels: release

#1579 Completely get rid of `MonoRocksDBStore`
  CHANGES.md
  Libplanet.Explorer.Executable/Program.cs
  Libplanet.Extensions.Cocona.Tests/Commands/StatsCommandTest.cs
  Libplanet.Extensions.Cocona.Tests/Commands/StoreCommandTest.cs
  Libplanet.Extensions.Cocona/Commands/StatsCommand.cs
  Libplanet.Extensions.Cocona/Commands/StoreCommand.cs
  Libplanet.RocksDBStore.Tests/MonoRocksDBStoreFixture.cs
  Libplanet.RocksDBStore.Tests/MonoRocksDBStoreTest.cs
  Libplanet.RocksDBStore/MonoRocksDBStore.cs
Labels: storage, api

#1580 Bad log fix
  Libplanet/Blockchain/BlockChain.MineBlock.cs
Labels: bug

#1582 Broadcast new blocks immediately after they are appended
  CHANGES.md
  Libplanet.Tests/Blockchain/NullPolicy.cs
  Libplanet.Tests/Net/SwarmTest.Broadcast.cs
  Libplanet.Tests/Net/SwarmTest.cs
  Libplanet/Blockchain/BlockChain.cs
  Libplanet/Net/Swarm.BlockSync.cs
  Libplanet/Net/Swarm.cs
Labels: bug, network

#1584 Experiments with CircleCI as a replacement of Azure Pipelines
  .circleci/config.yml
  .circleci/xunit-junit.xslt
  .github/workflows/check-build.yaml
  .gitignore
  CONTRIBUTING.md
  Libplanet.Analyzers.Tests/ActionAnalyzerTest.cs
  Libplanet.Analyzers.Tests/CSharpAnalysisFactAttribute.cs
  Libplanet.Analyzers.Tests/Libplanet.Analyzers.Tests.csproj
  Libplanet.Analyzers.Tests/Verifiers/CSharpAnalysisTheoryAttribute.cs
  Libplanet.Explorer.UnitTests/Libplanet.Explorer.UnitTests.csproj
  Libplanet.Explorer/Libplanet.Explorer.csproj
  Libplanet.Extensions.Cocona.Tests/Libplanet.Extensions.Cocona.Tests.csproj
  Libplanet.RocksDBStore.Tests/Libplanet.RocksDBStore.Tests.csproj
  Libplanet.Stun.Tests/Libplanet.Stun.Tests.csproj
  Libplanet.Tests/Blockchain/BlockChainTest.MineBlock.cs
  Libplanet.Tests/Libplanet.Tests.csproj
  Libplanet.Tests/Net/BlockCompletionTest.cs
  Libplanet.Tests/Net/SwarmTest.Broadcast.cs
  Libplanet.Tests/Net/SwarmTest.Preload.cs
  Libplanet.Tests/Net/SwarmTest.cs
  Libplanet/KeyStore/Web3KeyStore.cs
  README.md
Labels: discussion needed, ci & cd

#1585 Release 0.19.3
  CHANGES.md
Labels: release

#1586 Port 0.19.3 & release 0.20.1
  .circleci/config.yml
  .circleci/xunit-junit.xslt
  .github/workflows/check-build.yaml
  .gitignore
  CHANGES.md
  CONTRIBUTING.md
  Libplanet.Analyzers.Tests/ActionAnalyzerTest.cs
  Libplanet.Analyzers.Tests/CSharpAnalysisFactAttribute.cs
  Libplanet.Analyzers.Tests/Libplanet.Analyzers.Tests.csproj
  Libplanet.Analyzers.Tests/Verifiers/CSharpAnalysisTheoryAttribute.cs
  Libplanet.Explorer.UnitTests/Libplanet.Explorer.UnitTests.csproj
  Libplanet.Explorer/Libplanet.Explorer.csproj
  Libplanet.Extensions.Cocona.Tests/Libplanet.Extensions.Cocona.Tests.csproj
  Libplanet.RocksDBStore.Tests/Libplanet.RocksDBStore.Tests.csproj
  Libplanet.Stun.Tests/Libplanet.Stun.Tests.csproj
  Libplanet.Tests/Blockchain/BlockChainTest.MineBlock.cs
  Libplanet.Tests/Blockchain/NullPolicy.cs
  Libplanet.Tests/Libplanet.Tests.csproj
  Libplanet.Tests/Net/BlockCompletionTest.cs
  Libplanet.Tests/Net/SwarmTest.Broadcast.cs
  Libplanet.Tests/Net/SwarmTest.Preload.cs
  Libplanet.Tests/Net/SwarmTest.cs
  Libplanet/Blockchain/BlockChain.MineBlock.cs
  Libplanet/Blockchain/BlockChain.cs
  Libplanet/KeyStore/Web3KeyStore.cs
  Libplanet/Net/Swarm.BlockSync.cs
  Libplanet/Net/Swarm.cs
  README.md
Labels: release

#1592 Fix RockDBStore.ForkIndexes() bug
  CHANGES.md
  Libplanet.RocksDBStore/RocksDBStore.cs
  Libplanet.Tests/Store/StoreTest.cs
Labels: bug, storage

#1595 Release 0.20.2
  CHANGES.md
Labels: release

#1570 Tune `MerkleTrie`
  CHANGES.md
  Libplanet.RocksDBStore/RocksDBKeyValueStore.cs
  Libplanet.Tests/Store/StateStoreExtensionsTest.cs
  Libplanet.Tests/Store/Trie/KeyValueStoreTest.cs
  Libplanet.Tests/Store/TrieStateStoreTest.cs
  Libplanet/Store/StateStoreExtensions.cs
  Libplanet/Store/Trie/CacheableKeyValueStore.cs
  Libplanet/Store/Trie/DefaultKeyValueStore.cs
  Libplanet/Store/Trie/IKeyValueStore.cs
  Libplanet/Store/Trie/ITrie.cs
  Libplanet/Store/Trie/MemoryKeyValueStore.cs
  Libplanet/Store/Trie/MerkleTrie.cs
Labels: storage

#1523 Introduce TCP transport
  .gitignore
  CHANGES.md
  Libplanet.Extensions.Cocona/Commands/ApvCommand.cs
  Libplanet.Tests/Net/Protocols/ProtocolTest.cs
  Libplanet.Tests/Net/Protocols/TestTransport.cs
  Libplanet.Tests/Net/SwarmTest.Broadcast.cs
  Libplanet.Tests/Net/SwarmTest.Fixtures.cs
  Libplanet.Tests/Net/SwarmTest.cs
  Libplanet.Tests/Net/Transports/BoundPeerExtensionsTest.cs
  Libplanet.Tests/Net/Transports/NetMQTransportTest.cs
  Libplanet.Tests/Net/Transports/TcpTransportTest.cs
  Libplanet.Tests/Net/Transports/TransportTest.cs
  Libplanet/Net/AsyncDelegate.cs
  Libplanet/Net/Messages/MessageCodec.cs
  Libplanet/Net/Protocols/KademliaProtocol.cs
  Libplanet/Net/Swarm.MessageHandlers.cs
  Libplanet/Net/Swarm.cs
  Libplanet/Net/SwarmOptions.cs
  Libplanet/Net/Transports/BoundPeerExtensions.cs
  Libplanet/Net/Transports/ITransport.cs
  Libplanet/Net/Transports/InvalidMagicCookieException.cs
  Libplanet/Net/Transports/NetMQTransport.cs
  Libplanet/Net/Transports/TcpTransport.cs
Labels: network

#1603 Get away from Azure Pipelines
  .azure-pipelines/dotnet-core.yml
  .azure-pipelines/mono.yml
  .github/auto_assign.yml
  .github/workflows/check-build.yaml
  CONTRIBUTING.md
  README.md
  azure-pipelines.yml
Labels: ci & cd

#1604 Release 0.21.0
  CHANGES.md
Labels: release

#1609 Upgrade Bencodex to 0.4.0-dev.20211123080042+d7f6c810
  CHANGES.md
  Libplanet.Analyzers.Tests/ActionAnalyzerTest.cs
  Libplanet.Explorer.Executable/Program.cs
  Libplanet.Explorer/GraphTypes/ActionType.cs
  Libplanet.Extensions.Cocona.Tests/Commands/MptCommandTest.cs
  Libplanet.Tests/Action/ActionContextTest.cs
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
  Libplanet.Tests/Blockchain/BlockChainTest.Append.cs
  Libplanet.Tests/Blockchain/BlockChainTest.MineBlock.cs
  Libplanet.Tests/Blockchain/NullPolicy.cs
  Libplanet.Tests/Blocks/BlockTest.cs
  Libplanet.Tests/Common/Action/RandomAction.cs
  Libplanet.Tests/Fixtures/Arithmetic.cs
  Libplanet.Tests/Net/AppProtocolVersionTest.cs
  Libplanet.Tests/Net/SwarmTest.cs
  Libplanet.Tests/Store/Trie/MerkleTrieExtensionsTest.cs
  Libplanet.Tests/Store/Trie/MerkleTrieTest.cs
  Libplanet.Tests/Store/Trie/Nodes/FullNodeTest.cs
  Libplanet.Tests/Store/Trie/Nodes/NodeDecoderTest.cs
  Libplanet.Tests/Store/Trie/Nodes/ShortNodeTest.cs
  Libplanet.Tests/Store/Trie/Nodes/ValueNodeTest.cs
  Libplanet.Tests/Tx/TransactionTest.cs
  Libplanet/Blockchain/BlockChain.MineBlock.cs
  Libplanet/Blockchain/Policies/BlockPolicy.cs
  Libplanet/Blockchain/Policies/IBlockPolicy.cs
  Libplanet/Blockchain/Renderers/Debug/ValidatingActionRenderer.cs
  Libplanet/Blocks/Block.cs
  Libplanet/Blocks/BlockMarshaler.cs
  Libplanet/Blocks/InvalidBlockBytesLengthException.cs
  Libplanet/Libplanet.csproj
  Libplanet/Store/BaseStore.cs
  Libplanet/Store/Trie/MerkleTrie.cs
  Libplanet/Store/Trie/Nodes/BaseNode.cs
  Libplanet/Store/Trie/Nodes/FullNode.cs
  Libplanet/Store/Trie/Nodes/HashNode.cs
  Libplanet/Store/Trie/Nodes/NodeDecoder.cs
  Libplanet/Store/Trie/Nodes/ShortNode.cs
  Libplanet/Store/Trie/Nodes/ValueNode.cs
  Libplanet/Tx/Transaction.cs
Labels: storage

#1615 Release 0.21.1
  CHANGES.md
Labels: release

#1624 Change LRU cache implementation for `BlockSet<T>`
  CHANGES.md
  Libplanet/Libplanet.csproj
  Libplanet/Store/BlockSet.cs
Labels: storage

#1625 Distribute Libplanet.Stun as a separate NuGet package
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: network, packaging

#1629 Release 0.22.0
  CHANGES.md
Labels: release
