Repository planetarium/libplanet, pull requests merged in 2021-05, with the labels that each got.

#1278 Enforce AsyncIO in NetMQTransport instead of Swarm<T>
  CHANGES.md
  Libplanet/Net/Swarm.cs
  Libplanet/Net/Transports/NetMQTransport.cs
Labels: bug, network

#1275 Execute `Transaction<T>.Actions` all or nothing at all
  CHANGES.md
  Libplanet.Tests/Action/ActionContextTest.cs
  Libplanet.Tests/Action/ActionEvaluationTest.cs
  Libplanet.Tests/Blockchain/Renderers/AnonymousActionRendererTest.cs
  Libplanet.Tests/Blockchain/Renderers/AtomicActionRendererTest.cs
  Libplanet.Tests/Blockchain/Renderers/DelayedActionRendererTest.cs
  Libplanet.Tests/Blockchain/Renderers/LoggedActionRendererTest.cs
  Libplanet.Tests/Fixtures/Arithmetic.cs
  Libplanet.Tests/Fixtures/IntegerSet.cs
  Libplanet.Tests/Fixtures/OperatorType.cs
  Libplanet.Tests/Fixtures/OperatorTypeExtensions.cs
  Libplanet.Tests/RandomExtensions.cs
  Libplanet.Tests/Tx/TransactionTest.cs
  Libplanet/Action/ActionContext.cs
  Libplanet/Action/ActionEvaluation.cs
  Libplanet/Action/IActionContext.cs
  Libplanet/Blockchain/BlockChain.cs
  Libplanet/Blockchain/Renderers/AtomicActionRenderer.cs
  Libplanet/Blockchain/Renderers/DelayedActionRenderer.cs
  Libplanet/Blockchain/Renderers/IActionRenderer.cs
  Libplanet/Tx/Transaction.cs
Labels: bug

#1291 feat(explorer): use directly chain & store, from context
  .idea/.idea.Libplanet/.idea/indexLayout.xml
  Libplanet.Explorer/Queries/Query.cs
Labels: bug, explorer

#1226 Don't include executable project when bundle
  .github/bin/bundle.sh
Labels: bug

#1308 Fix a typo in `Libplanet.Explorer.Queries.Query.IsValidTransacion`
  Libplanet.Explorer/Queries/ExplorerQuery.cs
Labels: bug, explorer

#1304 Let `BlockChain<T>.MineBlock()` also updates `TxExecution`s
  .github/workflows/push-docker-image.yml
  .idea/.idea.Libplanet/.idea/indexLayout.xml
  Libplanet.Extensions.Cocona/Commands/ApvCommand.cs
  Libplanet.Tests/Blockchain/BlockChainTest.Append.cs
  Libplanet.Tests/Blockchain/BlockChainTest.Internals.cs
  Libplanet.Tests/Blockchain/BlockChainTest.MineBlock.cs
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet/Action/AccountStateDeltaExtensions.cs
  Libplanet/Blockchain/BlockChain.TxExecution.cs
  Libplanet/Blockchain/BlockChain.cs
Labels: bug

#1233 feat(cli): improve `mpt diff` output
  CHANGES.md
  CONTRIBUTING.md
  Libplanet.Extensions.Cocona.Tests/Commands/MptCommandTest.cs
  Libplanet.Extensions.Cocona.Tests/Libplanet.Extensions.Cocona.Tests.csproj
  Libplanet.Extensions.Cocona.Tests/Services/TestToolConfigurationService.cs
  Libplanet.Extensions.Cocona/Commands/KeyCommand.cs
  Libplanet.Extensions.Cocona/Commands/MptCommand.cs
  Libplanet.Extensions.Cocona/Libplanet.Extensions.Cocona.csproj
  Libplanet.Extensions.Cocona/Utils.cs
  Libplanet.sln
  Libplanet/AssemblyInfo.cs
Labels: tools

#1311 Remove `IActionContext.BlockHash` property
  .vscode/settings.json
  CHANGES.md
  Libplanet.Tests/Action/ActionContextTest.cs
  Libplanet.Tests/Action/ActionEvaluationTest.cs
  Libplanet.Tests/Blockchain/Renderers/AnonymousActionRendererTest.cs
  Libplanet.Tests/Blockchain/Renderers/DelayedActionRendererTest.cs
  Libplanet.Tests/Blockchain/Renderers/LoggedActionRendererTest.cs
  Libplanet.sln.DotSettings
  Libplanet/Action/ActionContext.cs
  Libplanet/Action/ActionEvaluation.cs
  Libplanet/Action/IActionContext.cs
Labels: bug

#1312 Semantic highlighting update for VSCode
  .vscode/settings.json
Labels: suggestion

#1298 feat: add store block, tx commands
  CHANGES.md
  Libplanet.Extensions.Cocona.Tests/Commands/StoreCommandTest.cs
  Libplanet.Extensions.Cocona.Tests/Libplanet.Extensions.Cocona.Tests.csproj
  Libplanet.Extensions.Cocona.Tests/UtilsTest.cs
  Libplanet.Extensions.Cocona/Commands/StoreCommand.cs
  Libplanet.Extensions.Cocona/Utils.cs
  Libplanet.RocksDBStore.Tests/MonoRocksDBStoreFixture.cs
  Libplanet.RocksDBStore.Tests/RocksDBStoreFixture.cs
  Libplanet.Tests/Store/DefaultStoreFixture.cs
  Libplanet.Tests/Store/StoreFixture.cs
  Libplanet.Tools/Program.cs
Labels: tools
