Repository planetarium/libplanet, pull requests merged in 2022-09, with the labels that each got.

#2273 `BlockChain<T>.MakeTransaction()` for system actions
  CHANGES.md
  Libplanet.Net.Tests/SwarmTest.Broadcast.cs
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet/Blockchain/BlockChain.cs
Labels: bug, api, Small

#2276 No more automatically assign every maintainer
  .github/auto_assign.yml
Labels: Extra Small

#2277 Reinstate missing tests
  Libplanet.Net.Tests/SwarmTest.cs
Labels: Extra Large

#2278 Longer propagation delay for test
  Libplanet.Net.Tests/Consensus/ConsensusReactorTestBase.cs
  Libplanet.Net.Tests/SwarmTest.Broadcast.cs
Labels: Extra Small

#2279 Fix typo on the CHANGES.md
  CHANGES.md
Labels: docs, Extra Small

#2284 🔀 Merge main to pbft
  .github/auto_assign.yml
  CHANGES.md
  Libplanet.Net.Tests/SwarmTest.Broadcast.cs
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet/Blockchain/BlockChain.cs
  Libplanet/Libplanet.csproj
Labels: Small

#2283 ⬆️ Bump becodex to 0.5.0
  CHANGES.md
  Libplanet.Tests/Action/PolymorphicActionTest.cs
  Libplanet.Tests/Assets/CurrencyTest.cs
  Libplanet.Tests/Blocks/BlockMarshalerTest.cs
  Libplanet.Tests/Common/Action/DumbAction.cs
  Libplanet.Tests/Fixtures/Arithmetic.cs
  Libplanet.Tests/Store/StoreTest.cs
  Libplanet.Tests/Tx/TransactionTest.cs
  Libplanet/Action/PolymorphicAction.cs
  Libplanet/Action/Sys/Mint.cs
  Libplanet/Action/Sys/Registry.cs
  Libplanet/Action/Sys/Transfer.cs
  Libplanet/Assets/Currency.cs
  Libplanet/Blocks/BlockMarshaler.cs
  Libplanet/Blocks/BlockMetadata.cs
  Libplanet/Libplanet.csproj
  Libplanet/Store/BaseStore.cs
Labels: Medium

#2189 Add innerAction name getter
  CHANGES.md
  Libplanet/Action/PolymorphicAction.cs
Labels: Extra Small, Squash Needed

#2198 Add Block, Explorer, Transaction schema classes.
  CHANGES.md
  Libplanet.Explorer/Schemas/LibplanetExplorerSchema.cs
Labels: Extra Small, Squash Needed, sprint-20220821

#2289 🧹 Clean up unnecessary log
  Libplanet.Net/Transports/NetMQTransport.cs
Labels: Extra Small

#2282 Add `BondedValidatorSet`
  Libplanet.Tests/PoS/BondedValidatorSetCtrlTest.cs
  Libplanet.Tests/PoS/BondedValidatorSetTest.cs
  Libplanet.Tests/PoS/BondedValidatorTest.cs
  Libplanet.Tests/PoS/DelegationTest.cs
  Libplanet.Tests/PoS/RedelegationEntryTest.cs
  Libplanet.Tests/PoS/RedelegationTest.cs
  Libplanet.Tests/PoS/UndelegationEntryTest.cs
  Libplanet.Tests/PoS/UndelegationTest.cs
  Libplanet.Tests/PoS/ValidatorPowerComparerTest.cs
  Libplanet.Tests/PoS/ValidatorPowerIndexCtrlTest.cs
  Libplanet.Tests/PoS/ValidatorPowerTest.cs
  Libplanet.Tests/PoS/ValidatorTest.cs
  Libplanet/PoS/Control/BondedValidatorSetCtrl.cs
  Libplanet/PoS/Control/ValidatorPowerSetCtrl.cs
  Libplanet/PoS/Misc/ReservedAddress.cs
  Libplanet/PoS/Model/BondedValidator.cs
  Libplanet/PoS/Model/BondedValidatorSet.cs
  Libplanet/PoS/Model/Delegation.cs
  Libplanet/PoS/Model/Redelegation.cs
  Libplanet/PoS/Model/RedelegationEntry.cs
  Libplanet/PoS/Model/UnbondingSet.cs
  Libplanet/PoS/Model/Undelegation.cs
  Libplanet/PoS/Model/UndelegationEntry.cs
  Libplanet/PoS/Model/Validator.cs
  Libplanet/PoS/Model/ValidatorPower.cs
  Libplanet/PoS/Model/ValidatorPowerIndex.cs
  Libplanet/PoS/Model/ValidatorPowerSet.cs
  Libplanet/PoS/Util/AddressComparer.cs
  Libplanet/PoS/Util/ValidatorPowerComparer.cs
Labels: Extra Large

#2292 Minor `BlockContent` refactor
  CHANGES.md
  Libplanet.Net.Tests/SwarmTest.Preload.cs
  Libplanet.Tests/Blocks/BlockMetadataTest.cs
  Libplanet.Tests/TestUtils.cs
  Libplanet/Blocks/BlockContent.cs
  Libplanet/Blocks/BlockMetadata.cs
  Libplanet/Blocks/PreEvaluationBlock.cs
  Libplanet/Blocks/PreEvaluationBlockHeader.cs
Labels: Extra Small

#2293 Make namespaces correct
  Libplanet.Tests/PoS/BondedValidatorSetCtrlTest.cs
  Libplanet.Tests/PoS/DelegateCtrlTest.cs
  Libplanet.Tests/PoS/RedelegateCtrlTest.cs
  Libplanet.Tests/PoS/UndelegateCtrlTest.cs
  Libplanet.Tests/PoS/ValidatorCtrlTest.cs
  Libplanet.Tests/PoS/ValidatorPowerIndexCtrlTest.cs
  Libplanet.Tests/PoS/ValidatorPowerSetCtrlTest.cs
  Libplanet.Tests/PoS/ValidatorTest.cs
  Libplanet/PoS/Action/Sys/CancelUndelegation.cs
  Libplanet/PoS/Action/Sys/Delegate.cs
  Libplanet/PoS/Action/Sys/PromoteValidator.cs
  Libplanet/PoS/Action/Sys/Redelegate.cs
  Libplanet/PoS/Action/Sys/Undelegate.cs
  Libplanet/PoS/Control/Bond.cs
  Libplanet/PoS/Control/BondedValidatorSetCtrl.cs
  Libplanet/PoS/Control/DelegateCtrl.cs
  Libplanet/PoS/Control/RedelegateCtrl.cs
  Libplanet/PoS/Control/UnbondingSetCtrl.cs
  Libplanet/PoS/Control/UndelegateCtrl.cs
  Libplanet/PoS/Control/ValidatorCtrl.cs
  Libplanet/PoS/Control/ValidatorPowerIndexCtrl.cs
  Libplanet/PoS/Control/ValidatorPowerSetCtrl.cs
  Libplanet/PoS/Model/Validator.cs
Labels: Small, pos

#2291 Check marshaled transactions size instead of entire block size
  CHANGES.md
  Libplanet.Explorer.Executable/Options.cs
  Libplanet.Explorer.Executable/Program.cs
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
  Libplanet.Tests/Blockchain/BlockChainTest.Append.cs
  Libplanet.Tests/Blockchain/BlockChainTest.MineBlock.cs
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet/Blockchain/BlockChain.MineBlock.cs
  Libplanet/Blockchain/Policies/BlockPolicy.cs
  Libplanet/Blockchain/Policies/IBlockPolicy.cs
  Libplanet/Blockchain/Policies/NullBlockPolicy.cs
  Libplanet/Blocks/BlockMarshaler.cs
  Libplanet/Blocks/InvalidBlockBytesLengthException.cs
Labels: Medium

#2299 🔀 Merge main to pbft
  CHANGES.md
  Libplanet.Explorer.Executable/Options.cs
  Libplanet.Explorer.Executable/Program.cs
  Libplanet.Explorer/Schemas/LibplanetExplorerSchema.cs
  Libplanet.Net.Tests/TestUtils.cs
  Libplanet.Net/Transports/NetMQTransport.cs
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
  Libplanet.Tests/Action/PolymorphicActionTest.cs
  Libplanet.Tests/Assets/CurrencyTest.cs
  Libplanet.Tests/Blockchain/BlockChainTest.Append.cs
  Libplanet.Tests/Blockchain/BlockChainTest.MineBlock.cs
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet.Tests/Common/Action/DumbAction.cs
  Libplanet.Tests/Fixtures/Arithmetic.cs
  Libplanet.Tests/Store/StoreTest.cs
  Libplanet.Tests/Tx/TransactionTest.cs
  Libplanet/Action/PolymorphicAction.cs
  Libplanet/Action/Sys/Mint.cs
  Libplanet/Action/Sys/Registry.cs
  Libplanet/Action/Sys/Transfer.cs
  Libplanet/Assets/Currency.cs
  Libplanet/Blockchain/BlockChain.MineBlock.cs
  Libplanet/Blockchain/Policies/BlockPolicy.cs
  Libplanet/Blockchain/Policies/IBlockPolicy.cs
  Libplanet/Blockchain/Policies/NullBlockPolicy.cs
  Libplanet/Blocks/BlockMarshaler.cs
  Libplanet/Blocks/InvalidBlockBytesLengthException.cs
  Libplanet/Libplanet.csproj
  Libplanet/Store/BaseStore.cs
Labels: Large

#2302 🧹 General renaming and reordering of fixture construction
  Libplanet.Tests/Blocks/BlockContentExtensionsTest.cs
  Libplanet.Tests/Blocks/BlockContentTest.cs
  Libplanet.Tests/Blocks/BlockMarshalerTest.cs
  Libplanet.Tests/Blocks/BlockMetadataExtensionsTest.cs
  Libplanet.Tests/Blocks/BlockMetadataTest.cs
  Libplanet.Tests/Blocks/BlockTest.cs
  Libplanet.Tests/Blocks/PreEvaluationBlockHeaderTest.cs
  Libplanet.Tests/Blocks/PreEvaluationBlockTest.cs
  Libplanet.Tests/Fixtures/BlockContentFixture.cs
Labels: Extra Large

#2304 🔀 Merge main to pbft
  Libplanet.Tests/Blocks/BlockContentExtensionsTest.cs
  Libplanet.Tests/Blocks/BlockContentTest.cs
  Libplanet.Tests/Blocks/BlockMarshalerTest.cs
  Libplanet.Tests/Blocks/BlockMetadataExtensionsTest.cs
  Libplanet.Tests/Blocks/BlockMetadataTest.cs
  Libplanet.Tests/Blocks/BlockTest.cs
  Libplanet.Tests/Blocks/PreEvaluationBlockHeaderTest.cs
  Libplanet.Tests/Blocks/PreEvaluationBlockTest.cs
  Libplanet.Tests/Fixtures/BlockContentFixture.cs
Labels: Large

#2237 Add verifiable random function
  CHANGES.md
  Libplanet.Tests/Crypto/VrfTest.cs
  Libplanet/Crypto/DefaultCryptoBackend.cs
  Libplanet/Crypto/ICryptoBackend.cs
  Libplanet/Crypto/PrivateKey.cs
  Libplanet/Crypto/PublicKey.cs
Labels: Medium, pbft

#2305 document: fix changelog due to change on target branch
  CHANGES.md
Labels: Extra Small

#2310 🔀 Merge main to pbft
  CHANGES.md
  Libplanet.Node.Tests/UntypedTransactionTest.cs
  Libplanet.Tests/Blocks/BlockMarshalerTest.cs
  Libplanet.Tests/Common/Action/Attack.cs
  Libplanet.Tests/Common/Action/BattleResult.cs
  Libplanet.Tests/Common/Action/DetectRehearsal.cs
  Libplanet.Tests/Common/Action/DumbAction.cs
  Libplanet.Tests/Common/Action/MinerReward.cs
  Libplanet.Tests/Common/Action/Sleep.cs
  Libplanet.Tests/Common/Action/ThrowException.cs
  Libplanet.Tests/Store/Trie/MerkleTrieTest.cs
  Libplanet.Tests/Tx/TxMetadataTest.cs
  Libplanet/Assets/Currency.cs
  Libplanet/Blocks/BlockCommit.cs
  Libplanet/Libplanet.csproj
  Libplanet/Store/BlockDigest.cs
  Libplanet/Tx/TxMetadata.cs
  Libplanet/Tx/TxSuccess.cs
Labels: Medium

#2223 Introduce BLS digital signature
  CHANGES.md
  Libplanet.Tests/Crypto/BlsPrivateKeyTest.cs
  Libplanet.Tests/Crypto/BlsPublicKeyTest.cs
  Libplanet.Tests/Crypto/BlsSignatureTest.cs
  Libplanet.Tests/Crypto/PrivateKeyTest.cs
  Libplanet.Tests/Crypto/PublicKeyTest.cs
  Libplanet/Consensus/Vote.cs
  Libplanet/Crypto/BlsCryptoBackend.cs
  Libplanet/Crypto/BlsPrivateKey.cs
  Libplanet/Crypto/BlsPublicKey.cs
  Libplanet/Crypto/BlsSignature.cs
  Libplanet/Crypto/BlsSignatureExtensions.cs
  Libplanet/Crypto/CryptoConfig.cs
  Libplanet/Crypto/DefaultCryptoBackend.cs
  Libplanet/Crypto/ICryptoBackend.cs
  Libplanet/Crypto/IPrivateKey.cs
  Libplanet/Crypto/IPublicKey.cs
  Libplanet/Crypto/PrivateKey.cs
  Libplanet/Crypto/PublicKey.cs
  Libplanet/Libplanet.csproj
Labels: Extra Large, pbft

#2311 Fix `NetMQTransport` disposal & Release 0.41.2
  CHANGES.md
  Libplanet.Net/Swarm.cs
  Libplanet.Net/Transports/NetMQTransport.cs
Labels: Extra Small

#2313 Prepare 0.41.3
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: Extra Small

#2281 Using BLS Signature in PBFT voting
  CHANGES.md
  Libplanet.Explorer.Executable/Options.cs
  Libplanet.Explorer.Executable/Program.cs
  Libplanet.Net.Tests/BoundPeerTest.cs
  Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextNonProposerTest.cs
  Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextProposerTest.cs
  Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextTest.cs
  Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextTestBase.cs
  Libplanet.Net.Tests/Consensus/ConsensusReactorTestBase.cs
  Libplanet.Net.Tests/Consensus/Context/ContextNonProposerTest.cs
  Libplanet.Net.Tests/Consensus/Context/ContextProposerTest.cs
  Libplanet.Net.Tests/Consensus/Context/ContextProposerValidRoundTest.cs
  Libplanet.Net.Tests/Consensus/Context/ContextTest.cs
  Libplanet.Net.Tests/Consensus/Context/ContextTestBase.cs
  Libplanet.Net.Tests/Consensus/GossipTest.cs
  Libplanet.Net.Tests/Consensus/MessageCacheTest.cs
  Libplanet.Net.Tests/SwarmTest.Fixtures.cs
  Libplanet.Net.Tests/TestUtils.cs
  Libplanet.Net/BoundPeer.cs
  Libplanet.Net/Consensus/ConsensusContext.cs
  Libplanet.Net/Consensus/ConsensusReactor.cs
  Libplanet.Net/Consensus/ConsensusReactorOption.cs
  Libplanet.Net/Consensus/Context.Mutate.cs
  Libplanet.Net/Consensus/Context.cs
  Libplanet.Net/Messages/ConsensusMessage.cs
  Libplanet.Net/Messages/ConsensusPropose.cs
  Libplanet.Net/Messages/IMessageCodec.cs
  Libplanet.Net/Messages/NetMQMessageCodec.cs
  Libplanet.Net/Swarm.cs
  Libplanet.Net/Transports/InvalidCredentialException.cs
  Libplanet.Net/Transports/InvalidMessageSignatureException.cs
  Libplanet.Net/Transports/NetMQTransport.cs
  Libplanet.Node/NodeConfig.cs
  Libplanet.Node/SwarmConfig.cs
  Libplanet.Tests/AddressExtensionsTest.cs
  Libplanet.Tests/Blockchain/BlockChainTest.MineBlock.cs
  Libplanet.Tests/Blocks/BlockCommitTest.cs
  Libplanet.Tests/Blocks/BlockFixture.cs
  Libplanet.Tests/Blocks/PreEvaluationBlockHeaderTest.cs
  Libplanet.Tests/Consensus/VoteSetTest.cs
  Libplanet.Tests/Consensus/VoteTest.cs
  Libplanet.Tests/TestUtils.cs
  Libplanet/Address.cs
  Libplanet/AddressExtensions.cs
  Libplanet/Consensus/Vote.cs
  Libplanet/Consensus/VoteSet.cs
  Libplanet/Crypto/BlsPublicKey.cs
  Libplanet/Crypto/IPublicKey.cs
  Libplanet/Crypto/PublicKey.cs
  Libplanet/Crypto/PublicKeyGetter.cs
Labels: Extra Large, pbft

#2317 Support chain migration from PoW-based blockchain to PBFT-based blockchain
  CHANGES.md
  Libplanet/Blocks/Block.cs
  Libplanet/Blocks/BlockHeader.cs
  Libplanet/Blocks/BlockMetadata.cs
  Libplanet/Store/BlockSet.cs
Labels: pbft

#2320 Let `Address` and `TxId` implement `IEquatable<T>`
  CHANGES.md
  Libplanet/Address.cs
  Libplanet/Tx/TxId.cs
Labels: bug, api, Extra Small

#2319 Introduce: Dynamic validator
  Libplanet.Explorer.Executable/Program.cs
  Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextNonProposerTest.cs
  Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextProposerTest.cs
  Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextTest.cs
  Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextTestBase.cs
  Libplanet.Net.Tests/Consensus/ConsensusReactorTestBase.cs
  Libplanet.Net.Tests/Consensus/Context/ContextTestBase.cs
  Libplanet.Net.Tests/Messages/MessageTest.cs
  Libplanet.Net.Tests/SwarmTest.Broadcast.cs
  Libplanet.Net.Tests/SwarmTest.Preload.cs
  Libplanet.Net.Tests/SwarmTest.cs
  Libplanet.Net.Tests/TestUtils.cs
  Libplanet.Net/Consensus/ConsensusContext.cs
  Libplanet.Net/Consensus/ConsensusReactor.cs
  Libplanet.Node.Tests/UntypedBlockTest.cs
  Libplanet.Node/NodeUtils.cs
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
  Libplanet.Tests/Blockchain/BlockChainTest.Append.cs
  Libplanet.Tests/Blockchain/BlockChainTest.ValidateNextBlock.cs
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet.Tests/Blockchain/Renderers/AtomicActionRendererTest.cs
  Libplanet.Tests/Blockchain/Renderers/DelayedActionRendererTest.cs
  Libplanet.Tests/Blocks/PreEvaluationBlockTest.cs
  Libplanet.Tests/Fixtures/IntegerSet.cs
  Libplanet.Tests/Store/StoreFixture.cs
  Libplanet.Tests/Store/StoreTest.cs
  Libplanet.Tests/TestUtils.cs
  Libplanet/Action/ActionEvaluator.cs
  Libplanet/Blockchain/BlockChain.PoS.cs
  Libplanet/Blockchain/BlockChain.cs
  Libplanet/Blockchain/Policies/BlockPolicy.cs
  Libplanet/Blockchain/Policies/IBlockPolicy.cs
  Libplanet/Blockchain/Policies/NullBlockPolicy.cs
  Libplanet/Blockchain/Renderers/Debug/ValidatingActionRenderer.cs
  Libplanet/Blocks/PreEvaluationBlock.cs
  Libplanet/PoS/Action/BlockAction.cs
  Libplanet/PoS/Action/PoSAction.cs
  Libplanet/PoS/Model/BondedValidatorSet.cs
  Libplanet/PoS/Model/ValidatorSet.cs
Labels: Large, pos

#2316 Fix reward distribution to be more flexible, to handle multiple currencies
  CHANGES.md
  Libplanet.Net.Tests/SwarmTest.Broadcast.cs
  Libplanet.Net.Tests/SwarmTest.Preload.cs
  Libplanet.Net.Tests/TestUtils.cs
  Libplanet.Node.Tests/UntypedBlockTest.cs
  Libplanet.Node/NodeUtils.cs
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
  Libplanet.Tests/Action/Sys/MintTest.cs
  Libplanet.Tests/Action/Sys/TransferTest.cs
  Libplanet.Tests/Blockchain/BlockChainTest.ValidateNextBlock.cs
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet.Tests/Blocks/PreEvaluationBlockTest.cs
  Libplanet.Tests/Fixtures/IntegerSet.cs
  Libplanet.Tests/PoS/DelegateCtrlTest.cs
  Libplanet.Tests/PoS/DistributeTest.cs
  Libplanet.Tests/PoS/PoSTest.cs
  Libplanet.Tests/PoS/RedelegateCtrlTest.cs
  Libplanet.Tests/PoS/UndelegateCtrlTest.cs
  Libplanet.Tests/PoS/ValidatorCtrlTest.cs
  Libplanet.Tests/PoS/ValidatorPowerIndexCtrlTest.cs
  Libplanet.Tests/PoS/ValidatorSetCtrlTest.cs
  Libplanet.Tests/Store/StoreFixture.cs
  Libplanet.Tests/Store/StoreTest.cs
  Libplanet.Tests/TestUtils.cs
  Libplanet/Action/ActionContext.cs
  Libplanet/Action/ActionEvaluator.cs
  Libplanet/Action/IActionContext.cs
  Libplanet/Action/Sys/Mint.cs
  Libplanet/Action/Sys/Transfer.cs
  Libplanet/Blockchain/BlockChain.cs
  Libplanet/Blocks/PreEvaluationBlock.cs
  Libplanet/PoS/Action/PoSAction.cs
  Libplanet/PoS/Action/Sys/CancelUndelegation.cs
  Libplanet/PoS/Action/Sys/Delegate.cs
  Libplanet/PoS/Action/Sys/PromoteValidator.cs
  Libplanet/PoS/Action/Sys/Redelegate.cs
  Libplanet/PoS/Action/Sys/Undelegate.cs
  Libplanet/PoS/Action/Sys/WithdrawDelegator.cs
  Libplanet/PoS/Action/Sys/WithdrawValidator.cs
  Libplanet/PoS/Control/AllocateReward.cs
  Libplanet/PoS/Control/Bond.cs
  Libplanet/PoS/Control/DelegateCtrl.cs
  Libplanet/PoS/Control/RedelegateCtrl.cs
  Libplanet/PoS/Control/UndelegateCtrl.cs
  Libplanet/PoS/Control/ValidatorCtrl.cs
  Libplanet/PoS/Control/ValidatorRewardsCtrl.cs
  Libplanet/PoS/Model/ValidatorRewards.cs
Labels: Extra Large, pos

#2323 🚀 Release 0.42.0
  CHANGES.md
Labels: Extra Small

#2326 🔀 Merge main 0.42.0 to pbft
  CHANGES.md
  Libplanet.Net/Swarm.cs
  Libplanet.Net/Transports/NetMQTransport.cs
  Libplanet/Address.cs
  Libplanet/Tx/TxId.cs
Labels: Extra Small

#2324 🔧 Prepare 0.43.0
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: Extra Small

#2327 Change access modifier for reserved addresses
  Libplanet/PoS/Misc/ReservedAddress.cs
Labels: Extra Small

#2328 Change access modifier of WithdrawValidator constructor to pulic
  Libplanet/PoS/Action/Sys/WithdrawValidator.cs
Labels: Extra Small

#2325 🔧 Prepare 0.42.1
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: Extra Small

#2322 Serialize/deserialize better with `System.Text.Json.JsonSerializer`
  .circleci/config.yml
  CHANGES.md
  Libplanet.Extensions.Cocona/Libplanet.Extensions.Cocona.csproj
  Libplanet.Extensions.Cocona/Utils.cs
  Libplanet.Node.Tests/Libplanet.Node.Tests.csproj
  Libplanet.Node/SwarmConfig.cs
  Libplanet.Tests/AddressTest.cs
  Libplanet.Tests/Assets/CurrencyTest.cs
  Libplanet.Tests/Assets/FungibleAssetValueTest.cs
  Libplanet.Tests/Blocks/BlockHashTest.cs
  Libplanet.Tests/HashDigestTest.cs
  Libplanet.Tests/Libplanet.Tests.csproj
  Libplanet.Tests/TestUtils.cs
  Libplanet.Tests/Tx/TxIdTest.cs
  Libplanet/Address.cs
  Libplanet/Assets/Currency.cs
  Libplanet/Assets/FungibleAssetValue.cs
  Libplanet/Blocks/BlockHash.cs
  Libplanet/HashDigest.cs
  Libplanet/Libplanet.csproj
  Libplanet/Tx/TxId.cs
Labels: api, Extra Large

#2229 Make interface for routing table (#2046)
  CHANGES.md
  Libplanet.Net/Protocols/IRoutingTable.cs
  Libplanet.Net/Protocols/RoutingTable.cs
Labels: stale, Extra Small, Squash Needed, sprint-20220821

#2334 Change access modifier of `Libplnet.PoS.Asset`
  Libplanet/PoS/Misc/Asset.cs
Labels: Extra Small

#2336 Update gossip table from seed node
  Libplanet.Net.Tests/Consensus/ConsensusReactorTestBase.cs
  Libplanet.Net.Tests/Consensus/GossipTest.cs
  Libplanet.Net.Tests/SwarmTest.Fixtures.cs
  Libplanet.Net/Consensus/ConsensusReactor.cs
  Libplanet.Net/Consensus/ConsensusReactorOption.cs
  Libplanet.Net/Consensus/Gossip.cs
  Libplanet.Net/Swarm.cs
Labels: Small, pos

#2339 Fix serialize `Transaction<T>` bug when its contain systemAction
  CHANGES.md
  Libplanet.Tests/Tx/TransactionTest.cs
  Libplanet/Tx/Transaction.cs
Labels: bug, Extra Small

#2340 Release 0.40.2
  CHANGES.md
Labels: bug, release, Extra Small

#2342 Port 0.40.2 & 0.41.3, and release 0.42.1
  CHANGES.md
  Libplanet.Tests/Tx/TransactionTest.cs
  Libplanet/Tx/Transaction.cs
Labels: bug, release, Extra Small

#2344 Port 0.40.2, 0.41.3, and 0.42.1 to main (0.43.x)
  CHANGES.md
  Libplanet.Tests/Tx/TransactionTest.cs
  Libplanet/Tx/Transaction.cs
Labels: bug, release, Extra Small

#2337 Restore native token predicate
  CHANGES.md
  Libplanet.Net.Tests/Messages/MessageTest.cs
  Libplanet.Net.Tests/SwarmTest.Broadcast.cs
  Libplanet.Net.Tests/SwarmTest.Preload.cs
  Libplanet.Net.Tests/TestUtils.cs
  Libplanet.Node.Tests/UntypedBlockTest.cs
  Libplanet.Node/NodeUtils.cs
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
  Libplanet.Tests/Action/Sys/MintTest.cs
  Libplanet.Tests/Action/Sys/TransferTest.cs
  Libplanet.Tests/Blockchain/BlockChainTest.ValidateNextBlock.cs
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet.Tests/Blocks/PreEvaluationBlockTest.cs
  Libplanet.Tests/Fixtures/IntegerSet.cs
  Libplanet.Tests/Store/StoreFixture.cs
  Libplanet.Tests/Store/StoreTest.cs
  Libplanet.Tests/TestUtils.cs
  Libplanet/Action/ActionContext.cs
  Libplanet/Action/ActionEvaluator.cs
  Libplanet/Action/IActionContext.cs
  Libplanet/Action/Sys/Mint.cs
  Libplanet/Action/Sys/Registry.cs
  Libplanet/Action/Sys/Transfer.cs
  Libplanet/Blockchain/BlockChain.cs
  Libplanet/Blocks/PreEvaluationBlock.cs
  Libplanet/PoS/Action/Sys/WithdrawDelegator.cs
  Libplanet/PoS/Action/Sys/WithdrawValidator.cs
  Libplanet/PoS/Control/AllocateReward.cs
  Libplanet/PoS/Exception/NullNativeTokensException.cs
  Libplanet/PoS/Misc/ReservedAddress.cs
  Libplanet/PoS/Model/ValidatorRewards.cs
Labels: Medium

#2345 Update consensus' routing table from seed node
  Libplanet.Net.Tests/Consensus/ConsensusReactorTestBase.cs
  Libplanet.Net.Tests/Consensus/GossipTest.cs
  Libplanet.Net.Tests/SwarmTest.Fixtures.cs
  Libplanet.Net/Consensus/ConsensusReactor.cs
  Libplanet.Net/Consensus/ConsensusReactorOption.cs
  Libplanet.Net/Consensus/Gossip.cs
  Libplanet.Net/Swarm.cs
Labels: Small, pbft

#2349 Added pluggable validators policy
  CHANGES.md
  Libplanet.Explorer.Executable/Program.cs
  Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextTest.cs
  Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextTestBase.cs
  Libplanet.Net.Tests/Consensus/ConsensusReactorTestBase.cs
  Libplanet.Net.Tests/Consensus/Context/ContextTestBase.cs
  Libplanet.Net.Tests/TestUtils.cs
  Libplanet.Net/Consensus/ConsensusContext.cs
  Libplanet.Net/Consensus/ConsensusReactor.cs
  Libplanet/Blockchain/BlockChain.MineBlock.cs
  Libplanet/Blockchain/Policies/BlockPolicy.cs
  Libplanet/Blockchain/Policies/IBlockPolicy.cs
  Libplanet/Blockchain/Policies/NullBlockPolicy.cs
Labels: Small

#2352 PBFT migration preparatory PoW BPV policy
  Libplanet.Explorer.Executable/Program.cs
  Libplanet.Tests/Blockchain/Policies/BlockPolicyTest.cs
  Libplanet/Blockchain/Policies/BlockPolicy.cs
  Libplanet/Blockchain/Policies/IBlockPolicy.cs
  Libplanet/Blockchain/Policies/NullBlockPolicy.cs
Labels: Extra Small

#2355 `BlockCommit.Votes` no longer nullable or default
  Libplanet/Blocks/BlockCommit.cs
Labels: Extra Small

#2236 Add get random seed method
  CHANGES.md
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
  Libplanet/Action/ActionEvaluator.cs
Labels: Small, Squash Needed

#2358 Make `bindSignature()` can take tx w/ a system action & release 0.40.3
  CHANGES.md
  Libplanet.Explorer.Tests/GraphQLTestUtils.cs
  Libplanet.Explorer.Tests/TransactionQueryTest.cs
  Libplanet.Explorer/Queries/TransactionQuery.cs
Labels: bug, release, Medium

#2359 Port 0.40.3 & release 0.41.4
  CHANGES.md
  Libplanet.Explorer.Tests/TransactionQueryTest.cs
  Libplanet.Explorer/Queries/TransactionQuery.cs
Labels: bug, release, Medium

#2360 Port 0.40.3 & 0.41.4, and release 0.42.2
  CHANGES.md
  Libplanet.Explorer.Tests/TransactionQueryTest.cs
  Libplanet.Explorer/Queries/TransactionQuery.cs
Labels: bug, release, Medium

#2361 Port 0.40.3, 0.41.4, & 0.42.2 to main (0.43.x)
  CHANGES.md
  Libplanet.Explorer.Tests/TransactionQueryTest.cs
  Libplanet.Explorer/Queries/TransactionQuery.cs
Labels: bug, release, Medium

#2348 Caching `LastCommit`
  CHANGES.md
  Libplanet.Explorer/Store/LiteDBRichStore.cs
  Libplanet.Explorer/Store/MySQLRichStore.cs
  Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextNonProposerTest.cs
  Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextProposerTest.cs
  Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextTest.cs
  Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextTestBase.cs
  Libplanet.Net.Tests/Consensus/ConsensusReactorTestBase.cs
  Libplanet.Net.Tests/Consensus/Context/ContextTest.cs
  Libplanet.Net.Tests/Consensus/Context/ContextTestBase.cs
  Libplanet.Net.Tests/TestUtils.cs
  Libplanet.Net/Consensus/ConsensusContext.cs
  Libplanet.Net/Consensus/ConsensusReactor.cs
  Libplanet.Net/Consensus/ConsensusReactorOption.cs
  Libplanet.Net/Consensus/Context.cs
  Libplanet.Net/Swarm.cs
  Libplanet.RocksDBStore/RocksDBStore.cs
  Libplanet.Tests/Blocks/BlockFixture.cs
  Libplanet.Tests/Blocks/PreEvaluationBlockHeaderTest.cs
  Libplanet.Tests/Consensus/VoteSetTest.cs
  Libplanet.Tests/Consensus/VoteTest.cs
  Libplanet.Tests/Store/ProxyStore.cs
  Libplanet.Tests/Store/StoreTest.cs
  Libplanet.Tests/Store/StoreTracker.cs
  Libplanet/Blocks/BlockCommit.cs
  Libplanet/Consensus/Vote.cs
  Libplanet/Consensus/VoteSet.cs
  Libplanet/Store/BaseStore.cs
  Libplanet/Store/DefaultStore.cs
  Libplanet/Store/IStore.cs
  Libplanet/Store/MemoryStore.cs
Labels: Extra Large, pbft
