Repository planetarium/libplanet, pull requests merged in 2022-12, with the labels that each got.

#2598 Fix `TxMetadata.Bencodex()` encoding timestamp & release 0.44.3
  CHANGES.md
  Libplanet.Tests/Blocks/BlockContentTest.cs
  Libplanet.Tests/Fixtures/BlockContentFixture.cs
  Libplanet.Tests/Tx/TxMetadataTest.cs
  Libplanet/Tx/TxMetadata.cs
Labels: bug, release, Extra Small

#2599 Port 0.44.3 to main (0.45.x)
  CHANGES.md
  Libplanet.Tests/Blocks/BlockContentTest.cs
  Libplanet.Tests/Fixtures/BlockContentFixture.cs
  Libplanet.Tests/Tx/TxMetadataTest.cs
  Libplanet/Tx/TxMetadata.cs
Labels: bug, Extra Small

#2604 Revert "Merge pull request #2572 from dahlia/graphql"
  CHANGES.md
  Libplanet.Explorer.Executable/Program.cs
  Libplanet.Explorer.Tests/GraphQLTestUtils.cs
  Libplanet.Explorer.Tests/GraphTypes/ByteStringTypeTest.cs
  Libplanet.Explorer.Tests/Queries/TransactionQueryTest.cs
  Libplanet.Explorer/ExplorerStartup.cs
  Libplanet.Explorer/GraphTypes/ActionType.cs
  Libplanet.Explorer/GraphTypes/AddressType.cs
  Libplanet.Explorer/GraphTypes/BencodexValueType.cs
  Libplanet.Explorer/GraphTypes/BlockPolicyType.cs
  Libplanet.Explorer/GraphTypes/BlockType.cs
  Libplanet.Explorer/GraphTypes/ByteStringType.cs
  Libplanet.Explorer/GraphTypes/CurrencyType.cs
  Libplanet.Explorer/GraphTypes/FungibleAssetValueType.cs
  Libplanet.Explorer/GraphTypes/NodeStateType.cs
  Libplanet.Explorer/GraphTypes/PublicKeyType.cs
  Libplanet.Explorer/GraphTypes/TransactionType.cs
  Libplanet.Explorer/GraphTypes/TxResultType.cs
  Libplanet.Explorer/Libplanet.Explorer.csproj
  Libplanet.Explorer/Mutations/TransactionMutation.cs
  Libplanet.Explorer/Queries/BlockQuery.cs
  Libplanet.Explorer/Queries/ExplorerQuery.cs
  Libplanet.Explorer/Queries/StateQuery.cs
  Libplanet.Explorer/Queries/TransactionQuery.cs
  Libplanet.Explorer/Schemas/ConfigureLibplanetExplorerSchema.cs
  Libplanet.Explorer/Schemas/GraphQLBuilderExtensions.cs
  Libplanet.Explorer/Schemas/LibplanetExplorerSchema.cs
Labels: Extra Large

#2605 Release 0.45.0
  CHANGES.md
Labels: Extra Small

#2606 Prepare 0.46.0
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: Extra Small

#2609 Removed automatic internal reassignment of `Store` to `StateStore`
  CHANGES.md
  Libplanet/Blockchain/BlockChain.cs
Labels: Extra Small

#2597 Fix dynamic validator related tests
  CHANGES.md
  Libplanet.Explorer.Tests/Queries/TransactionQueryTest.cs
  Libplanet.Explorer/Queries/StateQuery.cs
  Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextNonProposerTest.cs
  Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextTest.cs
  Libplanet.Net.Tests/Consensus/Context/ContextProposerTest.cs
  Libplanet.Net.Tests/Consensus/Context/ContextTest.cs
  Libplanet.Net.Tests/Messages/MessageTest.cs
  Libplanet.Net.Tests/SwarmTest.Broadcast.cs
  Libplanet.Net.Tests/SwarmTest.Preload.cs
  Libplanet.Net.Tests/SwarmTest.cs
  Libplanet.Net.Tests/TestUtils.cs
  Libplanet.Net/Consensus/Context.Mutate.cs
  Libplanet.Net/Consensus/Context.cs
  Libplanet.Net/Consensus/MessageLog.cs
  Libplanet.Net/Messages/ConsensusMsg.cs
  Libplanet.Net/Messages/ConsensusPreCommitMsg.cs
  Libplanet.Net/Messages/ConsensusPreVoteMsg.cs
  Libplanet.Net/Messages/ConsensusProposalMsg.cs
  Libplanet.Net/Swarm.BlockSync.cs
  Libplanet.Tests/Action/ActionContextTest.cs
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
  Libplanet.Tests/Blockchain/BlockChainTest.Append.cs
  Libplanet.Tests/Blockchain/BlockChainTest.MineBlock.cs
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet.Tests/Blockchain/Policies/BlockPolicyTest.cs
  Libplanet.Tests/Blocks/BlockContentTest.cs
  Libplanet.Tests/Blocks/BlockMarshalerTest.cs
  Libplanet.Tests/Blocks/BlockMetadataTest.cs
  Libplanet.Tests/Blocks/PreEvaluationBlockHeaderTest.cs
  Libplanet.Tests/Common/Action/DumbAction.cs
  Libplanet.Tests/Consensus/ValidatorSetTest.cs
  Libplanet.Tests/Consensus/ValidatorTest.cs
  Libplanet.Tests/Consensus/VoteTest.cs
  Libplanet.Tests/Fixtures/BlockContentFixture.cs
  Libplanet.Tests/Fixtures/IntegerSet.cs
  Libplanet.Tests/Store/StoreTest.cs
  Libplanet.Tests/TestUtils.cs
  Libplanet/Action/AccountStateDeltaImpl.cs
  Libplanet/Action/IAccountStateDelta.cs
  Libplanet/Action/Sys/Promote.cs
  Libplanet/Action/Sys/Registry.cs
  Libplanet/Action/Sys/SetValidator.cs
  Libplanet/Action/ValidatorAlreadyExistException.cs
  Libplanet/Action/ValidatorDoesNotExistException.cs
  Libplanet/Blocks/BlockCommit.cs
  Libplanet/Consensus/IVoteMetadata.cs
  Libplanet/Consensus/Proposal.cs
  Libplanet/Consensus/ProposalMetadata.cs
  Libplanet/Consensus/Validator.cs
  Libplanet/Consensus/ValidatorSet.cs
  Libplanet/Consensus/Vote.cs
  Libplanet/Consensus/VoteMetadata.cs
Labels: Extra Large

#2614 Exclude linux-unity-test on workflow
  .circleci/config.yml
Labels: Extra Small

#2607 Context bootstrapping
  Libplanet.Net.Tests/SwarmTest.cs
  Libplanet.Net/Consensus/ConsensusContext.cs
  Libplanet.Net/Consensus/ConsensusReactor.cs
  Libplanet.Net/Consensus/Context.Async.cs
  Libplanet.Net/Consensus/MessageLog.cs
  Libplanet.Net/Swarm.cs
Labels: Medium

#2615 🧹 Removed `InvalidBlockDifficultyException`
  Libplanet/Blocks/InvalidBlockDifficultyException.cs
Labels: Extra Small

#2619 Made `Swap()` no longer allowed on non canonical chains
  CHANGES.md
  Libplanet/Blockchain/BlockChain.Swap.cs
Labels: Extra Small

#2620 Fix explorer's validators query
  Libplanet.Explorer.Tests/Queries/StateQueryTest.cs
  Libplanet.Explorer/GraphTypes/ValidatorType.cs
  Libplanet.Explorer/Queries/StateQuery.cs
Labels: Small, pbft

#2616 Add `IAction systemAction` parameter to `BlockChain.ProposeGenesisBlock()`
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet/Blockchain/BlockChain.cs
Labels: Extra Small

#2618 Fixed logging context for `BlockChain<T>`
  Libplanet/Blockchain/BlockChain.cs
Labels: Extra Small

#2628 fix: invalid syntax in CI
  .github/workflows/build.yaml
Labels: ci & cd, Extra Small

#2629 🧹 Fixed `IStore` interface method description
  Libplanet/Store/IStore.cs
Labels: No Changes

#2600 Increase performance of NetMQTransport and related features
  Libplanet.Net/TxCompletion.cs
Labels: network, Medium

#2632 introduce: continuous benchmark
  .circleci/config.yml
  .github/workflows/benchmarks-main.yml
  .github/workflows/benchmarks-pr.yml
  .github/workflows/benchmarks.yml
Labels: ci & cd, Large

#2634 Remove exclusive option
  .github/workflows/benchmarks-main.yml
Labels: bug, ci & cd, Extra Small

#2633 `ConsensusContext<T>.HandleMessage()` return type as `bool`
  Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextTest.cs
  Libplanet.Net/Consensus/ConsensusContext.cs
Labels: Extra Small

#2626 Introduce peers and validators query
  CHANGES.md
  Libplanet.Explorer.Executable/Program.cs
  Libplanet.Explorer.Tests/Queries/TransactionQueryTest.cs
  Libplanet.Explorer/GraphTypes/BoundPeerType.cs
  Libplanet.Explorer/GraphTypes/NodeStateType.cs
  Libplanet.Explorer/Interfaces/IBlockChainContext.cs
  Libplanet.Explorer/Libplanet.Explorer.csproj
  Libplanet.Net/Consensus/ConsensusReactor.cs
  Libplanet.Net/Swarm.cs
Labels: Extra Small

#2636 Fix benchmark script error
  .github/workflows/benchmarks-main.yml
Labels: bug, ci & cd, Extra Small

#2631 Improve network performance & Release 0.44.4
  CHANGES.md
  Libplanet.Net/Protocols/KademliaProtocol.cs
  Libplanet.Net/Swarm.MessageHandlers.cs
  Libplanet.Net/Swarm.cs
  Libplanet.Net/Transports/NetMQTransport.cs
  Libplanet.Net/TxCompletion.cs
Labels: Extra Large

#2639 Changed `NewHeight()` behavior
  Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextTest.cs
  Libplanet.Net/Consensus/ConsensusContext.cs
Labels: Small

#2641 Port 0.44.4 to 0.45-maintenance & Release 0.45.1
  CHANGES.md
  Libplanet.Net/Protocols/KademliaProtocol.cs
  Libplanet.Net/Swarm.MessageHandlers.cs
  Libplanet.Net/Swarm.cs
  Libplanet.Net/Transports/NetMQTransport.cs
  Libplanet.Net/TxCompletion.cs
Labels: Extra Large

#2640 Prepare 0.44.5
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: Extra Small

#2644 Changed to allow commit failure due to desync between `Context<T>` and `BlockChain<T>`
  Libplanet.Net/Consensus/Context.Mutate.cs
Labels: Extra Small

#2647 ♻️ Removed `ConsensusContext<T>.Commit()`
  Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextTest.cs
  Libplanet.Net.Tests/Consensus/Context/ContextTest.cs
  Libplanet.Net/Consensus/ConsensusContext.Event.cs
  Libplanet.Net/Consensus/ConsensusContext.cs
  Libplanet.Net/Consensus/ConsensusReactor.cs
  Libplanet.Net/Consensus/ConsensusReactorOption.cs
  Libplanet.Net/Consensus/Context.Async.cs
  Libplanet.Net/Consensus/Context.Mutate.cs
Labels: Medium

#2646 Load block action from delegator
  CHANGES.md
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet/Action/ActionEvaluator.cs
  Libplanet/Action/IActionTypeLoader.cs
  Libplanet/Action/PolicyBlockActionGetter.cs
  Libplanet/Action/StaticActionTypeLoader.cs
  Libplanet/Blockchain/BlockChain.cs
  Libplanet/Blocks/PreEvaluationBlock.cs
Labels: Small

#2648 Fix bug on ActionExecutionState
  Libplanet.Net/Swarm.BlockSync.cs
Labels: Extra Small

#2651 🔧 Faster `BlockCommit` cache management
  CHANGES.md
  Libplanet.Net/Swarm.BlockSync.cs
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet/Blockchain/BlockChain.cs
Labels: Extra Small

#2654 Improve `NetMQTransport` again
  CHANGES.md
  Libplanet.Net/Protocols/KBucketDictionary.cs
  Libplanet.Net/Protocols/KademliaProtocol.cs
  Libplanet.Net/Swarm.MessageHandlers.cs
  Libplanet.Net/Swarm.cs
  Libplanet.Net/Transports/NetMQTransport.cs
Labels: Medium, Squash Needed

#2655 Fix stateQuery
  CHANGES.md
  Libplanet.Explorer/Queries/ExplorerQuery.cs
Labels: bug, Extra Small

#2657 Release 0.44.5
  CHANGES.md
Labels: Extra Small

#2642 Prepare 0.45.2
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: Extra Small

#2659 Port 0.44.5 to 0.45-maintenance
  CHANGES.md
  Libplanet.Net/Protocols/KBucketDictionary.cs
  Libplanet.Net/Protocols/KademliaProtocol.cs
  Libplanet.Net/Swarm.MessageHandlers.cs
  Libplanet.Net/Swarm.cs
  Libplanet.Net/Transports/NetMQTransport.cs
Labels: Medium

#2637 ci(gh-actions): update actions used node12
  .github/workflows/benchmarks-main.yml
  .github/workflows/benchmarks-pr.yml
  .github/workflows/build.yaml
  .github/workflows/check-build.yaml
  .github/workflows/main.yml
  .github/workflows/push-docker-image.yml
  .github/workflows/rebase.yml
Labels: ci & cd, Extra Small

#2660 Release Libplanet 0.45.2
  CHANGES.md
Labels: Extra Small

#2658 Prepare 0.44.6
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: Extra Small

#2661 Prepare 0.45.3
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: Extra Small

#2666 🔧 Benchmark CI fix
  .github/workflows/benchmarks-main.yml
  .github/workflows/benchmarks-pr.yml
Labels: Extra Small

#2664 🧹 Removed `IStore.GetCanonicalGenesisBlock<T>()`
  CHANGES.md
  Libplanet.Benchmarks/Store.cs
  Libplanet.Explorer/Store/LiteDBRichStore.cs
  Libplanet.Explorer/Store/MySQLRichStore.cs
  Libplanet.Tests/Store/ProxyStore.cs
  Libplanet.Tests/Store/StoreTest.cs
  Libplanet.Tests/Store/StoreTracker.cs
  Libplanet/Store/BaseStore.cs
  Libplanet/Store/IStore.cs
  Libplanet/Store/MemoryStore.cs
Labels: Small

#2669 🧹 Minor refactor for `KBucketDictionary`
  Libplanet.Net/Protocols/KBucketDictionary.cs
Labels: Extra Small

#2667 Fix NetMQ failures on Windows
  CHANGES.md
  Libplanet.Net/Transports/NetMQTransport.cs
  Libplanet/Blockchain/BlockChain.cs
  Libplanet/Blockchain/BlockLocator.cs
Labels: Extra Small

#2668 Fix typo 'dail' → 'dial'
  Libplanet.Net/Swarm.BlockCandidate.cs
  Libplanet.Net/Swarm.cs
Labels: bug, Extra Small, logging

#2670 Release Libplanet 0.44.6
  CHANGES.md
Labels: Extra Small

#2672 Port 0.44.6 to 0.45 & Release 0.45.3
  CHANGES.md
  Libplanet.Net/Protocols/KBucketDictionary.cs
  Libplanet.Net/Transports/NetMQTransport.cs
  Libplanet/Blockchain/BlockChain.cs
  Libplanet/Blockchain/BlockLocator.cs
Labels: Small

#2674 Prepare 0.45.4
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: Extra Small, Squash Needed

#2662 Port 0.45.3 to main
  CHANGES.md
  Libplanet.Net/Protocols/KBucketDictionary.cs
  Libplanet.Net/Protocols/KademliaProtocol.cs
  Libplanet.Net/Swarm.MessageHandlers.cs
  Libplanet.Net/Swarm.cs
  Libplanet.Net/Transports/NetMQTransport.cs
  Libplanet.Net/TxCompletion.cs
  Libplanet/Blockchain/BlockChain.cs
  Libplanet/Blockchain/BlockLocator.cs
Labels: Extra Large

#2676 Correct logging in `ActionEvaluator`
  Libplanet/Action/ActionEvaluator.cs
Labels: bug, Extra Small, logging

#2671 Prepare 0.44.7
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: Extra Small

#2649 Fix CI - benchmark for windows
  .github/workflows/benchmarks-main.yml
Labels: bug, Extra Small

#2653 Introduce `IActionTypeLoaderContext`
  CHANGES.md
  Libplanet/Action/ActionEvaluator.cs
  Libplanet/Action/ActionTypeLoaderContext.cs
  Libplanet/Action/IActionTypeLoader.cs
  Libplanet/Action/IActionTypeLoaderContext.cs
  Libplanet/Action/StaticActionTypeLoader.cs
Labels: Extra Small

#2680 🔧 Reduce test flakiness
  Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextNonProposerTest.cs
  Libplanet.Net.Tests/SwarmTest.Broadcast.cs
  Libplanet.Net.Tests/SwarmTest.cs
Labels: Extra Small

#2679 Fix benchmark problem
  .github/workflows/benchmarks-main.yml
  .github/workflows/benchmarks-pr.yml
  Libplanet.Benchmarks/Program.cs
  Libplanet.Benchmarks/SwarmBenchmark.cs
Labels: bug, ci & cd, Large

#2682 🔧 Relax benchmark alert threshold to 150%
  .github/workflows/benchmarks-pr.yml
Labels: Extra Small

#2681 🔧 Try running benchmarks to completion on other os failure
  .github/workflows/benchmarks-main.yml
  .github/workflows/benchmarks-pr.yml
Labels: Extra Small
