Repository planetarium/libplanet, pull requests merged in 2022-04, with the labels that each got.

#1879 Enforce concurrency on `KBucket` internal dictionaries
  CHANGES.md
  Libplanet.Net.Tests/Protocols/KBucketDictionaryTest.cs
  Libplanet.Net.Tests/Protocols/KBucketTest.cs
  Libplanet.Net.Tests/Protocols/ProtocolTest.cs
  Libplanet.Net/Protocols/KBucket.cs
  Libplanet.Net/Protocols/KBucketDictionary.cs
  Libplanet.Net/Protocols/RoutingTable.cs
Labels: Large

#1889 Decoding related exceptions refactored
  CHANGES.md
  Libplanet.Net.Tests/DifferentAppProtocolVersionExceptionTest.cs
  Libplanet.Net.Tests/InvalidMessageSignatureExceptionTest.cs
  Libplanet.Net.Tests/InvalidMessageTimestampExceptionTest.cs
  Libplanet.Net.Tests/Messages/MessageTest.cs
  Libplanet.Net/DifferentAppProtocolVersionException.cs
  Libplanet.Net/InvalidMessageSignatureException.cs
  Libplanet.Net/InvalidMessageTimestampException.cs
  Libplanet.Net/Messages/NetMQMessageCodec.cs
  Libplanet.Net/Messages/TcpMessageCodec.cs
  Libplanet.Net/Protocols/KademliaProtocol.cs
  Libplanet.Net/Transports/NetMQTransport.cs
  Libplanet.Net/Transports/TcpTransport.cs
Labels: Large

#1890 Separate `MessageValidator` for `IMessageCodec`s
  CHANGES.md
  Libplanet.Explorer.Executable/Program.cs
  Libplanet.Net.Tests/Messages/BlockHashesTest.cs
  Libplanet.Net.Tests/Messages/MessageTest.cs
  Libplanet.Net.Tests/Messages/MessageValidatorTest.cs
  Libplanet.Net.Tests/Messages/NetMQMessageCodecTest.cs
  Libplanet.Net.Tests/SwarmTest.AppProtocolVersion.cs
  Libplanet.Net.Tests/Transports/TcpTransportTest.cs
  Libplanet.Net/DifferentAppProtocolVersionEncountered.cs
  Libplanet.Net/Messages/IMessageCodec.cs
  Libplanet.Net/Messages/MessageValidator.cs
  Libplanet.Net/Messages/NetMQMessageCodec.cs
  Libplanet.Net/Messages/TcpMessageCodec.cs
  Libplanet.Net/Transports/BoundPeerExtensions.cs
  Libplanet.Net/Transports/NetMQTransport.cs
  Libplanet.Net/Transports/TcpTransport.cs
Labels: Extra Large

#1893 Release 0.32.0
  CHANGES.md
Labels: Extra Small

#1894 Prepare 0.32.1
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: Extra Small

#1895 Prepare 0.33.0
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: Extra Small

#1891 Remove Fody dependency from Libplanet
  CHANGES.md
  Libplanet.Net.Tests/Messages/MessageValidatorTest.cs
  Libplanet.Net/ActionExecutionState.cs
  Libplanet.Net/BlockDownloadState.cs
  Libplanet.Net/BlockHashDownloadState.cs
  Libplanet.Net/BlockVerificationState.cs
  Libplanet.Net/BoundPeer.cs
  Libplanet.Net/FodyWeavers.xml
  Libplanet.Net/Libplanet.Net.csproj
  Libplanet.Net/Peer.cs
  Libplanet.Net/PreloadState.cs
  Libplanet.Tests/ByteUtilTest.cs
  Libplanet.Tests/Store/StoreTrackLog.cs
  Libplanet/Address.cs
  Libplanet/Blocks/InvalidBlockPreEvaluationHashException.cs
  Libplanet/Blocks/InvalidBlockTxHashException.cs
  Libplanet/ByteUtil.cs
  Libplanet/Crypto/PrivateKey.cs
  Libplanet/Crypto/PublicKey.cs
  Libplanet/Crypto/SymmetricKey.cs
  Libplanet/FodyWeavers.xml
  Libplanet/Libplanet.csproj
  Libplanet/Nonce.cs
  Libplanet/Store/Trie/MerkleTrie.cs
  Libplanet/Store/Trie/Nodes/HashNode.cs
  Libplanet/Store/Trie/Nodes/ValueNode.cs
  Libplanet/Tx/RawTransaction.cs
  Libplanet/Tx/Transaction.cs
  Libplanet/Tx/TxId.cs
Labels: Large

#1900 Reply to untrusted APV `Message`s
  CHANGES.md
  Libplanet.Net.Tests/Messages/MessageValidatorTest.cs
  Libplanet.Net.Tests/SwarmTest.AppProtocolVersion.cs
  Libplanet.Net/Transports/NetMQTransport.cs
  Libplanet.Net/Transports/TcpTransport.cs
Labels: Extra Small

#1901 Release 0.32.1
  CHANGES.md
Labels: Extra Small

#1902 Prepare 0.32.2
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: Extra Small

#1903 Port/0.32.1 to main
  CHANGES.md
  Libplanet.Net.Tests/SwarmTest.AppProtocolVersion.cs
  Libplanet.Net/Transports/NetMQTransport.cs
  Libplanet.Net/Transports/TcpTransport.cs
Labels: Extra Small

#1899 Fix unit test bug in linux-unity-test
  .circleci/config.yml
  Libplanet/Store/DefaultStore.cs
Labels: bug, Extra Small

#1905 Sanity check added to IMessageCodec.Encode()
  CHANGES.md
  Libplanet.Net.Tests/InvalidCredentialExceptionTest.cs
  Libplanet.Net.Tests/Messages/BlockHashesTest.cs
  Libplanet.Net.Tests/Messages/MessageTest.cs
  Libplanet.Net.Tests/Transports/BoundPeerExtensionsTest.cs
  Libplanet.Net.Tests/Transports/TcpTransportTest.cs
  Libplanet.Net/InvalidCredentialException.cs
  Libplanet.Net/Messages/IMessageCodec.cs
  Libplanet.Net/Messages/NetMQMessageCodec.cs
  Libplanet.Net/Messages/TcpMessageCodec.cs
  Libplanet.Net/Transports/BoundPeerExtensions.cs
Labels: Medium

#1909 update action evaluation log [skip changelog]
  Libplanet/Action/ActionEvaluator.cs
Labels: Extra Small

#1906 Context agnostic `IMessageCodec`s
  CHANGES.md
  Libplanet.Net.Tests/DifferentAppProtocolVersionExceptionTest.cs
  Libplanet.Net.Tests/InvalidMessageTimestampExceptionTest.cs
  Libplanet.Net.Tests/Messages/BlockHashesTest.cs
  Libplanet.Net.Tests/Messages/MessageTest.cs
  Libplanet.Net.Tests/Messages/MessageValidatorTest.cs
  Libplanet.Net.Tests/Messages/NetMQMessageCodecTest.cs
  Libplanet.Net.Tests/Transports/TcpTransportTest.cs
  Libplanet.Net/DifferentAppProtocolVersionException.cs
  Libplanet.Net/InvalidMessageTimestampException.cs
  Libplanet.Net/Messages/IMessageCodec.cs
  Libplanet.Net/Messages/MessageValidator.cs
  Libplanet.Net/Messages/NetMQMessageCodec.cs
  Libplanet.Net/Messages/TcpMessageCodec.cs
  Libplanet.Net/Protocols/KademliaProtocol.cs
  Libplanet.Net/Transports/BoundPeerExtensions.cs
  Libplanet.Net/Transports/NetMQTransport.cs
  Libplanet.Net/Transports/TcpTransport.cs
Labels: Extra Large

#1911 Plug `ITransport` `Exception`s leak
  CHANGES.md
  Libplanet.Net.Tests/Messages/MessageTest.cs
  Libplanet.Net.Tests/Messages/MessageValidatorTest.cs
  Libplanet.Net.Tests/Protocols/TestTransport.cs
  Libplanet.Net.Tests/Transports/CommunicationFailExceptionTest.cs
  Libplanet.Net.Tests/Transports/DifferentAppProtocolVersionExceptionTest.cs
  Libplanet.Net.Tests/Transports/InvalidCredentialExceptionTest.cs
  Libplanet.Net.Tests/Transports/InvalidMessageSignatureExceptionTest.cs
  Libplanet.Net.Tests/Transports/InvalidMessageTimestampExceptionTest.cs
  Libplanet.Net.Tests/Transports/MessageSendFailedExceptionTest.cs
  Libplanet.Net.Tests/Transports/SendMessageFailExceptionTest.cs
  Libplanet.Net.Tests/Transports/TransportTest.cs
  Libplanet.Net/Messages/MessageValidator.cs
  Libplanet.Net/Messages/NetMQMessageCodec.cs
  Libplanet.Net/Messages/TcpMessageCodec.cs
  Libplanet.Net/Protocols/KademliaProtocol.cs
  Libplanet.Net/Swarm.cs
  Libplanet.Net/Transports/CommunicationFailException.cs
  Libplanet.Net/Transports/DifferentAppProtocolVersionException.cs
  Libplanet.Net/Transports/ITransport.cs
  Libplanet.Net/Transports/InvalidCredentialException.cs
  Libplanet.Net/Transports/InvalidMagicCookieException.cs
  Libplanet.Net/Transports/InvalidMessageSignatureException.cs
  Libplanet.Net/Transports/InvalidMessageTimestampException.cs
  Libplanet.Net/Transports/NetMQTransport.cs
  Libplanet.Net/Transports/SendMessageFailException.cs
  Libplanet.Net/Transports/TcpTransport.cs
Labels: Large

#1913 Release 0.33.0
  CHANGES.md
Labels: Extra Small

#1915 Prepare 0.33.1
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: Extra Small

#1914 Prepare 0.34.0
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: Extra Small

#1919 New message for PBFT
  Libplanet.Net/Messages/ConsensusCommit.cs
  Libplanet.Net/Messages/ConsensusCommit23.cs
  Libplanet.Net/Messages/Message.cs
Labels: Extra Small

#1916 `TxPolicyViolationException` should contain `InnerException`
  CHANGES.md
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet.Tests/Blockchain/Policies/BlockPolicyTest.cs
  Libplanet/Blockchain/BlockChain.cs
  Libplanet/Tx/InvalidTxException.cs
  Libplanet/Tx/TxPolicyViolationException.cs
Labels: good first issue, consensus, Small

#1924 Defer `Transaction<T>` policy validation to after nonce check
  CHANGES.md
  Libplanet/Blockchain/BlockChain.MineBlock.cs
Labels: Extra Small

#1927 Release 0.33.1
  CHANGES.md
Labels: Extra Small

#1930 Remove ConsensusVote23 and ConsensusCommit23 messages
  Libplanet.Net/Messages/ConsensusCommit23.cs
  Libplanet.Net/Messages/ConsensusVote23.cs
  Libplanet.Net/Messages/Message.cs
  Libplanet.Net/Messages/NetMQMessageCodec.cs
  Libplanet.Net/Messages/TcpMessageCodec.cs
Labels: Extra Small

#1925 Remove rethrowing of caught exception
  Libplanet.Tests/Blockchain/BlockChainTest.cs
Labels: Extra Small

#1928 Prepare 0.33.2
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: Extra Small

#1929 Port 0.33.1 to main
  CHANGES.md
  Libplanet/Blockchain/BlockChain.MineBlock.cs
Labels: Extra Small
