Repository planetarium/libplanet, pull requests merged in 2022-08, with the labels that each got.

#2183 Introduce `IAccountStateView`
  CHANGES.md
  Libplanet/Action/AccountStateDeltaImpl.cs
  Libplanet/Action/IAccountStateDelta.cs
  Libplanet/Action/IAccountStateView.cs
Labels: suggestion, api, Extra Small

#2173 Bump target framework to 6.0 for test projects
  .circleci/config.yml
  .devcontainer/devcontainer.json
  .github/bin/dist-pack.sh
  .github/workflows/benchmarks.yml
  .github/workflows/check-build.yaml
  .github/workflows/main.yml
  CHANGES.md
  CONTRIBUTING.md
  Dockerfile.explorer
  Libplanet.Analyzers.Tests/Libplanet.Analyzers.Tests.csproj
  Libplanet.Benchmarks/Libplanet.Benchmarks.csproj
  Libplanet.Explorer.Executable/Libplanet.Explorer.Executable.csproj
  Libplanet.Explorer.Tests/Libplanet.Explorer.Tests.csproj
  Libplanet.Explorer/Libplanet.Explorer.csproj
  Libplanet.Explorer/README.md
  Libplanet.Extensions.Cocona.Tests/Libplanet.Extensions.Cocona.Tests.csproj
  Libplanet.Net.Tests/Libplanet.Net.Tests.csproj
  Libplanet.Node.Tests/Libplanet.Node.Tests.csproj
  Libplanet.RocksDBStore.Tests/Libplanet.RocksDBStore.Tests.csproj
  Libplanet.Stun.Tests/Libplanet.Stun.Tests.csproj
  Libplanet.Tests/Libplanet.Tests.csproj
  Libplanet.sln
  global.json
Labels: Medium

#2191 Hotfix Dockerfile.explorer
  Dockerfile.explorer
Labels: Extra Small

#2178 Refactor `Context` for thread safety and covering additional edge cases
  Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextNonProposerTest.cs
  Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextProposerTest.cs
  Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextTest.cs
  Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextTestBase.cs
  Libplanet.Net.Tests/Consensus/Context/ContextNonProposerTest.cs
  Libplanet.Net.Tests/Consensus/Context/ContextProposerTest.cs
  Libplanet.Net.Tests/Consensus/Context/ContextProposerValidRoundTest.cs
  Libplanet.Net.Tests/Consensus/Context/ContextTest.cs
  Libplanet.Net.Tests/Consensus/Context/ContextTestBase.cs
  Libplanet.Net.Tests/TestUtils.cs
  Libplanet.Net/Consensus/ConsensusContext.cs
  Libplanet.Net/Consensus/Context.Async.cs
  Libplanet.Net/Consensus/Context.Event.cs
  Libplanet.Net/Consensus/Context.Mutate.cs
  Libplanet.Net/Consensus/Context.cs
  Libplanet/Blockchain/BlockChain.MineBlock.cs
Labels: Extra Large

#2195 `MessageLog` added
  Libplanet.Net/Consensus/Context.Async.cs
  Libplanet.Net/Consensus/Context.Mutate.cs
  Libplanet.Net/Consensus/Context.cs
  Libplanet.Net/Consensus/MessageLog.cs
Labels: Medium

#2130 Add GQL mutations & queries to Libplanet.Explorer
  CHANGES.md
  Libplanet.Explorer/GraphTypes/BencodexValueType.cs
  Libplanet.Explorer/GraphTypes/TxResult.cs
  Libplanet.Explorer/GraphTypes/TxResultType.cs
  Libplanet.Explorer/GraphTypes/TxStatusType.cs
  Libplanet.Explorer/Mutations/TransactionMutation.cs
  Libplanet.Explorer/Queries/TransactionQuery.cs
Labels: Large, Squash Needed

#2197 `ExceptionOccurred` `EventHandler<Exception>` added to `Context`
  Libplanet.Net.Tests/Consensus/Context/ContextTest.cs
  Libplanet.Net/Consensus/Context.Async.cs
  Libplanet.Net/Consensus/Context.Event.cs
  Libplanet.Net/Consensus/Context.Mutate.cs
Labels: Large

#2175 Native tokens & system actions
  CHANGES.md
  Libplanet.Explorer.Executable/Program.cs
  Libplanet.Explorer/Queries/TransactionQuery.cs
  Libplanet.Net.Tests/SwarmTest.Broadcast.cs
  Libplanet.Net.Tests/SwarmTest.Fixtures.cs
  Libplanet.Net.Tests/SwarmTest.Preload.cs
  Libplanet.Net.Tests/SwarmTest.cs
  Libplanet.Net/Swarm.BlockSync.cs
  Libplanet.Node.Tests/UntypedBlockTest.cs
  Libplanet.Node.Tests/UntypedTransactionTest.cs
  Libplanet.Node/NodeUtils.cs
  Libplanet.Node/UntypedTransaction.cs
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
  Libplanet.Tests/Action/Sys/MintTest.cs
  Libplanet.Tests/Action/Sys/RegistryTest.cs
  Libplanet.Tests/Action/Sys/TransferTest.cs
  Libplanet.Tests/Blockchain/BlockChainTest.ValidateNextBlock.cs
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet.Tests/Blockchain/Renderers/AtomicActionRendererTest.cs
  Libplanet.Tests/Blocks/BlockContentTest.cs
  Libplanet.Tests/Blocks/PreEvaluationBlockTest.cs
  Libplanet.Tests/Fixtures/BlockContentFixture.cs
  Libplanet.Tests/Fixtures/IntegerSet.cs
  Libplanet.Tests/Store/StoreFixture.cs
  Libplanet.Tests/Store/StoreTest.cs
  Libplanet.Tests/TestUtils.cs
  Libplanet.Tests/Tx/TransactionTest.cs
  Libplanet/Action/ActionContext.cs
  Libplanet/Action/ActionEvaluator.cs
  Libplanet/Action/IActionContext.cs
  Libplanet/Action/Sys/Mint.cs
  Libplanet/Action/Sys/Registry.cs
  Libplanet/Action/Sys/Transfer.cs
  Libplanet/Assets/FungibleAssetValue.cs
  Libplanet/Assets/NonNativeTokenException.cs
  Libplanet/Blockchain/BlockChain.cs
  Libplanet/Blockchain/Policies/BlockPolicy.cs
  Libplanet/Blockchain/Policies/IBlockPolicy.cs
  Libplanet/Blockchain/Policies/NullBlockPolicy.cs
  Libplanet/Blockchain/Renderers/Debug/ValidatingActionRenderer.cs
  Libplanet/Blocks/PreEvaluationBlock.cs
  Libplanet/Tx/Transaction.cs
  Libplanet/Tx/TxMetadata.cs
Labels: Extra Large

#2202 `Context` edge case test added
  Libplanet.Net.Tests/Consensus/Context/ContextNonProposerTest.cs
Labels: Extra Small

#2205 Package reference fix
  Libplanet.Node.Tests/Libplanet.Node.Tests.csproj
  Libplanet.Tests/Libplanet.Tests.csproj
Labels: Extra Small

#2204 Upgrade Ubuntu 18.04 image to latest in GitHub Actions
  .github/workflows/benchmarks.yml
  .github/workflows/check-build.yaml
  .github/workflows/main.yml
Labels: Extra Small

#2210 🧹 Changelog formatting
  CHANGES.md
Labels: Medium

#2211 🚀 Release 0.40.0
  CHANGES.md
Labels: Extra Small

#2212 🔧 Prepare 0.41.0
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: Extra Small

#2213 🔧 Prepare 0.40.1
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: Extra Small

#2216 🧹 `TcpMessageCodec` removed
  CHANGES.md
  Libplanet.Net/Messages/TcpMessageCodec.cs
Labels: Medium

#2219 Refactor `IceServer.CreateTurnClient()`
  CHANGES.md
  Libplanet.Net.Tests/IceServerTest.cs
  Libplanet.Net/IceServer.cs
  Libplanet.Net/Transports/NetMQTransport.cs
  Libplanet.Stun/IIceServer.cs
  Libplanet.Stun/IceServerException.cs
  Libplanet.Stun/Stun/TurnClient.cs
Labels: network, Medium

#2217 Bump block protocol version to 4
  CHANGES.md
  Libplanet.Net.Tests/Consensus/MessageCacheTest.cs
  Libplanet.Net.Tests/Messages/MessageTest.cs
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
  Libplanet.Tests/Blocks/BlockMetadataTest.cs
  Libplanet.Tests/Blocks/PreEvaluationBlockHeaderTest.cs
  Libplanet/Blocks/BlockMetadata.cs
Labels: Small

#2215 ♻️ Refactor `NetMQTransport`'s initialization
  CHANGES.md
  Libplanet.Net.Tests/Protocols/ProtocolTest.cs
  Libplanet.Net.Tests/Protocols/TestTransport.cs
  Libplanet.Net.Tests/SwarmTest.Broadcast.cs
  Libplanet.Net.Tests/SwarmTest.Preload.cs
  Libplanet.Net.Tests/SwarmTest.cs
  Libplanet.Net.Tests/Transports/NetMQTransportTest.cs
  Libplanet.Net.Tests/Transports/TransportTest.cs
  Libplanet.Net/Swarm.cs
  Libplanet.Net/Transports/ITransport.cs
  Libplanet.Net/Transports/NetMQTransport.cs
Labels: network, Large

#2201 Remove unused tx related methods from IStore (#1538)
  CHANGES.md
  Libplanet.Explorer/Store/LiteDBRichStore.cs
  Libplanet.Explorer/Store/MySQLRichStore.cs
  Libplanet.RocksDBStore/RocksDBStore.cs
  Libplanet.Tests/Store/ProxyStore.cs
  Libplanet.Tests/Store/StoreTest.cs
  Libplanet.Tests/Store/StoreTracker.cs
  Libplanet/Store/BaseStore.cs
  Libplanet/Store/DefaultStore.cs
  Libplanet/Store/IStore.cs
  Libplanet/Store/MemoryStore.cs
Labels: Medium, sprint-20220821

#2232 Add `PeerString` property
  CHANGES.md
  Libplanet.Net.Tests/BoundPeerTest.cs
  Libplanet.Net/BoundPeer.cs
Labels: Extra Small, sprint-20220821

#2228 More `BoundPeer` type enforcement
  CHANGES.md
  Libplanet.Net.Tests/Messages/BlockHashesTest.cs
  Libplanet.Net.Tests/Messages/MessageTest.cs
  Libplanet.Net.Tests/Messages/MessageValidatorTest.cs
  Libplanet.Net.Tests/Messages/NetMQMessageCodecTest.cs
  Libplanet.Net.Tests/Transports/InvalidMessageSignatureExceptionTest.cs
  Libplanet.Net/DifferentAppProtocolVersionEncountered.cs
  Libplanet.Net/Messages/IMessageCodec.cs
  Libplanet.Net/Messages/Message.cs
  Libplanet.Net/Messages/MessageValidator.cs
  Libplanet.Net/Messages/NetMQMessageCodec.cs
  Libplanet.Net/Transports/BoundPeerExtensions.cs
  Libplanet.Net/Transports/InvalidMessageSignatureException.cs
Labels: Extra Small

#2233 Remove `Peer`
  CHANGES.md
  Libplanet.Net.Tests/BoundPeerTest.cs
  Libplanet.Net.Tests/PeerTest.cs
  Libplanet.Net.Tests/Protocols/TestTransport.cs
  Libplanet.Net.Tests/SwarmTest.AppProtocolVersion.cs
  Libplanet.Net.Tests/SwarmTest.cs
  Libplanet.Net.Tests/Transports/TransportTest.cs
  Libplanet.Net/BlockCandidateTable.cs
  Libplanet.Net/BoundPeer.cs
  Libplanet.Net/Messages/IMessageCodec.cs
  Libplanet.Net/Messages/Message.cs
  Libplanet.Net/Peer.cs
  Libplanet.Net/PeerChainState.cs
  Libplanet.Net/PeerState.cs
  Libplanet.Net/Protocols/IProtocol.cs
  Libplanet.Net/Protocols/KademliaProtocol.cs
  Libplanet.Net/Protocols/RoutingTable.cs
  Libplanet.Net/Swarm.cs
  Libplanet.Net/SwarmOptions.cs
  Libplanet.Net/Transports/DifferentAppProtocolVersionException.cs
  Libplanet.Net/Transports/ITransport.cs
  Libplanet.Net/Transports/InvalidMessageSignatureException.cs
  Libplanet.Net/Transports/NetMQTransport.cs
Labels: network, Large

#2238 🧹 Some old typo fix
  CHANGES.md
Labels: Extra Small

#2186 Replace `UserContext` with .NET DI
  Libplanet.Explorer.Tests/GraphQLTestUtils.cs
  Libplanet.Explorer.Tests/GraphTypes/BlockTypeTest.cs
  Libplanet.Explorer/GraphTypes/BlockType.cs
Labels: Small, Squash Needed, sprint-20220821

#2227 GraphQL APIs for native tokens
  CHANGES.md
  Libplanet.Explorer.Tests/GraphTypes/BlockPolicyTypeTest.cs
  Libplanet.Explorer.Tests/GraphTypes/CurrencyTypeTest.cs
  Libplanet.Explorer.Tests/GraphTypes/FungibleAssetValueTypeTest.cs
  Libplanet.Explorer.Tests/Queries/StateQueryTest.cs
  Libplanet.Explorer/GraphTypes/BlockPolicyType.cs
  Libplanet.Explorer/GraphTypes/BlockType.cs
  Libplanet.Explorer/GraphTypes/CurrencyType.cs
  Libplanet.Explorer/GraphTypes/FungibleAssetValueType.cs
  Libplanet.Explorer/GraphTypes/TransactionType.cs
  Libplanet.Explorer/Libplanet.Explorer.csproj
  Libplanet.Explorer/Queries/ExplorerQuery.cs
  Libplanet.Explorer/Queries/StateQuery.cs
  Libplanet/Blockchain/Policies/IBlockPolicy.cs
  Libplanet/Blocks/IBlockMetadata.cs
Labels: Extra Large

#2225 Refactor IAccountStateDelta
  CHANGES.md
  Libplanet.Explorer.Tests/GraphTypes/CurrencyTypeTest.cs
  Libplanet.Explorer.Tests/Queries/StateQueryTest.cs
  Libplanet.Tests/Action/AccountStateDeltaImplTest.cs
  Libplanet.Tests/Action/AccountStateDeltaImplV0Test.cs
  Libplanet.Tests/Action/AccountStateDeltaImplV3Test.cs
  Libplanet.Tests/Action/AccountStateDeltaTest.cs
  Libplanet.Tests/Action/ActionContextTest.cs
  Libplanet.Tests/Action/ActionEvaluationTest.cs
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
  Libplanet.Tests/Action/Sys/MintTest.cs
  Libplanet.Tests/Assets/CurrencyTest.cs
  Libplanet.Tests/Assets/FungibleAssetValueTest.cs
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet.Tests/Blocks/BlockMetadataTest.cs
  Libplanet.Tests/Blocks/PreEvaluationBlockHeaderTest.cs
  Libplanet/Action/AccountStateDeltaExtensions.cs
  Libplanet/Action/AccountStateDeltaImpl.cs
  Libplanet/Action/AccountStateDeltaImplV0.cs
  Libplanet/Action/AccountStateDeltaImplV3.cs
  Libplanet/Action/ActionEvaluator.cs
  Libplanet/Action/IAccountStateDelta.cs
  Libplanet/Action/IAccountStateView.cs
  Libplanet/Action/TotalSupplyGetter.cs
  Libplanet/Action/TotalSupplyNotTrackableException.cs
  Libplanet/Assets/Currency.cs
  Libplanet/Blockchain/BlockChain.cs
  Libplanet/Blockchain/IBlockChainStates.cs
  Libplanet/Blockchain/NullChainStates.cs
  Libplanet/Blockchain/TotalSupplyStateCompleter.cs
  Libplanet/Blocks/BlockMetadata.cs
Labels: Extra Large

#2241 Standardize custom Exception parameter ordering (#2239)
  CHANGES.md
  Libplanet.Net.Tests/SwarmTest.cs
  Libplanet.Net/Protocols/KademliaProtocol.cs
  Libplanet.Net/Protocols/PingTimeoutException.cs
  Libplanet.Net/Swarm.BlockCandidate.cs
  Libplanet.Net/Swarm.BlockSync.cs
  Libplanet.Node/UntypedTransaction.cs
  Libplanet.Tests/Action/DuplicateActionTypeIdentifierExceptionTest.cs
  Libplanet.Tests/Action/InsufficientBalanceExceptionTest.cs
  Libplanet.Tests/Action/SupplyOverflowExceptionTest.cs
  Libplanet.Tests/Action/TotalSupplyNotTrackableExceptionTest.cs
  Libplanet.Tests/Action/UnexpectedlyTerminatedActionExceptionTest.cs
  Libplanet.Tests/Blockchain/BlockChainTest.Append.cs
  Libplanet.Tests/Blockchain/BlockChainTest.MineBlock.cs
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet.Tests/Blockchain/Policies/BlockPolicyTest.cs
  Libplanet.Tests/Blocks/InvalidBlockPreEvaluationHashExceptionTest.cs
  Libplanet.Tests/TransactionExtensions.cs
  Libplanet/Action/AccountStateDeltaImpl.cs
  Libplanet/Action/AccountStateDeltaImplV0.cs
  Libplanet/Action/ActionEvaluator.cs
  Libplanet/Action/CurrencyPermissionException.cs
  Libplanet/Action/DuplicateActionTypeIdentifierException.cs
  Libplanet/Action/InsufficientBalanceException.cs
  Libplanet/Action/MissingActionTypeException.cs
  Libplanet/Action/PolymorphicAction.cs
  Libplanet/Action/SupplyOverflowException.cs
  Libplanet/Action/TotalSupplyNotTrackableException.cs
  Libplanet/Action/UnexpectedlyTerminatedActionException.cs
  Libplanet/Blockchain/BlockChain.Swap.cs
  Libplanet/Blockchain/BlockChain.cs
  Libplanet/Blockchain/Renderers/Debug/InvalidRenderException.cs
  Libplanet/Blockchain/Renderers/Debug/ValidatingActionRenderer.cs
  Libplanet/Blocks/BlockHeader.cs
  Libplanet/Blocks/BlockMetadata.cs
  Libplanet/Blocks/InvalidBlockPreEvaluationHashException.cs
  Libplanet/Blocks/InvalidBlockProtocolVersionException.cs
  Libplanet/Blocks/InvalidBlockPublicKeyException.cs
  Libplanet/Blocks/InvalidBlockSignatureException.cs
  Libplanet/Blocks/InvalidBlockStateRootHashException.cs
  Libplanet/Blocks/InvalidBlockTotalDifficultyException.cs
  Libplanet/Blocks/InvalidBlockTxHashException.cs
  Libplanet/Blocks/InvalidGenesisBlockException.cs
  Libplanet/Blocks/PreEvaluationBlockHeader.cs
  Libplanet/KeyStore/NoKeyException.cs
  Libplanet/KeyStore/Web3KeyStore.cs
  Libplanet/Tx/InvalidTxException.cs
  Libplanet/Tx/InvalidTxGenesisHashException.cs
  Libplanet/Tx/InvalidTxIdException.cs
  Libplanet/Tx/InvalidTxNonceException.cs
  Libplanet/Tx/InvalidTxSignatureException.cs
  Libplanet/Tx/Transaction.cs
  Libplanet/Tx/TxExcerptExtensions.cs
  Libplanet/Tx/TxPolicyViolationException.cs
Labels: Large

#2246 🚀 Release 0.41.0
  CHANGES.md
Labels: Extra Small

#2248 🔧 Prepare 0.41.1
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: Extra Small

#2249 🔧 Prepare 0.42.0
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: Extra Small

#2250 🔀 Merge 0.41.0 to pbft
  CHANGES.md
  Libplanet.Net.Tests/SwarmTest.cs
  Libplanet.Net/Protocols/KademliaProtocol.cs
  Libplanet.Net/Protocols/PingTimeoutException.cs
  Libplanet.Net/Swarm.BlockCandidate.cs
  Libplanet.Net/Swarm.BlockSync.cs
  Libplanet.Node/UntypedTransaction.cs
  Libplanet.Tests/Action/DuplicateActionTypeIdentifierExceptionTest.cs
  Libplanet.Tests/Action/InsufficientBalanceExceptionTest.cs
  Libplanet.Tests/Action/SupplyOverflowExceptionTest.cs
  Libplanet.Tests/Action/TotalSupplyNotTrackableExceptionTest.cs
  Libplanet.Tests/Action/UnexpectedlyTerminatedActionExceptionTest.cs
  Libplanet.Tests/Blockchain/BlockChainTest.Append.cs
  Libplanet.Tests/Blockchain/BlockChainTest.MineBlock.cs
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet.Tests/Blockchain/Policies/BlockPolicyTest.cs
  Libplanet.Tests/Blocks/InvalidBlockPreEvaluationHashExceptionTest.cs
  Libplanet.Tests/TransactionExtensions.cs
  Libplanet/Action/AccountStateDeltaImpl.cs
  Libplanet/Action/AccountStateDeltaImplV0.cs
  Libplanet/Action/ActionEvaluator.cs
  Libplanet/Action/CurrencyPermissionException.cs
  Libplanet/Action/DuplicateActionTypeIdentifierException.cs
  Libplanet/Action/InsufficientBalanceException.cs
  Libplanet/Action/MissingActionTypeException.cs
  Libplanet/Action/PolymorphicAction.cs
  Libplanet/Action/SupplyOverflowException.cs
  Libplanet/Action/TotalSupplyNotTrackableException.cs
  Libplanet/Action/UnexpectedlyTerminatedActionException.cs
  Libplanet/Blockchain/BlockChain.Swap.cs
  Libplanet/Blockchain/BlockChain.cs
  Libplanet/Blockchain/Renderers/Debug/InvalidRenderException.cs
  Libplanet/Blockchain/Renderers/Debug/ValidatingActionRenderer.cs
  Libplanet/Blocks/BlockHeader.cs
  Libplanet/Blocks/BlockMetadata.cs
  Libplanet/Blocks/InvalidBlockPreEvaluationHashException.cs
  Libplanet/Blocks/InvalidBlockProtocolVersionException.cs
  Libplanet/Blocks/InvalidBlockPublicKeyException.cs
  Libplanet/Blocks/InvalidBlockSignatureException.cs
  Libplanet/Blocks/InvalidBlockStateRootHashException.cs
  Libplanet/Blocks/InvalidBlockTotalDifficultyException.cs
  Libplanet/Blocks/InvalidBlockTxHashException.cs
  Libplanet/Blocks/InvalidGenesisBlockException.cs
  Libplanet/Blocks/PreEvaluationBlockHeader.cs
  Libplanet/KeyStore/NoKeyException.cs
  Libplanet/KeyStore/Web3KeyStore.cs
  Libplanet/Tx/InvalidTxException.cs
  Libplanet/Tx/InvalidTxGenesisHashException.cs
  Libplanet/Tx/InvalidTxIdException.cs
  Libplanet/Tx/InvalidTxNonceException.cs
  Libplanet/Tx/InvalidTxSignatureException.cs
  Libplanet/Tx/Transaction.cs
  Libplanet/Tx/TxExcerptExtensions.cs
  Libplanet/Tx/TxPolicyViolationException.cs
Labels: Large

#2252 Chains are compared only using index
  CHANGES.md
  Libplanet.Explorer.Executable/Program.cs
  Libplanet.Net.Tests/SwarmTest.Broadcast.cs
  Libplanet.Net.Tests/SwarmTest.Consensus.cs
  Libplanet.Net.Tests/SwarmTest.Preload.cs
  Libplanet.Net.Tests/SwarmTest.cs
  Libplanet.Net/BlockDemandTable.cs
  Libplanet.Net/Swarm.BlockCandidate.cs
  Libplanet.Net/Swarm.BlockSync.cs
  Libplanet.Net/Swarm.cs
  Libplanet.Tests/Blockchain/Renderers/DelayedActionRendererTest.cs
  Libplanet.Tests/Blockchain/Renderers/DelayedRendererTest.cs
  Libplanet.Tests/Blockchain/TotalDifficultyComparerTest.cs
  Libplanet/Blockchain/Policies/BlockPolicy.cs
  Libplanet/Blockchain/Policies/IBlockPolicy.cs
  Libplanet/Blockchain/Policies/NullBlockPolicy.cs
  Libplanet/Blockchain/Renderers/DelayedActionRenderer.cs
  Libplanet/Blockchain/Renderers/DelayedRenderer.cs
  Libplanet/Blockchain/TotalDifficultyComparer.cs
  Libplanet/Blocks/IBlockExcerpt.cs
Labels: Large

#2253 Use default `Nonce` for pbft `Block<T>`s
  Libplanet/Blockchain/BlockChain.MineBlock.cs
  Libplanet/Blocks/BlockContent.cs
Labels: Extra Small

#2254 Use propose for tests
  CHANGES.md
  Libplanet.Benchmarks/BlockChain.cs
  Libplanet.Benchmarks/ProposeBlock.cs
  Libplanet.Benchmarks/Store.cs
  Libplanet.Benchmarks/SwarmBenchmark.cs
  Libplanet.Extensions.Cocona.Tests/Commands/StoreCommandTest.cs
  Libplanet.Net.Tests/BlockCompletionTest.cs
  Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextNonProposerTest.cs
  Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextTest.cs
  Libplanet.Net.Tests/Consensus/Context/ContextNonProposerTest.cs
  Libplanet.Net.Tests/Consensus/Context/ContextProposerTest.cs
  Libplanet.Net.Tests/Consensus/Context/ContextProposerValidRoundTest.cs
  Libplanet.Net.Tests/Consensus/Context/ContextTest.cs
  Libplanet.Net.Tests/Messages/MessageTest.cs
  Libplanet.Net.Tests/SwarmTest.Broadcast.cs
  Libplanet.Net.Tests/SwarmTest.Fixtures.cs
  Libplanet.Net.Tests/SwarmTest.Preload.cs
  Libplanet.Net.Tests/SwarmTest.cs
  Libplanet.Tests/Action/AccountStateDeltaImplTest.cs
  Libplanet.Tests/Action/AccountStateDeltaImplV0Test.cs
  Libplanet.Tests/Action/AccountStateDeltaTest.cs
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
  Libplanet.Tests/Blockchain/BlockChainTest.Append.cs
  Libplanet.Tests/Blockchain/BlockChainTest.Internals.cs
  Libplanet.Tests/Blockchain/BlockChainTest.MineBlock.cs
  Libplanet.Tests/Blockchain/BlockChainTest.Stage.cs
  Libplanet.Tests/Blockchain/BlockChainTest.ValidateNextBlock.cs
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet.Tests/Blockchain/Policies/BlockPolicyTest.cs
  Libplanet.Tests/Blockchain/Renderers/AnonymousActionRendererTest.cs
  Libplanet.Tests/Blockchain/Renderers/AnonymousRendererTest.cs
  Libplanet.Tests/Blockchain/Renderers/AtomicActionRendererTest.cs
  Libplanet.Tests/Blockchain/Renderers/DelayedActionRendererTest.cs
  Libplanet.Tests/Blockchain/Renderers/DelayedRendererTest.cs
  Libplanet.Tests/Blockchain/Renderers/LoggedActionRendererTest.cs
  Libplanet.Tests/Blockchain/Renderers/LoggedRendererTest.cs
  Libplanet.Tests/Blockchain/Renderers/NonblockActionRendererTest.cs
  Libplanet.Tests/Blockchain/Renderers/NonblockRendererTest.cs
  Libplanet.Tests/Blocks/BlockFixture.cs
  Libplanet.Tests/Blocks/BlockTest.cs
  Libplanet.Tests/Fixtures/IntegerSet.cs
  Libplanet.Tests/Store/StoreFixture.cs
  Libplanet.Tests/Store/StoreTest.cs
  Libplanet.Tests/TestUtils.cs
  Libplanet/Blockchain/BlockChain.MineBlock.cs
  Libplanet/Blockchain/BlockChain.cs
Labels: Extra Large

#2255 Remove difficulty policy
  CHANGES.md
  Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextNonProposerTest.cs
  Libplanet.Tests/Blockchain/BlockChainTest.ValidateNextBlock.cs
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet/Blockchain/Policies/BlockPolicy.cs
  Libplanet/Blockchain/Policies/IBlockPolicy.cs
  Libplanet/Blockchain/Policies/NullBlockPolicy.cs
Labels: Extra Small

#2256 Remove total difficulty
  CHANGES.md
  Libplanet.Explorer.Tests/GraphTypes/BlockTypeTest.cs
  Libplanet.Explorer/GraphTypes/BlockType.cs
  Libplanet.Net.Tests/Consensus/Context/ContextTestBase.cs
  Libplanet.Net.Tests/Messages/MessageTest.cs
  Libplanet.Net.Tests/Messages/NetMQMessageCodecTest.cs
  Libplanet.Net.Tests/SwarmTest.cs
  Libplanet.Net/BlockDemand.cs
  Libplanet.Net/Messages/ChainStatusMsg.cs
  Libplanet.Net/Messages/Message.cs
  Libplanet.Net/PeerChainState.cs
  Libplanet.Net/Swarm.MessageHandlers.cs
  Libplanet.Net/Swarm.cs
  Libplanet.Node.Tests/UntypedBlockTest.cs
  Libplanet.Node/UntypedBlock.cs
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
  Libplanet.Tests/Blockchain/BlockChainTest.ValidateNextBlock.cs
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet.Tests/Blocks/BlockContentTest.cs
  Libplanet.Tests/Blocks/BlockMarshalerTest.cs
  Libplanet.Tests/Blocks/BlockMetadataTest.cs
  Libplanet.Tests/Blocks/PreEvaluationBlockHeaderTest.cs
  Libplanet.Tests/Blocks/SimpleBlockExcerpt.cs
  Libplanet.Tests/TestUtils.cs
  Libplanet/Blockchain/BlockChain.MineBlock.cs
  Libplanet/Blockchain/Renderers/DelayedRenderer.cs
  Libplanet/Blocks/Block.cs
  Libplanet/Blocks/BlockContent.cs
  Libplanet/Blocks/BlockContentExtensions.cs
  Libplanet/Blocks/BlockExcerptExtensions.cs
  Libplanet/Blocks/BlockHeader.cs
  Libplanet/Blocks/BlockMarshaler.cs
  Libplanet/Blocks/BlockMetadata.cs
  Libplanet/Blocks/BlockMetadataExtensions.cs
  Libplanet/Blocks/BlockPerception.cs
  Libplanet/Blocks/IBlockExcerpt.cs
  Libplanet/Blocks/IBlockMetadata.cs
  Libplanet/Blocks/InvalidBlockTotalDifficultyException.cs
  Libplanet/Blocks/PreEvaluationBlock.cs
  Libplanet/Blocks/PreEvaluationBlockHeader.cs
  Libplanet/Store/BlockDigest.cs
Labels: Large

#2257 Remove difficulty
  CHANGES.md
  Libplanet.Explorer.Executable/Options.cs
  Libplanet.Explorer.Executable/Program.cs
  Libplanet.Explorer.Tests/GraphTypes/BlockTypeTest.cs
  Libplanet.Explorer/GraphTypes/BlockType.cs
  Libplanet.Extensions.Cocona/Commands/StatsCommand.cs
  Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextNonProposerTest.cs
  Libplanet.Net.Tests/Consensus/Context/ContextTestBase.cs
  Libplanet.Net.Tests/Messages/MessageTest.cs
  Libplanet.Node.Tests/UntypedBlockTest.cs
  Libplanet.Node/UntypedBlock.cs
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
  Libplanet.Tests/Blockchain/BlockChainTest.ValidateNextBlock.cs
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet.Tests/Blockchain/Policies/BlockPolicyTest.cs
  Libplanet.Tests/Blocks/BlockContentTest.cs
  Libplanet.Tests/Blocks/BlockMarshalerTest.cs
  Libplanet.Tests/Blocks/BlockMetadataTest.cs
  Libplanet.Tests/Blocks/PreEvaluationBlockHeaderTest.cs
  Libplanet.Tests/Blocks/PreEvaluationBlockTest.cs
  Libplanet.Tests/Fixtures/BlockContentFixture.cs
  Libplanet.Tests/TestUtils.cs
  Libplanet/Blockchain/BlockChain.MineBlock.cs
  Libplanet/Blockchain/Policies/BlockPolicy.cs
  Libplanet/Blockchain/Policies/DifficultyAdjustment.cs
  Libplanet/Blocks/Block.cs
  Libplanet/Blocks/BlockContent.cs
  Libplanet/Blocks/BlockContentExtensions.cs
  Libplanet/Blocks/BlockHeader.cs
  Libplanet/Blocks/BlockMarshaler.cs
  Libplanet/Blocks/BlockMetadata.cs
  Libplanet/Blocks/BlockMetadataExtensions.cs
  Libplanet/Blocks/IBlockMetadata.cs
  Libplanet/Blocks/IPreEvaluationBlockHeader.cs
  Libplanet/Blocks/PreEvaluationBlock.cs
  Libplanet/Blocks/PreEvaluationBlockHeader.cs
  Libplanet/Store/BlockDigest.cs
Labels: Large

#2263 Remove nonce
  CHANGES.md
  Libplanet.Explorer.Tests/GraphTypes/BlockTypeTest.cs
  Libplanet.Explorer/GraphTypes/BlockType.cs
  Libplanet.Net.Tests/Messages/MessageTest.cs
  Libplanet.Net.Tests/SwarmTest.Preload.cs
  Libplanet.Node.Tests/UntypedBlockTest.cs
  Libplanet.Node/UntypedBlock.cs
  Libplanet.Tests/Blocks/BlockContentTest.cs
  Libplanet.Tests/Blocks/BlockMarshalerTest.cs
  Libplanet.Tests/Blocks/BlockMetadataTest.cs
  Libplanet.Tests/Blocks/PreEvaluationBlockHeaderTest.cs
  Libplanet.Tests/Fixtures/BlockContentFixture.cs
  Libplanet.Tests/TestUtils.cs
  Libplanet/Blockchain/BlockChain.MineBlock.cs
  Libplanet/Blocks/Block.cs
  Libplanet/Blocks/BlockContent.cs
  Libplanet/Blocks/BlockHeader.cs
  Libplanet/Blocks/BlockMarshaler.cs
  Libplanet/Blocks/BlockMetadata.cs
  Libplanet/Blocks/IPreEvaluationBlock.cs
  Libplanet/Blocks/IPreEvaluationBlockHeader.cs
  Libplanet/Blocks/InvalidBlockNonceException.cs
  Libplanet/Blocks/PreEvaluationBlock.cs
  Libplanet/Blocks/PreEvaluationBlockHeader.cs
  Libplanet/Store/BlockDigest.cs
  Libplanet/Tx/ITxMetadata.cs
Labels: Extra Large

#2264 Remove mining
  CHANGES.md
  Libplanet.Explorer.Tests/GraphTypes/BlockTypeTest.cs
  Libplanet.Net.Tests/Consensus/Context/ContextTestBase.cs
  Libplanet.Net.Tests/SwarmTest.Broadcast.cs
  Libplanet.Node/NodeUtils.cs
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
  Libplanet.Tests/Blockchain/BlockChainTest.MineBlock.cs
  Libplanet.Tests/Blockchain/BlockChainTest.ValidateNextBlock.cs
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet.Tests/Blockchain/Renderers/DelayedActionRendererTest.cs
  Libplanet.Tests/Blocks/BlockContentTest.cs
  Libplanet.Tests/Blocks/BlockTest.cs
  Libplanet.Tests/Blocks/PreEvaluationBlockHeaderTest.cs
  Libplanet.Tests/Blocks/PreEvaluationBlockTest.cs
  Libplanet.Tests/Fixtures/IntegerSet.cs
  Libplanet/Blockchain/BlockChain.MineBlock.cs
  Libplanet/Blockchain/BlockChain.cs
  Libplanet/Blocks/PreEvaluationBlock.cs
Labels: Large

#2268 Fix `Transaction<T>.Create()` & release 0.40.1
  CHANGES.md
  Libplanet.Tests/Tx/TransactionTest.cs
  Libplanet/Tx/Transaction.cs
Labels: bug, release, Small

#2265 Remove HashalgorithmType
  CHANGES.md
  Libplanet.Extensions.Cocona.Tests/Commands/StoreCommandTest.cs
  Libplanet.Node.Tests/UntypedBlockTest.cs
  Libplanet.Node/UntypedBlock.cs
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
  Libplanet.Tests/Action/UnexpectedlyTerminatedActionExceptionTest.cs
  Libplanet.Tests/Blockchain/BlockChainTest.MineBlock.cs
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet.Tests/Blocks/BlockMarshalerTest.cs
  Libplanet.Tests/Blocks/BlockMetadataTest.cs
  Libplanet.Tests/Blocks/PreEvaluationBlockHeaderTest.cs
  Libplanet.Tests/HashAlgorithmTypeTest.cs
  Libplanet.Tests/HashcashTest.cs
  Libplanet/Action/ActionEvaluator.cs
  Libplanet/Action/UnexpectedlyTerminatedActionException.cs
  Libplanet/Blockchain/BlockChain.MineBlock.cs
  Libplanet/Blockchain/Renderers/Debug/ValidatingActionRenderer.cs
  Libplanet/Blocks/Block.cs
  Libplanet/Blocks/BlockHeader.cs
  Libplanet/Blocks/BlockMarshaler.cs
  Libplanet/Blocks/BlockMetadata.cs
  Libplanet/Blocks/IPreEvaluationBlockHeader.cs
  Libplanet/Blocks/PreEvaluationBlock.cs
  Libplanet/Blocks/PreEvaluationBlockHeader.cs
  Libplanet/HashAlgorithmType.cs
  Libplanet/Hashcash.cs
  Libplanet/Store/BlockDigest.cs
Labels: Large

#2270 Port 0.40.1 to 0.41-maintenance & release 0.41.1
  CHANGES.md
  Libplanet.Tests/Tx/TransactionTest.cs
  Libplanet/Tx/Transaction.cs
Labels: bug, release, Small

#2271 Prepare 0.41.2
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: Extra Small

#2274 🔀 Merge main 0.41.1 to pbft
  CHANGES.md
  Libplanet.Tests/Tx/TransactionTest.cs
  Libplanet/Libplanet.csproj
  Libplanet/Tx/Transaction.cs
Labels: Small
