Repository planetarium/libplanet, pull requests merged in 2022-10, with the labels that each got.

#2363 `Vote` class overhauled
  CHANGES.md
  Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextNonProposerTest.cs
  Libplanet.Net.Tests/Consensus/Context/ContextTest.cs
  Libplanet.Net.Tests/TestUtils.cs
  Libplanet.Net/Consensus/Context.Mutate.cs
  Libplanet.Net/Consensus/Context.cs
  Libplanet.Tests/Blockchain/BlockChainTest.MineBlock.cs
  Libplanet.Tests/Blocks/BlockCommitTest.cs
  Libplanet.Tests/Blocks/BlockFixture.cs
  Libplanet.Tests/Blocks/PreEvaluationBlockHeaderTest.cs
  Libplanet.Tests/Consensus/VoteSetTest.cs
  Libplanet.Tests/Consensus/VoteTest.cs
  Libplanet/Blocks/PreEvaluationBlockHeader.cs
  Libplanet/Consensus/IVoteMetadata.cs
  Libplanet/Consensus/Vote.cs
  Libplanet/Consensus/VoteMetadata.cs
  Libplanet/Consensus/VoteSet.cs
Labels: Extra Large

#2294 @planetarium/tx for creating transactions in JavaScript
  .github/bin/constants.sh
  .github/bin/dist-github-release.sh
  .github/bin/dist-npm.sh
  .github/bin/dist-pack.sh
  .github/workflows/main.yml
  @planetarium/cli
  @planetarium/tx/.editorconfig
  @planetarium/tx/.eslintrc.yaml
  @planetarium/tx/.gitignore
  @planetarium/tx/.prettierignore
  @planetarium/tx/.prettierrc.yaml
  @planetarium/tx/.vscode/extensions.json
  @planetarium/tx/.vscode/settings.json
  @planetarium/tx/README.md
  @planetarium/tx/hooks/pre-commit
  @planetarium/tx/package.json
  @planetarium/tx/src/action.ts
  @planetarium/tx/src/address.ts
  @planetarium/tx/src/assets.ts
  @planetarium/tx/src/binary.ts
  @planetarium/tx/src/blockhash.ts
  @planetarium/tx/src/index.ts
  @planetarium/tx/src/key.ts
  @planetarium/tx/src/tx/index.ts
  @planetarium/tx/src/tx/metadata.ts
  @planetarium/tx/src/tx/unsigned.ts
  @planetarium/tx/test/__snapshots__/action.test.ts.snap
  @planetarium/tx/test/__snapshots__/assets.test.ts.snap
  @planetarium/tx/test/action.test.ts
  @planetarium/tx/test/address.test.ts
  @planetarium/tx/test/assets.test.ts
  @planetarium/tx/test/blockhash.test.ts
  @planetarium/tx/test/bytes.ts
  @planetarium/tx/test/hex.ts
  @planetarium/tx/test/key.test.ts
  @planetarium/tx/test/tx/__snapshots__/metadata.test.ts.snap
  @planetarium/tx/test/tx/fixtures.ts
  @planetarium/tx/test/tx/metadata.test.ts
  @planetarium/tx/test/tx/unsigned.test.ts
  @planetarium/tx/tsconfig.json
  @planetarium/tx/vitest.config.ts
  CHANGES.md
  Libplanet.Extensions.Cocona/Commands/TxCommand.cs
  Libplanet.Tests/Action/Sys/MintTest.cs
  Libplanet.Tests/Action/Sys/TransferTest.cs
  Libplanet.Tests/Libplanet.Tests.csproj
  Libplanet.Tools/Program.cs
  Libplanet/Action/ActionListJsonConverter.cs
  Libplanet/Action/IAction.cs
  Libplanet/Action/Sys/Mint.cs
  Libplanet/Action/Sys/SysActionJsonConverter.cs
  Libplanet/Action/Sys/Transfer.cs
  Libplanet/Libplanet.csproj
  Libplanet/Tx/Transaction.cs
  hooks/pre-commit
Labels: Extra Large, js

#2364 Remove base classes in `Consensus` tests
  Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextNonProposerTest.cs
  Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextProposerTest.cs
  Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextTest.cs
  Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextTestBase.cs
  Libplanet.Net.Tests/Consensus/ConsensusReactorTest.cs
  Libplanet.Net.Tests/Consensus/ConsensusReactorTestBase.cs
  Libplanet.Net.Tests/Consensus/Context/ContextNonProposerTest.cs
  Libplanet.Net.Tests/Consensus/Context/ContextProposerTest.cs
  Libplanet.Net.Tests/Consensus/Context/ContextProposerValidRoundTest.cs
  Libplanet.Net.Tests/Consensus/Context/ContextTest.cs
  Libplanet.Net.Tests/Consensus/Context/ContextTestBase.cs
  Libplanet.Net.Tests/Consensus/GossipTest.cs
  Libplanet.Net.Tests/TestUtils.cs
Labels: Extra Large, pbft

#2354 Upgrade StyleCop analyzer to 1.2.0-beta.435
  Libplanet.Explorer/GraphTypes/BencodexValueType.cs
  Libplanet.Explorer/GraphTypes/ByteStringType.cs
  Libplanet.Explorer/Libplanet.Explorer.csproj
  Libplanet.Explorer/Queries/TransactionQuery.cs
  Libplanet.Explorer/Store/IRichStore.cs
  Libplanet.Explorer/Store/LiteDBRichStore.cs
  Libplanet.Explorer/Store/MySQLRichStore.cs
Labels: explorer, Extra Small

#2370 Fallback with `SHA1Managed` if the platform doesn't support
  Libplanet/Assets/Currency.cs
Labels: suggestion, Extra Small

#2371 Fixed typo in Libplanet.Blockchain.Policies.VoliatileStagePolicy
  Libplanet/Blockchain/Policies/VolatileStagePolicy.cs
Labels: hacktoberfest, Extra Small

#2353 Make TxResultType support TxSuccess fully
  CHANGES.md
  Libplanet.Explorer.Tests/GraphTypes/TxResultTypeTest.cs
  Libplanet.Explorer/GraphTypes/TxResult.cs
  Libplanet.Explorer/GraphTypes/TxResultType.cs
  Libplanet.Explorer/Queries/TransactionQuery.cs
Labels: explorer, Large

#2366 Implement nextNonce query in Libplanet.Explorer
  CHANGES.md
  Libplanet.Explorer.Tests/Queries/TransactionQueryTest.cs
  Libplanet.Explorer/Queries/TransactionQuery.cs
Labels: Small

#2331 Validate existence of +2/3 committed votes in `LastCommit`
  CHANGES.md
  Libplanet.Extensions.Cocona.Tests/Commands/StoreCommandTest.cs
  Libplanet.Net.Tests/BlockCompletionTest.cs
  Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextNonProposerTest.cs
  Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextTest.cs
  Libplanet.Net.Tests/Consensus/Context/ContextTest.cs
  Libplanet.Net.Tests/SwarmTest.Broadcast.cs
  Libplanet.Net.Tests/SwarmTest.Fixtures.cs
  Libplanet.Net.Tests/SwarmTest.Preload.cs
  Libplanet.Net.Tests/SwarmTest.cs
  Libplanet.Net.Tests/TestUtils.cs
  Libplanet.Tests/Action/AccountStateDeltaImplTest.cs
  Libplanet.Tests/Action/AccountStateDeltaTest.cs
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
  Libplanet.Tests/Blockchain/BlockChainTest.Append.cs
  Libplanet.Tests/Blockchain/BlockChainTest.MineBlock.cs
  Libplanet.Tests/Blockchain/BlockChainTest.Stage.cs
  Libplanet.Tests/Blockchain/BlockChainTest.ValidateNextBlock.cs
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet.Tests/Blockchain/Renderers/DelayedActionRendererTest.cs
  Libplanet.Tests/Blockchain/Renderers/DelayedRendererTest.cs
  Libplanet.Tests/Blocks/BlockCommitExtensionsTest.cs
  Libplanet.Tests/Blocks/BlockCommitTest.cs
  Libplanet.Tests/Blocks/BlockFixture.cs
  Libplanet.Tests/Blocks/BlockMarshalerTest.cs
  Libplanet.Tests/Blocks/PreEvaluationBlockHeaderTest.cs
  Libplanet.Tests/Fixtures/BlockContentFixture.cs
  Libplanet.Tests/Fixtures/IntegerSet.cs
  Libplanet.Tests/Store/StoreFixture.cs
  Libplanet.Tests/Store/StoreTest.cs
  Libplanet.Tests/TestUtils.cs
  Libplanet/Blockchain/BlockChain.cs
  Libplanet/Blockchain/Policies/NullBlockPolicy.cs
  Libplanet/Blocks/BlockCommit.cs
  Libplanet/Blocks/BlockCommitExtensions.cs
  Libplanet/Blocks/PreEvaluationBlockHeader.cs
  Libplanet/Consensus/Vote.cs
  Libplanet/Consensus/VoteMetadata.cs
Labels: Extra Large, pbft

#2375 🧹 Json serialization fix
  Libplanet.Tests/TestUtils.cs
  Libplanet/Consensus/Vote.cs
  Libplanet/Consensus/VoteMetadata.cs
Labels: Extra Small

#2376 Disallow empty set of votes for `BlockCommit`
  Libplanet.Tests/Blocks/BlockCommitTest.cs
  Libplanet.Tests/Store/StoreTest.cs
  Libplanet/Blocks/BlockCommit.cs
Labels: Small

#2378 Vote height and round consistency for `BlockCommit`
  Libplanet.Tests/Blocks/BlockCommitExtensionsTest.cs
  Libplanet.Tests/Blocks/BlockCommitTest.cs
  Libplanet.Tests/Blocks/PreEvaluationBlockHeaderTest.cs
  Libplanet/Blocks/BlockCommit.cs
Labels: Large

#2381 🔀 Merge 0.42.2 main to pbft
  CHANGES.md
  Libplanet.Explorer.Tests/TransactionQueryTest.cs
  Libplanet.Explorer/Queries/TransactionQuery.cs
  Libplanet.Tests/Tx/TransactionTest.cs
  Libplanet/Libplanet.csproj
  Libplanet/Tx/Transaction.cs
Labels: Medium

#2382 Option class for consensus timeout configuration
  CHANGES.md
  Libplanet.Net.Tests/TestUtils.cs
  Libplanet.Net/Consensus/ConsensusContext.cs
  Libplanet.Net/Consensus/ConsensusReactor.cs
  Libplanet.Net/Consensus/ConsensusReactorOption.cs
  Libplanet.Net/Consensus/Context.cs
  Libplanet.Net/Consensus/ContextTimeoutOption.cs
  Libplanet.Net/Swarm.cs
Labels: Medium, pbft

#2384 Expose `IComparable` and `IComparable<T>` interface methods for `Address`
  CHANGES.md
  Libplanet.Tests/AddressTest.cs
  Libplanet.Tests/Tx/TxIdTest.cs
  Libplanet/Address.cs
  Libplanet/Tx/TxId.cs
Labels: bug, Extra Small

#2321 More robust `Block<T>` and its subset-types structures
  CHANGES.md
  Libplanet.Explorer.Tests/GraphTypes/BlockTypeTest.cs
  Libplanet.Explorer.Tests/Queries/TransactionQueryTest.cs
  Libplanet.Net.Tests/SwarmTest.Broadcast.cs
  Libplanet.Net.Tests/SwarmTest.Preload.cs
  Libplanet.Node.Tests/UntypedBlockTest.cs
  Libplanet.Node/NodeUtils.cs
  Libplanet.Node/UntypedBlock.cs
  Libplanet.Tests/Action/AccountStateDeltaImplV0Test.cs
  Libplanet.Tests/Action/AccountStateDeltaTest.cs
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
  Libplanet.Tests/Blockchain/BlockChainTest.Append.cs
  Libplanet.Tests/Blockchain/BlockChainTest.MineBlock.cs
  Libplanet.Tests/Blockchain/BlockChainTest.ValidateNextBlock.cs
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet.Tests/Blocks/BlockContentExtensionsTest.cs
  Libplanet.Tests/Blocks/BlockContentTest.cs
  Libplanet.Tests/Blocks/BlockHeaderTest.cs
  Libplanet.Tests/Blocks/BlockMetadataExtensionsTest.cs
  Libplanet.Tests/Blocks/BlockMetadataTest.cs
  Libplanet.Tests/Blocks/BlockTest.cs
  Libplanet.Tests/Blocks/PreEvaluationBlockHeaderTest.cs
  Libplanet.Tests/Blocks/PreEvaluationBlockTest.cs
  Libplanet.Tests/Fixtures/BlockContentFixture.cs
  Libplanet.Tests/Fixtures/IntegerSet.cs
  Libplanet.Tests/TestUtils.cs
  Libplanet/Blockchain/BlockChain.MineBlock.cs
  Libplanet/Blockchain/BlockChain.cs
  Libplanet/Blocks/Block.cs
  Libplanet/Blocks/BlockContent.cs
  Libplanet/Blocks/BlockContentExtensions.cs
  Libplanet/Blocks/BlockHeader.cs
  Libplanet/Blocks/BlockMarshaler.cs
  Libplanet/Blocks/BlockMetadata.cs
  Libplanet/Blocks/BlockMetadataExtensions.cs
  Libplanet/Blocks/IBlockMetadata.cs
  Libplanet/Blocks/IBlockMetadataExtensions.cs
  Libplanet/Blocks/PreEvaluationBlock.cs
  Libplanet/Blocks/PreEvaluationBlockHeader.cs
  Libplanet/Store/BaseStore.cs
  Libplanet/Store/BlockDigest.cs
Labels: Extra Large

#2380 Implement different extra callbacks and ignore
  CHANGES.md
  Libplanet.Net.Tests/Messages/MessageValidatorTest.cs
  Libplanet.Net/Messages/MessageValidator.cs
Labels: Medium

#2387 🔀 Merge 637598588 to pbft
  Libplanet.Node/NodeUtils.cs
  Libplanet.Tests/Blocks/BlockMetadataExtensionsTest.cs
  Libplanet.Tests/Blocks/BlockMetadataTest.cs
  Libplanet.Tests/Blocks/PreEvaluationBlockHeaderTest.cs
  Libplanet/Blocks/BlockMarshaler.cs
  Libplanet/Blocks/BlockMetadata.cs
Labels: Medium

#2388 🔀 Merge 6aff6c657 to pbft
  Libplanet.Tests/Fixtures/BlockContentFixture.cs
  Libplanet/Blocks/BlockContent.cs
  Libplanet/Blocks/BlockMetadata.cs
Labels: Medium

#2389 Release 0.43.0
  CHANGES.md
Labels: Extra Small

#2391 🔀 Merge 81384a9ca to pbft
  Libplanet.Explorer.Tests/GraphTypes/BlockTypeTest.cs
  Libplanet.Explorer.Tests/Queries/TransactionQueryTest.cs
  Libplanet.Net.Tests/Consensus/Context/ContextNonProposerTest.cs
  Libplanet.Net.Tests/Consensus/Context/ContextProposerTest.cs
  Libplanet.Net.Tests/Consensus/Context/ContextProposerValidRoundTest.cs
  Libplanet.Net.Tests/SwarmTest.Broadcast.cs
  Libplanet.Net.Tests/SwarmTest.Preload.cs
  Libplanet.Node.Tests/UntypedBlockTest.cs
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
  Libplanet.Tests/Blockchain/BlockChainTest.Append.cs
  Libplanet.Tests/Blockchain/BlockChainTest.ValidateNextBlock.cs
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet.Tests/Blocks/BlockContentTest.cs
  Libplanet.Tests/Fixtures/IntegerSet.cs
  Libplanet.Tests/TestUtils.cs
  Libplanet/Blockchain/BlockChain.MineBlock.cs
  Libplanet/Blockchain/BlockChain.cs
  Libplanet/Blocks/BlockContent.cs
  Libplanet/Blocks/BlockMetadata.cs
Labels: Extra Large

#2392 🔀 Merge a3b762b3e to pbft
  Libplanet.Tests/Blocks/BlockContentTest.cs
  Libplanet/Blocks/BlockContent.cs
  Libplanet/Blocks/BlockMetadata.cs
Labels: Small

#2393 🔀 Merge ebc6a6b55 to pbft
  Libplanet.Net.Tests/Consensus/Context/ContextProposerTest.cs
  Libplanet.Net.Tests/Consensus/Context/ContextProposerValidRoundTest.cs
  Libplanet.Node.Tests/UntypedBlockTest.cs
  Libplanet.Tests/Blockchain/BlockChainTest.ValidateNextBlock.cs
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet.Tests/Blocks/BlockMetadataExtensionsTest.cs
  Libplanet.Tests/Blocks/BlockMetadataTest.cs
  Libplanet.Tests/Blocks/PreEvaluationBlockHeaderTest.cs
  Libplanet.Tests/Blocks/PreEvaluationBlockTest.cs
  Libplanet.Tests/Fixtures/BlockContentFixture.cs
  Libplanet.Tests/TestUtils.cs
  Libplanet/Blockchain/BlockChain.MineBlock.cs
  Libplanet/Blocks/BlockContent.cs
  Libplanet/Blocks/BlockMarshaler.cs
  Libplanet/Blocks/BlockMetadata.cs
Labels: Large

#2394 🔀 Merge dc9077350 to pbft
  Libplanet.Node.Tests/UntypedBlockTest.cs
  Libplanet.Node/NodeUtils.cs
  Libplanet.Tests/Blocks/BlockContentTest.cs
  Libplanet.Tests/Fixtures/IntegerSet.cs
  Libplanet.Tests/TestUtils.cs
  Libplanet/Blocks/BlockContent.cs
  Libplanet/Blocks/BlockMetadata.cs
  Libplanet/Blocks/IBlockMetadata.cs
Labels: Small

#2396 🔀 Merge 33512fe10 to pbft
  Libplanet.Tests/Blocks/PreEvaluationBlockHeaderTest.cs
  Libplanet/Blocks/PreEvaluationBlockHeader.cs
  Libplanet/Store/BlockDigest.cs
Labels: Extra Small

#2397 Merge bf76c168d to pbft
  Libplanet.Tests/Blocks/BlockContentExtensionsTest.cs
  Libplanet.Tests/Blocks/BlockContentTest.cs
  Libplanet/Blocks/BlockContent.cs
  Libplanet/Blocks/BlockContentExtensions.cs
Labels: Small

#2398 🔀 Merge 3d9ea863f to pbft
  Libplanet.Explorer.Tests/GraphTypes/BlockTypeTest.cs
  Libplanet.Explorer.Tests/Queries/TransactionQueryTest.cs
  Libplanet.Net.Tests/Consensus/Context/ContextNonProposerTest.cs
  Libplanet.Net.Tests/Consensus/Context/ContextProposerTest.cs
  Libplanet.Net.Tests/Consensus/Context/ContextProposerValidRoundTest.cs
  Libplanet.Net.Tests/SwarmTest.Broadcast.cs
  Libplanet.Net.Tests/SwarmTest.Preload.cs
  Libplanet.Node.Tests/UntypedBlockTest.cs
  Libplanet.Node/NodeUtils.cs
  Libplanet.Node/UntypedBlock.cs
  Libplanet.Tests/Action/AccountStateDeltaImplV0Test.cs
  Libplanet.Tests/Action/AccountStateDeltaTest.cs
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
  Libplanet.Tests/Blockchain/BlockChainTest.ValidateNextBlock.cs
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet.Tests/Blocks/BlockContentTest.cs
  Libplanet.Tests/Blocks/BlockHeaderTest.cs
  Libplanet.Tests/Blocks/BlockMetadataExtensionsTest.cs
  Libplanet.Tests/Blocks/BlockTest.cs
  Libplanet.Tests/Blocks/PreEvaluationBlockHeaderTest.cs
  Libplanet.Tests/Blocks/PreEvaluationBlockTest.cs
  Libplanet.Tests/Fixtures/BlockContentFixture.cs
  Libplanet.Tests/Fixtures/IntegerSet.cs
  Libplanet.Tests/TestUtils.cs
  Libplanet/Blockchain/BlockChain.MineBlock.cs
  Libplanet/Blockchain/BlockChain.cs
  Libplanet/Blocks/Block.cs
  Libplanet/Blocks/BlockContent.cs
  Libplanet/Blocks/BlockHeader.cs
  Libplanet/Blocks/BlockMarshaler.cs
  Libplanet/Blocks/BlockMetadata.cs
  Libplanet/Blocks/BlockMetadataExtensions.cs
  Libplanet/Blocks/IBlockMetadataExtensions.cs
  Libplanet/Blocks/PreEvaluationBlock.cs
  Libplanet/Blocks/PreEvaluationBlockHeader.cs
  Libplanet/Store/BlockDigest.cs
Labels: Extra Large

#2399 🔀 Merge 840974d1b to pbft
  CHANGES.md
  Libplanet.Explorer.Tests/GraphTypes/BlockTypeTest.cs
  Libplanet.Explorer.Tests/Queries/TransactionQueryTest.cs
  Libplanet.Net.Tests/Consensus/Context/ContextNonProposerTest.cs
  Libplanet.Net.Tests/SwarmTest.Broadcast.cs
  Libplanet.Net.Tests/SwarmTest.Preload.cs
  Libplanet.Node.Tests/UntypedBlockTest.cs
  Libplanet.Node/NodeUtils.cs
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
  Libplanet.Tests/Blockchain/BlockChainTest.ValidateNextBlock.cs
  Libplanet.Tests/Blocks/BlockContentTest.cs
  Libplanet.Tests/Blocks/BlockMetadataExtensionsTest.cs
  Libplanet.Tests/Blocks/BlockMetadataTest.cs
  Libplanet.Tests/Blocks/PreEvaluationBlockTest.cs
  Libplanet.Tests/Fixtures/BlockContentFixture.cs
  Libplanet.Tests/Fixtures/IntegerSet.cs
  Libplanet/Blockchain/BlockChain.cs
  Libplanet/Blocks/BlockMetadata.cs
Labels: Small

#2400 🔀 Merge 87053edaa to pbft
  Libplanet/Blockchain/BlockChain.cs
  Libplanet/Store/BaseStore.cs
  Libplanet/Store/BlockDigest.cs
Labels: Extra Small

#2402 Temporary test fix
  Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextNonProposerTest.cs
Labels: Extra Small

#2403 🧹 Some finishing touches; placeholder pre-eval-hash check
  Libplanet.Tests/Blocks/BlockMetadataTest.cs
  Libplanet.Tests/Blocks/PreEvaluationBlockHeaderTest.cs
  Libplanet/Blocks/Block.cs
  Libplanet/Blocks/BlockContent.cs
  Libplanet/Blocks/BlockMetadata.cs
  Libplanet/Blocks/PreEvaluationBlock.cs
  Libplanet/Blocks/PreEvaluationBlockHeader.cs
Labels: Large

#2401 Version bump: 0.44.0
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: Extra Small

#2404 🔀 Merge main to pbft
  CHANGES.md
  Libplanet.Explorer.Tests/GraphTypes/BlockTypeTest.cs
  Libplanet.Explorer.Tests/Queries/TransactionQueryTest.cs
  Libplanet.Net.Tests/Consensus/Context/ContextNonProposerTest.cs
  Libplanet.Net.Tests/Consensus/Context/ContextProposerTest.cs
  Libplanet.Net.Tests/Consensus/Context/ContextProposerValidRoundTest.cs
  Libplanet.Net.Tests/SwarmTest.Broadcast.cs
  Libplanet.Net.Tests/SwarmTest.Preload.cs
  Libplanet.Node.Tests/UntypedBlockTest.cs
  Libplanet.Node/NodeUtils.cs
  Libplanet.Node/UntypedBlock.cs
  Libplanet.Tests/Action/AccountStateDeltaImplV0Test.cs
  Libplanet.Tests/Action/AccountStateDeltaTest.cs
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
  Libplanet.Tests/Blockchain/BlockChainTest.Append.cs
  Libplanet.Tests/Blockchain/BlockChainTest.ValidateNextBlock.cs
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet.Tests/Blocks/BlockContentExtensionsTest.cs
  Libplanet.Tests/Blocks/BlockContentTest.cs
  Libplanet.Tests/Blocks/BlockHeaderTest.cs
  Libplanet.Tests/Blocks/BlockMetadataExtensionsTest.cs
  Libplanet.Tests/Blocks/BlockMetadataTest.cs
  Libplanet.Tests/Blocks/BlockTest.cs
  Libplanet.Tests/Blocks/PreEvaluationBlockHeaderTest.cs
  Libplanet.Tests/Blocks/PreEvaluationBlockTest.cs
  Libplanet.Tests/Fixtures/BlockContentFixture.cs
  Libplanet.Tests/Fixtures/IntegerSet.cs
  Libplanet.Tests/TestUtils.cs
  Libplanet/Blockchain/BlockChain.MineBlock.cs
  Libplanet/Blockchain/BlockChain.cs
  Libplanet/Blocks/Block.cs
  Libplanet/Blocks/BlockContent.cs
  Libplanet/Blocks/BlockContentExtensions.cs
  Libplanet/Blocks/BlockHeader.cs
  Libplanet/Blocks/BlockMarshaler.cs
  Libplanet/Blocks/BlockMetadata.cs
  Libplanet/Blocks/BlockMetadataExtensions.cs
  Libplanet/Blocks/IBlockMetadata.cs
  Libplanet/Blocks/IBlockMetadataExtensions.cs
  Libplanet/Blocks/PreEvaluationBlock.cs
  Libplanet/Blocks/PreEvaluationBlockHeader.cs
  Libplanet/Store/BaseStore.cs
  Libplanet/Store/BlockDigest.cs
Labels: Extra Large

#2405 Make all `TxResultType`'s internal types public
  CHANGES.md
  Libplanet.Explorer/GraphTypes/TxResultType.cs
Labels: Extra Small

#2406 Release 0.43.1
  CHANGES.md
Labels: release, Extra Small

#2408 Merge 0.43.1
  CHANGES.md
  Libplanet.Explorer/GraphTypes/TxResultType.cs
Labels: Extra Small

#2409 Version bump
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: Extra Small

#2390 Remove old contexts
  Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextTest.cs
  Libplanet.Net/Consensus/ConsensusContext.cs
  Libplanet.Net/Consensus/Context.cs
Labels: Small, pbft

#2410 🔀 Merge main 0.43.1 to pbft
  CHANGES.md
  Libplanet.Explorer/GraphTypes/TxResultType.cs
  Libplanet.Net.Tests/Messages/MessageValidatorTest.cs
  Libplanet.Net/Messages/MessageValidator.cs
  Libplanet/Libplanet.csproj
Labels: Medium

#2383 Subscribing all `Context` EventHandler
  Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextNonProposerTest.cs
  Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextProposerTest.cs
  Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextTest.cs
  Libplanet.Net.Tests/Consensus/Context/ContextTest.cs
  Libplanet.Net/Consensus/ConsensusContext.Event.cs
  Libplanet.Net/Consensus/ConsensusContext.cs
  Libplanet.Net/Consensus/Context.Async.cs
  Libplanet.Net/Consensus/Context.Event.cs
  Libplanet.Net/Consensus/Context.Mutate.cs
Labels: Medium, pbft

#2412 Added `BlockCommit` hash consistency check
  Libplanet.Tests/Blockchain/BlockChainTest.ValidateNextBlock.cs
  Libplanet.Tests/Blocks/BlockCommitTest.cs
  Libplanet.Tests/Blocks/BlockMetadataTest.cs
  Libplanet.Tests/Store/StoreTest.cs
  Libplanet/Blocks/BlockCommit.cs
  Libplanet/Blocks/BlockMetadata.cs
Labels: Medium

#2411 Access collision in `Context` dictionary
  Libplanet.Net/Consensus/ConsensusContext.cs
Labels: Small, pbft

#2373 Fix flakiness in PBFT `ConsensusContext` test
  Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextNonProposerTest.cs
  Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextProposerTest.cs
  Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextTest.cs
  Libplanet.Net.Tests/Consensus/ConsensusReactorTest.cs
  Libplanet.Net.Tests/Consensus/Context/ContextNonProposerTest.cs
  Libplanet.Net.Tests/Consensus/Context/ContextProposerTest.cs
  Libplanet.Net.Tests/Consensus/Context/ContextProposerValidRoundTest.cs
  Libplanet.Net.Tests/Consensus/Context/ContextTest.cs
Labels: Medium, pbft

#2413 ♻️ Renamed vote flags
  Libplanet.Explorer.Tests/Queries/TransactionQueryTest.cs
  Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextNonProposerTest.cs
  Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextProposerTest.cs
  Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextTest.cs
  Libplanet.Net.Tests/Consensus/Context/ContextNonProposerTest.cs
  Libplanet.Net.Tests/Consensus/Context/ContextProposerTest.cs
  Libplanet.Net.Tests/Consensus/Context/ContextProposerValidRoundTest.cs
  Libplanet.Net.Tests/Consensus/Context/ContextTest.cs
  Libplanet.Net.Tests/TestUtils.cs
  Libplanet.Net/Consensus/Context.Mutate.cs
  Libplanet.Net/Consensus/Context.cs
  Libplanet.Tests/Blockchain/BlockChainTest.ValidateNextBlock.cs
  Libplanet.Tests/Blocks/BlockCommitExtensionsTest.cs
  Libplanet.Tests/Blocks/BlockCommitTest.cs
  Libplanet.Tests/Blocks/BlockFixture.cs
  Libplanet.Tests/Blocks/BlockMetadataTest.cs
  Libplanet.Tests/Consensus/VoteSetTest.cs
  Libplanet.Tests/Consensus/VoteTest.cs
  Libplanet.Tests/TestUtils.cs
  Libplanet/Blocks/BlockCommitExtensions.cs
  Libplanet/Consensus/VoteFlag.cs
  Libplanet/Consensus/VoteSet.cs
Labels: Large

#2414 Moved vote signature validity check to constructor
  Libplanet.Net.Tests/Consensus/Context/ContextTest.cs
  Libplanet.Tests/Blockchain/BlockChainTest.MineBlock.cs
  Libplanet.Tests/Blockchain/BlockChainTest.ValidateNextBlock.cs
  Libplanet.Tests/Blocks/BlockCommitExtensionsTest.cs
  Libplanet.Tests/Blocks/BlockCommitTest.cs
  Libplanet.Tests/Consensus/VoteTest.cs
  Libplanet.Tests/Store/StoreTest.cs
  Libplanet/Consensus/Vote.cs
Labels: Large

#2415 Unexpected vote created with arbitrary `VoteFlag`
  Libplanet.Net.Tests/Consensus/Context/ContextNonProposerTest.cs
  Libplanet.Net.Tests/Consensus/Context/ContextTest.cs
  Libplanet.Net.Tests/Messages/MessageTest.cs
  Libplanet.Net.Tests/TestUtils.cs
  Libplanet.Net/Messages/ConsensusCommit.cs
  Libplanet.Net/Messages/ConsensusVote.cs
Labels: Extra Small, pbft

#2419 Added constraint on vote metadata
  Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextNonProposerTest.cs
  Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextTest.cs
  Libplanet.Net/Consensus/Context.cs
  Libplanet.Tests/Blocks/BlockCommitTest.cs
  Libplanet.Tests/Consensus/VoteMetadataTest.cs
  Libplanet.Tests/Consensus/VoteTest.cs
  Libplanet/Consensus/VoteMetadata.cs
  Libplanet/Consensus/VoteSet.cs
Labels: Small

#2422 Mismatch test fixture of `ConsensusContext` with actual implementation
  Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextTest.cs
  Libplanet.Net.Tests/TestUtils.cs
  Libplanet.Net/Consensus/ConsensusContext.cs
Labels: Extra Small, pbft

#2421 Thread-safe NewHeight method in `ConsensusContext`
  Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextNonProposerTest.cs
  Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextTest.cs
  Libplanet.Net/Consensus/ConsensusContext.cs
Labels: Small

#2426 Added constraints to `BlockCommit`
  Libplanet.Explorer.Tests/Queries/TransactionQueryTest.cs
  Libplanet.Explorer/Store/LiteDBRichStore.cs
  Libplanet.Explorer/Store/MySQLRichStore.cs
  Libplanet.Net.Tests/Consensus/Context/ContextTest.cs
  Libplanet.Net/Consensus/ConsensusContext.cs
  Libplanet.Net/Consensus/Context.cs
  Libplanet.RocksDBStore/RocksDBStore.cs
  Libplanet.Tests/Blockchain/BlockChainTest.MineBlock.cs
  Libplanet.Tests/Blocks/BlockCommitExtensionsTest.cs
  Libplanet.Tests/Blocks/BlockCommitTest.cs
  Libplanet.Tests/Blocks/BlockFixture.cs
  Libplanet.Tests/Blocks/BlockMarshalerTest.cs
  Libplanet.Tests/Blocks/BlockMetadataTest.cs
  Libplanet.Tests/Consensus/VoteSetTest.cs
  Libplanet.Tests/Store/ProxyStore.cs
  Libplanet.Tests/Store/StoreTest.cs
  Libplanet.Tests/Store/StoreTracker.cs
  Libplanet.Tests/TestUtils.cs
  Libplanet/Blockchain/BlockChain.MineBlock.cs
  Libplanet/Blocks/BlockCommit.cs
  Libplanet/Blocks/BlockCommitExtensions.cs
  Libplanet/Consensus/VoteSet.cs
  Libplanet/Store/BaseStore.cs
  Libplanet/Store/DefaultStore.cs
  Libplanet/Store/IStore.cs
  Libplanet/Store/MemoryStore.cs
Labels: Large

#2427 Rename consensus messages
  Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextNonProposerTest.cs
  Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextProposerTest.cs
  Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextTest.cs
  Libplanet.Net.Tests/Consensus/Context/ContextNonProposerTest.cs
  Libplanet.Net.Tests/Consensus/Context/ContextProposerTest.cs
  Libplanet.Net.Tests/Consensus/Context/ContextProposerValidRoundTest.cs
  Libplanet.Net.Tests/Consensus/Context/ContextTest.cs
  Libplanet.Net.Tests/Consensus/GossipTest.cs
  Libplanet.Net.Tests/Consensus/MessageCacheTest.cs
  Libplanet.Net.Tests/Messages/MessageTest.cs
  Libplanet.Net.Tests/TestUtils.cs
  Libplanet.Net/Consensus/ConsensusContext.Event.cs
  Libplanet.Net/Consensus/ConsensusContext.cs
  Libplanet.Net/Consensus/ConsensusReactor.cs
  Libplanet.Net/Consensus/ConsensusReactorOption.cs
  Libplanet.Net/Consensus/Context.Async.cs
  Libplanet.Net/Consensus/Context.Event.cs
  Libplanet.Net/Consensus/Context.Mutate.cs
  Libplanet.Net/Consensus/Context.cs
  Libplanet.Net/Consensus/InvalidBlockProposeMessageException.cs
  Libplanet.Net/Consensus/InvalidHeightMessageException.cs
  Libplanet.Net/Consensus/InvalidProposerProposeMessageException.cs
  Libplanet.Net/Consensus/InvalidValidatorVoteMessageException.cs
  Libplanet.Net/Consensus/MessageLog.cs
  Libplanet.Net/Messages/ConsensusMsg.cs
  Libplanet.Net/Messages/ConsensusPreCommitMsg.cs
  Libplanet.Net/Messages/ConsensusPreVoteMsg.cs
  Libplanet.Net/Messages/ConsensusProposeMsg.cs
  Libplanet.Net/Messages/NetMQMessageCodec.cs
Labels: Large

#2430 Added voting power requirement to `BlockCommit`
  Libplanet.Tests/Blockchain/BlockChainTest.ValidateNextBlock.cs
  Libplanet.Tests/Blocks/BlockCommitExtensionsTest.cs
  Libplanet.Tests/Blocks/BlockCommitTest.cs
  Libplanet.Tests/Blocks/BlockMetadataTest.cs
  Libplanet.Tests/Store/StoreTest.cs
  Libplanet/Blockchain/BlockChain.cs
  Libplanet/Blocks/BlockCommit.cs
  Libplanet/Blocks/BlockCommitExtensions.cs
Labels: Medium

#2428 Default `ConsensusContext.Height` value
  Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextTest.cs
  Libplanet.Net.Tests/TestUtils.cs
  Libplanet.Net/Consensus/ConsensusContext.cs
  Libplanet.Net/Consensus/ConsensusReactor.cs
Labels: Extra Small, pbft

#2431 Change removal `LastCommit` cache target
  Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextTest.cs
  Libplanet.Net/Consensus/ConsensusContext.cs
Labels: Small, pbft

#2432 `Context<T>.VoteSet` only returns same `BlockHash` with proposed block
  Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextTest.cs
  Libplanet.Net.Tests/Consensus/Context/ContextTest.cs
  Libplanet.Net/Consensus/Context.cs
Labels: Small, pbft

#2379 Discover indexes sequentially
  Libplanet.RocksDBStore/RocksDBStore.cs
  Libplanet.Tests/Store/StoreFixture.cs
  Libplanet.Tests/Store/StoreTest.cs
Labels: Medium

#2418 Add `json` field to `ActionType` GraphQL type
  CHANGES.md
  Libplanet.Explorer/GraphTypes/ActionType.cs
  Libplanet.Explorer/Libplanet.Explorer.csproj
Labels: explorer, Extra Small

#2420 Make `Libplanet.Explorer.Executable` work
  CHANGES.md
  Libplanet.Explorer.Tests/Controllers/GenericControllerFeatureProviderTests.cs
  Libplanet.Explorer/Controllers/ExplorerController.cs
  Libplanet.Explorer/Controllers/GenericControllerFeatureProvider.cs
  Libplanet.Explorer/Controllers/GenericControllerNameConvention.cs
  Libplanet.Explorer/Controllers/GraphQLBody.cs
  Libplanet.Explorer/ExplorerStartup.cs
  Libplanet.Explorer/Libplanet.Explorer.csproj
Labels: bug, explorer, Medium

#2365 Support osx-arm64
  .github/bin/constants.sh
  CHANGES.md
  Libplanet.Tools/Libplanet.Tools.csproj
  Libplanet.Tools/README.md
  Libplanet.Tools/download.mjs
  Libplanet.Tools/package.json
Labels: Small, Squash Needed

#2459 Optimize ByteUtil.CalculateHash()
  CHANGES.md
  Libplanet/ByteUtil.cs
Labels: Extra Small

#2462 Fix Mono CI
  Libplanet.Tools/Libplanet.Tools.csproj
Labels: Extra Small

#2463 🧹 Unnecessary code removed
  Libplanet.Net/Consensus/Context.Mutate.cs
  Libplanet/Blockchain/BlockChain.cs
  Libplanet/Blocks/BlockCommitExtensions.cs
Labels: Extra Small

#2457 Streamline `Bencodex` serialization for `Transaction<T>`
  CHANGES.md
  Libplanet.Node.Tests/UntypedBlockTest.cs
  Libplanet.Node.Tests/UntypedTransactionTest.cs
  Libplanet.Node/UntypedTransaction.cs
  Libplanet.Tests/Tx/TransactionTest.cs
  Libplanet.Tests/Tx/TxMetadataTest.cs
  Libplanet/Tx/Transaction.cs
  Libplanet/Tx/TxMetadata.cs
Labels: Large

#2464 🔨 Prevent invalid block proposal
  Libplanet.Net.Tests/Consensus/Context/ContextNonProposerTest.cs
  Libplanet.Net.Tests/Consensus/Context/ContextProposerTest.cs
  Libplanet.Net/Consensus/Context.Mutate.cs
  Libplanet.Net/Consensus/Context.cs
Labels: Small, pbft

#2466 Add `BlockHash` unmarshaler from `Block`
  CHANGES.md
  Libplanet.Tests/Blocks/BlockMarshalerTest.cs
  Libplanet/Blocks/BlockMarshaler.cs
Labels: Extra Small, pbft

#2465 Test cleanup
  Libplanet.Net.Tests/Consensus/Context/ContextNonProposerTest.cs
  Libplanet.Net.Tests/Consensus/Context/ContextProposerTest.cs
  Libplanet.Net.Tests/Consensus/Context/ContextProposerValidRoundTest.cs
  Libplanet.Net.Tests/Consensus/Context/ContextTest.cs
  Libplanet.Net.Tests/TestUtils.cs
  Libplanet.Net/Consensus/ConsensusContext.cs
  Libplanet.Net/Consensus/Context.Mutate.cs
  Libplanet.Net/Consensus/Context.cs
Labels: Extra Large

#2472 Caching `LastCommit` in `Context` disposing
  Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextTest.cs
  Libplanet.Net.Tests/Consensus/Context/ContextTest.cs
  Libplanet.Net.Tests/TestUtils.cs
  Libplanet.Net/Consensus/ConsensusContext.cs
  Libplanet.Net/Consensus/Context.cs
Labels: Medium, pbft

#2471 Fix `MessageLog.CountVotes(Round)` logic
  Libplanet.Net.Tests/Consensus/Context/ContextNonProposerTest.cs
  Libplanet.Net/Consensus/Context.Mutate.cs
  Libplanet.Net/Consensus/Context.cs
  Libplanet.Net/Consensus/MessageLog.cs
Labels: Small

#2386 Exclude problematic tests
  .circleci/config.yml
  Libplanet.Tests/Action/Sys/MintTest.cs
  Libplanet.Tests/Action/Sys/TransferTest.cs
Labels: Extra Small

#2461 Add signable consensus Proposal
  CHANGES.md
  Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextNonProposerTest.cs
  Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextTest.cs
  Libplanet.Net.Tests/Consensus/Context/ContextProposerValidRoundTest.cs
  Libplanet.Net.Tests/Consensus/Context/ContextTest.cs
  Libplanet.Net.Tests/Consensus/GossipTest.cs
  Libplanet.Net.Tests/Consensus/MessageCacheTest.cs
  Libplanet.Net.Tests/Consensus/ProposalMetaDataTest.cs
  Libplanet.Net.Tests/Consensus/ProposalTest.cs
  Libplanet.Net.Tests/Messages/MessageTest.cs
  Libplanet.Net.Tests/TestUtils.cs
  Libplanet.Net/Consensus/Context.Mutate.cs
  Libplanet.Net/Consensus/Context.cs
  Libplanet.Net/Consensus/Proposal.cs
  Libplanet.Net/Consensus/ProposalMetaData.cs
  Libplanet.Net/Messages/ConsensusProposeMsg.cs
Labels: Extra Large, pbft

#2477 ♻️ `Proposal` and `ProposalMetadata`
  Libplanet.Net.Tests/Consensus/Context/ContextTest.cs
  Libplanet.Net.Tests/Messages/MessageTest.cs
  Libplanet.Net.Tests/TestUtils.cs
  Libplanet.Net/Consensus/Context.Mutate.cs
  Libplanet.Net/Messages/ConsensusProposeMsg.cs
  Libplanet.Tests/Consensus/ProposalMetaDataTest.cs
  Libplanet.Tests/Consensus/ProposalTest.cs
  Libplanet/Consensus/Proposal.cs
  Libplanet/Consensus/ProposalMetaData.cs
Labels: Small

#2478 ♻️ Rename `ConsensusProposeMsg` to `ConsensusProposalMsg`
  Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextNonProposerTest.cs
  Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextTest.cs
  Libplanet.Net.Tests/Consensus/Context/ContextProposerTest.cs
  Libplanet.Net.Tests/Consensus/Context/ContextProposerValidRoundTest.cs
  Libplanet.Net.Tests/Consensus/Context/ContextTest.cs
  Libplanet.Net.Tests/Consensus/GossipTest.cs
  Libplanet.Net.Tests/Messages/MessageTest.cs
  Libplanet.Net.Tests/TestUtils.cs
  Libplanet.Net/Consensus/Context.Mutate.cs
  Libplanet.Net/Consensus/Context.cs
  Libplanet.Net/Consensus/InvalidBlockProposeMessageException.cs
  Libplanet.Net/Consensus/InvalidProposerProposeMessageException.cs
  Libplanet.Net/Consensus/MessageLog.cs
  Libplanet.Net/Messages/ConsensusProposalMsg.cs
  Libplanet.Net/Messages/NetMQMessageCodec.cs
  Libplanet/Consensus/Proposal.cs
Labels: Medium

#2479 🔨 Added stricter constraint for steps
  Libplanet.Net/Consensus/Context.Mutate.cs
Labels: Extra Small

#2481 ♻️ Minor fixes
  Libplanet.Net.Tests/Consensus/Context/ContextTest.cs
  Libplanet.Net.Tests/Messages/MessageTest.cs
  Libplanet.Net.Tests/TestUtils.cs
  Libplanet.Net/Consensus/Context.Async.cs
  Libplanet.Net/Consensus/Context.Mutate.cs
  Libplanet.Net/Messages/ConsensusPreCommitMsg.cs
  Libplanet.Net/Messages/ConsensusPreVoteMsg.cs
  Libplanet.Tests/Consensus/ProposalMetaDataTest.cs
  Libplanet.Tests/Consensus/ProposalTest.cs
  Libplanet/Consensus/ProposalMetaData.cs
Labels: Small

#2476 Uncaught exception in `ConsensusContext.NewHeight()`
  Libplanet.Net/Consensus/ConsensusContext.cs
  Libplanet.Net/Consensus/Context.cs
Labels: Extra Small, pbft

#2482 Add `BlockHash` to `Proposal`
  Libplanet.Net.Tests/Consensus/Context/ContextTest.cs
  Libplanet.Net.Tests/Messages/MessageTest.cs
  Libplanet.Net.Tests/TestUtils.cs
  Libplanet.Net/Consensus/Context.Mutate.cs
  Libplanet.Net/Messages/ConsensusMsg.cs
  Libplanet.Net/Messages/ConsensusPreCommitMsg.cs
  Libplanet.Net/Messages/ConsensusPreVoteMsg.cs
  Libplanet.Net/Messages/ConsensusProposalMsg.cs
  Libplanet/Consensus/Proposal.cs
  Libplanet/Consensus/ProposalMetaData.cs
  Libplanet/Consensus/VoteMetadata.cs
Labels: Medium

#2483 Unnecessary code removed
  Libplanet.Net.Tests/Consensus/Context/ContextTest.cs
  Libplanet.Net/Consensus/Context.Mutate.cs
  Libplanet.Net/Consensus/InvalidBlockProposeMessageException.cs
  Libplanet.Net/Messages/ConsensusMsg.cs
Labels: Small

#2487 Refactor `MessageLog`
  Libplanet.Net.Tests/Consensus/Context/MessageLogTest.cs
  Libplanet.Net/Consensus/Context.Mutate.cs
  Libplanet.Net/Consensus/Context.cs
  Libplanet.Net/Consensus/MessageLog.cs
Labels: Large

#2488 🔀 Merge main to pbft
  .circleci/config.yml
  .github/bin/constants.sh
  CHANGES.md
  Libplanet.Explorer.Tests/Controllers/GenericControllerFeatureProviderTests.cs
  Libplanet.Explorer/Controllers/ExplorerController.cs
  Libplanet.Explorer/Controllers/GenericControllerFeatureProvider.cs
  Libplanet.Explorer/Controllers/GenericControllerNameConvention.cs
  Libplanet.Explorer/Controllers/GraphQLBody.cs
  Libplanet.Explorer/ExplorerStartup.cs
  Libplanet.Explorer/Libplanet.Explorer.csproj
  Libplanet.Node.Tests/UntypedBlockTest.cs
  Libplanet.Node.Tests/UntypedTransactionTest.cs
  Libplanet.Node/UntypedTransaction.cs
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
  Libplanet.Tests/Action/Sys/MintTest.cs
  Libplanet.Tests/Action/Sys/TransferTest.cs
  Libplanet.Tests/Blockchain/BlockChainTest.Append.cs
  Libplanet.Tests/Common/Action/ThrowException.cs
  Libplanet.Tests/Fixtures/Arithmetic.cs
  Libplanet.Tests/Tx/TransactionTest.cs
  Libplanet.Tests/Tx/TxMetadataTest.cs
  Libplanet.Tools/Libplanet.Tools.csproj
  Libplanet.Tools/README.md
  Libplanet.Tools/download.mjs
  Libplanet.Tools/package.json
  Libplanet/ByteUtil.cs
  Libplanet/Tx/Transaction.cs
  Libplanet/Tx/TxMetadata.cs
Labels: Extra Large
