Repository planetarium/libplanet, pull requests merged in 2022-01, with the labels that each got.

#1689 Represent `ITrie` keys using `KeyBytes`
  CHANGES.md
  Libplanet.Extensions.Cocona/Commands/MptCommand.cs
  Libplanet.Tests/Action/ActionContextTest.cs
  Libplanet.Tests/Store/StateStoreExtensionsTest.cs
  Libplanet.Tests/Store/Trie/KeyBytesTest.cs
  Libplanet.Tests/Store/Trie/MerkleTrieExtensionsTest.cs
  Libplanet.Tests/Store/Trie/MerkleTrieTest.cs
  Libplanet.Tests/Store/Trie/TrieTest.cs
  Libplanet.Tests/Store/TrieStateStoreTest.cs
  Libplanet/Store/StateStoreExtensions.cs
  Libplanet/Store/Trie/ITrie.cs
  Libplanet/Store/Trie/ITrieExtensions.cs
  Libplanet/Store/Trie/KeyBytes.cs
  Libplanet/Store/Trie/MerkleTrie.cs
  Libplanet/Store/Trie/MerkleTrieExtensions.cs
Labels: storage

#1694 Release 0.25.0
  CHANGES.md
Labels: release

#1697 Release 0.25.1
  CHANGES.md
Labels: release

#1704 Change the way how `TxCompletion<TPeer, TAction>` fetch transaction from other peers
  CHANGES.md
  Libplanet/Net/TxCompletion.cs
Labels: bug

#1707 Release 0.25.2
  CHANGES.md
Labels: release

#1703 API changes for bulk retrieval of multiple states
  CHANGES.md
  Libplanet.Extensions.Cocona/Commands/MptCommand.cs
  Libplanet.Tests/Action/AccountStateDeltaTest.cs
  Libplanet.Tests/Action/ActionContextTest.cs
  Libplanet.Tests/Action/ActionEvaluationTest.cs
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
  Libplanet.Tests/Blockchain/BlockChainTest.Append.cs
  Libplanet.Tests/Blockchain/BlockChainTest.Internals.cs
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet.Tests/Fixtures/IntegerSet.cs
  Libplanet.Tests/Store/StateStoreExtensionsTest.cs
  Libplanet.Tests/Store/Trie/MerkleTrieTest.cs
  Libplanet.Tests/Store/Trie/TrieTest.cs
  Libplanet.Tests/Store/TrieStateStoreTest.cs
  Libplanet/Action/AccountStateDeltaImpl.cs
  Libplanet/Action/AccountStateGetter.cs
  Libplanet/Action/ActionEvaluator.cs
  Libplanet/Action/BalanceGetter.cs
  Libplanet/Action/IAccountStateDelta.cs
  Libplanet/Action/StateGetter.cs
  Libplanet/Blockchain/BlockChain.cs
  Libplanet/Blockchain/FungibleAssetStateCompleter.cs
  Libplanet/Blockchain/IBlockChainStates.cs
  Libplanet/Blockchain/NullChainStates.cs
  Libplanet/Blockchain/StateCompleter.cs
  Libplanet/Blockchain/StateCompleters.cs
  Libplanet/Blocks/PreEvaluationBlock.cs
  Libplanet/Store/StateStoreExtensions.cs
  Libplanet/Store/Trie/ITrie.cs
  Libplanet/Store/Trie/MerkleTrie.cs
Labels: storage, api

#1713 Fix `ArgumentOutOfRangeException` caused by uninitialized `BlockChain<T>`'s `GetStates()`
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet.Tests/Blockchain/NullPolicy.cs
  Libplanet/Blockchain/BlockChain.cs
Labels: bug, storage

#1715 Do not throw error in `NetMQTransport.DoBroadcast()` method & release 0.25.3
  CHANGES.md
  Libplanet/Net/Transports/NetMQTransport.cs
Labels: bug, network, release

#1717 Prepare 0.25.4
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: release

#1716 Port 0.25.3 into main
  CHANGES.md
  Libplanet/Net/Transports/NetMQTransport.cs
Labels: release

#1720 Update Discord links
  CONTRIBUTING.md
  Libplanet.Explorer/README.md
  README.md
Labels: docs, Extra Small

#1699 Introduce `Swarm<T>.BlockCandidateConsumer`
  CHANGES.md
  Libplanet.Tests/Net/SwarmTest.Consensus.cs
  Libplanet.Tests/Net/SwarmTest.cs
  Libplanet/Net/BlockCandidateTable.cs
  Libplanet/Net/Swarm.BlockCandidate.cs
  Libplanet/Net/Swarm.BlockSync.cs
  Libplanet/Net/Swarm.cs
Labels: network, Extra Large

#1719 Fix `RocksDBStore`'s inaccurate lock handling
  CHANGES.md
  Libplanet.RocksDBStore/RocksDBStore.cs
Labels: Extra Small

#1725 Release 0.25.4
  CHANGES.md
Labels: release, Extra Small

#1726 Prepare 0.25.5
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: Extra Small

#1727 Port 0.25.4 to main (0.26.x)
  CHANGES.md
  Libplanet.RocksDBStore/RocksDBStore.cs
  Libplanet/Net/TxCompletion.cs
Labels: Extra Small

#1728 Update Discord introduction
  CONTRIBUTING.md
Labels: Extra Small

#1730 Release 0.26.0
  CHANGES.md
Labels: release, Extra Small

#1732 Prepare 0.27.0
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: Extra Small

#1733 Configure GitHub Codespaces
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .vscode/extensions.json
  .vscode/settings.json
  .vscode/tasks.json
Labels: Extra Small

#1735 Chore - documentation clarification and internal type change
  CHANGES.md
  Libplanet/Net/DifferentAppProtocolVersionException.cs
  Libplanet/Net/Messages/Message.cs
  Libplanet/Net/Transports/ITransport.cs
  Libplanet/Net/Transports/NetMQTransport.cs
Labels: Medium

#1736 More atomic `DealerSocket` handling
  Libplanet/Net/Transports/NetMQTransport.cs
Labels: Extra Small

#1737 Release 0.26.1
  CHANGES.md
Labels: release, Extra Small

#1738 Prepare 0.26.2
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: Extra Small

#1739 Port 0.26.1 to main
  CHANGES.md
  Libplanet/Net/DifferentAppProtocolVersionException.cs
  Libplanet/Net/Messages/Message.cs
  Libplanet/Net/Transports/ITransport.cs
  Libplanet/Net/Transports/NetMQTransport.cs
Labels: Large

#1742 Update CHANGES.md
  CHANGES.md
Labels: Extra Small

#1691 Introduce `TrieStateStore.CopyStates()` method
  CHANGES.md
  Libplanet.Tests/Store/TrieStateStoreTest.cs
  Libplanet/Store/Trie/MerkleTrie.cs
  Libplanet/Store/TrieStateStore.cs
Labels: storage, Medium

#1743 Parallelize MPT path finding
  CHANGES.md
  Libplanet.Tests/Store/Trie/MerkleTriePathCursorTest.cs
  Libplanet.Tests/Store/Trie/Nodes/ShortNodeTest.cs
  Libplanet/Store/Trie/MerkleTrie.Path.cs
  Libplanet/Store/Trie/MerkleTrie.cs
  Libplanet/Store/Trie/Nodes/ShortNode.cs
Labels: storage, Extra Large

#1746 Rename project `Libplanet.Explorer.UnitTests` → `Libplanet.Explorer.Tests`
  .prettierignore
  CONTRIBUTING.md
  Libplanet.Explorer.Tests/Controllers/GenericControllerFeatureProviderTests.cs
  Libplanet.Explorer.Tests/GraphQLTestUtils.cs
  Libplanet.Explorer.Tests/GraphTypes/AddressTypeTest.cs
  Libplanet.Explorer.Tests/GraphTypes/BlockTypeTest.cs
  Libplanet.Explorer.Tests/GraphTypes/ByteStringTypeTest.cs
  Libplanet.Explorer.Tests/GraphTypes/PublicKeyTypeTest.cs
  Libplanet.Explorer.Tests/GraphTypes/ScalarGraphTypeTestBase.cs
  Libplanet.Explorer.Tests/GraphTypes/TransactionTypeTest.cs
  Libplanet.Explorer.Tests/Libplanet.Explorer.Tests.csproj
  Libplanet.Explorer.Tests/TestUtils.cs
  Libplanet.sln
Labels: Extra Small

#1747 Upgrade node-fetch for @planetarium/cli package
  CHANGES.md
  Libplanet.Tools/package.json
Labels: bug, tools, packaging, Extra Small

#1748 Expose `NullPolicy` as a public class
  CHANGES.md
  Libplanet.Benchmarks/BlockChain.cs
  Libplanet.Benchmarks/MineBlock.cs
  Libplanet.Benchmarks/SwarmBenchmark.cs
  Libplanet.RocksDBStore.Tests/RocksDBStoreTest.cs
  Libplanet.Tests/Action/AccountStateDeltaTest.cs
  Libplanet.Tests/Blockchain/BlockChainTest.Append.cs
  Libplanet.Tests/Blockchain/BlockChainTest.MineBlock.cs
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet.Tests/Fixtures/IntegerSet.cs
  Libplanet.Tests/Net/SwarmTest.Broadcast.cs
  Libplanet.Tests/Net/SwarmTest.cs
  Libplanet.Tests/Store/StoreTest.cs
  Libplanet/Blockchain/Policies/NullBlockPolicy.cs
Labels: Small

#1744 Remove `RoutingTable` dependency from `ITransport`
  CHANGES.md
  Libplanet.Tests/Net/Protocols/TestTransport.cs
  Libplanet.Tests/Net/Transports/NetMQTransportTest.cs
  Libplanet.Tests/Net/Transports/TcpTransportTest.cs
  Libplanet.Tests/Net/Transports/TransportTest.cs
  Libplanet/Net/Swarm.MessageHandlers.cs
  Libplanet/Net/Swarm.cs
  Libplanet/Net/Transports/ITransport.cs
  Libplanet/Net/Transports/NetMQTransport.cs
  Libplanet/Net/Transports/TcpTransport.cs
Labels: api, Large

#1749 Unnecessary clutter removed.
  Libplanet.Tests/Net/Messages/MessageTest.cs
  Libplanet/Net/Messages/IMessageCodec.cs
  Libplanet/Net/Messages/NetMQMessageCodec.cs
  Libplanet/Net/Messages/TcpMessageCodec.cs
Labels: Extra Small

#1752 Retries removed from `NetMQTransport`
  CHANGES.md
  Libplanet/Net/Transports/NetMQTransport.cs
Labels: Small

#1757 Enable null checker for all projects
  Libplanet.Explorer/Controllers/ExplorerController.cs
  Libplanet.Explorer/Controllers/GraphQLBody.cs
  Libplanet.Explorer/ExplorerStartup.cs
  Libplanet.Explorer/GraphTypes/ActionType.cs
  Libplanet.Explorer/GraphTypes/AddressType.cs
  Libplanet.Explorer/GraphTypes/BlockType.cs
  Libplanet.Explorer/GraphTypes/ByteStringType.cs
  Libplanet.Explorer/GraphTypes/NodeStateType.cs
  Libplanet.Explorer/GraphTypes/PublicKeyType.cs
  Libplanet.Explorer/GraphTypes/TransactionType.cs
  Libplanet.Explorer/Interfaces/IBlockChainContext.cs
  Libplanet.Explorer/Libplanet.Explorer.csproj
  Libplanet.Explorer/Queries/BlockQuery.cs
  Libplanet.Explorer/Queries/ExplorerQuery.cs
  Libplanet.Explorer/Queries/TransactionQuery.cs
  Libplanet.Explorer/Store/AddressRefDoc.cs
  Libplanet.Explorer/Store/IRichStore.cs
  Libplanet.Explorer/Store/LiteDBRichStore.cs
  Libplanet.Explorer/Store/MySQLRichStore.cs
  Libplanet.Explorer/Store/MySQLRichStoreOptions.cs
  Libplanet.RocksDBStore/Libplanet.RocksDBStore.csproj
  Libplanet.RocksDBStore/RocksDBKeyValueStore.cs
  Libplanet.RocksDBStore/RocksDBStore.cs
  Libplanet.RocksDBStore/RocksDBUtils.cs
  Libplanet.Stun/Libplanet.Stun.csproj
  Libplanet.Stun/Stun/Attributes/Attribute.cs
  Libplanet.Stun/Stun/Attributes/ConnectionId.cs
  Libplanet.Stun/Stun/Attributes/ErrorCode.cs
  Libplanet.Stun/Stun/Attributes/Fingerprint.cs
  Libplanet.Stun/Stun/Attributes/Lifetime.cs
  Libplanet.Stun/Stun/Attributes/MessageIntegrity.cs
  Libplanet.Stun/Stun/Attributes/Nonce.cs
  Libplanet.Stun/Stun/Attributes/Realm.cs
  Libplanet.Stun/Stun/Attributes/RequestedTransport.cs
  Libplanet.Stun/Stun/Attributes/Software.cs
  Libplanet.Stun/Stun/Attributes/StunAddressExtensions.cs
  Libplanet.Stun/Stun/Attributes/Username.cs
  Libplanet.Stun/Stun/Attributes/XorMappedAddress.cs
  Libplanet.Stun/Stun/Attributes/XorPeerAddress.cs
  Libplanet.Stun/Stun/Attributes/XorRelayedAddress.cs
  Libplanet.Stun/Stun/IStunContext.cs
  Libplanet.Stun/Stun/Messages/AllocateErrorResponse.cs
  Libplanet.Stun/Stun/Messages/AllocateRequest.cs
  Libplanet.Stun/Stun/Messages/AllocateSuccessResponse.cs
  Libplanet.Stun/Stun/Messages/BindingRequest.cs
  Libplanet.Stun/Stun/Messages/BindingSuccessResponse.cs
  Libplanet.Stun/Stun/Messages/ConnectRequest.cs
  Libplanet.Stun/Stun/Messages/ConnectSuccessResponse.cs
  Libplanet.Stun/Stun/Messages/ConnectionAttempt.cs
  Libplanet.Stun/Stun/Messages/ConnectionBindRequest.cs
  Libplanet.Stun/Stun/Messages/ConnectionBindSuccessResponse.cs
  Libplanet.Stun/Stun/Messages/CreatePermissionErrorResponse.cs
  Libplanet.Stun/Stun/Messages/CreatePermissionRequest.cs
  Libplanet.Stun/Stun/Messages/CreatePermissionSuccessResponse.cs
  Libplanet.Stun/Stun/Messages/RefreshErrorResponse.cs
  Libplanet.Stun/Stun/Messages/RefreshRequest.cs
  Libplanet.Stun/Stun/Messages/RefreshSuccessResponse.cs
  Libplanet.Stun/Stun/Messages/StunMessage.cs
  Libplanet.Stun/Stun/TurnClient.cs
  Libplanet.Stun/Stun/TurnClientException.cs
Labels: Small

#1756 Make some message classes public
  CHANGES.md
  Libplanet/Net/Messages/DifferentVersion.cs
  Libplanet/Net/Messages/FindNeighbors.cs
  Libplanet/Net/Messages/Neighbors.cs
  Libplanet/Net/Messages/Ping.cs
  Libplanet/Net/Messages/Pong.cs
Labels: Extra Small

#1758 Added metric log for transaction evaluation
  CHANGES.md
  Libplanet/Action/ActionEvaluator.cs
Labels: Extra Small

#1763 More info on transaction evaluation log
  Libplanet/Action/ActionEvaluator.cs
Labels: Extra Small

#1764 Record more logs during mining & release 0.26.2
  CHANGES.md
  Libplanet.Tests/EnumerableMeasurementTest.cs
  Libplanet/Action/ActionEvaluator.cs
  Libplanet/Blocks/PreEvaluationBlock.cs
  Libplanet/EnumerableMeasurement.cs
Labels: release, Medium

#1759 Use `BlockCandidateTable<T>` on `PollBlocksAsync`
  CHANGES.md
  Libplanet.Net.Tests/SwarmTest.Broadcast.cs
  Libplanet.Net/Swarm.BlockCandidate.cs
  Libplanet.Net/Swarm.BlockSync.cs
  Libplanet.Net/Swarm.cs
Labels: network, Medium

#1765 Prepare 0.26.3
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: Extra Small

#1766 Port 0.26.2 to main (0.27.x)
  CHANGES.md
  Libplanet.Tests/EnumerableMeasurementTest.cs
  Libplanet/Action/ActionEvaluator.cs
  Libplanet/Blocks/PreEvaluationBlock.cs
  Libplanet/EnumerableMeasurement.cs
Labels: Medium

#1768 Release 0.27.0
  CHANGES.md
Labels: release, Extra Small

#1769 Prepare 0.28.0
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: Extra Small
