Repository planetarium/libplanet, pull requests merged in 2022-02, with the labels that each got.

#1774 Measure time spend during `IsBlockNeeded` when receiving new `BlockHeaderMessage`
  Libplanet/Net/Swarm.MessageHandlers.cs
Labels: Extra Small

#1775 Preload multiple times to catch up tip close enough & release 0.26.3
  CHANGES.md
  Libplanet/EnumerableExtensions.cs
  Libplanet/Net/Swarm.cs
Labels: network, release, Medium

#1776 Prepare 0.26.4
  CHANGES.md
Labels: Extra Small

#1771 Finer `Exception`s
  CHANGES.md
  Libplanet.Net.Tests/InvalidMessageTimestampExceptionTest.cs
  Libplanet.Net.Tests/Messages/MessageTest.cs
  Libplanet.Net/InvalidMessageSignatureException.cs
  Libplanet.Net/InvalidMessageTimestampException.cs
  Libplanet.Net/Messages/IMessageCodec.cs
  Libplanet.Net/Messages/NetMQMessageCodec.cs
  Libplanet.Net/Messages/TcpMessageCodec.cs
  Libplanet.Net/Protocols/KademliaProtocol.cs
  Libplanet.Net/Transports/NetMQTransport.cs
Labels: Small

#1777 Port 0.26.3 & release 0.27.1
  CHANGES.md
  Libplanet.Net/Swarm.MessageHandlers.cs
  Libplanet.Net/Swarm.cs
  Libplanet/EnumerableExtensions.cs
Labels: release, Medium

#1779 Port 0.26.3/0.27.1 to main (0.28.x) & add `tipDeltaThreshold` to `Swarm<T>.PreloadAsync()`
  CHANGES.md
  Libplanet.Net/Swarm.MessageHandlers.cs
  Libplanet.Net/Swarm.cs
  Libplanet/EnumerableExtensions.cs
Labels: network, Medium

#1782 Render duration log added
  Libplanet/Blockchain/BlockChain.Swap.cs
Labels: Extra Small

#1778 Use `TrySendMultipartMessage` instead of `SendMultipartMessageAsync` extension method
  CHANGES.md
  Libplanet.Net/Transports/NetMQTransport.cs
Labels: Extra Small

#1783 Release 0.27.2
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: release, Extra Small

#1785 Port to 0.27.2 main
  CHANGES.md
  Libplanet.Net/Transports/NetMQTransport.cs
  Libplanet/Blockchain/BlockChain.Swap.cs
Labels: Small

#1784 Prepare 0.27.3
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: Extra Small

#1786 Add `MessageSendFailedException`
  CHANGES.md
  Libplanet.Net.Tests/Transports/MessageSendFailedExceptionTest.cs
  Libplanet.Net/Transports/MessageSendFailedException.cs
  Libplanet.Net/Transports/NetMQTransport.cs
Labels: Small

#1787 Add transport type selection for `SwarmTest`s by environment variables
  .circleci/config.yml
  Libplanet.Net.Tests/AppProtocolVersionTest.cs
  Libplanet.Net.Tests/BlockCompletionTest.cs
  Libplanet.Net.Tests/BoundPeerTest.cs
  Libplanet.Net.Tests/FactOnlyTurnAvailableAttribute.cs
  Libplanet.Net.Tests/IceServerTest.cs
  Libplanet.Net.Tests/InvalidMessageTimestampExceptionTest.cs
  Libplanet.Net.Tests/Messages/BlockHashesTest.cs
  Libplanet.Net.Tests/Messages/MessageTest.cs
  Libplanet.Net.Tests/Messages/NetMQMessageCodecTest.cs
  Libplanet.Net.Tests/PeerTest.cs
  Libplanet.Net.Tests/Protocols/KBucketTest.cs
  Libplanet.Net.Tests/Protocols/ProtocolTest.cs
  Libplanet.Net.Tests/Protocols/RoutingTableTest.cs
  Libplanet.Net.Tests/Protocols/TestMessage.cs
  Libplanet.Net.Tests/Protocols/TestTransport.cs
  Libplanet.Net.Tests/SwarmTest.AppProtocolVersion.cs
  Libplanet.Net.Tests/SwarmTest.Broadcast.cs
  Libplanet.Net.Tests/SwarmTest.Consensus.cs
  Libplanet.Net.Tests/SwarmTest.Fixtures.cs
  Libplanet.Net.Tests/SwarmTest.Preload.cs
  Libplanet.Net.Tests/SwarmTest.cs
  Libplanet.Net.Tests/Transports/BoundPeerExtensionsTest.cs
  Libplanet.Net.Tests/Transports/InvalidMagicCookieExceptionTest.cs
  Libplanet.Net.Tests/Transports/MessageSendFailedExceptionTest.cs
  Libplanet.Net.Tests/Transports/NetMQTransportTest.cs
  Libplanet.Net.Tests/Transports/TcpTransportTest.cs
  Libplanet.Net.Tests/Transports/TransportExceptionTest.cs
  Libplanet.Net.Tests/Transports/TransportTest.cs
Labels: ci & cd, Large

#1792 Revert #1759
  CHANGES.md
  Libplanet.Net.Tests/SwarmTest.Broadcast.cs
  Libplanet.Net/Swarm.BlockCandidate.cs
  Libplanet.Net/Swarm.BlockSync.cs
  Libplanet.Net/Swarm.cs
Labels: bug, Medium

#1795 Prepare 0.27.4
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: Extra Small

#1797 Port to 0.27.3 main
  CHANGES.md
  Libplanet.Net.Tests/SwarmTest.Broadcast.cs
  Libplanet.Net/Swarm.BlockCandidate.cs
  Libplanet.Net/Swarm.BlockSync.cs
  Libplanet.Net/Swarm.cs
Labels: Medium

#1799 Fix @planetarium/cli npm package
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .github/workflows/main.yml
  .vscode/extensions.json
  CHANGES.md
  Libplanet.Tools/.gitignore
  Libplanet.Tools/CONTRIBUTING.md
  Libplanet.Tools/bin/npm-test.ps1
  Libplanet.Tools/bin/npm-test.sh
  Libplanet.Tools/bin/planet.mjs
  Libplanet.Tools/download.js
  Libplanet.Tools/download.mjs
  Libplanet.Tools/install.mjs
  Libplanet.Tools/package.json
Labels: bug, tools, packaging, Extra Large

#1791 Bump RocksDbSharp for support arm64
  CHANGES.md
  Libplanet.RocksDBStore/Libplanet.RocksDBStore.csproj
Labels: Extra Small

#1798 Rollback #1759
  CHANGES.md
  Libplanet.Net.Tests/SwarmTest.Broadcast.cs
  Libplanet.Net/Swarm.BlockCandidate.cs
  Libplanet.Net/Swarm.BlockSync.cs
  Libplanet.Net/Swarm.cs
Labels: Medium

#1800 Release 0.27.4
  .devcontainer/devcontainer.json
  .vscode/extensions.json
  CHANGES.md
Labels: bug, release, Extra Small

#1801 Prepare 0.27.5
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: Extra Small

#1803 Porting #1791 (Bump RocksDbSharp for support arm64)
  CHANGES.md
  Libplanet.RocksDBStore/Libplanet.RocksDBStore.csproj
Labels: Extra Small

#1802 Additional network related metric logs
  CHANGES.md
  Libplanet/Net/Transports/NetMQTransport.cs
Labels: Small

#1804 Release 0.26.4
  CHANGES.md
Labels: release, Extra Small

#1806 Fix `VersionPrefix` & release 0.26.4
  Libplanet/Libplanet.csproj
Labels: bug, release, packaging, Extra Small

#1805 Prepare 0.26.5
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: Extra Small

#1808 Port 0.26.4 & release 0.27.5
  CHANGES.md
  Libplanet.Net/Transports/NetMQTransport.cs
  Libplanet.RocksDBStore/Libplanet.RocksDBStore.csproj
Labels: release, Small

#1796 Fix some flaky unit tests in `Libplanet.Net.Tests`
  CHANGES.md
  Libplanet.Tests/Net/SwarmTest.Broadcast.cs
  Libplanet.Tests/Net/SwarmTest.Preload.cs
  Libplanet.Tests/Net/SwarmTest.cs
  Libplanet.Tests/TestUtils.cs
  Libplanet/Net/Swarm.cs
Labels: Small

#1810 Fix `ThreadStateException` thrown by `NonblockRenderer<T>`
  CHANGES.md
  Libplanet.Tests/Blockchain/Renderers/NonblockRendererTest.cs
  Libplanet/Blockchain/Renderers/NonblockRenderer.cs
  Libplanet/Net/Swarm.BlockCandidate.cs
Labels: bug, Small

#1809 Port 0.27.6 to main (0.28.x)
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .github/workflows/main.yml
  .vscode/extensions.json
  CHANGES.md
  Libplanet.Net.Tests/SwarmTest.Broadcast.cs
  Libplanet.Net.Tests/SwarmTest.Preload.cs
  Libplanet.Net.Tests/SwarmTest.cs
  Libplanet.Net/Swarm.BlockCandidate.cs
  Libplanet.Net/Swarm.BlockSync.cs
  Libplanet.Net/Swarm.cs
  Libplanet.Net/Transports/NetMQTransport.cs
  Libplanet.Tests/Blockchain/Renderers/NonblockRendererTest.cs
  Libplanet.Tests/TestUtils.cs
  Libplanet.Tools/.gitignore
  Libplanet.Tools/CONTRIBUTING.md
  Libplanet.Tools/bin/npm-test.ps1
  Libplanet.Tools/bin/npm-test.sh
  Libplanet.Tools/bin/planet.mjs
  Libplanet.Tools/download.js
  Libplanet.Tools/download.mjs
  Libplanet.Tools/install.mjs
  Libplanet.Tools/package.json
  Libplanet/Blockchain/Renderers/NonblockRenderer.cs
Labels: Extra Large

#1815 Fix `HashDigest<T>.DeriveFrom()` on .NET Standard 2.0 & release 0.25.5
  CHANGES.md
  Libplanet/HashDigest.cs
Labels: bug, release, Extra Small

#1816 Port 0.25.5 & release 0.26.6
  CHANGES.md
  Libplanet/HashDigest.cs
Labels: release, Extra Small

#1817 Port 0.26.6 & release 0.27.7
  CHANGES.md
  Libplanet/HashDigest.cs
Labels: bug, release, Extra Small

#1818 Port 0.27.7 into main (0.28.x)
  CHANGES.md
  Libplanet/HashDigest.cs
Labels: bug, Extra Small

#1820 Bad tabbing introduced in `0.26.x`
  Libplanet.Net/Transports/NetMQTransport.cs
Labels: Extra Small

#1789 Single cancellation timer during `NetMQTransport.SendMessageWithReplyAsync()`
  CHANGES.md
  Libplanet.Net/NetMQSocketExtensions.cs
  Libplanet.Net/Transports/NetMQTransport.cs
Labels: Small

#1823 Allow `planet` command to take passphrase from stdin
  .devcontainer/devcontainer.json
  .vscode/extensions.json
  CHANGES.md
  Libplanet.Extensions.Cocona/Commands/ApvCommand.cs
  Libplanet.Extensions.Cocona/Commands/KeyCommand.cs
  Libplanet.Extensions.Cocona/Libplanet.Extensions.Cocona.csproj
  Libplanet.Extensions.Cocona/PassphraseParameters.cs
  Libplanet.Tools/Libplanet.Tools.csproj
Labels: bug, tools, Medium

#1518 OrderTxsForEvaluationV3 added
  CHANGES.md
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
  Libplanet.Tests/Blockchain/BlockChainTest.ValidateNextBlock.cs
  Libplanet.Tests/Blocks/BlockMetadataTest.cs
  Libplanet.Tests/Blocks/PreEvaluationBlockHeaderTest.cs
  Libplanet/Action/ActionEvaluator.cs
  Libplanet/Blocks/BlockMetadata.cs
Labels: Medium

#1773 Logging ActionEvaluator<T>.Evaluate() directly
  CHANGES.md
  Libplanet/Action/ActionEvaluator.cs
  Libplanet/Blockchain/BlockChain.cs
Labels: Small

#1825 Fix socket leak
  CHANGES.md
  Libplanet.Net/Transports/NetMQTransport.cs
Labels: Extra Small

#1824 Funnel broadcast to send
  CHANGES.md
  Libplanet.Net/Transports/NetMQTransport.cs
Labels: Small

#1826 Release 0.28.0
  CHANGES.md
Labels: Extra Small

#1827 Prepare 0.29.0
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: Extra Small

#1832 Unused parameter removed from `NetMQTransport()`
  CHANGES.md
  Libplanet.Net/Transports/NetMQTransport.cs
Labels: Extra Small

#1831 Fix/message timestamp buffer
  CHANGES.md
  Libplanet.Net.Tests/InvalidMessageTimestampExceptionTest.cs
  Libplanet.Net.Tests/Messages/MessageTest.cs
  Libplanet.Net.Tests/Transports/NetMQTransportTest.cs
  Libplanet.Net.Tests/Transports/TcpTransportTest.cs
  Libplanet.Net.Tests/Transports/TransportTest.cs
  Libplanet.Net/InvalidMessageTimestampException.cs
  Libplanet.Net/Messages/NetMQMessageCodec.cs
  Libplanet.Net/Messages/TcpMessageCodec.cs
  Libplanet.Net/Swarm.cs
  Libplanet.Net/SwarmOptions.cs
  Libplanet.Net/Transports/NetMQTransport.cs
  Libplanet.Net/Transports/TcpTransport.cs
Labels: Small
