Repository planetarium/libplanet, pull requests merged in 2022-05, with the labels that each got.

#1938 Add Height to ConsensusMessages
  Libplanet.Net/Messages/ConsensusCommit.cs
  Libplanet.Net/Messages/ConsensusMessage.cs
  Libplanet.Net/Messages/ConsensusPropose.cs
  Libplanet.Net/Messages/ConsensusVote.cs
Labels: Extra Small

#1920 feat(cli): introduce `planet key sign` command
  CHANGES.md
  Libplanet.Extensions.Cocona/Commands/KeyCommand.cs
Labels: suggestion, tools, Extra Small

#1939 Merge posplanet into libplanet
  Libplanet.Net.Tests/Consensus/ConsensusContextTest.cs
  Libplanet.Net.Tests/Consensus/ConsensusReactorTest.cs
  Libplanet.Net.Tests/Consensus/ReactorTest.cs
  Libplanet.Net.Tests/Consensus/RoundContextTest.cs
  Libplanet.Net.Tests/Consensus/States/DefaultStateTest.cs
  Libplanet.Net.Tests/Consensus/States/PreCommitStateTest.cs
  Libplanet.Net.Tests/Consensus/States/PreVoteStateTest.cs
  Libplanet.Net.Tests/Consensus/TimeoutTickerTest.cs
  Libplanet.Net.Tests/TestUtils.cs
  Libplanet.Net/Consensus/BaseStore.cs
  Libplanet.Net/Consensus/ConsensusContext.cs
  Libplanet.Net/Consensus/ConsensusReactor.cs
  Libplanet.Net/Consensus/DefaultState.cs
  Libplanet.Net/Consensus/IReactor.cs
  Libplanet.Net/Consensus/IState.cs
  Libplanet.Net/Consensus/PreCommitState.cs
  Libplanet.Net/Consensus/PreVoteState.cs
  Libplanet.Net/Consensus/RoundContext.cs
  Libplanet.Net/Consensus/TimeoutTicker.cs
  Libplanet.Net/Consensus/TryUnexpectedMessageHandleException.cs
  Libplanet.Net/Consensus/UnexpectedHeightProposeException.cs
  Libplanet.Net/Consensus/UnexpectedLeaderProposeException.cs
  Libplanet.Net/Consensus/UnexpectedRoundProposeException.cs
Labels: consensus, Extra Large

#1935 Abstract `DataModel` feature
  CHANGES.md
  Libplanet.Tests/Store/DataModelTest.cs
  Libplanet/Store/DataModel.Decode.cs
  Libplanet/Store/DataModel.Encode.cs
  Libplanet/Store/DataModel.cs
Labels: Extra Large

#1947 Remove unused/unnecessary stuff
  Libplanet.Net/Swarm.BlockSync.cs
  Libplanet.Net/Swarm.MessageHandlers.cs
  Libplanet.Net/Swarm.cs
Labels: Extra Small

#1950 [skip changelog] Fix broken tests
  Libplanet.Tests/Store/DataModelTest.cs
  Libplanet/Store/DataModel.cs
Labels: Extra Small

#1951 Release 0.34.0
  CHANGES.md
Labels: Extra Small

#1952 Prepare 0.35.0
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: Extra Small

#1966 `TimeSpanExtensions.Multiply()` added
  CHANGES.md
  Libplanet.Net.Tests/Messages/MessageValidatorTest.cs
  Libplanet.Tests/TimeSpanExtensionsTest.cs
  Libplanet/TimeSpanExtensions.cs
Labels: Extra Small

#1961 Unncessary/inappropriate uses of timeout removed
  CHANGES.md
  Libplanet.Net.Tests/BlockCompletionTest.cs
  Libplanet.Net/BlockCompletion.cs
  Libplanet.Net/Swarm.BlockCandidate.cs
  Libplanet.Net/Swarm.BlockSync.cs
  Libplanet.Net/Swarm.cs
Labels: Small

#1960 Add `Guid` support for `DataModel`
  CHANGES.md
  Libplanet.Tests/Store/DataModelTest.cs
  Libplanet/Store/DataModel.Decode.cs
  Libplanet/Store/DataModel.Encode.cs
  Libplanet/Store/DataModel.cs
Labels: Medium

#1967 [PBFT] Feature/consensus use block
  Libplanet.Net.Tests/Consensus/ConsensusContextTest.cs
  Libplanet.Net.Tests/Consensus/ConsensusReactorTest.cs
  Libplanet.Net.Tests/Consensus/ReactorTest.cs
  Libplanet.Net.Tests/Consensus/RoundContextTest.cs
  Libplanet.Net.Tests/Consensus/States/DefaultStateTest.cs
  Libplanet.Net.Tests/Consensus/States/PreCommitStateTest.cs
  Libplanet.Net.Tests/Consensus/States/PreVoteStateTest.cs
  Libplanet.Net.Tests/TestUtils.cs
  Libplanet.Net/Consensus/ConsensusContext.cs
  Libplanet.Net/Consensus/ConsensusReactor.cs
  Libplanet.Net/Consensus/DefaultState.cs
  Libplanet.Net/Consensus/IReactor.cs
  Libplanet.Net/Consensus/IState.cs
  Libplanet.Net/Consensus/PreCommitState.cs
  Libplanet.Net/Consensus/PreVoteState.cs
  Libplanet.Net/Consensus/RoundContext.cs
  Libplanet.Net/Consensus/UnexpectedBlockHashException.cs
  Libplanet.Net/Messages/ConsensusCommit.cs
  Libplanet.Net/Messages/ConsensusMessage.cs
  Libplanet.Net/Messages/ConsensusPropose.cs
  Libplanet.Net/Messages/ConsensusVote.cs
Labels: Extra Large, pbft

#1968 Introduce `Vote` and `VoteSet`
  Libplanet.Tests/Consensus/VoteSetTest.cs
  Libplanet.Tests/Consensus/VoteTest.cs
  Libplanet/Consensus/Vote.cs
  Libplanet/Consensus/VoteFlag.cs
  Libplanet/Consensus/VoteSet.cs
Labels: Large, pbft

#1969 Introduce `BlockCommit`
  Libplanet.Tests/Blocks/BlockCommitTest.cs
  Libplanet/Blocks/Block.cs
  Libplanet/Blocks/BlockCommit.cs
  Libplanet/Blocks/BlockHeader.cs
  Libplanet/Blocks/BlockMarshaler.cs
  Libplanet/Blocks/BlockMetadata.cs
  Libplanet/Blocks/IBlockMetadata.cs
  Libplanet/Blocks/PreEvaluationBlockHeader.cs
  Libplanet/Consensus/VoteSet.cs
  Libplanet/Store/BlockDigest.cs
Labels: Medium, pbft

#1970 Prevent duplicated commit
  Libplanet.Net.Tests/Consensus/ConsensusContextTest.cs
  Libplanet.Net.Tests/Consensus/ConsensusReactorTest.cs
  Libplanet.Net/Consensus/ConsensusContext.cs
  Libplanet.Net/Consensus/PreCommitState.cs
  Libplanet.Net/Consensus/RoundContext.cs
Labels: bug, Small, pbft

#1962 Added `TimeoutOptions` to `SwarmOptions`
  CHANGES.md
  Libplanet.Benchmarks/SwarmBenchmark.cs
  Libplanet.Explorer.Executable/Program.cs
  Libplanet.Net.Tests/SwarmTest.Preload.cs
  Libplanet.Net.Tests/SwarmTest.cs
  Libplanet.Net/Swarm.cs
  Libplanet.Net/SwarmOptions.cs
  Libplanet.Net/TimeoutOptions.cs
Labels: Medium

#1975 Release 0.35.0
  CHANGES.md
Labels: Extra Small

#1976 Prepare 0.36.0
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: Extra Small

#1977 Prepare 0.35.1
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: Extra Small

#1979 Using `Vote` and `VoteSet` on the PBFT
  Libplanet.Explorer.Executable/Program.cs
  Libplanet.Net.Tests/Consensus/ConsensusContextTest.cs
  Libplanet.Net.Tests/Consensus/ConsensusReactorTest.cs
  Libplanet.Net.Tests/Consensus/ReactorTest.cs
  Libplanet.Net.Tests/Consensus/RoundContextTest.cs
  Libplanet.Net.Tests/Consensus/States/DefaultStateTest.cs
  Libplanet.Net.Tests/Consensus/States/PreCommitStateTest.cs
  Libplanet.Net.Tests/Consensus/States/PreVoteStateTest.cs
  Libplanet.Net.Tests/TestUtils.cs
  Libplanet.Net/Consensus/ConsensusContext.cs
  Libplanet.Net/Consensus/ConsensusReactor.cs
  Libplanet.Net/Consensus/DefaultState.cs
  Libplanet.Net/Consensus/PreCommitState.cs
  Libplanet.Net/Consensus/PreVoteState.cs
  Libplanet.Net/Consensus/RoundContext.cs
  Libplanet.Net/Messages/ConsensusCommit.cs
  Libplanet.Net/Messages/ConsensusVote.cs
  Libplanet/Blockchain/Policies/BlockPolicy.cs
  Libplanet/Blockchain/Policies/IBlockPolicy.cs
  Libplanet/Blockchain/Policies/NullBlockPolicy.cs
Labels: network, Large, pbft

#1983 Reference to a wrong constant fixed
  CHANGES.md
  Libplanet.Net/TimeoutOptions.cs
Labels: Extra Small

#1984 :rocket: Release 0.35.1
  CHANGES.md
Labels: Extra Small

#1985 :hammer: prepare 0.35.2
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: Extra Small

#1986 :twisted_rightwards_arrows: Port/0.35.1 to main
  CHANGES.md
  Libplanet.Net/TimeoutOptions.cs
Labels: Extra Small

#1987 [skip changelog] Setup Libplanet.Unity
  Libplanet.Unity.Tests/Libplanet.Unity.Tests.csproj
  Libplanet.Unity/Libplanet.Unity.csproj
  Libplanet.sln
Labels: Medium

#1982 Unused SwarmOptions.BlockDownloadTimeout property removed
  CHANGES.md
  Libplanet.Net.Tests/SwarmTest.Preload.cs
  Libplanet.Net/Swarm.BlockSync.cs
  Libplanet.Net/SwarmOptions.cs
Labels: Extra Small

#1989 Changelog hotfix
  CHANGES.md
Labels: Extra Small

#1988 Merge `main` branch
  CHANGES.md
  Libplanet.Net.Tests/SwarmTest.Preload.cs
  Libplanet.Net/Swarm.BlockSync.cs
  Libplanet.Net/SwarmOptions.cs
Labels: Medium

#1990 Removed `findNeighborsTimeout` from `BootstrapAsync()`
  CHANGES.md
  Libplanet.Explorer.Executable/Program.cs
  Libplanet.Net.Tests/Protocols/ProtocolTest.cs
  Libplanet.Net.Tests/Protocols/TestTransport.cs
  Libplanet.Net.Tests/SwarmTest.cs
  Libplanet.Net/Protocols/IProtocol.cs
  Libplanet.Net/Protocols/KademliaProtocol.cs
  Libplanet.Net/Swarm.cs
Labels: Extra Small

#1978 `UntypedBlock` & `UntypedTransaction`
  .github/bin/constants.sh
  CHANGES.md
  CONTRIBUTING.md
  Docs/docfx.json
  Libplanet.Node.Tests/Libplanet.Node.Tests.csproj
  Libplanet.Node.Tests/UntypedBlockTest.cs
  Libplanet.Node.Tests/UntypedTransactionTest.cs
  Libplanet.Node.Tests/xunit.runner.mono.json
  Libplanet.Node/Libplanet.Node.csproj
  Libplanet.Node/UntypedBlock.cs
  Libplanet.Node/UntypedTransaction.cs
  Libplanet.Tests/Blocks/BlockTest.cs
  Libplanet.Tests/ByteUtilTest.cs
  Libplanet.Tests/Crypto/PublicKeyTest.cs
  Libplanet.Tests/TransactionExtensions.cs
  Libplanet.Tests/Tx/TransactionTest.cs
  Libplanet.Tests/Tx/TxIdTest.cs
  Libplanet.Tests/Tx/TxMetadataTest.cs
  Libplanet.sln
  Libplanet/AssemblyInfo.cs
  Libplanet/Blocks/Block.cs
  Libplanet/Blocks/BlockContent.cs
  Libplanet/Blocks/BlockContentExtensions.cs
  Libplanet/Blocks/BlockMarshaler.cs
  Libplanet/Blocks/PreEvaluationBlock.cs
  Libplanet/ByteUtil.cs
  Libplanet/Crypto/PublicKey.cs
  Libplanet/Tx/ITxExcerpt.cs
  Libplanet/Tx/ITxMetadata.cs
  Libplanet/Tx/InvalidTxPublicKeyException.cs
  Libplanet/Tx/RawTransaction.cs
  Libplanet/Tx/Transaction.cs
  Libplanet/Tx/TxExcerptExtensions.cs
  Libplanet/Tx/TxId.cs
  Libplanet/Tx/TxMetadata.cs
Labels: Extra Large

#1998 :rocket: Release 0.36.0
  CHANGES.md
Labels: Extra Small

#2004 Merge 0.36.0 to libplanet-unity
  .github/bin/constants.sh
  CHANGES.md
  CONTRIBUTING.md
  Docs/docfx.json
  Libplanet.Explorer.Executable/Program.cs
  Libplanet.Net.Tests/Protocols/ProtocolTest.cs
  Libplanet.Net.Tests/Protocols/TestTransport.cs
  Libplanet.Net.Tests/SwarmTest.cs
  Libplanet.Net/Protocols/IProtocol.cs
  Libplanet.Net/Protocols/KademliaProtocol.cs
  Libplanet.Net/Swarm.cs
  Libplanet.Node.Tests/Libplanet.Node.Tests.csproj
  Libplanet.Node.Tests/UntypedBlockTest.cs
  Libplanet.Node.Tests/UntypedTransactionTest.cs
  Libplanet.Node.Tests/xunit.runner.mono.json
  Libplanet.Node/Libplanet.Node.csproj
  Libplanet.Node/UntypedBlock.cs
  Libplanet.Node/UntypedTransaction.cs
  Libplanet.Tests/Blocks/BlockTest.cs
  Libplanet.Tests/ByteUtilTest.cs
  Libplanet.Tests/Crypto/PublicKeyTest.cs
  Libplanet.Tests/TransactionExtensions.cs
  Libplanet.Tests/Tx/TransactionTest.cs
  Libplanet.Tests/Tx/TxIdTest.cs
  Libplanet.Tests/Tx/TxMetadataTest.cs
  Libplanet.sln
  Libplanet/AssemblyInfo.cs
  Libplanet/Blocks/Block.cs
  Libplanet/Blocks/BlockContent.cs
  Libplanet/Blocks/BlockContentExtensions.cs
  Libplanet/Blocks/BlockMarshaler.cs
  Libplanet/Blocks/PreEvaluationBlock.cs
  Libplanet/ByteUtil.cs
  Libplanet/Crypto/PublicKey.cs
  Libplanet/Tx/ITxExcerpt.cs
  Libplanet/Tx/ITxMetadata.cs
  Libplanet/Tx/InvalidTxPublicKeyException.cs
  Libplanet/Tx/RawTransaction.cs
  Libplanet/Tx/Transaction.cs
  Libplanet/Tx/TxExcerptExtensions.cs
  Libplanet/Tx/TxId.cs
  Libplanet/Tx/TxMetadata.cs
Labels: Extra Large

#2005 Fix `KeyNotFoundException` thrown by `Transaction<T>()`
  CHANGES.md
  Libplanet.Tests/Tx/TransactionTest.cs
  Libplanet/Tx/Transaction.cs
Labels: bug, Extra Small

#2006 :rocket: Release 0.36.1
  CHANGES.md
Labels: Extra Small

#1996 Add `BlockCommit` of last block when mine a new block
  Libplanet.Tests/Blockchain/BlockChainTest.MineBlock.cs
  Libplanet.Tests/Blocks/BlockFixture.cs
  Libplanet.Tests/Blocks/BlockMarshalerTest.cs
  Libplanet.Tests/TestUtils.cs
  Libplanet/Blockchain/BlockChain.MineBlock.cs
Labels: Small, pbft

#2008 :twisted_rightwards_arrows: Port 0.36.1 to main
  CHANGES.md
  Libplanet.Tests/Tx/TransactionTest.cs
  Libplanet/Tx/Transaction.cs
Labels: Extra Small

#2007 :wrench: Prepare 0.36.2
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: Extra Small

#2010 Small updates on `Swarm<T>` docs
  .circleci/config.yml
  Libplanet.Net/Swarm.cs
Labels: network, docs, Extra Small

#2011 :twisted_rightwards_arrows: Merge `main` to `libplanet-node`
  .circleci/config.yml
  Libplanet.Net/Swarm.cs
Labels: Extra Small

#2003 Verify signature when received PBFT vote message
  Libplanet.Net.Tests/Consensus/ConsensusContextTest.cs
  Libplanet.Net.Tests/Consensus/ConsensusReactorTest.cs
  Libplanet.Net.Tests/Consensus/RoundContextTest.cs
  Libplanet.Net.Tests/Consensus/States/PreCommitStateTest.cs
  Libplanet.Net.Tests/Consensus/States/PreVoteStateTest.cs
  Libplanet.Net.Tests/TestUtils.cs
  Libplanet.Net/Consensus/ConsensusContext.cs
  Libplanet.Net/Consensus/ConsensusReactor.cs
  Libplanet.Net/Consensus/DefaultState.cs
  Libplanet.Net/Consensus/PreCommitState.cs
  Libplanet.Net/Consensus/PreVoteState.cs
  Libplanet.Net/Consensus/RoundContext.cs
  Libplanet.Tests/Consensus/VoteSetTest.cs
  Libplanet/Consensus/Vote.cs
  Libplanet/Consensus/VoteSet.cs
Labels: Large, pbft

#2009 Store voteset on memory when commit new block and access from reactor
  Libplanet.Net.Tests/Consensus/ReactorTest.cs
  Libplanet.Net.Tests/Consensus/RoundContextTest.cs
  Libplanet.Net/Consensus/ConsensusContext.cs
  Libplanet.Net/Consensus/ConsensusReactor.cs
  Libplanet.Net/Consensus/IReactor.cs
  Libplanet.Net/Consensus/PreCommitState.cs
  Libplanet.Net/Consensus/PreVoteState.cs
  Libplanet.Net/Consensus/RoundContext.cs
Labels: Small, pbft

#2013 ✨ Introduce `NodeUtils` class
  CHANGES.md
  Libplanet.Node/NodeUtils.cs
Labels: Small

#2002 Block Synchronization (refactored)
  Libplanet.Net.Tests/Consensus/ReactorTest.cs
  Libplanet.Net.Tests/Consensus/States/DefaultStateTest.cs
  Libplanet.Net.Tests/Consensus/States/PreVoteStateTest.cs
  Libplanet.Net/Consensus/ConsensusContext.cs
  Libplanet.Net/Consensus/ConsensusReactor.cs
  Libplanet.Net/Consensus/DefaultState.cs
  Libplanet.Net/Consensus/PreVoteState.cs
  Libplanet.Net/Consensus/RoundContext.cs
  Libplanet.Net/Consensus/VoteBlockNotExistsException.cs
Labels: Medium, pbft

#2019 `NodeUtils` private key handling
  Libplanet.Node.Tests/Libplanet.Node.Tests.csproj
  Libplanet.Node.Tests/NodeUtilsTest.cs
  Libplanet.Node/NodeUtils.cs
Labels: Small

#2020 [skip changelog] Bad project reference removed
  Libplanet.Node.Tests/Libplanet.Node.Tests.csproj
Labels: Extra Small

#2021 Various config classes added
  CHANGES.md
  Libplanet.Node/BootstrapConfig.cs
  Libplanet.Node/InitConfig.cs
  Libplanet.Node/PreloadConfig.cs
  Libplanet.Node/SwarmConfig.cs
  Libplanet.Node/SyncConfig.cs
Labels: Medium

#2024 `BootstrapOptions` added to `SwarmOptions`
  CHANGES.md
  Libplanet.Explorer.Executable/Program.cs
  Libplanet.Net.Tests/SwarmTest.cs
  Libplanet.Net/BootstrapOptions.cs
  Libplanet.Net/Swarm.cs
  Libplanet.Net/SwarmOptions.cs
  Libplanet.Net/TimeoutOptions.cs
Labels: Small

#2023 Recomitting Failed Round / Preparing Swarm
  Libplanet.Benchmarks/SwarmBenchmark.cs
  Libplanet.Explorer.Executable/Program.cs
  Libplanet.Net.Tests/Consensus/ConsensusReactorTest.cs
  Libplanet.Net.Tests/Consensus/ReactorTest.cs
  Libplanet.Net.Tests/SwarmTest.Fixtures.cs
  Libplanet.Net.Tests/SwarmTest.cs
  Libplanet.Net.Tests/Transports/BoundPeerExtensionsTest.cs
  Libplanet.Net/Consensus/CommitBlockNotExistsException.cs
  Libplanet.Net/Consensus/ConsensusContext.cs
  Libplanet.Net/Consensus/ConsensusReactor.cs
  Libplanet.Net/Consensus/DefaultState.cs
  Libplanet.Net/Consensus/IReactor.cs
  Libplanet.Net/Consensus/PreVoteState.cs
  Libplanet.Net/Swarm.cs
Labels: Large, pbft

#2026 IceServer now accepts only one URI.
  CHANGES.md
  Libplanet.Explorer.Executable/Options.cs
  Libplanet.Net.Tests/FactOnlyTurnAvailableAttribute.cs
  Libplanet.Net.Tests/IceServerTest.cs
  Libplanet.Net.Tests/SwarmTest.cs
  Libplanet.Net/IceServer.cs
Labels: Small

#2025 `PreloadOptions` added to `SwarmOptions`
  CHANGES.md
  Libplanet.Explorer.Executable/Program.cs
  Libplanet.Net.Tests/SwarmTest.Preload.cs
  Libplanet.Net/PreloadOptions.cs
  Libplanet.Net/Swarm.cs
  Libplanet.Net/SwarmOptions.cs
  Libplanet.Net/TimeoutOptions.cs
Labels: Small

#2027 🚀 Release 0.37.0
  CHANGES.md
Labels: Extra Small

#2028 🔧 Prepare 0.38.0
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: Extra Small

#2029 🔧 Prepare 0.37.1
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: Extra Small

#2030 🔀 Merge `main` into `libplanet-node`
  CHANGES.md
  Libplanet.Explorer.Executable/Options.cs
  Libplanet.Explorer.Executable/Program.cs
  Libplanet.Net.Tests/FactOnlyTurnAvailableAttribute.cs
  Libplanet.Net.Tests/IceServerTest.cs
  Libplanet.Net.Tests/SwarmTest.Preload.cs
  Libplanet.Net.Tests/SwarmTest.cs
  Libplanet.Net/BootstrapOptions.cs
  Libplanet.Net/IceServer.cs
  Libplanet.Net/PreloadOptions.cs
  Libplanet.Net/Swarm.cs
  Libplanet.Net/SwarmOptions.cs
  Libplanet.Net/TimeoutOptions.cs
  Libplanet.Node/SwarmConfig.cs
  Libplanet/Libplanet.csproj
Labels: Large

#2032 Chore/consensus logging
  Libplanet.Net/Consensus/ConsensusContext.cs
  Libplanet.Net/Consensus/ConsensusReactor.cs
Labels: Extra Small, pbft

#2031 Separate `ITransport`s (+ Prepare for PBFT Headless)
  Libplanet.Benchmarks/SwarmBenchmark.cs
  Libplanet.Explorer.Executable/Program.cs
  Libplanet.Net.Tests/Consensus/ConsensusReactorTest.cs
  Libplanet.Net.Tests/Consensus/ReactorTest.cs
  Libplanet.Net.Tests/SwarmTest.Fixtures.cs
  Libplanet.Net.Tests/SwarmTest.cs
  Libplanet.Net.Tests/Transports/BoundPeerExtensionsTest.cs
  Libplanet.Net/Consensus/ConsensusReactor.cs
  Libplanet.Net/Swarm.cs
Labels: Large, pbft

#2035 Expose `VoteSetOf` and `Propose`
  Libplanet.Net/Swarm.cs
Labels: Extra Small, pbft
