Repository planetarium/libplanet, pull requests merged in 2022-06, with the labels that each got.

#2000 `NetworkConfig` & `NodeConfig`
  CHANGES.md
  Libplanet.Node/NetworkConfig.cs
  Libplanet.Node/NodeConfig.cs
Labels: api, Small, ux

#2038 Improve logging about consensus
  Libplanet.Net/Consensus/ConsensusContext.cs
  Libplanet.Net/Consensus/ConsensusReactor.cs
  Libplanet.Net/Consensus/RoundContext.cs
Labels: Extra Small, pbft

#2040 Default host changed to localhost
  Libplanet.Node/InitConfig.cs
Labels: Extra Small

#2036 Newly styled up docs page.
  Docs/theme/styles/main.css
Labels: docs, Large

#2041 [skip changelog] Tests for `SwarmConfig`
  Libplanet.Node.Tests/NodeUtilsTest.cs
  Libplanet.Node.Tests/SwarmConfigTest.cs
  Libplanet.Node/BootstrapConfig.cs
  Libplanet.Node/InitConfig.cs
  Libplanet.Node/SwarmConfig.cs
  Libplanet.Node/SyncConfig.cs
Labels: Medium

#2042 Fix bug in consensus initial height
  Libplanet.Net/Consensus/ConsensusContext.cs
Labels: Extra Small, pbft

#2045 🔀 Merge `libplanet-node` to `main`
  CHANGES.md
  Libplanet.Node.Tests/Libplanet.Node.Tests.csproj
  Libplanet.Node.Tests/NodeUtilsTest.cs
  Libplanet.Node.Tests/SwarmConfigTest.cs
  Libplanet.Node/BootstrapConfig.cs
  Libplanet.Node/InitConfig.cs
  Libplanet.Node/NetworkConfig.cs
  Libplanet.Node/NodeConfig.cs
  Libplanet.Node/NodeUtils.cs
  Libplanet.Node/PreloadConfig.cs
  Libplanet.Node/SwarmConfig.cs
  Libplanet.Node/SyncConfig.cs
Labels: Extra Large

#2044 Use swarm key for PBFT consensus node distinguish
  Libplanet.Net/Swarm.cs
Labels: Extra Small, pbft

#2018 Allow 0x prefix for Address class
  CHANGES.md
  Libplanet.Tests/AddressTest.cs
  Libplanet/Address.cs
Labels: Extra Small, Squash Needed

#2034 Minor cleanup for consistency
  CHANGES.md
  Libplanet.Net.Tests/Protocols/ProtocolTest.cs
  Libplanet.Net.Tests/Protocols/TestTransport.cs
  Libplanet.Net.Tests/SwarmTest.Broadcast.cs
  Libplanet.Net.Tests/SwarmTest.cs
  Libplanet.Net/Protocols/KademliaProtocol.cs
  Libplanet.Net/Swarm.cs
  Libplanet.Stun/Stun/Messages/StunMessage.cs
  Libplanet.Stun/Stun/TurnClient.cs
  Libplanet/Blockchain/BlockChain.MineBlock.cs
Labels: Small

#2049 Unnecessary parameters removed for `IceServer()`
  CHANGES.md
  Libplanet.Explorer.Executable/Options.cs
  Libplanet.Net.Tests/FactOnlyTurnAvailableAttribute.cs
  Libplanet.Net.Tests/IceServerTest.cs
  Libplanet.Net.Tests/SwarmTest.cs
  Libplanet.Net/IceServer.cs
  Libplanet.Node.Tests/SwarmConfigTest.cs
  Libplanet.Node/SwarmConfig.cs
Labels: Medium

#2051 🚀 Release 0.38.0
  CHANGES.md
Labels: Extra Small

#2052 🔧 Prepare libplanet 0.39.0
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: Extra Small

#2057 Import unity dll dependency
  .github/bin/constants.sh
  CONTRIBUTING.md
  Docs/docfx.json
  Libplanet.Unity.Tests/Libplanet.Unity.csproj
  Libplanet.Unity/Libplanet.Unity.csproj
  Libplanet.Unity/MonoSingleton.cs
  Libplanet.sln
Labels: Extra Small

#2055 Refactor `IReactor` and payload `Block<T>` on the `ConsensusPropose`
  Libplanet.Net.Tests/Consensus/ConsensusContextTest.cs
  Libplanet.Net.Tests/Consensus/ConsensusReactorTest.cs
  Libplanet.Net.Tests/Consensus/ReactorTest.cs
  Libplanet.Net.Tests/Consensus/RoundContextTest.cs
  Libplanet.Net.Tests/Consensus/States/DefaultStateTest.cs
  Libplanet.Net.Tests/Consensus/States/PreCommitStateTest.cs
  Libplanet.Net.Tests/Consensus/States/PreVoteStateTest.cs
  Libplanet.Net/Consensus/BaseStore.cs
  Libplanet.Net/Consensus/ConsensusContext.cs
  Libplanet.Net/Consensus/ConsensusReactor.cs
  Libplanet.Net/Consensus/IReactor.cs
  Libplanet.Net/Consensus/RoundContext.cs
  Libplanet.Net/Consensus/State/DefaultState.cs
  Libplanet.Net/Consensus/State/IState.cs
  Libplanet.Net/Consensus/State/PreCommitState.cs
  Libplanet.Net/Consensus/State/PreVoteState.cs
  Libplanet.Net/Messages/ConsensusPropose.cs
  Libplanet.Net/Swarm.cs
Labels: Large, pbft

#2060 Miner Coroutine Object
  Libplanet.Unity/Miner/BaseMiner.cs
  Libplanet.Unity/Miner/IMineListener.cs
  Libplanet.Unity/Miner/SoloMiner.cs
  Libplanet.Unity/Miner/SwarmMiner.cs
  Libplanet.Unity/MonoSingleton.cs
Labels: api, Small, ux

#2066 [skip changelog] Bad namespace fixed
  Libplanet.Unity/ActionBase.cs
Labels: Extra Small

#2063 Added and Annotated graphql schema
  Libplanet.Explorer/schema.graphql
Labels: Medium

#2067 `Paths` and `Utils` for Unity
  Libplanet.Unity/Paths.cs
  Libplanet.Unity/Utils.cs
Labels: Extra Small

#2071 Generic removed from Miner
  Libplanet.Unity/Miner.cs
Labels: Extra Small

#2072 Various loader methods
  Libplanet.Unity/Utils.cs
Labels: Extra Small

#2073 Rename method for `Utils`
  Libplanet.Unity/Utils.cs
Labels: Extra Small

#2070 Clone Agent
  Libplanet.Unity/Agent.cs
  Libplanet.Unity/MonoSingleton.cs
  Libplanet.Unity/SwarmRunner.cs
  Libplanet.Unity/Utils.cs
Labels: Large

#2075 [skip changelog] TempPrivateKeysPath added to Paths
  Libplanet.Unity/Paths.cs
Labels: Extra Small

#2077 chore: fix tests in linux
  Libplanet.Net/Consensus/ConsensusReactor.cs
  Libplanet.Net/Consensus/IReactor.cs
Labels: bug, Extra Small

#2080 Editor menu items ported
  .github/bin/constants.sh
  Libplanet.Unity/Editor/BlockChainMenu.cs
  Libplanet.Unity/Editor/GenesisBlockMenu.cs
  Libplanet.Unity/Editor/PrivateKeyMenu.cs
  Libplanet.Unity/Editor/SwarmConfigMenu.cs
  Libplanet.Unity/Editor/UtilsMenu.cs
  Libplanet.Unity/Libplanet.Unity.csproj
  Libplanet.sln
Labels: Large

#2076 Improve PBFT consensus
  Libplanet.Net.Tests/Consensus/ConsensusContextTest.cs
  Libplanet.Net.Tests/Consensus/ConsensusReactorTest.cs
  Libplanet.Net.Tests/Consensus/ReactorTest.cs
  Libplanet.Net.Tests/Consensus/RoundContextTest.cs
  Libplanet.Net.Tests/Consensus/States/DefaultStateTest.cs
  Libplanet.Net.Tests/Consensus/States/PreCommitStateTest.cs
  Libplanet.Net.Tests/Consensus/States/PreVoteStateTest.cs
  Libplanet.Net.Tests/Libplanet.Net.Tests.csproj
  Libplanet.Net.Tests/TestUtils.cs
  Libplanet.Net/Consensus/ConsensusContext.cs
  Libplanet.Net/Consensus/ConsensusReactor.cs
  Libplanet.Net/Consensus/Context.cs
  Libplanet.Net/Consensus/IReactor.cs
  Libplanet.Net/Consensus/RoundContext.cs
  Libplanet.Net/Consensus/State/DefaultState.cs
  Libplanet.Net/Consensus/State/IState.cs
  Libplanet.Net/Consensus/State/PreCommitState.cs
  Libplanet.Net/Consensus/State/PreVoteState.cs
  Libplanet.Net/Consensus/Step.cs
  Libplanet.Net/Libplanet.Net.csproj
  Libplanet.Net/Messages/ConsensusMessage.cs
  Libplanet.Net/Messages/ConsensusPropose.cs
  Libplanet.Net/Swarm.cs
  Libplanet/Blockchain/BlockChain.cs
  Libplanet/Consensus/Vote.cs
  Libplanet/Consensus/VoteSet.cs
Labels: Extra Large

#2079 Libplanet.Tools key command now Import/Exports Web3 Formatted json.
  Libplanet.Extensions.Cocona/Commands/KeyCommand.cs
Labels: tools, Small

#2074 Added GraphQL type descriptions
  Libplanet.Explorer/GraphTypes/ActionType.cs
  Libplanet.Explorer/GraphTypes/BlockType.cs
  Libplanet.Explorer/GraphTypes/TransactionType.cs
Labels: Medium

#2083 bugfix: exception during .First
  Libplanet.Net.Tests/Consensus/ReactorTest.cs
  Libplanet.Net/Consensus/Context.cs
Labels: bug, Extra Small, pbft

#2084 Create VoteSet when `VoteSet()` is called
  Libplanet.Net/Consensus/Context.cs
Labels: Extra Small, pbft

#2086 `StaticPeers` are now `ConsensusPeers`
  Libplanet.Net.Tests/SwarmTest.cs
  Libplanet.Net/Consensus/ConsensusReactor.cs
  Libplanet.Net/Swarm.cs
  Libplanet.Net/SwarmOptions.cs
Labels: Medium, pbft

#2088 Start consensus when new block is appended
  Libplanet.Net.Tests/Consensus/ConsensusContextTest.cs
  Libplanet.Net.Tests/TestUtils.cs
  Libplanet.Net/Consensus/ConsensusContext.cs
Labels: Small, pbft

#2081 Unit Tests for new PBFT algorithm
  Libplanet.Net.Tests/Consensus/ConsensusContextTest.cs
  Libplanet.Net.Tests/Consensus/ContextTest.cs
  Libplanet.Net.Tests/TestUtils.cs
  Libplanet.Net/Consensus/ConsensusContext.cs
  Libplanet.Net/Consensus/Context.cs
  Libplanet.Net/Consensus/InvalidHeightIncreasingException.cs
  Libplanet.Net/Consensus/InvalidRoundMessageException.cs
Labels: Extra Large, pbft

#2092 Validate vote message
  Libplanet.Net.Tests/Consensus/ContextTest.cs
  Libplanet.Net/Consensus/Context.cs
  Libplanet.Net/Consensus/InvalidValidatorVoteMessageException.cs
  Libplanet/Consensus/Vote.cs
  Libplanet/Consensus/VoteSet.cs
Labels: Medium, pbft

#2097 refactor: Remove argument, parameter 'validators' from 'Swarm<T>' and 'ConsensusReactor<T>'
  Libplanet.Benchmarks/SwarmBenchmark.cs
  Libplanet.Explorer.Executable/Program.cs
  Libplanet.Net.Tests/Consensus/ConsensusReactorTest.cs
  Libplanet.Net.Tests/SwarmTest.Fixtures.cs
  Libplanet.Net.Tests/SwarmTest.cs
  Libplanet.Net.Tests/Transports/BoundPeerExtensionsTest.cs
  Libplanet.Net/Consensus/ConsensusReactor.cs
  Libplanet.Net/Swarm.cs
Labels: good first issue, Extra Small, pbft

#2098 refactor: Remove unnecessary field 'ConsensusRoutingTable' in 'Swarm<T>'
  Libplanet.Net/Swarm.cs
Labels: good first issue, Extra Small, pbft

#2089 Waiting for nodes to reach consensus
  Libplanet.Net/Consensus/ConsensusReactor.cs
  Libplanet.Net/Consensus/Context.cs
Labels: Extra Small, pbft

#2096 Store all messages for consensus regardless of it's height
  Libplanet.Net.Tests/Consensus/ConsensusContextTest.cs
  Libplanet.Net.Tests/Consensus/ContextTest.cs
  Libplanet.Net/Consensus/ConsensusContext.cs
  Libplanet.Net/Consensus/Context.cs
  Libplanet.Net/Consensus/Step.cs
Labels: Large, pbft

#2102 Make `PreviousHash` and `PreEvaluationHash` are equal.
  Libplanet.Net.Tests/SwarmTest.cs
  Libplanet.Net/Consensus/Context.cs
  Libplanet.Tests/Blockchain/BlockChainTest.ValidateNextBlock.cs
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet.Tests/Blocks/PreEvaluationBlockHeaderTest.cs
  Libplanet.Tests/Blocks/PreEvaluationBlockTest.cs
  Libplanet/Blockchain/BlockChain.MineBlock.cs
  Libplanet/Blockchain/BlockChain.cs
  Libplanet/Blocks/BlockContent.cs
  Libplanet/Blocks/PreEvaluationBlockHeader.cs
Labels: Extra Large, pbft

#2101 Bump `Cocona.Lite` to `2.0.*`
  CHANGES.md
  Libplanet.Extensions.Cocona/Libplanet.Extensions.Cocona.csproj
  Libplanet.Tools/Libplanet.Tools.csproj
  Libplanet.Tools/Program.cs
Labels: suggestion, tools, Extra Small

#2100 Narrow down PBFT unit tests to its methods
  Libplanet.Net.Tests/Consensus/Context/ContextNonProposerTest.cs
  Libplanet.Net.Tests/Consensus/Context/ContextProposerTest.cs
  Libplanet.Net.Tests/Consensus/Context/ContextProposerValidRoundTest.cs
  Libplanet.Net.Tests/Consensus/Context/ContextTest.cs
  Libplanet.Net.Tests/Consensus/Context/ContextTestBase.cs
  Libplanet.Net.Tests/Consensus/ContextTest.cs
  Libplanet.Net.Tests/Consensus/TimeoutTickerTest.cs
  Libplanet.Net.Tests/TestUtils.cs
  Libplanet.Net/Consensus/Context.cs
  Libplanet.Net/Consensus/TimeoutTicker.cs
Labels: Extra Large, pbft

#2106 Context process messages in single task
  Libplanet.Net.Tests/Consensus/ConsensusContextTest.cs
  Libplanet.Net/Consensus/ConsensusContext.cs
  Libplanet.Net/Consensus/Context.cs
Labels: Medium, pbft

#2109 refactor: ReactorTest and ConsensusReactorTest
  Libplanet.Net.Tests/Consensus/ConsensusContextTest.cs
  Libplanet.Net.Tests/Consensus/ConsensusReactorTest.cs
  Libplanet.Net.Tests/Consensus/Context/ContextNonProposerTest.cs
  Libplanet.Net.Tests/Consensus/Context/ContextProposerTest.cs
  Libplanet.Net.Tests/Consensus/Context/ContextProposerValidRoundTest.cs
  Libplanet.Net.Tests/Consensus/Context/ContextTest.cs
  Libplanet.Net.Tests/Consensus/Context/ContextTestBase.cs
  Libplanet.Net.Tests/Consensus/ContextTest.cs
  Libplanet.Net.Tests/Consensus/ReactorTest.cs
  Libplanet.Net.Tests/TestUtils.cs
  Libplanet.Net/Consensus/ConsensusReactor.cs
  Libplanet.Net/Consensus/Context.cs
Labels: Large, pbft

#2113 refactor: remove parameter `nodeId` from `Swarm<T>`
  Libplanet.Benchmarks/SwarmBenchmark.cs
  Libplanet.Explorer.Executable/Program.cs
  Libplanet.Net.Tests/Consensus/ConsensusContextTest.cs
  Libplanet.Net.Tests/Consensus/ConsensusReactorTest.cs
  Libplanet.Net.Tests/Consensus/Context/ContextNonProposerTest.cs
  Libplanet.Net.Tests/Consensus/Context/ContextProposerTest.cs
  Libplanet.Net.Tests/Consensus/Context/ContextProposerValidRoundTest.cs
  Libplanet.Net.Tests/Consensus/Context/ContextTest.cs
  Libplanet.Net.Tests/Consensus/Context/ContextTestBase.cs
  Libplanet.Net.Tests/Consensus/ReactorTest.cs
  Libplanet.Net.Tests/SwarmTest.Fixtures.cs
  Libplanet.Net.Tests/SwarmTest.cs
  Libplanet.Net.Tests/TestUtils.cs
  Libplanet.Net.Tests/Transports/BoundPeerExtensionsTest.cs
  Libplanet.Net/Consensus/ConsensusContext.cs
  Libplanet.Net/Consensus/ConsensusReactor.cs
  Libplanet.Net/Consensus/Context.cs
  Libplanet.Net/Messages/ConsensusCommit.cs
  Libplanet.Net/Messages/ConsensusMessage.cs
  Libplanet.Net/Messages/ConsensusPropose.cs
  Libplanet.Net/Messages/ConsensusVote.cs
  Libplanet.Net/Swarm.cs
  Libplanet.Tests/Blocks/BlockCommitTest.cs
  Libplanet.Tests/Blocks/BlockFixture.cs
  Libplanet.Tests/Consensus/VoteSetTest.cs
  Libplanet.Tests/Consensus/VoteTest.cs
  Libplanet/Consensus/Vote.cs
  Libplanet/Consensus/VoteSet.cs
Labels: good first issue, Large, pbft

#2114 feat: add block hash cache
  Libplanet.Net/Consensus/Context.cs
Labels: Extra Small

#2112 Fill `Block<T>.LastCommit` by getting voteset from last block's consensus context
  Libplanet.Net.Tests/Consensus/ConsensusContextTest.cs
  Libplanet.Net.Tests/Consensus/Context/ContextTest.cs
  Libplanet.Net/Consensus/ConsensusContext.cs
  Libplanet.Net/Consensus/Context.cs
  Libplanet/Blocks/BlockCommit.cs
  Libplanet/Consensus/VoteSet.cs
Labels: Medium, pbft

#2110 Fix typo in the CI script
  .circleci/config.yml
Labels: Extra Small

#2108 Add --path flag in `key` command, and implemented `key derive`
  CHANGES.md
  Libplanet.Extensions.Cocona/Commands/KeyCommand.cs
Labels: tools, Medium, ux

#2119 Fix API mismatch
  Libplanet.Node.Tests/SwarmConfigTest.cs
  Libplanet.Node/NodeConfig.cs
  Libplanet.Node/SwarmConfig.cs
  Libplanet.Node/SyncConfig.cs
Labels: Extra Small, pbft

#2056 Validate `LastCommit` field of the block
  Libplanet.Tests/Blockchain/BlockChainTest.MineBlock.cs
  Libplanet.Tests/Blocks/BlockFixture.cs
  Libplanet.Tests/Blocks/PreEvaluationBlockHeaderTest.cs
  Libplanet.Tests/Consensus/VoteTest.cs
  Libplanet/Blocks/InvalidBlockLastCommitException.cs
  Libplanet/Blocks/PreEvaluationBlockHeader.cs
  Libplanet/Consensus/VoteSet.cs
Labels: Large, pbft
