Repository planetarium/libplanet, pull requests merged in 2022-11, with the labels that each got.

#2489 🧹 Renaming for consistency
  CHANGES.md
  Libplanet.Net.Tests/Consensus/Context/MessageLogTest.cs
  Libplanet.Net.Tests/TestUtils.cs
  Libplanet.Net/Consensus/Context.Mutate.cs
  Libplanet.Net/Consensus/Context.cs
  Libplanet.Tests/Consensus/ProposalMetadataTest.cs
  Libplanet.Tests/Consensus/ProposalTest.cs
  Libplanet/Consensus/Proposal.cs
  Libplanet/Consensus/ProposalMetadata.cs
Labels: Medium

#2486 Possible empty peer table of `Gossip`
  Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextTest.cs
  Libplanet.Net.Tests/Consensus/ConsensusReactorTest.cs
  Libplanet.Net/Consensus/ConsensusReactor.cs
  Libplanet.Net/Consensus/Gossip.cs
Labels: Medium, pbft

#2491 Backport #2379 & release 0.43.2
  CHANGES.md
  Libplanet.RocksDBStore/RocksDBStore.cs
  Libplanet.Tests/Store/StoreFixture.cs
  Libplanet.Tests/Store/StoreTest.cs
Labels: bug, release, Medium

#2490 Feat/enrich explorer query
  Libplanet.Explorer/GraphTypes/TransactionType.cs
  Libplanet.Explorer/Queries/ExplorerQuery.cs
Labels: Extra Small

#2492 Port 0.43.2 to main (0.44.x)
  CHANGES.md
Labels: Extra Small

#2493 Added internal decision variable and removed public `CommittedRoud` from `Context`
  Libplanet.Net/Consensus/Context.Mutate.cs
  Libplanet.Net/Consensus/Context.cs
Labels: Extra Small

#2434 Changed `langword` tag rendering
  Docs/theme/styles/main.css
Labels: Extra Small

#2495 🧹 Remove `VoteSet`
  CHANGES.md
  Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextTest.cs
  Libplanet.Net.Tests/Consensus/Context/ContextTest.cs
  Libplanet.Net.Tests/Consensus/Context/MessageLogTest.cs
  Libplanet.Net.Tests/TestUtils.cs
  Libplanet.Net/Consensus/Context.Mutate.cs
  Libplanet.Net/Consensus/Context.cs
  Libplanet.Net/Consensus/MessageLog.cs
  Libplanet.Tests/Blockchain/BlockChainTest.MineBlock.cs
  Libplanet.Tests/Blockchain/BlockChainTest.ValidateNextBlock.cs
  Libplanet.Tests/Consensus/VoteSetTest.cs
  Libplanet.Tests/TestUtils.cs
  Libplanet/Blocks/BlockCommit.cs
  Libplanet/Consensus/VoteSet.cs
Labels: Extra Large

#2496 🧹 Use `langword` tags
  Libplanet.Net/Consensus/Context.cs
  Libplanet.Net/Consensus/Gossip.cs
  Libplanet.Net/Messages/MessageId.cs
  Libplanet/Consensus/Proposal.cs
  Libplanet/Consensus/Vote.cs
Labels: No Changes

#2497 ♻️ Refactor `Context` events
  Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextNonProposerTest.cs
  Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextProposerTest.cs
  Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextTest.cs
  Libplanet.Net.Tests/Consensus/Context/ContextNonProposerTest.cs
  Libplanet.Net.Tests/Consensus/Context/ContextProposerTest.cs
  Libplanet.Net.Tests/Consensus/Context/ContextProposerValidRoundTest.cs
  Libplanet.Net.Tests/Consensus/Context/ContextTest.cs
  Libplanet.Net.Tests/TestUtils.cs
  Libplanet.Net/Consensus/ConsensusContext.Event.cs
  Libplanet.Net/Consensus/Context.Async.cs
  Libplanet.Net/Consensus/Context.Event.cs
  Libplanet.Net/Consensus/Context.Mutate.cs
  Libplanet.Net/Consensus/Context.cs
Labels: Large

#2485 Improve some log messages
  Libplanet/Blockchain/BlockChain.cs
  Libplanet/Store/BaseStore.cs
Labels: Extra Small

#2499 ♻️ Use `Context.MessageBroadcasted` for tests
  Libplanet.Net.Tests/Consensus/Context/ContextNonProposerTest.cs
  Libplanet.Net.Tests/Consensus/Context/ContextProposerTest.cs
  Libplanet.Net.Tests/Consensus/Context/ContextProposerValidRoundTest.cs
  Libplanet.Net.Tests/Consensus/Context/ContextTest.cs
  Libplanet.Net.Tests/TestUtils.cs
Labels: Large

#2500 ♻️ Use `MessageBroadcasted` event handler for `ConsensusContext` tests
  Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextNonProposerTest.cs
  Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextProposerTest.cs
  Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextTest.cs
  Libplanet.Net.Tests/TestUtils.cs
Labels: Large

#2501 🚀 Release 0.44.0
  CHANGES.md
Labels: Extra Small

#2503 🔧 Prepare 0.45.0
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: Extra Small

#2502 🔧 Prepare 0.44.1
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: Extra Small

#2506 Refactor `MessageLog`
  Libplanet.Net.Tests/Consensus/Context/MessageLogTest.cs
  Libplanet.Net/Consensus/Context.Mutate.cs
  Libplanet.Net/Consensus/Context.cs
  Libplanet.Net/Consensus/MessageLog.cs
  Libplanet/Consensus/ProposerSelector.cs
Labels: Medium

#2508 Unsubscribe tip event in `ConsensusContext.Dispose()`
  Libplanet.Net/Consensus/ConsensusContext.cs
Labels: Extra Small, pbft

#2510 Collision between indexing and creating in `Dictionary<long, Context<T>>`
  Libplanet.Net/Consensus/ConsensusContext.cs
  Libplanet.Net/Consensus/Context.cs
Labels: Small, pbft

#2438 Validate lastcommit only when lastblock is PBFT based block
  Libplanet.Net/Consensus/ConsensusContext.cs
  Libplanet.Net/Consensus/Context.Async.cs
  Libplanet.Net/Consensus/Context.cs
  Libplanet.Net/Consensus/Gossip.cs
  Libplanet/Blockchain/BlockChain.cs
Labels: Small, pbft

#2520 Fix/app protocol version get hash code
  CHANGES.md
  Libplanet.Net.Tests/AppProtocolVersionTest.cs
  Libplanet.Net/AppProtocolVersion.cs
Labels: bug, Extra Small

#2519 Added `ValidatorSet`
  CHANGES.md
  Libplanet.Explorer.Executable/Program.cs
  Libplanet.Explorer.Tests/Queries/TransactionQueryTest.cs
  Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextNonProposerTest.cs
  Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextTest.cs
  Libplanet.Net.Tests/Consensus/Context/MessageLogTest.cs
  Libplanet.Net.Tests/SwarmTest.Broadcast.cs
  Libplanet.Net.Tests/SwarmTest.Fixtures.cs
  Libplanet.Net.Tests/SwarmTest.Preload.cs
  Libplanet.Net.Tests/SwarmTest.cs
  Libplanet.Net.Tests/TestUtils.cs
  Libplanet.Net/Consensus/ConsensusContext.cs
  Libplanet.Net/Consensus/ConsensusReactor.cs
  Libplanet.Net/Consensus/Context.Mutate.cs
  Libplanet.Net/Consensus/Context.cs
  Libplanet.Net/Consensus/MessageLog.cs
  Libplanet.Tests/Action/AccountStateDeltaTest.cs
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
  Libplanet.Tests/Blockchain/BlockChainTest.Append.cs
  Libplanet.Tests/Blockchain/BlockChainTest.MineBlock.cs
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet.Tests/Blockchain/Renderers/DelayedActionRendererTest.cs
  Libplanet.Tests/Blocks/BlockCommitExtensionsTest.cs
  Libplanet.Tests/Consensus/ValidatorSetTest.cs
  Libplanet.Tests/Fixtures/IntegerSet.cs
  Libplanet.Tests/Store/StoreTest.cs
  Libplanet.Tests/TestUtils.cs
  Libplanet/Blockchain/BlockChain.cs
  Libplanet/Blockchain/Policies/BlockPolicy.cs
  Libplanet/Blockchain/Policies/IBlockPolicy.cs
  Libplanet/Blockchain/Policies/NullBlockPolicy.cs
  Libplanet/Blocks/BlockCommitExtensions.cs
  Libplanet/Consensus/ValidatorSet.cs
Labels: Large

#2521 Fix hangs on .SendMessageAsync() & Release v0.43.3
  CHANGES.md
  Libplanet.Net.Tests/Transports/TransportTest.cs
  Libplanet.Net/Transports/NetMQTransport.cs
Labels: network, Small

#2523 🔀 🚀 Port 0.43.3 to 0.44-maintenance and release 0.44.1
  CHANGES.md
  Libplanet.Net.Tests/Transports/TransportTest.cs
  Libplanet.Net/Transports/NetMQTransport.cs
Labels: Small

#2524 🔧 Prepare 0.44.2
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: Extra Small

#2511 🔀 Merge main 0.44.0 to pbft
  CHANGES.md
  Docs/theme/styles/main.css
  Libplanet.Explorer/GraphTypes/TransactionType.cs
  Libplanet.Explorer/Queries/ExplorerQuery.cs
  Libplanet/Blockchain/BlockChain.cs
  Libplanet/Store/BaseStore.cs
Labels: Small

#2525 🔀 Port 0.44.1 to main
  CHANGES.md
  Libplanet.Net.Tests/Transports/TransportTest.cs
  Libplanet.Net/Transports/NetMQTransport.cs
Labels: Small

#2526 Run `ConsensusReactor` if `consensusOption` is given
  Libplanet.Net.Tests/SwarmTest.Fixtures.cs
  Libplanet.Net.Tests/SwarmTest.cs
  Libplanet.Net/Consensus/ConsensusReactor.cs
  Libplanet.Net/Swarm.cs
Labels: Small, pbft

#2517 Move `LastCommit` saving to `Commit`
  Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextTest.cs
  Libplanet.Net.Tests/Consensus/Context/ContextProposerTest.cs
  Libplanet.Net.Tests/Consensus/Context/ContextTest.cs
  Libplanet.Net/Consensus/ConsensusContext.cs
  Libplanet.Net/Consensus/Context.Mutate.cs
  Libplanet.Net/Consensus/Context.cs
Labels: Small, pbft

#2507 Inject ActionEvaluator and BlockChainStates explicitly
  CHANGES.md
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet/Blockchain/BlockChain.cs
  Libplanet/Blockchain/BlockChainStates.cs
Labels: Large, Squash Needed

#2515 Enhance gossip
  Libplanet.Net.Tests/Consensus/GossipTest.cs
  Libplanet.Net.Tests/SwarmTest.cs
  Libplanet.Net/Consensus/ConsensusReactor.cs
  Libplanet.Net/Consensus/Gossip.cs
Labels: network, Medium, pbft

#2533 Removed magic `constant`s
  Libplanet.Net.Tests/Messages/MessageIdTest.cs
  Libplanet.Net.Tests/Messages/MessageTest.cs
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
  Libplanet.Tests/Blocks/BlockCommitTest.cs
  Libplanet.Tests/Blocks/BlockMetadataTest.cs
  Libplanet.Tests/Blocks/InvalidBlockPreEvaluationHashExceptionTest.cs
  Libplanet.Tests/Consensus/VoteMetadataTest.cs
  Libplanet.Tests/Consensus/VoteTest.cs
  Libplanet.Tests/Tx/TxIdTest.cs
Labels: Extra Small

#2529 Removed policy controlled parameters from `MineBlock`
  CHANGES.md
  Libplanet.Tests/Blockchain/BlockChainTest.MineBlock.cs
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet.Tests/Blockchain/Policies/BlockPolicyTest.cs
  Libplanet/Blockchain/BlockChain.MineBlock.cs
Labels: Large

#2536 🧹 Reuse private keys for validator set
  Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextNonProposerTest.cs
  Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextProposerTest.cs
  Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextTest.cs
  Libplanet.Net.Tests/Consensus/Context/ContextNonProposerTest.cs
  Libplanet.Net.Tests/Consensus/Context/ContextProposerTest.cs
  Libplanet.Net.Tests/Consensus/Context/ContextProposerValidRoundTest.cs
  Libplanet.Net.Tests/Consensus/Context/ContextTest.cs
  Libplanet.Net.Tests/Consensus/Context/MessageLogTest.cs
  Libplanet.Net.Tests/Messages/MessageTest.cs
  Libplanet.Net.Tests/SwarmTest.Broadcast.cs
  Libplanet.Net.Tests/SwarmTest.Fixtures.cs
  Libplanet.Net.Tests/SwarmTest.Preload.cs
  Libplanet.Net.Tests/SwarmTest.cs
  Libplanet.Net.Tests/TestUtils.cs
  Libplanet.Tests/Action/AccountStateDeltaTest.cs
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
  Libplanet.Tests/Blockchain/BlockChainTest.Append.cs
  Libplanet.Tests/Blockchain/BlockChainTest.MineBlock.cs
  Libplanet.Tests/Blockchain/BlockChainTest.ValidateNextBlock.cs
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet.Tests/Blockchain/Renderers/DelayedActionRendererTest.cs
  Libplanet.Tests/Fixtures/IntegerSet.cs
  Libplanet.Tests/Store/StoreTest.cs
  Libplanet.Tests/TestUtils.cs
Labels: Extra Large

#2532 chore: fix build failure in linux mono [skip changelog]
  Libplanet.Tests/TestUtils.cs
Labels: ci & cd, Extra Small, pbft

#2537 🔀 Merge main to pbft
  CHANGES.md
  Libplanet.Net.Tests/AppProtocolVersionTest.cs
  Libplanet.Net.Tests/Transports/TransportTest.cs
  Libplanet.Net/AppProtocolVersion.cs
  Libplanet.Net/Transports/NetMQTransport.cs
  Libplanet.Tests/Blockchain/BlockChainTest.MineBlock.cs
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet.Tests/Blockchain/Policies/BlockPolicyTest.cs
  Libplanet/Blockchain/BlockChain.MineBlock.cs
  Libplanet/Blockchain/BlockChain.cs
  Libplanet/Blockchain/BlockChainStates.cs
  Libplanet/Libplanet.csproj
Labels: Extra Large

#2538 Refactor test fixture
  Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextNonProposerTest.cs
  Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextProposerTest.cs
  Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextTest.cs
  Libplanet.Net.Tests/Consensus/Context/ContextNonProposerTest.cs
  Libplanet.Net.Tests/Consensus/Context/ContextProposerTest.cs
  Libplanet.Net.Tests/Consensus/Context/ContextProposerValidRoundTest.cs
  Libplanet.Net.Tests/Consensus/Context/ContextTest.cs
  Libplanet.Net.Tests/TestUtils.cs
Labels: Medium

#2522 Move timeout related codes to `SendMessageAync()`
  Libplanet.Net/Transports/NetMQTransport.cs
Labels: network, Large, Squash Needed

#2498 Isolate problematic tests
  .circleci/config.yml
  Libplanet.Net.Tests/Transports/TransportTest.cs
  Libplanet.Node.Tests/SwarmConfigTest.cs
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
  Libplanet.Tests/Action/Sys/MintTest.cs
  Libplanet.Tests/Action/Sys/TransferTest.cs
  Libplanet.Tests/Blockchain/BlockChainTest.Append.cs
  Libplanet.Tests/Blockchain/BlockChainTest.Internals.cs
  Libplanet.Tests/Blockchain/BlockChainTest.MineBlock.cs
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet.Tests/Blockchain/Policies/BlockPolicyTest.cs
  Libplanet.Tests/Blockchain/Policies/StagePolicyTest.cs
  Libplanet.Tests/Blockchain/Policies/VolatileStagePolicyTest.cs
  Libplanet.Tests/Blockchain/Renderers/AnonymousActionRendererTest.cs
  Libplanet.Tests/Blockchain/Renderers/AnonymousRendererTest.cs
  Libplanet.Tests/Blockchain/Renderers/DelayedActionRendererTest.cs
  Libplanet.Tests/Blockchain/Renderers/DelayedRendererTest.cs
  Libplanet.Tests/Blockchain/Renderers/LoggedActionRendererTest.cs
  Libplanet.Tests/Blockchain/Renderers/NonblockRendererTest.cs
  Libplanet.Tests/Blocks/BlockContentTest.cs
  Libplanet.Tests/Blocks/BlockMetadataTest.cs
  Libplanet.Tests/Blocks/BlockTest.cs
  Libplanet.Tests/Blocks/PreEvaluationBlockTest.cs
  Libplanet.Tests/Store/BlockSetTest.cs
  Libplanet.Tests/Store/DefaultStoreTest.cs
  Libplanet.Tests/Store/StoreTest.cs
  Libplanet.Tests/TestUtils.cs
Labels: Large

#2543 ♻️ Renamed last commits to block commits where appropriate
  CHANGES.md
  Libplanet.Explorer/Store/LiteDBRichStore.cs
  Libplanet.Explorer/Store/MySQLRichStore.cs
  Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextNonProposerTest.cs
  Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextTest.cs
  Libplanet.Net.Tests/Consensus/Context/ContextTest.cs
  Libplanet.Net.Tests/Consensus/Context/MessageLogTest.cs
  Libplanet.Net.Tests/TestUtils.cs
  Libplanet.Net/Consensus/ConsensusContext.cs
  Libplanet.Net/Consensus/ConsensusReactor.cs
  Libplanet.Net/Consensus/ConsensusReactorOption.cs
  Libplanet.Net/Swarm.cs
  Libplanet.RocksDBStore/RocksDBStore.cs
  Libplanet.Tests/Store/ProxyStore.cs
  Libplanet.Tests/Store/StoreTest.cs
  Libplanet.Tests/Store/StoreTracker.cs
  Libplanet/Store/BaseStore.cs
  Libplanet/Store/DefaultStore.cs
  Libplanet/Store/IStore.cs
  Libplanet/Store/MemoryStore.cs
Labels: Large

#2540 Add `.ToString()` method to `BlockCommit` and `Vote`
  Libplanet.Net/Consensus/ConsensusContext.cs
  Libplanet.Net/Consensus/Context.Async.cs
  Libplanet.Net/Consensus/Context.cs
  Libplanet/Blocks/BlockCommit.cs
  Libplanet/Consensus/Vote.cs
Labels: Extra Small

#2545 Refactor `MessageType`
  CHANGES.md
  Libplanet.Net/Messages/ConsensusProposalMsg.cs
  Libplanet.Net/Messages/Message.cs
  Libplanet.Net/Messages/NetMQMessageCodec.cs
Labels: Extra Small

#2546 Changed `BlocksMsg` layout
  Libplanet.Net.Tests/Messages/NetMQMessageCodecTest.cs
  Libplanet.Net.Tests/SwarmTest.cs
  Libplanet.Net/Messages/BlocksMsg.cs
  Libplanet.Net/Swarm.MessageHandlers.cs
  Libplanet.Net/Swarm.cs
Labels: Extra Small

#2548 `Append()` stores `BlockCommit`
  CHANGES.md
  Libplanet.Benchmarks/SwarmBenchmark.cs
  Libplanet.Explorer.Tests/Libplanet.Explorer.Tests.csproj
  Libplanet.Explorer.Tests/Queries/TransactionQueryTest.cs
  Libplanet.Extensions.Cocona.Tests/Commands/StoreCommandTest.cs
  Libplanet.Net.Tests/BlockCompletionTest.cs
  Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextNonProposerTest.cs
  Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextTest.cs
  Libplanet.Net.Tests/Consensus/Context/ContextProposerTest.cs
  Libplanet.Net.Tests/Consensus/Context/ContextTest.cs
  Libplanet.Net.Tests/Consensus/Context/MessageLogTest.cs
  Libplanet.Net.Tests/SwarmTest.Broadcast.cs
  Libplanet.Net.Tests/SwarmTest.Fixtures.cs
  Libplanet.Net.Tests/SwarmTest.Preload.cs
  Libplanet.Net.Tests/SwarmTest.cs
  Libplanet.Net.Tests/TestUtils.cs
  Libplanet.Net/Consensus/ConsensusContext.cs
  Libplanet.Net/Consensus/Context.Mutate.cs
  Libplanet.Net/Swarm.BlockCandidate.cs
  Libplanet.Net/Swarm.BlockSync.cs
  Libplanet.RocksDBStore/RocksDBStore.cs
  Libplanet.Tests/Action/AccountStateDeltaImplTest.cs
  Libplanet.Tests/Action/AccountStateDeltaImplV0Test.cs
  Libplanet.Tests/Action/AccountStateDeltaTest.cs
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
  Libplanet.Tests/Blockchain/BlockChainTest.Append.cs
  Libplanet.Tests/Blockchain/BlockChainTest.Internals.cs
  Libplanet.Tests/Blockchain/BlockChainTest.MineBlock.cs
  Libplanet.Tests/Blockchain/BlockChainTest.Stage.cs
  Libplanet.Tests/Blockchain/BlockChainTest.ValidateNextBlock.cs
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet.Tests/Blockchain/Renderers/DelayedActionRendererTest.cs
  Libplanet.Tests/Blockchain/Renderers/DelayedRendererTest.cs
  Libplanet.Tests/Blocks/PreEvaluationBlockTest.cs
  Libplanet.Tests/Fixtures/IntegerSet.cs
  Libplanet.Tests/Store/StoreFixture.cs
  Libplanet.Tests/Store/StoreTest.cs
  Libplanet.Tests/TestUtils.cs
  Libplanet/Blockchain/BlockChain.cs
  Libplanet/Blocks/InvalidBlockCommitException.cs
Labels: Extra Large, pbft

#2554 Move `ConsensusContext<T>.ClearOldBlockCommitCache()` to `BlockChain<T>`
  CHANGES.md
  Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextTest.cs
  Libplanet.Net.Tests/TestUtils.cs
  Libplanet.Net/Consensus/ConsensusContext.cs
  Libplanet.Net/Consensus/ConsensusReactor.cs
  Libplanet.Net/Consensus/ConsensusReactorOption.cs
  Libplanet.Net/Swarm.cs
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet/Blockchain/BlockChain.cs
Labels: Medium, pbft

#2556 fix: Move putting `BlockCommit` to lock section
  Libplanet/Blockchain/BlockChain.cs
Labels: Extra Small, pbft

#2555 Homebrew Cask packaging
  CHANGES.md
  Libplanet.Tools/README.md
Labels: tools, packaging, Extra Small

#2557 Added test
  Libplanet.Tests/Blockchain/BlockChainTest.cs
Labels: Extra Small

#2539 Introduce IActionTypeLoader
  CHANGES.md
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
  Libplanet.Tests/Action/StaticActionTypeLoaderTest.cs
  Libplanet/Action/ActionEvaluator.cs
  Libplanet/Action/IActionTypeLoader.cs
  Libplanet/Action/PolymorphicAction.cs
  Libplanet/Action/StaticActionTypeLoader.cs
  Libplanet/Blockchain/Renderers/Debug/ValidatingActionRenderer.cs
  Libplanet/Blocks/Block.cs
  Libplanet/Blocks/IBlockContent.cs
  Libplanet/Blocks/IPreEvaluationBlock.cs
  Libplanet/Blocks/PreEvaluationBlock.cs
  Libplanet/Tx/ITransaction.cs
  Libplanet/Tx/Transaction.cs
Labels: Large

#2558 Send `BlockCommit` in `BlocksMsg`
  Libplanet.Net.Tests/BlockCompletionTest.cs
  Libplanet.Net.Tests/SwarmTest.Broadcast.cs
  Libplanet.Net.Tests/SwarmTest.cs
  Libplanet.Net/BlockCandidateTable.cs
  Libplanet.Net/BlockCompletion.cs
  Libplanet.Net/Messages/ConsensusPreCommitMsg.cs
  Libplanet.Net/Messages/ConsensusPreVoteMsg.cs
  Libplanet.Net/Messages/ConsensusProposalMsg.cs
  Libplanet.Net/Swarm.BlockCandidate.cs
  Libplanet.Net/Swarm.BlockSync.cs
  Libplanet.Net/Swarm.MessageHandlers.cs
  Libplanet.Net/Swarm.cs
  Libplanet.RocksDBStore/RocksDBStore.cs
  Libplanet.Tests/Blocks/BlockCommitTest.cs
  Libplanet.Tests/Consensus/ProposalTest.cs
  Libplanet.Tests/Consensus/VoteMetadataTest.cs
  Libplanet.Tests/Consensus/VoteTest.cs
  Libplanet/Blocks/BlockCommit.cs
  Libplanet/Consensus/Proposal.cs
  Libplanet/Consensus/ProposalMetadata.cs
  Libplanet/Consensus/Vote.cs
  Libplanet/Consensus/VoteMetadata.cs
  Libplanet/Store/DefaultStore.cs
Labels: Large

#2562 Provide explorer in also `/graphql/explorer`
  CHANGES.md
  Libplanet.Explorer/ExplorerStartup.cs
Labels: explorer, Extra Small

#2561 Validate `BlockCommit` while in `BlockChain<T>.Append()`
  CHANGES.md
  Libplanet.Explorer.Tests/Queries/TransactionQueryTest.cs
  Libplanet.Net.Tests/SwarmTest.Preload.cs
  Libplanet.Net.Tests/SwarmTest.cs
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
  Libplanet.Tests/Blockchain/BlockChainTest.Append.cs
  Libplanet.Tests/Blockchain/BlockChainTest.MineBlock.cs
  Libplanet.Tests/Blockchain/BlockChainTest.ValidateNextBlock.cs
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet.Tests/Blocks/PreEvaluationBlockTest.cs
  Libplanet/Blockchain/BlockChain.cs
Labels: Large, pbft

#2563 Provide `schema` command to get explorer schema
  CHANGES.md
  Libplanet.Explorer.Executable/Program.cs
Labels: explorer, Extra Small

#2565 Ignore NetMQTransport's TimeoutException
  Libplanet.Net/Swarm.cs
  Libplanet.Net/Transports/NetMQTransport.cs
Labels: Small, logging

#2571 Bump BouncyCastle
  CHANGES.md
  Libplanet/Crypto/DefaultCryptoBackend.cs
  Libplanet/Libplanet.csproj
Labels: Extra Small

#2573 Refactor `BlockCommit` caching
  Libplanet.Explorer/Store/LiteDBRichStore.cs
  Libplanet.Explorer/Store/MySQLRichStore.cs
  Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextTest.cs
  Libplanet.Net.Tests/SwarmTest.Preload.cs
  Libplanet.Net/Swarm.BlockCandidate.cs
  Libplanet.Net/Swarm.BlockSync.cs
  Libplanet.Net/Swarm.cs
  Libplanet.RocksDBStore/RocksDBStore.cs
  Libplanet.Tests/Blockchain/BlockChainTest.Append.cs
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet.Tests/Store/ProxyStore.cs
  Libplanet.Tests/Store/StoreTest.cs
  Libplanet.Tests/Store/StoreTracker.cs
  Libplanet/Blockchain/BlockChain.cs
  Libplanet/Store/BaseStore.cs
  Libplanet/Store/DefaultStore.cs
  Libplanet/Store/IStore.cs
  Libplanet/Store/MemoryStore.cs
Labels: Large

#2574 🧹 Changelog
  CHANGES.md
Labels: Extra Small

#2578 🔀 Merge `pbft-validate-block-commit` branch
  CHANGES.md
  Libplanet.Explorer.Tests/Queries/TransactionQueryTest.cs
  Libplanet.Explorer/Store/LiteDBRichStore.cs
  Libplanet.Explorer/Store/MySQLRichStore.cs
  Libplanet.Net.Tests/BlockCompletionTest.cs
  Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextTest.cs
  Libplanet.Net.Tests/SwarmTest.Broadcast.cs
  Libplanet.Net.Tests/SwarmTest.Preload.cs
  Libplanet.Net.Tests/SwarmTest.cs
  Libplanet.Net.Tests/TestUtils.cs
  Libplanet.Net/BlockCandidateTable.cs
  Libplanet.Net/BlockCompletion.cs
  Libplanet.Net/Consensus/ConsensusContext.cs
  Libplanet.Net/Consensus/ConsensusReactor.cs
  Libplanet.Net/Consensus/ConsensusReactorOption.cs
  Libplanet.Net/Messages/ConsensusPreCommitMsg.cs
  Libplanet.Net/Messages/ConsensusPreVoteMsg.cs
  Libplanet.Net/Messages/ConsensusProposalMsg.cs
  Libplanet.Net/Swarm.BlockCandidate.cs
  Libplanet.Net/Swarm.BlockSync.cs
  Libplanet.Net/Swarm.MessageHandlers.cs
  Libplanet.Net/Swarm.cs
  Libplanet.RocksDBStore/RocksDBStore.cs
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
  Libplanet.Tests/Blockchain/BlockChainTest.Append.cs
  Libplanet.Tests/Blockchain/BlockChainTest.MineBlock.cs
  Libplanet.Tests/Blockchain/BlockChainTest.ValidateNextBlock.cs
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet.Tests/Blocks/BlockCommitTest.cs
  Libplanet.Tests/Blocks/PreEvaluationBlockTest.cs
  Libplanet.Tests/Consensus/ProposalTest.cs
  Libplanet.Tests/Consensus/VoteMetadataTest.cs
  Libplanet.Tests/Consensus/VoteTest.cs
  Libplanet.Tests/Store/ProxyStore.cs
  Libplanet.Tests/Store/StoreTest.cs
  Libplanet.Tests/Store/StoreTracker.cs
  Libplanet/Blockchain/BlockChain.cs
  Libplanet/Blocks/BlockCommit.cs
  Libplanet/Consensus/Proposal.cs
  Libplanet/Consensus/ProposalMetadata.cs
  Libplanet/Consensus/Vote.cs
  Libplanet/Consensus/VoteMetadata.cs
  Libplanet/Store/BaseStore.cs
  Libplanet/Store/DefaultStore.cs
  Libplanet/Store/IStore.cs
  Libplanet/Store/MemoryStore.cs
Labels: Extra Large

#2572 Upgrade GraphQL-related dependencies
  CHANGES.md
  Libplanet.Explorer.Executable/Program.cs
  Libplanet.Explorer.Tests/GraphQLTestUtils.cs
  Libplanet.Explorer.Tests/GraphTypes/ByteStringTypeTest.cs
  Libplanet.Explorer.Tests/Queries/TransactionQueryTest.cs
  Libplanet.Explorer/ExplorerStartup.cs
  Libplanet.Explorer/GraphTypes/ActionType.cs
  Libplanet.Explorer/GraphTypes/AddressType.cs
  Libplanet.Explorer/GraphTypes/BencodexValueType.cs
  Libplanet.Explorer/GraphTypes/BlockPolicyType.cs
  Libplanet.Explorer/GraphTypes/BlockType.cs
  Libplanet.Explorer/GraphTypes/ByteStringType.cs
  Libplanet.Explorer/GraphTypes/CurrencyType.cs
  Libplanet.Explorer/GraphTypes/FungibleAssetValueType.cs
  Libplanet.Explorer/GraphTypes/NodeStateType.cs
  Libplanet.Explorer/GraphTypes/PublicKeyType.cs
  Libplanet.Explorer/GraphTypes/TransactionType.cs
  Libplanet.Explorer/GraphTypes/TxResultType.cs
  Libplanet.Explorer/Libplanet.Explorer.csproj
  Libplanet.Explorer/Mutations/TransactionMutation.cs
  Libplanet.Explorer/Queries/BlockQuery.cs
  Libplanet.Explorer/Queries/ExplorerQuery.cs
  Libplanet.Explorer/Queries/StateQuery.cs
  Libplanet.Explorer/Queries/TransactionQuery.cs
  Libplanet.Explorer/Schemas/ConfigureLibplanetExplorerSchema.cs
  Libplanet.Explorer/Schemas/GraphQLBuilderExtensions.cs
  Libplanet.Explorer/Schemas/LibplanetExplorerSchema.cs
Labels: explorer, packaging, Extra Large

#2586 Command-line completion support for planet CLI
  CHANGES.md
  Libplanet.Tools/Program.cs
  Libplanet.Tools/README.md
Labels: tools, Extra Small

#2589 Improve performance of `VolatileStagePolicy.Iterate()` and `.GetNextTxNonce()` & Release 0.44.2
  CHANGES.md
  Libplanet/Blockchain/Policies/VolatileStagePolicy.cs
Labels: Extra Small

#2591 Prepare 0.44.3
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: Extra Small

#2592 Port 0.44.2 to main
  CHANGES.md
  Libplanet/Blockchain/Policies/VolatileStagePolicy.cs
Labels: Extra Small

#2594 🧹 Changelog
  CHANGES.md
Labels: Extra Small

#2575 🧹 Remove `BlockPerception`
  CHANGES.md
  Libplanet.Explorer/Store/LiteDBRichStore.cs
  Libplanet.Explorer/Store/MySQLRichStore.cs
  Libplanet.Extensions.Cocona/Commands/StatsCommand.cs
  Libplanet.Net.Tests/SwarmTest.Consensus.cs
  Libplanet.Net/Swarm.BlockCandidate.cs
  Libplanet.Net/Swarm.BlockSync.cs
  Libplanet.RocksDBStore/RocksDBStore.cs
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet.Tests/Blockchain/TotalDifficultyComparerTest.cs
  Libplanet.Tests/Store/ProxyStore.cs
  Libplanet.Tests/Store/StoreTest.cs
  Libplanet.Tests/Store/StoreTracker.cs
  Libplanet/Blockchain/BlockChain.cs
  Libplanet/Blocks/BlockPerception.cs
  Libplanet/Store/BaseStore.cs
  Libplanet/Store/DefaultStore.cs
  Libplanet/Store/IStore.cs
  Libplanet/Store/MemoryStore.cs
Labels: Large

#2593 Introduce `IBlockPolicy.GetMinBlockProtocolVersion()`
  CHANGES.md
  Libplanet.Explorer.Executable/Program.cs
  Libplanet.Tests/Blockchain/Policies/BlockPolicyTest.cs
  Libplanet/Blockchain/Policies/BlockPolicy.cs
  Libplanet/Blockchain/Policies/IBlockPolicy.cs
  Libplanet/Blockchain/Policies/NullBlockPolicy.cs
Labels: Extra Small
