Repository planetarium/libplanet, pull requests merged in 2022-07, with the labels that each got.

#2129 Add docstring for `BlockChain.ProposeBlock()`
  Libplanet.Net/Consensus/Context.cs
  Libplanet.Node/UntypedBlock.cs
  Libplanet/Blockchain/BlockChain.MineBlock.cs
  Libplanet/Blockchain/Policies/BlockPolicy.cs
Labels: docs, Extra Small, pbft

#2123 BlockDigest / VoteSet comment
  Libplanet/Consensus/VoteSet.cs
  Libplanet/Store/BlockDigest.cs
Labels: Extra Small, pbft

#2116 fix: Prevent improper parsing on 'Uri.UserInfo' with exception
  CHANGES.md
  Libplanet.Net.Tests/IceServerTest.cs
  Libplanet.Net/IceServer.cs
Labels: good first issue, api, Extra Small

#2124 Comment `Net.Consensus` related changes
  Libplanet.Net/Consensus/CommitBlockNotExistsException.cs
  Libplanet.Net/Consensus/ConsensusContext.cs
  Libplanet.Net/Consensus/ConsensusReactor.cs
  Libplanet.Net/Consensus/ConsensusReactorOption.cs
  Libplanet.Net/Consensus/Context.cs
  Libplanet.Net/Consensus/IReactor.cs
  Libplanet.Net/Consensus/InvalidBlockProposeMessageException.cs
  Libplanet.Net/Consensus/InvalidHeightIncreasingException.cs
  Libplanet.Net/Consensus/InvalidHeightMessageException.cs
  Libplanet.Net/Consensus/InvalidProposerProposeMessageException.cs
  Libplanet.Net/Consensus/InvalidRoundMessageException.cs
  Libplanet.Net/Consensus/InvalidValidatorVoteMessageException.cs
  Libplanet.Net/Consensus/TryUnexpectedMessageHandleException.cs
  Libplanet.Net/Consensus/UnexpectedBlockHashException.cs
  Libplanet.Net/Consensus/UnexpectedHeightProposeException.cs
  Libplanet.Net/Consensus/UnexpectedLeaderProposeException.cs
  Libplanet.Net/Consensus/UnexpectedRoundProposeException.cs
  Libplanet.Net/Consensus/VoteBlockNotExistsException.cs
  Libplanet.Net/Messages/ConsensusCommit.cs
  Libplanet.Net/Messages/ConsensusMessage.cs
  Libplanet.Net/Messages/ConsensusPropose.cs
  Libplanet.Net/Messages/ConsensusVote.cs
Labels: docs, Medium, pbft

#2134 Default number of workers raised to 100
  CHANGES.md
  Libplanet.Explorer.Executable/Program.cs
  Libplanet.Net/Swarm.cs
Labels: Extra Small

#2091 fix: issue #1696
  CHANGES.md
  Libplanet.Tests/Crypto/PrivateKeyTest.cs
  Libplanet/Crypto/GenerateKeyParamTriesExceedException.cs
  Libplanet/Crypto/PrivateKey.cs
Labels: Extra Small

#2135 docs: add missing link in changelog
  CHANGES.md
Labels: docs, Extra Small

#2125 fix: fix flaky test `SwarmTest.BroadcastBlockWithSkip`
  Libplanet.Net.Tests/SwarmTest.Broadcast.cs
Labels: Extra Small

#2122 Add changelog for PBFT -> main
  CHANGES.md
  Libplanet.Node/SwarmConfig.cs
Labels: docs, Small, pbft

#2136 Let `PolymorphicAction<T>` allow `T` to be inherited from the entry assembly
  CHANGES.md
  Libplanet/Action/PolymorphicAction.cs
Labels: api, Extra Small

#2137 Refactor `DataModel`
  Libplanet.Benchmarks/DataModel/DataModelBenchmark.LeafModel.cs
  Libplanet.Benchmarks/DataModel/DataModelBenchmark.MidModel.cs
  Libplanet.Benchmarks/DataModel/DataModelBenchmark.RootModel.cs
  Libplanet.Benchmarks/DataModel/DataModelBenchmark.cs
  Libplanet.Tests/Store/DataModelTest.cs
  Libplanet/Store/DataModel.Decode.cs
  Libplanet/Store/DataModel.Encode.cs
Labels: Extra Large

#2142 Make `PolymorphicAction<T>` more robust
  CHANGES.md
  Libplanet.Tests/Action/DuplicateActionTypeIdentifierExceptionTest.cs
  Libplanet.Tests/Action/PolymorphicActionTest.cs
  Libplanet/Action/ActionTypeAttribute.cs
  Libplanet/Action/DuplicateActionTypeIdentifierException.cs
  Libplanet/Action/PolymorphicAction.cs
Labels: bug, api, Medium

#2144 Use `object` instead of `dynamic` for Unity Mono compatibility.
  Libplanet/Store/DataModel.Decode.cs
Labels: Medium

#2139 `TcpTransport` removed
  .circleci/config.yml
  CHANGES.md
  Libplanet.Net.Tests/SwarmTest.Fixtures.cs
  Libplanet.Net.Tests/SwarmTest.cs
  Libplanet.Net.Tests/Transports/BoundPeerExtensionsTest.cs
  Libplanet.Net.Tests/Transports/InvalidMagicCookieExceptionTest.cs
  Libplanet.Net.Tests/Transports/TcpTransportTest.cs
  Libplanet.Net/Swarm.cs
  Libplanet.Net/SwarmOptions.cs
  Libplanet.Net/Transports/BoundPeerExtensions.cs
  Libplanet.Net/Transports/InvalidMagicCookieException.cs
  Libplanet.Net/Transports/TcpTransport.cs
  Libplanet.Node.Tests/SwarmConfigTest.cs
  Libplanet.Node/InitConfig.cs
  Libplanet.Node/SwarmConfig.cs
Labels: Extra Large

#2145 🚀 Release 0.39.0
  CHANGES.md
Labels: Extra Small

#2146 🔧 Prepare 0.39.1
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: Extra Small

#2147 🔧 Prepare 0.40.0
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: Extra Small

#2148 Slightly improve CI/CD experience
  .circleci/config.yml
  .github/auto_assign.yml
  .github/bin/dist-nuget.sh
Labels: ci & cd, Extra Small

#2141 test/refactor: `ConsensusContextTest` and remove `ITransport` from some PBFT tests
  Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextNonProposerTest.cs
  Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextProposerTest.cs
  Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextTest.cs
  Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextTestBase.cs
  Libplanet.Net.Tests/Consensus/ConsensusContextTest.cs
  Libplanet.Net.Tests/Consensus/Context/ContextNonProposerTest.cs
  Libplanet.Net.Tests/Consensus/Context/ContextProposerTest.cs
  Libplanet.Net.Tests/Consensus/Context/ContextProposerValidRoundTest.cs
  Libplanet.Net.Tests/Consensus/Context/ContextTest.cs
  Libplanet.Net.Tests/Consensus/Context/ContextTestBase.cs
  Libplanet.Net.Tests/SwarmTest.Fixtures.cs
  Libplanet.Net.Tests/Transports/BoundPeerExtensionsTest.cs
  Libplanet.Node.Tests/SwarmConfigTest.cs
Labels: Extra Large, pbft

#2154 Merge main into PBFT
  .circleci/config.yml
  .github/auto_assign.yml
  .github/bin/dist-nuget.sh
  CHANGES.md
  Libplanet.Benchmarks/DataModel/DataModelBenchmark.LeafModel.cs
  Libplanet.Benchmarks/DataModel/DataModelBenchmark.MidModel.cs
  Libplanet.Benchmarks/DataModel/DataModelBenchmark.RootModel.cs
  Libplanet.Benchmarks/DataModel/DataModelBenchmark.cs
  Libplanet.Explorer.Executable/Program.cs
  Libplanet.Extensions.Cocona/Commands/Key/DerivationCommand.cs
  Libplanet.Net.Tests/IceServerTest.cs
  Libplanet.Net.Tests/SwarmTest.Broadcast.cs
  Libplanet.Net.Tests/SwarmTest.Fixtures.cs
  Libplanet.Net.Tests/SwarmTest.cs
  Libplanet.Net.Tests/Transports/BoundPeerExtensionsTest.cs
  Libplanet.Net.Tests/Transports/InvalidMagicCookieExceptionTest.cs
  Libplanet.Net.Tests/Transports/TcpTransportTest.cs
  Libplanet.Net/IceServer.cs
  Libplanet.Net/Swarm.cs
  Libplanet.Net/SwarmOptions.cs
  Libplanet.Net/Transports/BoundPeerExtensions.cs
  Libplanet.Net/Transports/InitTransport.cs
  Libplanet.Net/Transports/InvalidMagicCookieException.cs
  Libplanet.Net/Transports/TcpTransport.cs
  Libplanet.Net/Transports/TransportType.cs
  Libplanet.Node.Tests/SwarmConfigTest.cs
  Libplanet.Node/InitConfig.cs
  Libplanet.Node/SwarmConfig.cs
  Libplanet.Tests/Action/DuplicateActionTypeIdentifierExceptionTest.cs
  Libplanet.Tests/Action/PolymorphicActionTest.cs
  Libplanet.Tests/Crypto/PrivateKeyTest.cs
  Libplanet.Tests/Store/DataModelTest.cs
  Libplanet/Action/ActionTypeAttribute.cs
  Libplanet/Action/DuplicateActionTypeIdentifierException.cs
  Libplanet/Action/PolymorphicAction.cs
  Libplanet/Crypto/GenerateKeyParamTriesExceedException.cs
  Libplanet/Crypto/PrivateKey.cs
  Libplanet/Libplanet.csproj
  Libplanet/Store/DataModel.Decode.cs
  Libplanet/Store/DataModel.Encode.cs
Labels: pbft

#2140 Expose BlockLocator and Libplanet.Net related functions in BlockChain<T>
  CHANGES.md
  Libplanet/Blockchain/BlockChain.cs
  Libplanet/Blockchain/BlockLocator.cs
Labels: Medium, Squash Needed

#2159 Fix timestamp-related problems in RocksDBStore
  CHANGES.md
  Libplanet.RocksDBStore/RocksDBStore.cs
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet/Blockchain/BlockChain.cs
Labels: Squash Needed

#2168 Let `DelayedActionRendererTest.ClearRenderBufferWhenItsInterval()` try up to 3 times
  Libplanet.Tests/Blockchain/Renderers/DelayedActionRendererTest.cs
Labels: bug, ci & cd

#2177 Gossip protocol for consensus messages
  CHANGES.md
  Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextNonProposerTest.cs
  Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextTest.cs
  Libplanet.Net.Tests/Consensus/Context/ContextTest.cs
  Libplanet.Net.Tests/Consensus/GossipTest.cs
  Libplanet.Net.Tests/Consensus/MessageCacheTest.cs
  Libplanet.Net.Tests/Messages/MessageIdTest.cs
  Libplanet.Net.Tests/Messages/MessageTest.cs
  Libplanet.Net.Tests/TestUtils.cs
  Libplanet.Net/Consensus/ConsensusReactor.cs
  Libplanet.Net/Consensus/Context.cs
  Libplanet.Net/Consensus/Gossip.cs
  Libplanet.Net/Consensus/InvalidValidatorVoteMessageException.cs
  Libplanet.Net/Consensus/MessageCache.cs
  Libplanet.Net/Libplanet.Net.csproj
  Libplanet.Net/Messages/ConsensusCommit.cs
  Libplanet.Net/Messages/ConsensusMessage.cs
  Libplanet.Net/Messages/ConsensusPropose.cs
  Libplanet.Net/Messages/ConsensusVote.cs
  Libplanet.Net/Messages/HaveMessage.cs
  Libplanet.Net/Messages/Message.cs
  Libplanet.Net/Messages/MessageId.cs
  Libplanet.Net/Messages/NetMQMessageCodec.cs
  Libplanet.Net/Messages/WantMessage.cs
Labels: network, pbft

#2185 Change 'Message' names
  Libplanet.Net.Tests/Messages/BlockHashesTest.cs
  Libplanet.Net.Tests/Messages/MessageTest.cs
  Libplanet.Net.Tests/Messages/MessageValidatorTest.cs
  Libplanet.Net.Tests/Messages/NetMQMessageCodecTest.cs
  Libplanet.Net.Tests/SwarmTest.Broadcast.cs
  Libplanet.Net.Tests/SwarmTest.cs
  Libplanet.Net.Tests/Transports/CommunicationFailExceptionTest.cs
  Libplanet.Net.Tests/Transports/SendMessageFailExceptionTest.cs
  Libplanet.Net.Tests/Transports/TransportTest.cs
  Libplanet.Net/BootstrapOptions.cs
  Libplanet.Net/Messages/BlockHashesMsg.cs
  Libplanet.Net/Messages/BlockHeaderMsg.cs
  Libplanet.Net/Messages/BlocksMsg.cs
  Libplanet.Net/Messages/ChainStatusMsg.cs
  Libplanet.Net/Messages/DifferentVersionMsg.cs
  Libplanet.Net/Messages/FindNeighborsMsg.cs
  Libplanet.Net/Messages/GetBlockHashesMsg.cs
  Libplanet.Net/Messages/GetBlocksMsg.cs
  Libplanet.Net/Messages/GetChainStatusMsg.cs
  Libplanet.Net/Messages/GetTxsMsg.cs
  Libplanet.Net/Messages/NeighborsMsg.cs
  Libplanet.Net/Messages/NetMQMessageCodec.cs
  Libplanet.Net/Messages/PingMsg.cs
  Libplanet.Net/Messages/PongMsg.cs
  Libplanet.Net/Messages/TcpMessageCodec.cs
  Libplanet.Net/Messages/TxIdsMsg.cs
  Libplanet.Net/Messages/TxMsg.cs
  Libplanet.Net/PreloadOptions.cs
  Libplanet.Net/Protocols/IProtocol.cs
  Libplanet.Net/Protocols/KademliaProtocol.cs
  Libplanet.Net/Swarm.MessageHandlers.cs
  Libplanet.Net/Swarm.cs
  Libplanet.Net/SwarmOptions.cs
  Libplanet.Net/TimeoutOptions.cs
  Libplanet.Net/Transports/BoundPeerExtensions.cs
  Libplanet.Net/Transports/NetMQTransport.cs
  Libplanet.Node/SyncConfig.cs
Labels: Squash Needed

#2179 Add GenesisHash to ActionEvaluator
  CHANGES.md
  Libplanet.Tests/Action/ActionContextTest.cs
  Libplanet.Tests/Action/ActionEvaluationTest.cs
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
  Libplanet.Tests/Blockchain/Renderers/AnonymousActionRendererTest.cs
  Libplanet.Tests/Blockchain/Renderers/DelayedActionRendererTest.cs
  Libplanet.Tests/Blockchain/Renderers/LoggedActionRendererTest.cs
  Libplanet.Tests/Blockchain/Renderers/NonblockActionRendererTest.cs
  Libplanet/Action/ActionContext.cs
  Libplanet/Action/ActionEvaluator.cs
  Libplanet/Action/IActionContext.cs
  Libplanet/Blockchain/BlockChain.cs
  Libplanet/Blocks/PreEvaluationBlock.cs
Labels: api
