Repository planetarium/libplanet, pull requests merged in 2022-03, with the labels that each got.

#1840 Logging format update for consistency
  Libplanet/Action/ActionEvaluator.cs
Labels: Extra Small

#1839 DealerSocket linger added
  CHANGES.md
  Libplanet.Net/Transports/NetMQTransport.cs
Labels: Extra Small

#1841 Release 0.28.1
  CHANGES.md
Labels: Extra Small

#1843 Port 0.28.1 to main
  CHANGES.md
  Libplanet.Net/Transports/NetMQTransport.cs
  Libplanet/Action/ActionEvaluator.cs
Labels: Extra Small

#1838 Replace ColumnFamilies to key prefix for index db
  CHANGES.md
  Libplanet.Extensions.Cocona/Commands/StoreCommand.cs
  Libplanet.RocksDBStore.Tests/RocksDBStoreTest.cs
  Libplanet.RocksDBStore/RocksDBStore.cs
Labels: Large

#1847 Fix bug in migration indexes
  Libplanet.RocksDBStore/RocksDBStore.cs
Labels: bug, Extra Small

#1851 Combined logging for `NetMQTransport.SendMessageWithReplyAsync()`
  Libplanet.Net/Transports/NetMQTransport.cs
Labels: Extra Small

#1852 Silence `RocksDBStore.GetBlockDigest()` for non-existent block hashes & release 0.28.2
  CHANGES.md
  Libplanet.RocksDBStore/RocksDBStore.cs
  Libplanet/Store/BlockDigest.cs
  Libplanet/Store/DefaultStore.cs
Labels: bug, storage, release, Extra Small, logging

#1849 Deprecate `ITransport.SendMessageAsync()`
  CHANGES.md
  Libplanet.Net.Tests/Protocols/TestTransport.cs
  Libplanet.Net.Tests/SwarmTest.Broadcast.cs
  Libplanet.Net.Tests/SwarmTest.cs
  Libplanet.Net.Tests/Transports/TransportTest.cs
  Libplanet.Net/Protocols/KademliaProtocol.cs
  Libplanet.Net/Swarm.cs
  Libplanet.Net/Transports/ITransport.cs
  Libplanet.Net/Transports/NetMQTransport.cs
  Libplanet.Net/Transports/TcpTransport.cs
Labels: network, Medium

#1856 Subtags added to metric logs for easy parsing
  Libplanet.Net/Transports/NetMQTransport.cs
  Libplanet/Action/ActionEvaluator.cs
  Libplanet/Blockchain/BlockChain.Swap.cs
  Libplanet/Blockchain/BlockChain.cs
  Libplanet/Blockchain/Policies/VolatileStagePolicy.cs
Labels: Extra Small

#1854 Port 0.28.2 to main (0.29.x)
  .github/workflows/main.yml
  CHANGES.md
  Libplanet.RocksDBStore/RocksDBStore.cs
  Libplanet/Store/BlockDigest.cs
  Libplanet/Store/DefaultStore.cs
Labels: Small

#1857 Inbound message tracking metric log added
  Libplanet.Net/Transports/NetMQTransport.cs
Labels: Extra Small

#1855 [skip changelog] Unnecessary broadcast poller removed
  Libplanet.Net/Transports/NetMQTransport.cs
Labels: Extra Small

#1845 Reply `Pong` to `TxIds` and `BlockHeaderMessage`
  CHANGES.md
  Libplanet.Net/Swarm.MessageHandlers.cs
Labels: network, Extra Small

#1858 Revert IndexDB migration
  CHANGES.md
  Libplanet.Extensions.Cocona/Commands/StoreCommand.cs
  Libplanet.RocksDBStore.Tests/RocksDBStoreTest.cs
  Libplanet.RocksDBStore/RocksDBStore.cs
Labels: Large

#1859 Release 0.29.0
  .github/workflows/main.yml
  CHANGES.md
Labels: release, Extra Small

#1860 Make the release script more robust
  .github/bin/dist-github-release.sh
Labels: bug, ci & cd, Extra Small

#1861 Prepare 0.30.0
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: Extra Small

#1862 Remove column family from index db and add support for migration
  CHANGES.md
  Libplanet.Extensions.Cocona/Commands/StoreCommand.cs
  Libplanet.RocksDBStore.Tests/RocksDBStoreTest.cs
  Libplanet.RocksDBStore/RocksDBStore.cs
Labels: Large

#1868 Release 0.30.0
  CHANGES.md
Labels: release, Extra Small

#1875 Revert #1871
  CHANGES.md
  Libplanet.Net.Tests/Protocols/ProtocolTest.cs
  Libplanet.Net/Protocols/Kademlia.cs
  Libplanet.Net/Protocols/KademliaProtocol.cs
Labels: Extra Small

#1869 Prepare 0.31.0
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: Extra Small

#1870 Prepare 0.30.1
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: Extra Small

#1876 Increase `Message` receive throughput
  CHANGES.md
  Libplanet.Stun/Stun/TurnClient.cs
Labels: network, Extra Small

#1877 Some name changes in Kademlia for clarity
  CHANGES.md
  Libplanet.Net.Tests/Protocols/ProtocolTest.cs
  Libplanet.Net/Protocols/Kademlia.cs
  Libplanet.Net/Protocols/KademliaProtocol.cs
Labels: Extra Small

#1881 Release 0.31.0
  CHANGES.md
Labels: Extra Small

#1882 Prepare 0.32.0
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: Extra Small

#1883 Prepare 0.31.1
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: Extra Small

#1878 Add `IStore.PruneOutdatedChains()`
  CHANGES.md
  Libplanet.Explorer/Store/LiteDBRichStore.cs
  Libplanet.Explorer/Store/MySQLRichStore.cs
  Libplanet.RocksDBStore.Tests/RocksDBStoreTest.cs
  Libplanet.RocksDBStore/RocksDBStore.cs
  Libplanet.Tests/Store/ProxyStore.cs
  Libplanet.Tests/Store/StoreTest.cs
  Libplanet.Tests/Store/StoreTracker.cs
  Libplanet/Store/BaseStore.cs
  Libplanet/Store/DefaultStore.cs
  Libplanet/Store/IStore.cs
  Libplanet/Store/MemoryStore.cs
Labels: storage, Medium
