Repository planetarium/libplanet, pull requests merged in 2023-10, with the labels that each got.

#3437 ♻️ Immutable `IActionContext`
  CHANGES.md
  Libplanet.Action.Tests/ActionContextTest.cs
  Libplanet.Action.Tests/Common/DumbAction.cs
  Libplanet.Action.Tests/Common/RandomAction.cs
  Libplanet.Action/ActionContext.cs
  Libplanet.Action/ActionEvaluator.cs
  Libplanet.Action/CommittedActionContext.cs
  Libplanet.Action/IActionContext.cs
  Libplanet.Action/ICommittedActionContext.cs
  Libplanet.Analyzers.Tests/ActionAnalyzerTest.cs
  Libplanet.Analyzers/ActionAnalyzer.cs
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet/Blockchain/BlockChain.Evaluate.cs
  Libplanet/Blockchain/BlockChain.Swap.cs
Labels: Medium

#3438 ♻️ Partially remove `IStore`/`BlockChain` dependency from `IActionEvaluator`
  CHANGES.md
  Libplanet.Action/ActionEvaluator.cs
  Libplanet.Action/IActionEvaluator.cs
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet/Blockchain/BlockChain.Evaluate.cs
  Libplanet/Blockchain/BlockChain.Swap.cs
Labels: Small

#3439 Remove IBlockChainStates dependency; replaced with IStateStore
  CHANGES.md
  Libplanet.Action/ActionEvaluator.cs
  Libplanet.Benchmarks/AppendBlock.cs
  Libplanet.Benchmarks/BlockChain.cs
  Libplanet.Benchmarks/ProposeBlock.cs
  Libplanet.Explorer.Executable/Program.cs
  Libplanet.Explorer.Tests/GeneratedBlockChainFixture.cs
  Libplanet.Extensions.Cocona/Commands/BlockCommand.cs
  Libplanet.Net.Tests/Consensus/ConsensusReactorTest.cs
  Libplanet.Net.Tests/SwarmTest.Broadcast.cs
  Libplanet.RocksDBStore.Tests/RocksDBStoreTest.cs
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
  Libplanet.Tests/Blockchain/BlockChainTest.Append.cs
  Libplanet.Tests/Blockchain/BlockChainTest.ProposeBlock.cs
  Libplanet.Tests/Blockchain/BlockChainTest.ValidateNextBlock.cs
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet.Tests/Blockchain/Policies/BlockPolicyTest.cs
  Libplanet.Tests/Blockchain/Policies/StagePolicyTest.cs
  Libplanet.Tests/Blocks/PreEvaluationBlockTest.cs
  Libplanet.Tests/Fixtures/IntegerSet.cs
  Libplanet.Tests/Store/StoreFixture.cs
  Libplanet.Tests/Store/StoreTest.cs
  Libplanet.Tests/TestUtils.cs
  Libplanet/Blockchain/NullChainStates.cs
Labels: Medium

#3440 🔀 Libplanet 3.5.0 candidate
  CHANGES.md
  Libplanet.Action.Tests/ActionContextTest.cs
  Libplanet.Action.Tests/Common/DumbAction.cs
  Libplanet.Action.Tests/Common/RandomAction.cs
  Libplanet.Action/ActionContext.cs
  Libplanet.Action/ActionEvaluator.cs
  Libplanet.Action/CommittedActionContext.cs
  Libplanet.Action/IActionContext.cs
  Libplanet.Action/IActionEvaluator.cs
  Libplanet.Action/ICommittedActionContext.cs
  Libplanet.Analyzers.Tests/ActionAnalyzerTest.cs
  Libplanet.Analyzers/ActionAnalyzer.cs
  Libplanet.Benchmarks/AppendBlock.cs
  Libplanet.Benchmarks/BlockChain.cs
  Libplanet.Benchmarks/ProposeBlock.cs
  Libplanet.Explorer.Executable/Program.cs
  Libplanet.Explorer.Tests/GeneratedBlockChainFixture.cs
  Libplanet.Extensions.Cocona/Commands/BlockCommand.cs
  Libplanet.Net.Tests/Consensus/ConsensusReactorTest.cs
  Libplanet.Net.Tests/SwarmTest.Broadcast.cs
  Libplanet.RocksDBStore.Tests/RocksDBStoreTest.cs
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
  Libplanet.Tests/Blockchain/BlockChainTest.Append.cs
  Libplanet.Tests/Blockchain/BlockChainTest.ProposeBlock.cs
  Libplanet.Tests/Blockchain/BlockChainTest.ValidateNextBlock.cs
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet.Tests/Blockchain/Policies/BlockPolicyTest.cs
  Libplanet.Tests/Blockchain/Policies/StagePolicyTest.cs
  Libplanet.Tests/Blocks/PreEvaluationBlockTest.cs
  Libplanet.Tests/Fixtures/IntegerSet.cs
  Libplanet.Tests/Store/StoreFixture.cs
  Libplanet.Tests/Store/StoreTest.cs
  Libplanet.Tests/TestUtils.cs
  Libplanet/Blockchain/BlockChain.Evaluate.cs
  Libplanet/Blockchain/BlockChain.Swap.cs
  Libplanet/Blockchain/NullChainStates.cs
Labels: Large

#3441 🚀 Release 3.5.0
  CHANGES.md
Labels: Extra Small

#3445 ♻️ Commit from `IActionEvaluator`
  CHANGES.md
  Libplanet.Action/ActionEvaluator.cs
  Libplanet.Action/IActionEvaluator.cs
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
  Libplanet.Tests/Blockchain/BlockChainTest.Append.cs
  Libplanet.Tests/Blocks/PreEvaluationBlockTest.cs
  Libplanet.Tests/Store/StoreFixture.cs
  Libplanet/Blockchain/BlockChain.Evaluate.cs
  Libplanet/Blockchain/BlockChain.Swap.cs
  Libplanet/Blockchain/BlockChain.cs
Labels: Medium

#3457 🧹 Partial removal of `Bencodex.Types.Dictionary.GetValue<T>()` usage
  Libplanet.Types/Consensus/Validator.cs
  Libplanet.Types/Consensus/Vote.cs
  Libplanet.Types/Consensus/VoteMetadata.cs
  Libplanet/Consensus/Maj23.cs
  Libplanet/Consensus/Maj23Metadata.cs
  Libplanet/Consensus/Proposal.cs
  Libplanet/Consensus/ProposalClaim.cs
  Libplanet/Consensus/ProposalClaimMetadata.cs
  Libplanet/Consensus/ProposalMetadata.cs
  Libplanet/Consensus/VoteSetBits.cs
  Libplanet/Consensus/VoteSetBitsMetadata.cs
Labels: Medium

#3458 🧹 General refactoring to remove `Dictionary.GetValue<T>()`
  Libplanet.Action.Tests/Common/BattleResult.cs
  Libplanet.Action.Tests/Common/DumbAction.cs
  Libplanet.Action.Tests/Common/MinerReward.cs
  Libplanet.Action.Tests/Common/RandomAction.cs
  Libplanet.Action.Tests/Common/SetStatesAtBlock.cs
  Libplanet.Action.Tests/Common/SetValidator.cs
  Libplanet.Action.Tests/Common/ThrowException.cs
  Libplanet.Action/IAction.cs
  Libplanet.Store/BlockDigest.cs
  Libplanet.Tests/Store/StoreTest.cs
  Libplanet.Tests/Tx/TxMarshalerTest.cs
  Libplanet.Types/Blocks/BlockCommit.cs
  Libplanet.Types/Tx/TxMetadata.cs
Labels: Small

#3456 Add conditional exports to support cjs
  @planetarium/account-aws-kms/package.json
  @planetarium/account/package.json
  @planetarium/tx/package.json
Labels: Extra Small, js

#3459 fix import mjs to require cjs
  @planetarium/account-aws-kms/package.json
  @planetarium/account/package.json
  @planetarium/tx/package.json
Labels: Extra Small, js

#3461 Upgrade `Bencodex` to `0.16.0`
  CHANGES.md
  Libplanet.Action/Libplanet.Action.csproj
  Libplanet.Common/Libplanet.Common.csproj
  Libplanet.Crypto/Libplanet.Crypto.csproj
  Libplanet.Explorer.Tests/GraphTypes/TransactionTypeTest.cs
  Libplanet.Explorer/GraphTypes/ActionType.cs
  Libplanet.Explorer/Libplanet.Explorer.csproj
  Libplanet.Extensions.Cocona/Commands/ApvCommand.cs
  Libplanet.Store/BaseStore.cs
  Libplanet.Store/Libplanet.Store.csproj
  Libplanet.Store/Trie/MerkleTrie.Path.cs
  Libplanet.Store/Trie/MerkleTrie.cs
  Libplanet.Store/Trie/Nodes/NodeDecoder.cs
  Libplanet.Tests/Blocks/BlockMarshalerTest.cs
  Libplanet.Types/Libplanet.Types.csproj
  Libplanet.Types/Tx/TxMarshaler.cs
  Libplanet/Libplanet.csproj
Labels: Small

#3463 🚀 Release 3.7.0
  CHANGES.md
Labels: release, Extra Small

#3466 Use Nodejs 18
  .github/workflows/build.yaml
Labels: bug, ci & cd, Extra Small

#3465 🔧 Prepare 4.0.0
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: release, Extra Small

#3467 Convert planetarium/libplanet to GitHub Actions
  .github/actions/codecov/action.yml
  .github/actions/concat_files/action.yml
  .github/actions/linux_netcore_test_base/action.yml
  .github/actions/macos_netcore_test_base/action.yml
  .github/actions/netcore_build_base/action.yml
  .github/actions/netcore_test_base/action.yml
  .github/actions/ulimit/action.yml
  .github/workflows/docs.yml
  .github/workflows/main.yml
Labels: Extra Large

#3464 🔧 Prepare 3.7.1
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: release, Extra Small

#3468 Use Node 20, Update Yarn and some dependencies.
  .github/workflows/build.yaml
  .github/workflows/yarn.yaml
  .vscode/settings.json
  .yarn/plugins/@yarnpkg/plugin-typescript.cjs
  .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
  .yarn/releases/yarn-3.4.1.cjs
  .yarn/releases/yarn-4.0.1.cjs
  .yarn/sdks/typescript/lib/tsserver.js
  .yarn/sdks/typescript/lib/tsserverlibrary.js
  .yarn/sdks/typescript/lib/typescript.js
  .yarn/sdks/typescript/package.json
  .yarnrc.yml
  @planetarium/account-aws-kms/package.json
  @planetarium/account-aws-kms/src/AwsKmsAccount.ts
  @planetarium/account-aws-kms/src/crypto/browser.ts
  @planetarium/account-aws-kms/src/crypto/node.ts
  @planetarium/account-aws-kms/tsconfig.json
  @planetarium/account-aws-kms/vitest.config.ts
  @planetarium/account-web3-secret-storage/package.json
  @planetarium/account-web3-secret-storage/tsconfig.json
  @planetarium/account/package.json
  @planetarium/account/tsconfig.json
  @planetarium/tx/package.json
  @planetarium/tx/src/tx/signed.ts
  @planetarium/tx/tsconfig.json
  package.json
  rome.json
  yarn.lock
Labels: ci & cd, Medium, dependencies

#3471 🧹 Fix build warnings
  Libplanet.Action/ActionEvaluator.cs
  Libplanet.Action/State/World.cs
  Libplanet.Explorer.Tests/Queries/StateQueryTest.cs
  Libplanet/Blockchain/BlockChain.cs
Labels: Extra Small

#3472 🧹 Reorganize and cleanup `BlockChain`
  Libplanet/Blockchain/BlockChain.States.cs
  Libplanet/Blockchain/BlockChain.cs
Labels: Medium
