Repository planetarium/libplanet, pull requests merged in 2023-11, with the labels that each got.

#3473 Fix `AccountMetrics` to initialize
  Libplanet.Action/AccountMetrics.cs
  Libplanet.Action/ActionEvaluator.cs
Labels: Extra Small

#3479 🔧 Prepare 3.8.0
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: Extra Small

#3481 🧹 Use `Address.Bencoded` instead of `Address.ByteArray`
  Libplanet.Action.Tests/Common/Attack.cs
  Libplanet.Action.Tests/Common/DetectRehearsal.cs
  Libplanet.Action.Tests/Common/DumbAction.cs
  Libplanet.Action.Tests/Common/SetStatesAtBlock.cs
  Libplanet.Action.Tests/Loader/IndexedActionLoaderTest.cs
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
  Libplanet.Tests/Blocks/BlockMarshalerTest.cs
  Libplanet.Tests/Tx/TxMarshalerTest.cs
  Libplanet.Tests/Tx/TxMetadataTest.cs
  Libplanet.Types/Assets/Currency.cs
  Libplanet.Types/Blocks/BlockMarshaler.cs
  Libplanet.Types/Blocks/BlockMetadata.cs
  Libplanet.Types/Tx/TxMarshaler.cs
  Libplanet.Types/Tx/TxMetadata.cs
Labels: Small

#3482 🔨 @planetarium/tx: export encodeFungibleAssetValue
  @planetarium/tx/src/index.ts
Labels: Extra Small, js

#3485 ♻️ Remove `Rehearsal` from `IActionContext`
  CHANGES.md
  Libplanet.Action.Tests/ActionEvaluationTest.cs
  Libplanet.Action.Tests/Common/DetectRehearsal.cs
  Libplanet.Action.Tests/Common/DumbAction.cs
  Libplanet.Action.Tests/Common/ExecuteRecord.cs
  Libplanet.Action.Tests/Common/RandomAction.cs
  Libplanet.Action.Tests/Common/ThrowException.cs
  Libplanet.Action.Tests/Sys/InitializeTest.cs
  Libplanet.Action/ActionContext.cs
  Libplanet.Action/ActionEvaluator.cs
  Libplanet.Action/CommittedActionContext.cs
  Libplanet.Action/IActionContext.cs
  Libplanet.Action/ICommittedActionContext.cs
  Libplanet.Action/UnexpectedlyTerminatedActionException.cs
  Libplanet.Tests/Action/AccountDiffTest.cs
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
  Libplanet.Tests/Blockchain/Renderers/LoggedActionRendererTest.cs
  Libplanet/Blockchain/Renderers/LoggedActionRenderer.cs
Labels: Medium

#3480 ♻️ Disallow creation of new `Transaction`s with a non-empty `UpdatedAddresses`
  CHANGES.md
  Libplanet.Explorer.Tests/GeneratedBlockChainFixture.cs
  Libplanet.Extensions.Cocona.Tests/Commands/StoreCommandTest.cs
  Libplanet.Net.Tests/Consensus/ContextNonProposerTest.cs
  Libplanet.Net.Tests/Consensus/ContextTest.cs
  Libplanet.Net.Tests/SwarmTest.Preload.cs
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
  Libplanet.Tests/Blockchain/BlockChainTest.Append.cs
  Libplanet.Tests/Blockchain/BlockChainTest.Internals.cs
  Libplanet.Tests/Blockchain/BlockChainTest.ProposeBlock.cs
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet.Tests/Blocks/BlockContentTest.cs
  Libplanet.Tests/Fixtures/BlockContentFixture.cs
  Libplanet.Tests/Fixtures/IntegerSet.cs
  Libplanet.Tests/Store/StoreFixture.cs
  Libplanet.Tests/Store/StoreTest.cs
  Libplanet.Tests/Tx/TransactionExtensionsTest.cs
  Libplanet.Tests/Tx/TransactionTest.cs
  Libplanet.Tests/Tx/TxFixture.cs
  Libplanet.Tests/Tx/TxInvoiceTest.cs
  Libplanet.Tests/Tx/UnsignedTxTest.cs
  Libplanet.Types/AssemblyInfo.cs
  Libplanet.Types/Tx/ITxInvoice.cs
  Libplanet.Types/Tx/Transaction.cs
  Libplanet.Types/Tx/TxInvoice.cs
  Libplanet/Blockchain/BlockChain.cs
Labels: Extra Large

#3487 replace: use `RocksDb` instead `Planetarium.RocksDbSharp`
  .circleci/config.yml
  CHANGES.md
  Libplanet.RocksDBStore/Libplanet.RocksDBStore.csproj
  Libplanet.RocksDBStore/RocksDBStore.cs
Labels: storage, Extra Small

#3493 🧹 Remove `DumbAction` rehearsal code
  Libplanet.Action.Tests/Common/DumbAction.cs
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
  Libplanet.Tests/Blockchain/BlockChainTest.ProposeBlock.cs
  Libplanet.Tests/TestUtils.cs
  Libplanet.Tests/Tx/TransactionTest.cs
  Libplanet.Tests/Tx/TxActionListTest.cs
  Libplanet.Tests/Tx/TxInvoiceTest.cs
  Libplanet.Tests/Tx/UnsignedTxTest.cs
Labels: Medium

#3491 test: fix tests
  Libplanet.Action.Tests/ActionEvaluationTest.cs
  Libplanet.Action.Tests/Mocks/MockWorldState.cs
  Libplanet.Action.Tests/Sys/InitializeTest.cs
  Libplanet.Action.Tests/Sys/RegistryTest.cs
Labels: Extra Small

#3495 ✨ ♻️ `HashNode` caching
  CHANGES.md
  Libplanet.Action/State/AccountState.cs
  Libplanet.Action/State/AccountStateCache.cs
  Libplanet.Extensions.Cocona/Commands/MptCommand.cs
  Libplanet.Store/HashNodeCache.cs
  Libplanet.Store/Trie/MerkleTrie.cs
  Libplanet.Store/TrieStateStore.Commit.cs
  Libplanet.Store/TrieStateStore.cs
Labels: Large

#3488 ➕ introduce: `RocksDb` instance type
  CHANGES.md
  Libplanet.Common/NameValueCollectionExtensions.cs
  Libplanet.RocksDBStore.Tests/RocksDBKeyValueStoreTest.cs
  Libplanet.RocksDBStore.Tests/RocksDBStoreTest.cs
  Libplanet.RocksDBStore/RocksDBInstanceType.cs
  Libplanet.RocksDBStore/RocksDBKeyValueStore.cs
  Libplanet.RocksDBStore/RocksDBStore.cs
  Libplanet.RocksDBStore/RocksDBUtils.cs
Labels: storage, Medium

#3515 🚀 Release 3.8.0
  CHANGES.md
Labels: Extra Small

#3517 🔧 Prepare 3.9.0
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: Extra Small

#3516 🔧 Prepare 3.8.1
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: Extra Small

#3519 Fix bug on gossip denial
  CHANGES.md
  Libplanet.Net/Consensus/GossipConsensusMessageCommunicator.cs
Labels: Extra Small

#3521 Fix AccountMetrics to initialize
  CHANGES.md
  Libplanet.Action/AccountMetrics.cs
  Libplanet.Action/ActionEvaluator.cs
Labels: Extra Small

#3522 🚀 Release 3.8.1
  CHANGES.md
Labels: release, Extra Small

#3523 ♻️ Refactor random seed generation
  CHANGES.md
  Libplanet.Action/ActionEvaluator.cs
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
Labels: Medium

#3490 Workaround for yarn install fail
  package.json
Labels: Extra Small

#3526 🔀 Port 3.8.1 to 3.9.0
  CHANGES.md
  Libplanet.Action/AccountMetrics.cs
  Libplanet.Action/ActionEvaluator.cs
  Libplanet.Net/Consensus/GossipConsensusMessageCommunicator.cs
Labels: Extra Small

#3525 🔧 Prepare 3.8.2
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: release, Extra Small

#3524 Adjust timing of the state migration
  CHANGES.md
  Libplanet.Action/ActionEvaluator.cs
  Libplanet.Net.Tests/Consensus/ContextNonProposerTest.cs
  Libplanet.Net.Tests/Messages/MessageTest.cs
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
  Libplanet.Tests/Blockchain/BlockChainTest.Append.cs
  Libplanet.Tests/Blockchain/BlockChainTest.Internals.cs
  Libplanet.Tests/Blockchain/BlockChainTest.ValidateNextBlock.cs
  Libplanet.Tests/Blocks/BlockMetadataTest.cs
  Libplanet.Tests/Blocks/PreEvaluationBlockHeaderTest.cs
  Libplanet.Types/Blocks/BlockMetadata.cs
Labels: Medium

#3529 ♻️ Update `TxInvoice` specification
  CHANGES.md
  Libplanet.Tests/Tx/TxInvoiceTest.cs
  Libplanet.Types/Tx/TxInvoice.cs
Labels: Small

#3530 ♻️ `ActionEvaluator` context scoping
  CHANGES.md
  Libplanet.Action.Tests/ActionContextTest.cs
  Libplanet.Action.Tests/ActionEvaluationTest.cs
  Libplanet.Action.Tests/Sys/InitializeTest.cs
  Libplanet.Action/ActionContext.cs
  Libplanet.Action/ActionEvaluator.cs
  Libplanet.Action/IActionContext.cs
  Libplanet.Action/ITxContext.cs
  Libplanet.Action/State/Account.cs
  Libplanet.Action/State/IAccount.cs
  Libplanet.Action/TxContext.cs
  Libplanet.Explorer.Tests/Queries/StateQueryTest.cs
  Libplanet.Tests/Action/AccountDiffTest.cs
  Libplanet.Tests/Action/AccountV0Test.cs
  Libplanet.Tests/Action/AccountV1Test.cs
  Libplanet.Tests/Blockchain/Renderers/AnonymousActionRendererTest.cs
  Libplanet.Tests/Blockchain/Renderers/LoggedActionRendererTest.cs
Labels: Large

#3527 remove: useless gh action
  .github/actions/codecov/action.yml
  .github/actions/concat_files/action.yml
  .github/actions/linux_netcore_test_base/action.yml
  .github/actions/macos_netcore_test_base/action.yml
  .github/actions/netcore_build_base/action.yml
  .github/actions/netcore_test_base/action.yml
  .github/actions/ulimit/action.yml
  .github/workflows/main.yml
Labels: ci & cd, Large
