Repository planetarium/libplanet, pull requests merged in 2023-05, with the labels that each got.

#3124 🧹 Changelog
  CHANGES.md
Labels: Extra Small

#3125 Update txexecution
  CHANGES.md
  Libplanet/Blockchain/BlockChain.cs
Labels: bug, Extra Small

#3127 🧹 Remove `PreEvaluationBlock.Evaluate()`
  CHANGES.md
  Libplanet.Explorer.Tests/GeneratedBlockChainFixture.cs
  Libplanet.Net.Tests/Consensus/Context/ContextNonProposerTest.cs
  Libplanet.Net.Tests/Consensus/Context/ContextProposerValidRoundTest.cs
  Libplanet.Net.Tests/SwarmTest.Broadcast.cs
  Libplanet.Net.Tests/SwarmTest.Preload.cs
  Libplanet.Net.Tests/SwarmTest.cs
  Libplanet.Tests/Action/AccountStateDeltaImplTest.cs
  Libplanet.Tests/Action/AccountStateDeltaTest.cs
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
  Libplanet.Tests/Blockchain/BlockChainTest.Append.cs
  Libplanet.Tests/Blockchain/BlockChainTest.Internals.cs
  Libplanet.Tests/Blockchain/BlockChainTest.ValidateNextBlock.cs
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet.Tests/Blocks/PreEvaluationBlockTest.cs
  Libplanet/Blockchain/BlockChain.Evaluate.cs
  Libplanet/Blocks/PreEvaluationBlock.cs
Labels: Extra Large

#3128 Add regression test for appending hotfix
  Libplanet.Tests/Blockchain/BlockChainTest.Append.cs
Labels: Extra Small

#3129 Append index at last when appending new block
  Libplanet/Blockchain/BlockChain.cs
Labels: Extra Small

#3130 Fix index cache in RocksDBStore
  CHANGES.md
  Libplanet.RocksDBStore/RocksDBStore.cs
Labels: bug, storage, api, Extra Small

#3131 🚀 Release 1.0.1
  CHANGES.md
Labels: release, Extra Small

#3135 ♻️ Changed `IActionTypeLoader` to `IActionLoader`
  CHANGES.md
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
  Libplanet.Tests/Action/StaticActionTypeLoaderTest.cs
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet.Tests/TestUtils.cs
  Libplanet/Action/ActionEvaluator.cs
  Libplanet/Action/ActionTypeLoaderContext.cs
  Libplanet/Action/IActionLoader.cs
  Libplanet/Action/IActionTypeLoader.cs
  Libplanet/Action/PolymorphicAction.cs
  Libplanet/Action/StaticActionLoader.cs
  Libplanet/Blockchain/BlockChain.Evaluate.cs
  Libplanet/Blockchain/BlockChain.cs
Labels: Medium

#3132 Port changes from 1.0.1
  CHANGES.md
  Libplanet.RocksDBStore/RocksDBStore.cs
  Libplanet.Tests/Blockchain/BlockChainTest.Append.cs
  Libplanet/Blockchain/BlockChain.cs
Labels: Small

#3136 🔧 Filter malformed `Transaction`s when proposing `Block`s
  CHANGES.md
  Libplanet.Tests/Blockchain/BlockChainTest.ProposeBlock.cs
  Libplanet/Action/ActionEvaluator.cs
  Libplanet/Action/IActionEvaluator.cs
  Libplanet/Action/IActionLoader.cs
  Libplanet/Action/StaticActionLoader.cs
  Libplanet/Blockchain/BlockChain.ProposeBlock.cs
Labels: Medium

#3137 Fix mutation to be consumed sequentially
  CHANGES.md
  Libplanet.Net.Tests/Consensus/Context/ContextTest.cs
  Libplanet.Net/Consensus/Context.Async.cs
  Libplanet.Tests/Common/Action/DelayAction.cs
Labels: Medium

#3140 🔧 Filter malformed `Block`s from `BlockChain<T>.Append()` and `Context<T>.IsValid()`
  CHANGES.md
  Libplanet.Net.Tests/Consensus/Context/ContextNonProposerTest.cs
  Libplanet.Net/Consensus/Context.cs
  Libplanet.Tests/Action/StaticActionTypeLoaderTest.cs
  Libplanet.Tests/Blockchain/BlockChainTest.Append.cs
  Libplanet/Action/ActionEvaluator.cs
  Libplanet/Action/IActionLoader.cs
  Libplanet/Action/InvalidActionException.cs
  Libplanet/Action/StaticActionLoader.cs
  Libplanet/Blockchain/BlockChain.Evaluate.cs
  Libplanet/Blockchain/BlockChain.cs
Labels: Medium

#3141 🚀 Release 1.1.0
  CHANGES.md
Labels: Extra Small

#3142 🔧 Prepare 1.2.0
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: Extra Small

#3117 Render `IValue` action instead of `IAction`
  CHANGES.md
  Libplanet.Net.Tests/SwarmTest.Broadcast.cs
  Libplanet.Net.Tests/SwarmTest.Preload.cs
  Libplanet.Net.Tests/SwarmTest.cs
  Libplanet.Tests/Blockchain/BlockChainTest.Append.cs
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet.Tests/Blockchain/Renderers/AnonymousActionRendererTest.cs
  Libplanet.Tests/Blockchain/Renderers/AtomicActionRendererTest.cs
  Libplanet.Tests/Blockchain/Renderers/LoggedActionRendererTest.cs
  Libplanet.Tests/TestUtils.cs
  Libplanet/Blockchain/BlockChain.Swap.cs
  Libplanet/Blockchain/Renderers/AnonymousActionRenderer.cs
  Libplanet/Blockchain/Renderers/AtomicActionRenderer.cs
  Libplanet/Blockchain/Renderers/Debug/RecordingActionRenderer.cs
  Libplanet/Blockchain/Renderers/Debug/RenderRecord.cs
  Libplanet/Blockchain/Renderers/Debug/ValidatingActionRenderer.cs
  Libplanet/Blockchain/Renderers/IActionRenderer.cs
  Libplanet/Blockchain/Renderers/LoggedActionRenderer.cs
Labels: api, Medium

#3109 Limit resource usage of message handling
  CHANGES.md
  Libplanet.Explorer.Executable/Program.cs
  Libplanet.Net.Tests/Consensus/GossipTest.cs
  Libplanet.Net.Tests/NullableSemaphoreTest.cs
  Libplanet.Net.Tests/Options/HostOptionsTest.cs
  Libplanet.Net.Tests/SwarmTest.Broadcast.cs
  Libplanet.Net.Tests/SwarmTest.Fixtures.cs
  Libplanet.Net.Tests/SwarmTest.cs
  Libplanet.Net.Tests/TestUtils.cs
  Libplanet.Net.Tests/Transports/BoundPeerExtensionsTest.cs
  Libplanet.Net.Tests/Transports/NetMQTransportTest.cs
  Libplanet.Net.Tests/Transports/TransportTest.cs
  Libplanet.Net/NullableSemaphore.cs
  Libplanet.Net/Options/AppProtocolVersionOptions.cs
  Libplanet.Net/Options/BootstrapOptions.cs
  Libplanet.Net/Options/HostOptions.cs
  Libplanet.Net/Options/PreloadOptions.cs
  Libplanet.Net/Options/SwarmOptions.cs
  Libplanet.Net/Options/TaskRegulationOptions.cs
  Libplanet.Net/Options/TimeoutOptions.cs
  Libplanet.Net/Swarm.MessageHandlers.cs
  Libplanet.Net/Swarm.cs
  Libplanet.Net/Transports/NetMQTransport.cs
Labels: Large

#3151 Make `CurrencyInputType.totalSupplyTrackable` optional
  CHANGES.md
  Libplanet.Explorer.Tests/GraphTypes/CurrencyInputTypeTest.cs
  Libplanet.Explorer/GraphTypes/CurrencyInputType.cs
Labels: explorer, Small

#3149 Remove `StaticActionLoader.Create<T>()` from `BlockChain<T>`
  CHANGES.md
  Libplanet.Benchmarks/AppendBlock.cs
  Libplanet.Benchmarks/BlockChain.cs
  Libplanet.Benchmarks/ProposeBlock.cs
  Libplanet.Explorer.Tests/GeneratedBlockChainFixture.cs
  Libplanet.Explorer.Tests/Queries/StateQueryTest.cs
  Libplanet.Net.Tests/Consensus/ConsensusReactorTest.cs
  Libplanet.Net.Tests/SwarmTest.Broadcast.cs
  Libplanet.RocksDBStore.Tests/RocksDBStoreTest.cs
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
  Libplanet.Tests/Blockchain/BlockChainTest.Append.cs
  Libplanet.Tests/Blockchain/BlockChainTest.ProposeBlock.cs
  Libplanet.Tests/Blockchain/BlockChainTest.ValidateNextBlock.cs
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet.Tests/Blockchain/Policies/BlockPolicyTest.cs
  Libplanet.Tests/Blockchain/Policies/StagePolicyTest.cs
  Libplanet.Tests/Blocks/PreEvaluationBlockTest.cs
  Libplanet.Tests/Fixtures/IntegerSet.cs
  Libplanet.Tests/Store/StoreTest.cs
  Libplanet.Tests/TestUtils.cs
  Libplanet/Action/ActionEvaluator.cs
  Libplanet/AssemblyInfo.cs
  Libplanet/Blockchain/BlockChain.Evaluate.cs
  Libplanet/Blockchain/BlockChain.cs
  Libplanet/Blockchain/BlockChainStates.cs
  Libplanet/Blockchain/IBlockChainStates.cs
  Libplanet/Blockchain/NullChainStates.cs
Labels: api, Extra Large, Squash Needed, Breaking Change

#3153 🧹 Removed native tokens
  CHANGES.md
  Libplanet.Benchmarks/AppendBlock.cs
  Libplanet.Benchmarks/BlockChain.cs
  Libplanet.Benchmarks/ProposeBlock.cs
  Libplanet.Explorer.Tests/GeneratedBlockChainFixture.cs
  Libplanet.Explorer.Tests/GraphTypes/BlockPolicyTypeTest.cs
  Libplanet.Explorer.Tests/Queries/StateQueryTest.cs
  Libplanet.Explorer/GraphTypes/BlockPolicyType.cs
  Libplanet.Explorer/Queries/ExplorerQuery.cs
  Libplanet.Extensions.Cocona.Tests/BlockPolicyParamsTest.cs
  Libplanet.Extensions.Cocona/BlockPolicyParams.cs
  Libplanet.Extensions.Cocona/Commands/BlockCommand.cs
  Libplanet.Net.Tests/Consensus/ConsensusReactorTest.cs
  Libplanet.Net.Tests/SwarmTest.Broadcast.cs
  Libplanet.RocksDBStore.Tests/RocksDBStoreTest.cs
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
  Libplanet.Tests/Action/Sys/MintTest.cs
  Libplanet.Tests/Action/Sys/TransferTest.cs
  Libplanet.Tests/Blockchain/BlockChainTest.Append.cs
  Libplanet.Tests/Blockchain/BlockChainTest.ProposeBlock.cs
  Libplanet.Tests/Blockchain/BlockChainTest.ValidateNextBlock.cs
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet.Tests/Blockchain/Policies/BlockPolicyTest.cs
  Libplanet.Tests/Blockchain/Policies/StagePolicyTest.cs
  Libplanet.Tests/Blocks/PreEvaluationBlockTest.cs
  Libplanet.Tests/Fixtures/IntegerSet.cs
  Libplanet.Tests/Store/StoreFixture.cs
  Libplanet.Tests/Store/StoreTest.cs
  Libplanet.Tests/TestUtils.cs
  Libplanet/Action/ActionEvaluator.cs
  Libplanet/Action/IActionContext.cs
  Libplanet/Action/Sys/Mint.cs
  Libplanet/Action/Sys/Transfer.cs
  Libplanet/Assets/NonNativeTokenException.cs
  Libplanet/Blockchain/BlockChain.Evaluate.cs
  Libplanet/Blockchain/BlockChain.ProposeBlock.cs
  Libplanet/Blockchain/BlockChain.cs
  Libplanet/Blockchain/Policies/BlockPolicy.cs
  Libplanet/Blockchain/Policies/IBlockPolicy.cs
  Libplanet/Blockchain/Policies/NullBlockPolicy.cs
Labels: Large

#3144 feat: `UsedGas`, `AvailableGas` in `IAccountStateDelta` and more
  CHANGES.md
  Libplanet.Tests/Action/ActionContextTest.cs
  Libplanet.Tests/Action/ActionEvaluationTest.cs
  Libplanet.Tests/Action/Sys/InitializeTest.cs
  Libplanet.Tests/Action/Sys/MintTest.cs
  Libplanet.Tests/Action/Sys/TransferTest.cs
  Libplanet.Tests/Blockchain/Renderers/AnonymousActionRendererTest.cs
  Libplanet.Tests/Blockchain/Renderers/LoggedActionRendererTest.cs
  Libplanet/Action/ActionContext.cs
  Libplanet/Action/ActionEvaluator.cs
  Libplanet/Action/GasLimitExceededException.cs
  Libplanet/Action/GasLimitNegativeException.cs
  Libplanet/Action/GasMeter.cs
  Libplanet/Action/GasUseNegativeException.cs
  Libplanet/Action/IActionContext.cs
  Libplanet/Action/IGasMeter.cs
Labels: Medium, pos

#3148 Refactor `IActionLoader`
  CHANGES.md
  Libplanet.Benchmarks/AppendBlock.cs
  Libplanet.Benchmarks/BlockChain.cs
  Libplanet.Benchmarks/ProposeBlock.cs
  Libplanet.Explorer.Tests/GeneratedBlockChainFixture.cs
  Libplanet.Net.Tests/Consensus/ConsensusReactorTest.cs
  Libplanet.Net.Tests/SwarmTest.Broadcast.cs
  Libplanet.RocksDBStore.Tests/RocksDBStoreTest.cs
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
  Libplanet.Tests/Action/Loader/IndexedActionLoaderTest.cs
  Libplanet.Tests/Action/Loader/SingleActionLoaderTest.cs
  Libplanet.Tests/Action/Loader/TypedActionLoaderTest.cs
  Libplanet.Tests/Action/PolymorphicActionLoaderTest.cs
  Libplanet.Tests/Action/PolymorphicActionTest.cs
  Libplanet.Tests/Action/StaticActionTypeLoaderTest.cs
  Libplanet.Tests/Blockchain/BlockChainTest.Append.cs
  Libplanet.Tests/Blockchain/BlockChainTest.ProposeBlock.cs
  Libplanet.Tests/Blockchain/BlockChainTest.ValidateNextBlock.cs
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet.Tests/Blockchain/Policies/BlockPolicyTest.cs
  Libplanet.Tests/Blockchain/Policies/StagePolicyTest.cs
  Libplanet.Tests/Blocks/BlockHeaderTest.cs
  Libplanet.Tests/Blocks/PreEvaluationBlockTest.cs
  Libplanet.Tests/Fixtures/IntegerSet.cs
  Libplanet.Tests/Store/StoreTest.cs
  Libplanet.Tests/TestUtils.cs
  Libplanet/Action/ActionEvaluator.cs
  Libplanet/Action/IActionEvaluator.cs
  Libplanet/Action/InvalidActionException.cs
  Libplanet/Action/Loader/IActionLoader.cs
  Libplanet/Action/Loader/IndexedActionLoader.cs
  Libplanet/Action/Loader/SingleActionLoader.cs
  Libplanet/Action/Loader/TypedActionLoader.cs
  Libplanet/Action/PolymorphicAction.cs
  Libplanet/Action/PolymorphicActionLoader.cs
  Libplanet/Action/StaticActionLoader.cs
  Libplanet/Blockchain/BlockChain.Evaluate.cs
  Libplanet/Blockchain/BlockChain.cs
Labels: Extra Large, Breaking Change

#3157 🧹 Remove remaining native tokens related API
  Libplanet.Explorer.Executable/Program.cs
  Libplanet.Tests/Action/Sys/MintTest.cs
  Libplanet.Tests/Action/Sys/TransferTest.cs
  Libplanet.Tests/Store/StoreFixture.cs
  Libplanet.Tests/TestUtils.cs
  Libplanet/Action/ActionContext.cs
Labels: Extra Small

#3158 🔧 Added `ReloadLoader()` method
  CHANGES.md
  Libplanet/Action/PolymorphicAction.cs
  Libplanet/Action/PolymorphicActionLoader.cs
Labels: Extra Small

#3160 Fix @planetarium/cli installer bug on Linux/macOS & release 1.0.3
  CHANGES.md
  Libplanet.Tools/download.mjs
Labels: bug, tools, release, ci & cd, packaging, Extra Small, js

#3159 🧹 Removed Mint and Transfer actions
  CHANGES.md
  Libplanet.Explorer.Tests/GeneratedBlockChainFixture.cs
  Libplanet.Explorer.Tests/Queries/TransactionQueryTest.cs
  Libplanet.Tests/Action/Loader/TypedActionLoaderTest.cs
  Libplanet.Tests/Action/Sys/MintTest.cs
  Libplanet.Tests/Action/Sys/RegistryTest.cs
  Libplanet.Tests/Action/Sys/TransferTest.cs
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet.Tests/Tx/TransactionTest.cs
  Libplanet.Tests/Tx/TxActionListTest.cs
  Libplanet/Action/Sys/Mint.cs
  Libplanet/Action/Sys/Transfer.cs
Labels: Extra Large

#3161 Release 1.1.1 (a port of 1.0.3)
  CHANGES.md
  Libplanet.Tools/download.mjs
Labels: release, Extra Small

#3162 Port 1.0.3 & 1.1.1 to main (1.2.x)
  CHANGES.md
  Libplanet.Tools/download.mjs
Labels: Extra Small

#3164 Removed `IActionContext.GenesisHash`
  CHANGES.md
  Libplanet.Benchmarks/AppendBlock.cs
  Libplanet.Benchmarks/BlockChain.cs
  Libplanet.Benchmarks/ProposeBlock.cs
  Libplanet.Explorer.Tests/GeneratedBlockChainFixture.cs
  Libplanet.Net.Tests/Consensus/ConsensusReactorTest.cs
  Libplanet.Net.Tests/SwarmTest.Broadcast.cs
  Libplanet.RocksDBStore.Tests/RocksDBStoreTest.cs
  Libplanet.Tests/Action/ActionContextTest.cs
  Libplanet.Tests/Action/ActionEvaluationTest.cs
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
  Libplanet.Tests/Action/Sys/InitializeTest.cs
  Libplanet.Tests/Blockchain/BlockChainTest.Append.cs
  Libplanet.Tests/Blockchain/BlockChainTest.ProposeBlock.cs
  Libplanet.Tests/Blockchain/BlockChainTest.ValidateNextBlock.cs
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet.Tests/Blockchain/Policies/BlockPolicyTest.cs
  Libplanet.Tests/Blockchain/Policies/StagePolicyTest.cs
  Libplanet.Tests/Blockchain/Renderers/AnonymousActionRendererTest.cs
  Libplanet.Tests/Blockchain/Renderers/LoggedActionRendererTest.cs
  Libplanet.Tests/Blocks/PreEvaluationBlockTest.cs
  Libplanet.Tests/Fixtures/IntegerSet.cs
  Libplanet.Tests/Store/StoreTest.cs
  Libplanet.Tests/TestUtils.cs
  Libplanet/Action/ActionContext.cs
  Libplanet/Action/ActionEvaluator.cs
  Libplanet/Action/IActionContext.cs
  Libplanet/Blockchain/BlockChain.Evaluate.cs
  Libplanet/Blockchain/BlockChain.cs
Labels: Large

#3167 🚀 Release 1.2.0
  CHANGES.md
Labels: Extra Small

#3171 🔧 Prepare 1.2.1
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: Extra Small

#3170 🔧 Prepare 1.3.0
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: Extra Small

#3152 Periodic `MessageId` handling in `Gossip`
  CHANGES.md
  Libplanet.Net.Tests/Consensus/GossipTest.cs
  Libplanet.Net/Consensus/Gossip.cs
Labels: network, Medium, pbft

#3174 Fixed query for tx with actions
  CHANGES.md
  Libplanet.Explorer.Tests/GraphTypes/TransactionTypeTest.cs
  Libplanet.Explorer/GraphTypes/ActionType.cs
Labels: Extra Small

#3154 Use block sync logic on preload
  CHANGES.md
  Libplanet.Net.Tests/SwarmTest.Broadcast.cs
  Libplanet.Net.Tests/SwarmTest.Preload.cs
  Libplanet.Net/ActionExecutionState.cs
  Libplanet.Net/BlockDownloadState.cs
  Libplanet.Net/BlockHashDownloadState.cs
  Libplanet.Net/BlockSyncState.cs
  Libplanet.Net/BlockVerificationState.cs
  Libplanet.Net/StateDownloadState.cs
  Libplanet.Net/Swarm.BlockCandidate.cs
  Libplanet.Net/Swarm.BlockSync.cs
  Libplanet.Net/Swarm.cs
Labels: Extra Large

#3172 ♻️ Refactor `BlockChain<T>` constructors
  CHANGES.md
  Libplanet.Explorer.Executable/Program.cs
  Libplanet.Explorer.Tests/GeneratedBlockChainFixture.cs
  Libplanet.Extensions.Cocona/Commands/BlockCommand.cs
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
  Libplanet.Tests/Blockchain/BlockChainTest.Append.cs
  Libplanet.Tests/Blockchain/BlockChainTest.ProposeBlock.cs
  Libplanet.Tests/Blockchain/BlockChainTest.ValidateNextBlock.cs
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet.Tests/Blocks/PreEvaluationBlockTest.cs
  Libplanet.Tests/Fixtures/IntegerSet.cs
  Libplanet.Tests/Store/StoreFixture.cs
  Libplanet.Tests/Store/StoreTest.cs
  Libplanet.Tests/TestUtils.cs
  Libplanet/Blockchain/BlockChain.Evaluate.cs
  Libplanet/Blockchain/BlockChain.ProposeBlock.cs
  Libplanet/Blockchain/BlockChain.cs
Labels: Extra Large

#3183 🧹 Remove `<T>` from `Context<T>` and `ConsensusContext<T>`
  CHANGES.md
  Libplanet.Net.Tests/Consensus/ConsensusContextNonProposerTest.cs
  Libplanet.Net.Tests/Consensus/ConsensusContextProposerTest.cs
  Libplanet.Net.Tests/Consensus/ConsensusContextTest.cs
  Libplanet.Net.Tests/Consensus/ConsensusReactorTest.cs
  Libplanet.Net.Tests/Consensus/ContextNonProposerTest.cs
  Libplanet.Net.Tests/Consensus/ContextProposerTest.cs
  Libplanet.Net.Tests/Consensus/ContextProposerValidRoundTest.cs
  Libplanet.Net.Tests/Consensus/ContextTest.cs
  Libplanet.Net.Tests/Consensus/MessageLogTest.cs
  Libplanet.Net.Tests/TestUtils.cs
  Libplanet.Net/Consensus/ConsensusContext.Event.cs
  Libplanet.Net/Consensus/ConsensusContext.cs
  Libplanet.Net/Consensus/ConsensusReactor.cs
  Libplanet.Net/Consensus/ConsensusReactorOption.cs
  Libplanet.Net/Consensus/Context.Async.cs
  Libplanet.Net/Consensus/Context.Event.cs
  Libplanet.Net/Consensus/Context.Mutate.cs
  Libplanet.Net/Consensus/Context.cs
  Libplanet.Net/Consensus/ContextTimeoutOption.cs
  Libplanet.Net/Consensus/InvalidConsensusMessageException.cs
  Libplanet.Net/Consensus/InvalidHeightIncreasingException.cs
  Libplanet.Net/Consensus/MessageLog.cs
  Libplanet.Net/Messages/ConsensusMsg.cs
  Libplanet.Net/Swarm.cs
Labels: Medium

#3184 🧹 Remove `<T>` from `Swarm<T>`
  CHANGES.md
  Libplanet.Explorer.Executable/Program.cs
  Libplanet.Explorer.Tests/Queries/MockBlockChainContext.cs
  Libplanet.Explorer/Interfaces/IBlockChainContext.cs
  Libplanet.Net.Tests/BlockCandidateTableTest.cs
  Libplanet.Net.Tests/BlockCompletionTest.cs
  Libplanet.Net.Tests/SwarmTest.Broadcast.cs
  Libplanet.Net.Tests/SwarmTest.Fixtures.cs
  Libplanet.Net.Tests/SwarmTest.Preload.cs
  Libplanet.Net.Tests/SwarmTest.cs
  Libplanet.Net.Tests/Transports/BoundPeerExtensionsTest.cs
  Libplanet.Net/BlockCandidateTable.cs
  Libplanet.Net/BlockCompletion.cs
  Libplanet.Net/BlockDemand.cs
  Libplanet.Net/DifferentAppProtocolVersionEncountered.cs
  Libplanet.Net/Options/AppProtocolVersionOptions.cs
  Libplanet.Net/Options/HostOptions.cs
  Libplanet.Net/Options/SwarmOptions.cs
  Libplanet.Net/Options/TimeoutOptions.cs
  Libplanet.Net/Swarm.BlockCandidate.cs
  Libplanet.Net/Swarm.BlockSync.cs
  Libplanet.Net/Swarm.MessageHandlers.cs
  Libplanet.Net/Swarm.cs
  Libplanet.Net/Transports/DifferentAppProtocolVersionException.cs
  Libplanet.Net/TxCompletion.cs
  Libplanet/Action/ActionEvaluator.cs
Labels: Extra Large

#3185 🧹 Remove `<T>` from `Libplanet.Explorer`
  CHANGES.md
  Libplanet.Explorer.Cocona.Tests/Commands/IndexCommandTest.cs
  Libplanet.Explorer.Cocona/Commands/IndexCommand.cs
  Libplanet.Explorer.Executable/Program.cs
  Libplanet.Explorer.Tests/GraphQLTestUtils.cs
  Libplanet.Explorer.Tests/GraphTypes/BlockTypeTest.cs
  Libplanet.Explorer.Tests/GraphTypes/TransactionTypeTest.cs
  Libplanet.Explorer.Tests/Indexing/BlockChainIndexFixture.cs
  Libplanet.Explorer.Tests/Indexing/BlockChainIndexTest.cs
  Libplanet.Explorer.Tests/Indexing/IBlockChainIndexFixture.cs
  Libplanet.Explorer.Tests/Indexing/RocksDbBlockChainIndexFixture.cs
  Libplanet.Explorer.Tests/Indexing/RocksDbBlockChainIndexTest.cs
  Libplanet.Explorer.Tests/Queries/MockBlockChainContext.cs
  Libplanet.Explorer.Tests/Queries/MockBlockChainContextWithIndex.cs
  Libplanet.Explorer.Tests/Queries/StateQueryTest.cs
  Libplanet.Explorer.Tests/Queries/TransactionQueryGeneratedTest.cs
  Libplanet.Explorer.Tests/Queries/TransactionQueryGeneratedWithIndexTest.cs
  Libplanet.Explorer.Tests/Queries/TransactionQueryTest.cs
  Libplanet.Explorer.Tests/Queries/TransactionQueryWithIndexTest.cs
  Libplanet.Explorer/ExplorerStartup.cs
  Libplanet.Explorer/GraphTypes/ActionType.cs
  Libplanet.Explorer/GraphTypes/BlockType.cs
  Libplanet.Explorer/GraphTypes/NodeStateType.cs
  Libplanet.Explorer/GraphTypes/TransactionType.cs
  Libplanet.Explorer/Indexing/BlockChainIndexBase.cs
  Libplanet.Explorer/Indexing/IBlockChainIndex.cs
  Libplanet.Explorer/Indexing/IndexingService.cs
  Libplanet.Explorer/Interfaces/IBlockChainContext.cs
  Libplanet.Explorer/Mutations/TransactionMutation.cs
  Libplanet.Explorer/Queries/BlockQuery.cs
  Libplanet.Explorer/Queries/ExplorerQuery.cs
  Libplanet.Explorer/Queries/StateQuery.cs
  Libplanet.Explorer/Queries/TransactionQuery.cs
  Libplanet.Explorer/Schemas/LibplanetExplorerSchema.cs
Labels: Large, Breaking Change

#3190 🚀 Release 1.3.0
  CHANGES.md
Labels: Extra Small

#3191 🔧 Prepare 1.4.0
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: Extra Small

#3193 🧹 Remove `PolymorphicAction<T>`
  CHANGES.md
  Libplanet.Explorer.Tests/GeneratedBlockChainFixture.cs
  Libplanet.Explorer.Tests/Queries/TransactionQueryGeneratedTest.cs
  Libplanet.Explorer.Tests/SimpleAction.cs
  Libplanet.Tests/Action/Loader/IndexedActionLoaderTest.cs
  Libplanet.Tests/Action/Loader/SingleActionLoaderTest.cs
  Libplanet.Tests/Action/PolymorphicActionLoaderTest.cs
  Libplanet.Tests/Action/PolymorphicActionTest.cs
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet.Tests/Common/Action/Attack.cs
  Libplanet.Tests/Common/Action/BaseAction.cs
  Libplanet.Tests/Common/Action/DetectRehearsal.cs
  Libplanet.Tests/Common/Action/Sleep.cs
  Libplanet.Tests/Tx/TxFixture.cs
  Libplanet.Tests/Tx/TxMarshalerTest.cs
  Libplanet/Action/IAction.cs
  Libplanet/Action/MissingActionTypeException.cs
  Libplanet/Action/PolymorphicAction.cs
  Libplanet/Action/PolymorphicActionLoader.cs
  Libplanet/Tx/Transaction.cs
Labels: Extra Large, Breaking Change

#3168 🧹 Removed GetTrie() from IBlockChainStates
  CHANGES.md
  Libplanet.Tests/Action/ActionContextTest.cs
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
  Libplanet.Tests/Action/Sys/InitializeTest.cs
  Libplanet/Action/ActionContext.cs
  Libplanet/Action/ActionEvaluator.cs
  Libplanet/Action/IActionContext.cs
  Libplanet/Blockchain/BlockChain.cs
  Libplanet/Blockchain/BlockChainStates.cs
  Libplanet/Blockchain/IBlockChainStates.cs
Labels: Medium, Breaking Change

#3195 ♻️ General API cleanup for `BlockChain.Create()`
  CHANGES.md
  Libplanet.Extensions.Cocona/Commands/BlockCommand.cs
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
  Libplanet.Tests/Blockchain/BlockChainTest.ProposeBlock.cs
  Libplanet.Tests/Blockchain/BlockChainTest.ValidateNextBlock.cs
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet.Tests/Blocks/PreEvaluationBlockTest.cs
  Libplanet.Tests/Fixtures/IntegerSet.cs
  Libplanet.Tests/Store/StoreFixture.cs
  Libplanet.Tests/Store/StoreTest.cs
  Libplanet.Tests/TestUtils.cs
  Libplanet/Blockchain/BlockChain.Evaluate.cs
  Libplanet/Blockchain/BlockChain.ProposeBlock.cs
  Libplanet/Blockchain/BlockChain.cs
Labels: Small
