Repository planetarium/libplanet, pull requests merged in 2023-01, with the labels that each got.

#2687 Add unit tests related to `SetValidator` system action
  Libplanet.Tests/Action/AccountStateDeltaTest.cs
  Libplanet.Tests/Action/Sys/SetValidatorTest.cs
  Libplanet/Action/AccountStateDeltaImpl.cs
  Libplanet/Action/IAccountStateDelta.cs
Labels: Medium

#2684 Fix bugs and stabilize unit test again
  CHANGES.md
  Libplanet.Net.Tests/SwarmTest.Broadcast.cs
  Libplanet.Net/AsyncDelegate.cs
  Libplanet.Net/Libplanet.Net.csproj
  Libplanet.Net/Protocols/KademliaProtocol.cs
  Libplanet.Net/Transports/NetMQTransport.cs
  Libplanet.Net/TxCompletion.cs
Labels: network, Large

#2689 Port 0.44.7
  CHANGES.md
  Libplanet.Net.Tests/SwarmTest.Broadcast.cs
  Libplanet.Net/AsyncDelegate.cs
  Libplanet.Net/Libplanet.Net.csproj
  Libplanet.Net/Protocols/KademliaProtocol.cs
  Libplanet.Net/Transports/NetMQTransport.cs
  Libplanet.Net/TxCompletion.cs
Labels: Extra Large

#2692 Prepare 0.45.5
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: Extra Small

#2693 Introduce `AppProtocolVersionOptions`
  CHANGES.md
  Libplanet.Explorer.Executable/Program.cs
  Libplanet.Net.Tests/Messages/MessageValidatorTest.cs
  Libplanet.Net.Tests/SwarmTest.AppProtocolVersion.cs
  Libplanet.Net.Tests/SwarmTest.Fixtures.cs
  Libplanet.Net.Tests/SwarmTest.cs
  Libplanet.Net.Tests/Transports/BoundPeerExtensionsTest.cs
  Libplanet.Net.Tests/Transports/NetMQTransportTest.cs
  Libplanet.Net.Tests/Transports/TransportTest.cs
  Libplanet.Net/AppProtocolVersionOptions.cs
  Libplanet.Net/Messages/MessageValidator.cs
  Libplanet.Net/Swarm.cs
  Libplanet.Net/Transports/NetMQTransport.cs
  Libplanet.Node/NetworkConfig.cs
  Libplanet.Node/NodeConfig.cs
Labels: Large

#2694 Dynamic validator on pow
  CHANGES.md
  Libplanet.Explorer.Tests/Queries/StateQueryTest.cs
  Libplanet.Explorer/Queries/ExplorerQuery.cs
  Libplanet.Explorer/Queries/StateQuery.cs
  Libplanet.Net.Tests/SwarmTest.Preload.cs
  Libplanet.Net/Swarm.BlockSync.cs
  Libplanet.Tests/Action/AccountStateDeltaImplTest.cs
  Libplanet.Tests/Action/AccountStateDeltaImplV0Test.cs
  Libplanet.Tests/Action/AccountStateDeltaTest.cs
  Libplanet.Tests/Action/ActionContextTest.cs
  Libplanet.Tests/Action/ActionEvaluationTest.cs
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
  Libplanet.Tests/Action/Sys/MintTest.cs
  Libplanet.Tests/Action/Sys/SetValidatorTest.cs
  Libplanet.Tests/Action/Sys/TransferTest.cs
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet.Tests/Blockchain/Renderers/AnonymousActionRendererTest.cs
  Libplanet.Tests/Blockchain/Renderers/DelayedActionRendererTest.cs
  Libplanet.Tests/Blockchain/Renderers/LoggedActionRendererTest.cs
  Libplanet.Tests/Blockchain/Renderers/NonblockActionRendererTest.cs
  Libplanet.Tests/Common/Action/DumbAction.cs
  Libplanet.Tests/Consensus/ValidatorSetTest.cs
  Libplanet.Tests/Consensus/ValidatorTest.cs
  Libplanet.Tests/Fixtures/IntegerSet.cs
  Libplanet.Tests/TestUtils.cs
  Libplanet/Action/AccountStateDeltaExtensions.cs
  Libplanet/Action/AccountStateDeltaImpl.cs
  Libplanet/Action/AccountStateDeltaImplV0.cs
  Libplanet/Action/ActionEvaluationsExtensions.cs
  Libplanet/Action/ActionEvaluator.cs
  Libplanet/Action/IAccountStateDelta.cs
  Libplanet/Action/IAccountStateView.cs
  Libplanet/Action/Sys/Registry.cs
  Libplanet/Action/Sys/SetValidator.cs
  Libplanet/Action/ValidatorSetGetter.cs
  Libplanet/Blockchain/BlockChain.cs
  Libplanet/Blockchain/BlockChainStates.cs
  Libplanet/Blockchain/IBlockChainStates.cs
  Libplanet/Blockchain/KeyConverters.cs
  Libplanet/Blockchain/NullChainStates.cs
  Libplanet/Blockchain/StateCompleterSet.cs
  Libplanet/Blockchain/ValidatorSetStateCompleter.cs
  Libplanet/Blockchain/ValidatorSetStateCompleters.cs
  Libplanet/Blocks/PreEvaluationBlock.cs
  Libplanet/Consensus/Validator.cs
  Libplanet/Consensus/ValidatorSet.cs
Labels: Extra Large

#2686 Bump 0.44.7 to pbft
  CHANGES.md
  Libplanet.Net.Tests/SwarmTest.Broadcast.cs
  Libplanet.Net/AsyncDelegate.cs
  Libplanet.Net/Libplanet.Net.csproj
  Libplanet.Net/Protocols/KBucketDictionary.cs
  Libplanet.Net/Protocols/KademliaProtocol.cs
  Libplanet.Net/Swarm.MessageHandlers.cs
  Libplanet.Net/Swarm.cs
  Libplanet.Net/Transports/NetMQTransport.cs
  Libplanet.Net/TxCompletion.cs
  Libplanet.Tests/Blocks/BlockContentTest.cs
  Libplanet.Tests/Fixtures/BlockContentFixture.cs
  Libplanet.Tests/Tx/TxMetadataTest.cs
  Libplanet/Blockchain/BlockChain.cs
  Libplanet/Blockchain/BlockLocator.cs
  Libplanet/Blockchain/Policies/VolatileStagePolicy.cs
  Libplanet/Tx/TxMetadata.cs
Labels: Extra Large

#2696 Fix explorer's validators query
  Libplanet.Explorer.Tests/Queries/StateQueryTest.cs
  Libplanet.Explorer/GraphTypes/ValidatorType.cs
  Libplanet.Explorer/Queries/StateQuery.cs
Labels: Small

#2690 Port/0.45.4 & remove `workers` option for `NetMQTransport`
  CHANGES.md
  Libplanet.Explorer.Executable/Options.cs
  Libplanet.Explorer.Executable/Program.cs
  Libplanet.Net.Tests/SwarmTest.Broadcast.cs
  Libplanet.Net.Tests/SwarmTest.Fixtures.cs
  Libplanet.Net.Tests/SwarmTest.cs
  Libplanet.Net.Tests/Transports/NetMQTransportTest.cs
  Libplanet.Net/AsyncDelegate.cs
  Libplanet.Net/Libplanet.Net.csproj
  Libplanet.Net/Protocols/KademliaProtocol.cs
  Libplanet.Net/Swarm.cs
  Libplanet.Net/Transports/NetMQTransport.cs
  Libplanet.Net/TxCompletion.cs
Labels: network, Extra Large

#2699 New subcommand: `planet store chain-ids`
  CHANGES.md
  Libplanet.Extensions.Cocona/Commands/StoreCommand.cs
  Libplanet.Tools/Program.cs
Labels: storage, tools, Extra Small

#2701 Introduce `HostOptions`
  CHANGES.md
  Libplanet.Explorer.Executable/Program.cs
  Libplanet.Net.Tests/HostOptionsTest.cs
  Libplanet.Net.Tests/SwarmTest.Fixtures.cs
  Libplanet.Net.Tests/SwarmTest.cs
  Libplanet.Net.Tests/Transports/BoundPeerExtensionsTest.cs
  Libplanet.Net.Tests/Transports/NetMQTransportTest.cs
  Libplanet.Net.Tests/Transports/TransportTest.cs
  Libplanet.Net/HostOptions.cs
  Libplanet.Net/Swarm.cs
  Libplanet.Net/Transports/NetMQTransport.cs
  Libplanet.Node.Tests/SwarmConfigTest.cs
  Libplanet.Node/InitConfig.cs
  Libplanet.Node/NodeConfig.cs
Labels: Large

#2704 Show tip hash for Libplanet.Explorer.Cocona.Commands.StoreCommand.ChainIds
  Libplanet.Extensions.Cocona/Commands/StoreCommand.cs
  Libplanet.Extensions.Cocona/Utils.cs
Labels: Extra Small

#2705 Add `-P`/`--public-key` option to `planet key derive` subcommand
  CHANGES.md
  Libplanet.Extensions.Cocona/Commands/KeyCommand.cs
Labels: tools, Extra Small

#2710 ♻️ Optimize preload
  Libplanet/Blockchain/BlockChain.Swap.cs
Labels: Small

#2708 fix/transport: socket count
  CHANGES.md
  Libplanet.Net/Transports/NetMQTransport.cs
Labels: network, Small, logging

#2713 Turn recursion to iteration on `RocksDBStore.IndexBlockHash()`
  Libplanet.RocksDBStore/RocksDBStore.cs
Labels: storage, Extra Small

#2706 🧹 Cleanup preload
  Libplanet.Net/Swarm.BlockSync.cs
Labels: Medium

#2717 Modify Equals methods on Validator, ValidatorSet
  Libplanet/Action/AccountStateDeltaImpl.cs
  Libplanet/Consensus/Validator.cs
  Libplanet/Consensus/ValidatorSet.cs
Labels: Extra Small

#2718 🔧 Reduced tx lifespan from 3 hours to 10 minutes
  CHANGES.md
  Libplanet/Blockchain/Policies/VolatileStagePolicy.cs
Labels: Extra Small

#2721 Validate hostname in `BoundPeer` type
  Libplanet.Net.Tests/BoundPeerTest.cs
  Libplanet.Net.Tests/Transports/TransportTest.cs
  Libplanet.Net/BoundPeer.cs
Labels: bug, network, Extra Small

#2716 Pow dynamic validator
  CHANGES.md
  Libplanet.Explorer.Tests/Queries/StateQueryTest.cs
  Libplanet.Explorer/GraphTypes/ValidatorType.cs
  Libplanet.Explorer/Queries/StateQuery.cs
  Libplanet.Tests/Action/AccountStateDeltaImplTest.cs
  Libplanet.Tests/Action/AccountStateDeltaImplV0Test.cs
  Libplanet.Tests/Action/AccountStateDeltaTest.cs
  Libplanet.Tests/Action/ActionContextTest.cs
  Libplanet.Tests/Action/ActionEvaluationTest.cs
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
  Libplanet.Tests/Action/Sys/MintTest.cs
  Libplanet.Tests/Action/Sys/SetValidatorTest.cs
  Libplanet.Tests/Action/Sys/TransferTest.cs
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet.Tests/Blockchain/Renderers/AnonymousActionRendererTest.cs
  Libplanet.Tests/Blockchain/Renderers/DelayedActionRendererTest.cs
  Libplanet.Tests/Blockchain/Renderers/LoggedActionRendererTest.cs
  Libplanet.Tests/Blockchain/Renderers/NonblockActionRendererTest.cs
  Libplanet.Tests/Common/Action/DumbAction.cs
  Libplanet.Tests/Consensus/ValidatorSetTest.cs
  Libplanet.Tests/Consensus/ValidatorTest.cs
  Libplanet.Tests/Fixtures/IntegerSet.cs
  Libplanet.Tests/TestUtils.cs
  Libplanet/Action/AccountStateDeltaExtensions.cs
  Libplanet/Action/AccountStateDeltaImpl.cs
  Libplanet/Action/AccountStateDeltaImplV0.cs
  Libplanet/Action/ActionEvaluationsExtensions.cs
  Libplanet/Action/ActionEvaluator.cs
  Libplanet/Action/IAccountStateDelta.cs
  Libplanet/Action/IAccountStateView.cs
  Libplanet/Action/Sys/Registry.cs
  Libplanet/Action/Sys/SetValidator.cs
  Libplanet/Action/ValidatorSetGetter.cs
  Libplanet/Blockchain/BlockChain.cs
  Libplanet/Blockchain/BlockChainStates.cs
  Libplanet/Blockchain/IBlockChainStates.cs
  Libplanet/Blockchain/KeyConverters.cs
  Libplanet/Blockchain/NullChainStates.cs
  Libplanet/Blockchain/StateCompleterSet.cs
  Libplanet/Blockchain/ValidatorSetStateCompleter.cs
  Libplanet/Blockchain/ValidatorSetStateCompleters.cs
  Libplanet/Blocks/PreEvaluationBlock.cs
  Libplanet/Consensus/Validator.cs
  Libplanet/Consensus/ValidatorSet.cs
Labels: Extra Large

#2719 Fix NetMQSocket leak
  CHANGES.md
  Libplanet.Net.Tests/Transports/NetMQTransportTest.cs
  Libplanet.Net/Transports/NetMQTransport.cs
Labels: bug, network, Medium

#2584 ♻️ Refactor `BlockLocator`
  CHANGES.md
  Libplanet.Net.Tests/SwarmTest.Preload.cs
  Libplanet.Net.Tests/SwarmTest.cs
  Libplanet.Net/Swarm.cs
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet.Tests/Blockchain/BlockLocatorTest.cs
  Libplanet/Blockchain/BlockChain.cs
  Libplanet/Blockchain/BlockLocator.cs
  Libplanet/Store/IStore.cs
Labels: Large

#2724 🚀 Release 0.46.0
  CHANGES.md
Labels: Extra Small

#2725 release: prepare 0.46.1
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: release, Extra Small

#2726 release: prepare 0.47
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: release, Extra Small

#2728 Update `Validator`, `ValidatorSet` specs
  Libplanet.Net.Tests/Messages/MessageTest.cs
  Libplanet.Net/Consensus/Context.Mutate.cs
  Libplanet.Tests/Action/AccountStateDeltaTest.cs
  Libplanet.Tests/Action/ActionContextTest.cs
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
  Libplanet.Tests/Action/Sys/SetValidatorTest.cs
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet.Tests/Blocks/BlockMetadataTest.cs
  Libplanet.Tests/Blocks/PreEvaluationBlockHeaderTest.cs
  Libplanet.Tests/Common/Action/DumbAction.cs
  Libplanet.Tests/Consensus/ValidatorSetTest.cs
  Libplanet.Tests/Consensus/ValidatorTest.cs
  Libplanet.Tests/TestUtils.cs
  Libplanet/Action/AccountStateDeltaExtensions.cs
  Libplanet/Action/AccountStateDeltaImpl.cs
  Libplanet/Action/ActionEvaluationsExtensions.cs
  Libplanet/Action/IAccountStateDelta.cs
  Libplanet/Action/Sys/SetValidator.cs
  Libplanet/Consensus/Validator.cs
  Libplanet/Consensus/ValidatorSet.cs
Labels: Large

#2729 Backports the transport-related fixes from 0.46.0 to 0.45-maintenance
  CHANGES.md
  Libplanet.Net.Tests/BoundPeerTest.cs
  Libplanet.Net.Tests/Transports/NetMQTransportTest.cs
  Libplanet.Net.Tests/Transports/TransportTest.cs
  Libplanet.Net/BoundPeer.cs
  Libplanet.Net/Transports/NetMQTransport.cs
Labels: Medium

#2727 Elide duplicated prefix of paths in Web3KeyStore & Release 0.45.5
  CHANGES.md
  Libplanet/KeyStore/Web3KeyStore.cs
Labels: bug, Extra Small

#2732 Use .NET 6 & C# 10 on CLI tools
  CHANGES.md
  Libplanet.Extensions.Cocona.Tests/Commands/MptCommandTest.cs
  Libplanet.Extensions.Cocona.Tests/Commands/StatsCommandTest.cs
  Libplanet.Extensions.Cocona.Tests/Commands/StoreCommandTest.cs
  Libplanet.Extensions.Cocona.Tests/Libplanet.Extensions.Cocona.Tests.csproj
  Libplanet.Extensions.Cocona.Tests/Services/TestToolConfigurationService.cs
  Libplanet.Extensions.Cocona.Tests/UtilsTest.cs
  Libplanet.Extensions.Cocona/Commands/ApvCommand.cs
  Libplanet.Extensions.Cocona/Commands/KeyCommand.cs
  Libplanet.Extensions.Cocona/Commands/MptCommand.cs
  Libplanet.Extensions.Cocona/Commands/StatsCommand.cs
  Libplanet.Extensions.Cocona/Commands/StoreCommand.cs
  Libplanet.Extensions.Cocona/Commands/TxCommand.cs
  Libplanet.Extensions.Cocona/ConsolePasswordReader.cs
  Libplanet.Extensions.Cocona/Extensions/ICoconaLiteServiceCollectionExtensions.cs
  Libplanet.Extensions.Cocona/Libplanet.Extensions.Cocona.csproj
  Libplanet.Extensions.Cocona/PassphraseParameters.cs
  Libplanet.Extensions.Cocona/Services/IConfigurationService.cs
  Libplanet.Extensions.Cocona/Services/JsonConfigurationService.cs
  Libplanet.Extensions.Cocona/Utils.cs
  Libplanet.Tools/Libplanet.Tools.csproj
  Libplanet.Tools/Program.cs
Labels: tools, packaging, Extra Large

#2733 Remove Validator related methods from interfaces
  CHANGES.md
  Libplanet.Tests/Action/ActionContextTest.cs
  Libplanet/Action/AccountStateDeltaImpl.cs
  Libplanet/Action/IAccountStateDelta.cs
  Libplanet/Action/IAccountStateView.cs
  Libplanet/Action/IValidatorSupportStateDelta.cs
  Libplanet/Action/ValidatorStateExtensions.cs
Labels: Extra Small

#2748 🧹 Fixed typos
  CHANGES.md
Labels: Extra Small

#2753 Remove unnecessary policy for PBFT
  CHANGES.md
  Libplanet.Explorer.Executable/Program.cs
  Libplanet/Blockchain/Policies/BlockPolicy.cs
  Libplanet/Blockchain/Policies/IBlockPolicy.cs
  Libplanet/Blockchain/Policies/NullBlockPolicy.cs
Labels: Extra Small

#2743 Refactor/extract transport
  CHANGES.md
  Libplanet.Explorer.Executable/Program.cs
  Libplanet.Net.Tests/Protocols/TestTransport.cs
  Libplanet.Net.Tests/SwarmTest.Fixtures.cs
  Libplanet.Net.Tests/SwarmTest.cs
  Libplanet.Net.Tests/Transports/BoundPeerExtensionsTest.cs
  Libplanet.Net/Swarm.cs
  Libplanet.Net/Transports/ITransport.cs
  Libplanet.Net/Transports/NetMQTransport.cs
  Libplanet.Node/NodeConfig.cs
Labels: Medium

#2754 fix: Adjustment effective changes from hang in the CI research
  Libplanet.Net.Tests/Libplanet.Net.Tests.csproj
  Libplanet.Net.Tests/SwarmTest.AppProtocolVersion.cs
  Libplanet.Net.Tests/SwarmTest.Broadcast.cs
  Libplanet.Net.Tests/SwarmTest.Consensus.cs
  Libplanet.Net.Tests/SwarmTest.Fixtures.cs
  Libplanet.Net.Tests/SwarmTest.Preload.cs
  Libplanet.Net.Tests/SwarmTest.cs
  Libplanet.Net.Tests/Transports/NetMQTransportTest.cs
  Libplanet.Net.Tests/Transports/TransportTest.cs
Labels: bug, ci & cd, Extra Large

#2756 Serialize/deserialize `Block<T>` better with `System.Text.Json.JsonSerializer`
  @planetarium/tx/package.json
  @planetarium/tx/test/tx/unsigned.test.ts
  CHANGES.md
  Libplanet.Explorer/Queries/TransactionQuery.cs
  Libplanet.Extensions.Cocona/Commands/StoreCommand.cs
  Libplanet.Extensions.Cocona/Utils.cs
  Libplanet.Tests/Blockchain/BlockChainTest.MineBlock.cs
  Libplanet.Tests/Blocks/BlockMetadataTest.cs
  Libplanet.Tests/Blocks/PreEvaluationBlockHeaderTest.cs
  Libplanet.Tests/ByteUtilTest.cs
  Libplanet.Tests/Crypto/PublicKeyTest.cs
  Libplanet.Tests/JsonConverters/BigIntegerJsonConverterTest.cs
  Libplanet.Tests/JsonConverters/ByteArrayJsonConverterTest.cs
  Libplanet.Tests/NonceTest.cs
  Libplanet.Tests/Store/Trie/MerkleTriePathCursorTest.cs
  Libplanet.Tests/Store/Trie/Nodes/NodeDecoderTest.cs
  Libplanet.Tests/Store/Trie/Nodes/ShortNodeTest.cs
  Libplanet.Tests/Store/Trie/Nodes/ValueNodeTest.cs
  Libplanet.Tests/Tx/TxIdTest.cs
  Libplanet/Address.cs
  Libplanet/AssemblyInfo.cs
  Libplanet/Blocks/Block.cs
  Libplanet/Blocks/BlockHash.cs
  Libplanet/ByteUtil.cs
  Libplanet/Crypto/PublicKey.cs
  Libplanet/HashDigest.cs
  Libplanet/JsonConverters/BigIntegerJsonConverter.cs
  Libplanet/JsonConverters/ByteArrayJsonConverter.cs
  Libplanet/Nonce.cs
  Libplanet/Store/Trie/KeyBytes.cs
  Libplanet/Tx/TxId.cs
Labels: Extra Large

#2758 New subcommands to CLI: `planet block analyze` & `planet block generate-genesis`
  CHANGES.md
  Libplanet.Extensions.Cocona.Tests/BlockPolicyParamsTest.cs
  Libplanet.Extensions.Cocona.Tests/Commands/MptCommandTest.cs
  Libplanet.Extensions.Cocona.Tests/Commands/StoreCommandTest.cs
  Libplanet.Extensions.Cocona.Tests/Libplanet.Extensions.Cocona.Tests.csproj
  Libplanet.Extensions.Cocona.Tests/UtilsTest.cs
  Libplanet.Extensions.Cocona/BlockPolicyParams.cs
  Libplanet.Extensions.Cocona/Commands/ApvCommand.cs
  Libplanet.Extensions.Cocona/Commands/BlockCommand.cs
  Libplanet.Extensions.Cocona/Commands/KeyCommand.cs
  Libplanet.Tools/Program.cs
  Libplanet/Blockchain/BlockChain.cs
Labels: Large
