Repository planetarium/libplanet, pull requests merged in 2023-03, with the labels that each got.

#2873 Make `PolymorphicAction<T>._actionTypeLoader` configurable
  CHANGES.md
  Libplanet/Action/PolymorphicAction.cs
Labels: Extra Small

#2874 🧹 Logging sanitization
  CHANGES.md
  Libplanet.Net/BlockCandidateTable.cs
  Libplanet.Net/Transports/NetMQTransport.cs
  Libplanet.Tests/EnumerableMeasurementTest.cs
  Libplanet/Action/ActionEvaluator.cs
  Libplanet/Blockchain/BlockChain.Swap.cs
  Libplanet/Blockchain/BlockChain.cs
  Libplanet/Blockchain/Policies/VolatileStagePolicy.cs
  Libplanet/Store/TrieStateStore.cs
Labels: Medium

#2839 Dummy context generation to fill blockchain on test
  Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextNonProposerTest.cs
  Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextProposerTest.cs
  Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextTest.cs
  Libplanet.Net.Tests/Consensus/Context/ContextProposerTest.cs
  Libplanet.Net.Tests/Consensus/Context/ContextTest.cs
  Libplanet.Net.Tests/TestUtils.cs
  Libplanet.Tests/TestUtils.cs
Labels: Medium

#2880 🧹 General update to logging
  Libplanet.Net/Transports/NetMQTransport.cs
  Libplanet.Net/TxCompletion.cs
  Libplanet/Blockchain/Policies/VolatileStagePolicy.cs
Labels: Extra Small

#2881 🚀 Release 0.49.2
  CHANGES.md
Labels: Extra Small

#2883 🔧 Prepare 0.49.3
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: Extra Small

#2884 🔀 Port 0.49.2 to 0.50.x
  CHANGES.md
  Libplanet.Net/BlockCandidateTable.cs
  Libplanet.Net/Transports/NetMQTransport.cs
  Libplanet.Net/TxCompletion.cs
  Libplanet/Action/ActionEvaluator.cs
  Libplanet/Blockchain/Policies/VolatileStagePolicy.cs
Labels: Small

#2885 🚀 Release 0.50.1
  CHANGES.md
Labels: Extra Small

#2876 Always test @planetarium/cli install with the latest version
  .github/workflows/main.yml
Labels: bug, ci & cd, Extra Small, js

#2886 Always test @planetarium/cli install with the latest version
  .github/workflows/yarn.yaml
Labels: bug, ci & cd, Extra Small, js

#2887 🔧 Prepare 0.50.2
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: Extra Small

#2888 🔀 Port 0.50.1 to main
  Libplanet.Net/BlockCandidateTable.cs
  Libplanet.Net/Transports/NetMQTransport.cs
  Libplanet.Net/TxCompletion.cs
  Libplanet/Action/ActionEvaluator.cs
  Libplanet/Blockchain/Policies/VolatileStagePolicy.cs
Labels: Small

#2890 🧹 Minor cleanup for `DefaultStore` code comprehension
  Libplanet/Store/DefaultStore.cs
Labels: Extra Small

#2892 Fix release script
  .github/bin/dist-pack.sh
  .github/workflows/build.yaml
  .github/workflows/yarn.yaml
Labels: bug, release, ci & cd, Extra Small

#2893 Fix release script
  .github/bin/dist-pack.sh
  .github/workflows/build.yaml
Labels: bug, release, ci & cd, Extra Small

#2870 fix/pbft: parallel replying / task-switching between kademlia
  Libplanet.Net/Consensus/Gossip.cs
  Libplanet.Net/Protocols/KademliaProtocol.cs
Labels: network, Extra Small, pbft

#2896 🔧 Prepare 0.51.1
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: Extra Small

#2897 🔧 Prepare 0.52.0
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: Extra Small

#2863 Added `BlockChain<T>.Create()`
  CHANGES.md
  Libplanet.Net.Tests/Consensus/ConsensusReactorTest.cs
  Libplanet.Net.Tests/SwarmTest.Broadcast.cs
  Libplanet.RocksDBStore.Tests/RocksDBStoreTest.cs
  Libplanet.Tests/Blockchain/BlockChainTest.Append.cs
  Libplanet.Tests/Blockchain/BlockChainTest.MineBlock.cs
  Libplanet.Tests/Blockchain/BlockChainTest.ValidateNextBlock.cs
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet.Tests/Blockchain/Policies/BlockPolicyTest.cs
  Libplanet.Tests/Blockchain/Policies/StagePolicyTest.cs
  Libplanet.Tests/Blockchain/Renderers/DelayedActionRendererTest.cs
  Libplanet.Tests/Blocks/PreEvaluationBlockTest.cs
  Libplanet.Tests/Fixtures/IntegerSet.cs
  Libplanet.Tests/Store/StoreTest.cs
  Libplanet.Tests/TestUtils.cs
  Libplanet/Blockchain/BlockChain.cs
Labels: Large

#2882 `@planetarium/tx`: support tx signing / signed txs and use `Account` from `@planetarium/account`
  @planetarium/account/src/Account.ts
  @planetarium/account/src/Address.ts
  @planetarium/account/src/PublicKey.ts
  @planetarium/account/src/index.ts
  @planetarium/account/test/Account.test.ts
  @planetarium/account/test/Address.test.ts
  @planetarium/account/test/PublicKey.test.ts
  @planetarium/account/test/RawPrivateKey.test.ts
  @planetarium/account/test/setup.ts
  @planetarium/account/tsconfig.json
  @planetarium/tx/package.json
  @planetarium/tx/src/bytes.ts
  @planetarium/tx/src/tx/index.ts
  @planetarium/tx/src/tx/signed.ts
  @planetarium/tx/src/tx/unsigned.ts
  @planetarium/tx/test/address.test.ts
  @planetarium/tx/test/blockhash.test.ts
  @planetarium/tx/test/key.test.ts
  @planetarium/tx/test/tx/fixtures.ts
  @planetarium/tx/test/tx/signed.test.ts
  CHANGES.md
  package.json
  rome.json
  yarn.lock
Labels: Extra Large

#2875 Cherry-pick `Make PolymorphicAction<T>._actionTypeLoader configurable`
  CHANGES.md
  Libplanet/Action/PolymorphicAction.cs
Labels: Extra Small

#2899 ♻️ Remove side effects from `BlockChain<T>()`
  CHANGES.md
  Libplanet/Blockchain/BlockChain.cs
Labels: Medium

#2902 ci/bench: benchmark for branches
  .github/workflows/benchmarks-merged.yml
  .github/workflows/benchmarks-pr.yml
  Libplanet.Benchmarks/AppendBlock.cs
  Libplanet.Benchmarks/BlockChain.cs
  Libplanet.Benchmarks/ProposeBlock.cs
Labels: ci & cd, Extra Small

#2904 ci/bench: use trigger branch/tag name as directory [skip changelog]
  .github/workflows/benchmarks-merged.yml
Labels: ci & cd

#2901 Release 0.50.2
  CHANGES.md
Labels: release, Extra Small

#2908 ci/bench: cherrypick of bench pr update to 0.47-maintenance
  .github/workflows/benchmarks-merged.yml
  .github/workflows/benchmarks-pr.yml
Labels: ci & cd

#2910 ci/bench: missing cherry pick in 2908
  .github/workflows/benchmarks-merged.yml
Labels: ci & cd

#2909 ci/bench: cherrypick of bench pr update to 0.48-maintenance
  .github/workflows/benchmarks-merged.yml
  .github/workflows/benchmarks-pr.yml
Labels: ci & cd

#2911 ci/bench: cherrypick of bench pr update to 0.46-maintenance
  .github/workflows/benchmarks-merged.yml
  .github/workflows/benchmarks-pr.yml
Labels: ci & cd

#2912 ci/bench: cherrypick of bench pr update to 0.49-maintenance
  .github/workflows/benchmarks-merged.yml
  .github/workflows/benchmarks-pr.yml
Labels: ci & cd

#2913 ci/bench: cherrypick of bench pr update to 0.51-maintenance
  .github/workflows/benchmarks-merged.yml
  .github/workflows/benchmarks-pr.yml
Labels: ci & cd

#2905 ci/bench: cherrypick of bench pr update to 0.50-maintenance
  .github/workflows/benchmarks-merged.yml
  .github/workflows/benchmarks-pr.yml
Labels: ci & cd, Extra Small

#2917 Fix ActionExecutionState total count
  Libplanet.Net/Swarm.BlockSync.cs
Labels: Extra Small

#2918 🚀 Release 0.51.1
  CHANGES.md
Labels: Extra Small

#2920 Fix typo 0.51.1
  CHANGES.md
Labels: Extra Small

#2894 ♻️ Refactor block commit cache
  CHANGES.md
  Libplanet.Explorer/Store/LiteDBRichStore.cs
  Libplanet.Explorer/Store/MySQLRichStore.cs
  Libplanet.Net/Swarm.BlockSync.cs
  Libplanet.RocksDBStore/RocksDBStore.cs
  Libplanet.Tests/Blockchain/BlockChainTest.Append.cs
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet.Tests/Store/ProxyStore.cs
  Libplanet.Tests/Store/StoreTracker.cs
  Libplanet/Blockchain/BlockChain.cs
  Libplanet/Store/BaseStore.cs
  Libplanet/Store/DefaultStore.cs
  Libplanet/Store/IStore.cs
  Libplanet/Store/MemoryStore.cs
Labels: Medium

#2922 🔧 Prepare 0.51.2
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: release, Extra Small

#2921 Merge 0.51.1 to main
  CHANGES.md
  Libplanet.Net/Swarm.BlockSync.cs
Labels: release, Extra Small

#2919 🚀 Release 0.52.0
  CHANGES.md
Labels: Extra Small

#2925 🔧 Prepare 0.53.0
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: Extra Small

#2703 Remove StateCompleters
  CHANGES.md
  Libplanet.Explorer.Tests/Queries/StateQueryTest.cs
  Libplanet.Explorer/Queries/ExplorerQuery.cs
  Libplanet.Explorer/Queries/StateQuery.cs
  Libplanet.Net/Swarm.BlockCandidate.cs
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
  Libplanet.Tests/Blockchain/BlockChainTest.MineBlock.cs
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet/Action/ActionEvaluator.cs
  Libplanet/Action/StaticActionTypeLoader.cs
  Libplanet/Blockchain/BlockChain.Recalculate.cs
  Libplanet/Blockchain/BlockChain.Swap.cs
  Libplanet/Blockchain/BlockChain.cs
  Libplanet/Blockchain/BlockChainStates.cs
  Libplanet/Blockchain/FungibleAssetStateCompleter.cs
  Libplanet/Blockchain/FungibleAssetStateCompleters.cs
  Libplanet/Blockchain/IBlockChainStates.cs
  Libplanet/Blockchain/NullChainStates.cs
  Libplanet/Blockchain/Renderers/Debug/ValidatingActionRenderer.cs
  Libplanet/Blockchain/StateCompleter.cs
  Libplanet/Blockchain/StateCompleterSet.cs
  Libplanet/Blockchain/StateCompleters.cs
  Libplanet/Blockchain/TotalSupplyStateCompleter.cs
  Libplanet/Blockchain/TotalSupplyStateCompleters.cs
  Libplanet/Blockchain/ValidatorSetStateCompleter.cs
  Libplanet/Blockchain/ValidatorSetStateCompleters.cs
  Libplanet/Blocks/PreEvaluationBlock.cs
  Libplanet/Tx/Transaction.cs
Labels: Extra Large

#2927 ♻️🚀 Updated `Validator` bencoding and release 0.46.3
  CHANGES.md
  Libplanet.Tests/Action/Sys/SetValidatorTest.cs
  Libplanet/Consensus/Validator.cs
Labels: Extra Small

#2929 🔀🚀 Port 0.46.2 and 0.46.3 to 0.47.1 and release 0.47.1
  CHANGES.md
  Libplanet.Net/Swarm.BlockSync.cs
  Libplanet.Tests/Action/Sys/SetValidatorTest.cs
  Libplanet/Consensus/Validator.cs
Labels: Small

#2931 🔀🚀 Port 0.47.1 to 0.48.1 and release 0.48.1
  CHANGES.md
  Libplanet.Net/Swarm.BlockSync.cs
  Libplanet.Tests/Action/Sys/SetValidatorTest.cs
  Libplanet/Consensus/Validator.cs
Labels: Small

#2937 🔀 Port 0.50.3 to 0.51.2
  CHANGES.md
  Libplanet.Net.Tests/Messages/MessageTest.cs
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
  Libplanet.Tests/Action/Sys/SetValidatorTest.cs
  Libplanet.Tests/Blocks/BlockMetadataTest.cs
  Libplanet.Tests/Blocks/PreEvaluationBlockHeaderTest.cs
  Libplanet/Consensus/Validator.cs
Labels: Small

#2889 Use @planetarium/bencodex instead of disjukr/bencodex
  @planetarium/account/package.json
  @planetarium/tx/package.json
  @planetarium/tx/src/action.ts
  @planetarium/tx/src/address.ts
  @planetarium/tx/src/assets.ts
  @planetarium/tx/src/blockhash.ts
  @planetarium/tx/src/key.ts
  @planetarium/tx/src/tx/metadata.ts
  @planetarium/tx/src/tx/signed.ts
  @planetarium/tx/src/tx/unsigned.ts
  @planetarium/tx/test/__snapshots__/action.test.ts.snap
  @planetarium/tx/test/__snapshots__/assets.test.ts.snap
  @planetarium/tx/test/action.test.ts
  @planetarium/tx/test/address.test.ts
  @planetarium/tx/test/assets.test.ts
  @planetarium/tx/test/blockhash.test.ts
  @planetarium/tx/test/key.test.ts
  @planetarium/tx/test/setup.ts
  @planetarium/tx/test/tx/__snapshots__/metadata.test.ts.snap
  @planetarium/tx/test/tx/metadata.test.ts
  @planetarium/tx/test/tx/signed.test.ts
  @planetarium/tx/test/tx/unsigned.test.ts
  @planetarium/tx/vitest.config.ts
  CHANGES.md
  yarn.lock
Labels: api, Extra Large, js

#2938 ♻️ Refactor `BlockCommit` encoding
  CHANGES.md
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
  Libplanet/Blocks/BlockCommit.cs
Labels: Extra Small

#2943 ♻️ Updated `Vote.Encoded` and `Proposal.Encoded`
  CHANGES.md
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
  Libplanet/Consensus/Proposal.cs
  Libplanet/Consensus/ProposalMetadata.cs
  Libplanet/Consensus/Vote.cs
  Libplanet/Consensus/VoteMetadata.cs
Labels: Extra Small

#2944 🚀 Release 0.51.2
  CHANGES.md
Labels: Extra Small

#2946 🔀🚀 Port 0.51.2 to 0.52.1 and release 0.52.1
  CHANGES.md
  Libplanet.Net.Tests/Messages/MessageTest.cs
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
  Libplanet.Tests/Action/Sys/SetValidatorTest.cs
  Libplanet.Tests/Blocks/BlockMetadataTest.cs
  Libplanet.Tests/Blocks/PreEvaluationBlockHeaderTest.cs
  Libplanet/Blocks/BlockCommit.cs
  Libplanet/Consensus/Proposal.cs
  Libplanet/Consensus/ProposalMetadata.cs
  Libplanet/Consensus/Validator.cs
  Libplanet/Consensus/Vote.cs
  Libplanet/Consensus/VoteMetadata.cs
Labels: Medium

#2947 🔧 Prepare 0.52.2
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: Extra Small

#2936 🔧 Prepare 0.50.4
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: Extra Small

#2949 ♻️ Changed validator power to use Integer instead of Binary
  CHANGES.md
  Libplanet.Tests/Action/Sys/SetValidatorTest.cs
  Libplanet/Consensus/Validator.cs
Labels: Extra Small

#2948 🔀 Port 0.52.1 to main
  CHANGES.md
  Libplanet.Net.Tests/Messages/MessageTest.cs
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
  Libplanet.Tests/Action/Sys/SetValidatorTest.cs
  Libplanet.Tests/Blocks/BlockMetadataTest.cs
  Libplanet.Tests/Blocks/PreEvaluationBlockHeaderTest.cs
  Libplanet/Blocks/BlockCommit.cs
  Libplanet/Consensus/Proposal.cs
  Libplanet/Consensus/ProposalMetadata.cs
  Libplanet/Consensus/Validator.cs
  Libplanet/Consensus/Vote.cs
  Libplanet/Consensus/VoteMetadata.cs
Labels: Medium

#2950 🚀 Release 0.50.4
  CHANGES.md
Labels: Extra Small

#2952 🔀 Port 0.50.4 to main
  CHANGES.md
  Libplanet.Net.Tests/Messages/MessageTest.cs
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
  Libplanet.Tests/Action/Sys/SetValidatorTest.cs
  Libplanet.Tests/Blocks/BlockMetadataTest.cs
  Libplanet.Tests/Blocks/PreEvaluationBlockHeaderTest.cs
  Libplanet/Consensus/Validator.cs
Labels: Extra Small

#2951 🔧 Prepare 0.50.5
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: Extra Small

#2954 ♻️ `IBencodable` `Validator` and `ValidatorSet`
  CHANGES.md
  Libplanet.Tests/Action/Sys/SetValidatorTest.cs
  Libplanet.Tests/Consensus/ValidatorTest.cs
  Libplanet/Action/AccountStateDeltaExtensions.cs
  Libplanet/Action/ActionEvaluationsExtensions.cs
  Libplanet/Action/Sys/SetValidator.cs
  Libplanet/Consensus/Validator.cs
  Libplanet/Consensus/ValidatorSet.cs
Labels: Small

#2955 ♻️ `IBencodable` `BlockCommit`
  CHANGES.md
  Libplanet/Blocks/BlockCommit.cs
  Libplanet/Consensus/Validator.cs
  Libplanet/Consensus/ValidatorSet.cs
Labels: Extra Small

#2959 ♻️ `IBencodable` for `BlockHash`
  CHANGES.md
  Libplanet.Tests/Blocks/BlockHashTest.cs
  Libplanet/Blocks/BlockCommit.cs
  Libplanet/Blocks/BlockHash.cs
  Libplanet/Blocks/BlockMarshaler.cs
  Libplanet/Consensus/VoteMetadata.cs
  Libplanet/Tx/TxMetadata.cs
Labels: Extra Small

#2966 🚀 Release 0.50.5
  CHANGES.md
  Libplanet.Net/Transports/BoundPeerExtensions.cs
Labels: release, Extra Small

#2961 ♻️ `IBencodable` for `VoteMetadata` and `Vote`
  CHANGES.md
  Libplanet/Blocks/BlockCommit.cs
  Libplanet/Consensus/Vote.cs
  Libplanet/Consensus/VoteMetadata.cs
Labels: Small

#2970 ♻️ Refactor `Block<T>.LastCommit` encoding
  CHANGES.md
  Libplanet.Benchmarks/Commit.cs
  Libplanet.Net/Messages/ConsensusPreCommitMsg.cs
  Libplanet.Net/Messages/ConsensusPreVoteMsg.cs
  Libplanet.Net/Swarm.MessageHandlers.cs
  Libplanet.Net/Swarm.cs
  Libplanet.RocksDBStore/RocksDBStore.cs
  Libplanet.Tests/Blockchain/BlockChainTest.MineBlock.cs
  Libplanet.Tests/Blocks/BlockCommitTest.cs
  Libplanet.Tests/Blocks/BlockMarshalerTest.cs
  Libplanet.Tests/Consensus/VoteMetadataTest.cs
  Libplanet.Tests/Consensus/VoteTest.cs
  Libplanet/Blocks/BlockCommit.cs
  Libplanet/Blocks/BlockMarshaler.cs
  Libplanet/Consensus/Vote.cs
  Libplanet/Consensus/VoteMetadata.cs
  Libplanet/Store/DefaultStore.cs
Labels: Medium

#2965 🔧 Prepare 0.51.4
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: Extra Small

#2967 🔧 Prepare 0.50.6
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: release, Extra Small

#2972 Remove SetValidator action & Make `ValidatorStateExtensions` to public
  CHANGES.md
  Libplanet.Tests/Action/Sys/SetValidatorTest.cs
  Libplanet/Action/Sys/Registry.cs
  Libplanet/Action/Sys/SetValidator.cs
  Libplanet/Action/ValidatorStateExtensions.cs
Labels: consensus, Medium, pbft

#2974 🚀 Release 0.50.6
  CHANGES.md
Labels: Extra Small

#2566 Introduce `IFeeCalculator`
  CHANGES.md
  Libplanet.Explorer.Executable/Program.cs
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
  Libplanet/Action/ActionEvaluator.cs
  Libplanet/Action/IFeeCalculator.cs
  Libplanet/Blockchain/BlockChain.cs
  Libplanet/Blockchain/Policies/BlockPolicy.cs
  Libplanet/Blockchain/Policies/IBlockPolicy.cs
  Libplanet/Blockchain/Policies/NullBlockPolicy.cs
  Libplanet/Blocks/PreEvaluationBlock.cs
Labels: Small

#2962 @planetarium/account-aws-kms
  .github/bin/constants.sh
  .github/workflows/benchmarks-merged.yml
  .github/workflows/benchmarks-pr.yml
  .github/workflows/build.yaml
  .github/workflows/check-build.yaml
  .github/workflows/delete-old-artifacts.yml
  .github/workflows/main.yml
  .github/workflows/push-docker-image.yml
  .github/workflows/rebase.yml
  .github/workflows/yarn.yaml
  .vscode/extensions.json
  @planetarium/account-aws-kms/.gitignore
  @planetarium/account-aws-kms/CONTRIBUTING.md
  @planetarium/account-aws-kms/README.md
  @planetarium/account-aws-kms/examples/cli.ts
  @planetarium/account-aws-kms/package.json
  @planetarium/account-aws-kms/src/AwsKmsAccount.ts
  @planetarium/account-aws-kms/src/AwsKmsKeyId.ts
  @planetarium/account-aws-kms/src/AwsKmsKeyStore.ts
  @planetarium/account-aws-kms/src/AwsKmsMetadata.ts
  @planetarium/account-aws-kms/src/asn1.ts
  @planetarium/account-aws-kms/src/index.ts
  @planetarium/account-aws-kms/test/AwsKmsKeyStore.test.ts
  @planetarium/account-aws-kms/test/asn1.test.ts
  @planetarium/account-aws-kms/tsconfig.json
  @planetarium/account-aws-kms/vitest.config.ts
  @planetarium/account/src/PublicKey.ts
  @planetarium/account/src/Signature.ts
  @planetarium/account/test/Signature.test.ts
  CHANGES.md
  package.json
  yarn.lock
Labels: Extra Large

#2978 ♻️ Added additional metrics to measure evaluation duration
  Libplanet/Action/ActionEvaluator.cs
Labels: Extra Small

#2979 Add time measure for `AccountStateDeltaImpl.GetState()` method
  Libplanet/Action/AccountStateDeltaImpl.cs
  Libplanet/Action/ActionEvaluator.cs
Labels: Extra Small

#2980 Remove unused logic
  Libplanet/Blockchain/BlockChain.Recalculate.cs
Labels: Small

#2971 Get rid of Libplanet.Node
  CHANGES.md
  CONTRIBUTING.md
  Docs/docfx.json
  Libplanet.Node.Tests/Libplanet.Node.Tests.csproj
  Libplanet.Node.Tests/NodeUtilsTest.cs
  Libplanet.Node.Tests/SwarmConfigTest.cs
  Libplanet.Node.Tests/UntypedBlockTest.cs
  Libplanet.Node.Tests/UntypedTransactionTest.cs
  Libplanet.Node.Tests/xunit.runner.mono.json
  Libplanet.Node/BootstrapConfig.cs
  Libplanet.Node/InitConfig.cs
  Libplanet.Node/Libplanet.Node.csproj
  Libplanet.Node/NetworkConfig.cs
  Libplanet.Node/NodeConfig.cs
  Libplanet.Node/NodeUtils.cs
  Libplanet.Node/PreloadConfig.cs
  Libplanet.Node/SwarmConfig.cs
  Libplanet.Node/SyncConfig.cs
  Libplanet.Node/UntypedBlock.cs
  Libplanet.Node/UntypedTransaction.cs
  Libplanet.sln
  Libplanet/AssemblyInfo.cs
Labels: packaging, api, Extra Large, ux

#2981 🔧 Added logging info
  Libplanet/Action/AccountStateDeltaImpl.cs
Labels: Extra Small

#2983 🔧 Added state caching
  Libplanet/Blockchain/BlockChainStates.cs
Labels: Extra Small

#2985 🔧 Added caching to `AccountStateDeltaImpl`
  Libplanet/Action/AccountStateDeltaImpl.cs
  Libplanet/Blockchain/BlockChainStates.cs
Labels: Small

#2977 Flatten `ITxMetadata`/`ITxExcerpt` into `ITransaction`
  .vscode/settings.json
  CHANGES.md
  Libplanet.Explorer/Queries/TransactionQuery.cs
  Libplanet.Tests/Tx/TxMetadataTest.cs
  Libplanet.sln.DotSettings
  Libplanet/Action/ActionEvaluator.cs
  Libplanet/Tx/ITransaction.cs
  Libplanet/Tx/ITxExcerpt.cs
  Libplanet/Tx/ITxMetadata.cs
  Libplanet/Tx/Transaction.cs
  Libplanet/Tx/TransactionExtensions.cs
  Libplanet/Tx/TxMetadata.cs
Labels: Small

#2988 ♻️ Reduced call to lower level `GetStates()` with empty addresses
  Libplanet/Action/AccountStateDeltaImpl.cs
Labels: Extra Small

#2990 ♻️ Improved `KeyConverters` performance
  Libplanet/Blockchain/KeyConverters.cs
Labels: Extra Small

#2991 ♻️ Remove state delta cache
  Libplanet/Action/AccountStateDeltaImpl.cs
Labels: Extra Small

#2992 🔧 Cache during commit
  Libplanet/Blockchain/BlockChain.cs
  Libplanet/Blockchain/BlockChainStates.cs
Labels: Extra Small

#2993 ⏪ Revert set state cache
  Libplanet/Blockchain/BlockChain.cs
  Libplanet/Blockchain/BlockChainStates.cs
Labels: Extra Small

#2994 ⚡ Introduce `StateCache`
  Libplanet/Blockchain/BlockChain.cs
  Libplanet/Blockchain/BlockChainStates.cs
  Libplanet/Blockchain/StateCache.cs
Labels: Medium

#2995 🔧 Fixed improper cache fetching
  Libplanet/Blockchain/StateCache.cs
Labels: Extra Small

#2997 🚀 Release 0.53.0
  CHANGES.md
Labels: Extra Small

#2984 🚀 Prepare 0.50.7
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: Extra Small

#2975 🔀 Port 0.50.6 to 0.51.4
  CHANGES.md
  Libplanet.Net.Tests/Messages/MessageTest.cs
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
  Libplanet.Tests/Action/Sys/InitializeTest.cs
  Libplanet.Tests/Action/Sys/SetValidatorTest.cs
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet.Tests/Blocks/BlockMetadataTest.cs
  Libplanet.Tests/Blocks/PreEvaluationBlockHeaderTest.cs
  Libplanet.Tests/Common/Action/SetValidator.cs
  Libplanet.Tests/Fixtures/BlockContentFixture.cs
  Libplanet.Tests/TestUtils.cs
  Libplanet/Action/Sys/Initialize.cs
  Libplanet/Action/Sys/Registry.cs
  Libplanet/Action/ValidatorStateExtensions.cs
Labels: Large

#2976 🔀 Port 0.50.6 to 0.52.2
  CHANGES.md
  Libplanet.Net.Tests/Messages/MessageTest.cs
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
  Libplanet.Tests/Action/Sys/InitializeTest.cs
  Libplanet.Tests/Action/Sys/SetValidatorTest.cs
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet.Tests/Blocks/BlockMetadataTest.cs
  Libplanet.Tests/Blocks/PreEvaluationBlockHeaderTest.cs
  Libplanet.Tests/Common/Action/SetValidator.cs
  Libplanet.Tests/Fixtures/BlockContentFixture.cs
  Libplanet.Tests/TestUtils.cs
  Libplanet/Action/Sys/Initialize.cs
  Libplanet/Action/Sys/Registry.cs
  Libplanet/Action/ValidatorStateExtensions.cs
Labels: Large

#2999 Add `GetState` measurement for single action execution
  Libplanet/Action/AccountStateDeltaImpl.cs
  Libplanet/Action/ActionContext.cs
  Libplanet/Action/ActionEvaluator.cs
Labels: Extra Small

#3001 🚀 Release 0.51.4
  CHANGES.md
Labels: release

#3002 🔧 Prepare 0.51.4
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: release

#3004 🚀 Release 0.52.2
  CHANGES.md
Labels: release

#3005 🔧 Prepare 0.52.3
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: release

#2964 🔀 Port 0.51.3 to main
  CHANGES.md
  Libplanet.Net/Transports/BoundPeerExtensions.cs
Labels: Extra Small

#3008 Fix build and upload artifacts
  .circleci/config.yml
  .github/bin/constants.sh
Labels: bug, ci & cd

#3010 🔀 Port 0.50.6 to 0.53.1
  CHANGES.md
  Libplanet.Net.Tests/Messages/MessageTest.cs
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
  Libplanet.Tests/Action/Sys/InitializeTest.cs
  Libplanet.Tests/Action/Sys/SetValidatorTest.cs
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet.Tests/Blocks/BlockMetadataTest.cs
  Libplanet.Tests/Blocks/PreEvaluationBlockHeaderTest.cs
  Libplanet.Tests/Common/Action/SetValidator.cs
  Libplanet.Tests/Fixtures/BlockContentFixture.cs
  Libplanet.Tests/TestUtils.cs
  Libplanet/Action/Sys/Initialize.cs
  Libplanet/Action/Sys/Registry.cs
  Libplanet/Action/Sys/SetValidator.cs
Labels: release

#3012 🔧 Prepare 0.53.2
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: release

#3014 🔀 Port 0.51.4 to main
  CHANGES.md
  Libplanet.Net.Tests/Messages/MessageTest.cs
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
  Libplanet.Tests/Action/Sys/InitializeTest.cs
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet.Tests/Blocks/BlockMetadataTest.cs
  Libplanet.Tests/Blocks/PreEvaluationBlockHeaderTest.cs
  Libplanet.Tests/Common/Action/SetValidator.cs
  Libplanet.Tests/Fixtures/BlockContentFixture.cs
  Libplanet.Tests/TestUtils.cs
  Libplanet/Action/Sys/Initialize.cs
  Libplanet/Action/Sys/Registry.cs
Labels: release

#3015 🔀 Port 0.52.2 to main
  CHANGES.md
  Libplanet.Net.Tests/Messages/MessageTest.cs
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet.Tests/Blocks/BlockMetadataTest.cs
  Libplanet.Tests/Blocks/PreEvaluationBlockHeaderTest.cs
Labels: release

#3016 🔀 Port 0.53.1 to main
  CHANGES.md
Labels: release

#3009 Add measure metric for `GetState` method
  Libplanet/Action/AccountStateDeltaImpl.cs
  Libplanet/Action/ActionContext.cs
  Libplanet/Action/ActionEvaluator.cs
Labels: Extra Small

#3018 ⚡ Introduce `ChainStateCache`
  CHANGES.md
  Libplanet/Blockchain/BlockChainStates.cs
  Libplanet/Blockchain/ChainStateCache.cs
Labels: Small

#3019 ⚡ Parallel get states
  Libplanet/Blockchain/BlockChainStates.cs
Labels: Extra Small

#3017 Make `IValidatorSupportStateDelta` to public
  CHANGES.md
  Libplanet/Action/IValidatorSupportStateDelta.cs
Labels: Extra Small, pbft

#3020 🚀 Release 0.50.7
  CHANGES.md
Labels: release, Extra Small

#3022 🔀 Port 0.50.7 to 0.53.2
  CHANGES.md
  Libplanet/Action/AccountStateDeltaImpl.cs
  Libplanet/Action/ActionContext.cs
  Libplanet/Action/ActionEvaluator.cs
  Libplanet/Action/IValidatorSupportStateDelta.cs
  Libplanet/Blockchain/BlockChain.cs
  Libplanet/Blockchain/BlockChainStates.cs
  Libplanet/Blockchain/ChainStateCache.cs
  Libplanet/Blockchain/KeyConverters.cs
  Libplanet/ByteUtil.cs
Labels: release, Large

#3027 Add missing commit
  CHANGES.md
  Libplanet/Action/ValidatorStateExtensions.cs
Labels: Extra Small

#3029 Get new parameter for `BlockChain<T>.Create()`
  CHANGES.md
  Libplanet/Blockchain/BlockChain.cs
Labels: Extra Small

#3031 🔧 Prepare 0.53.3
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: release

#2986 Introduce `TxInvoice` and `UnsignedTx`
  @planetarium/tx/test/tx/signed.test.ts
  @planetarium/tx/test/tx/unsigned.test.ts
  CHANGES.md
  Libplanet.Explorer.Tests/Queries/TransactionQueryTest.cs
  Libplanet.Explorer/GraphTypes/TransactionType.cs
  Libplanet.Explorer/Queries/TransactionQuery.cs
  Libplanet.Extensions.Cocona/Commands/TxCommand.cs
  Libplanet.Net.Tests/Messages/NetMQMessageCodecTest.cs
  Libplanet.Net/Swarm.MessageHandlers.cs
  Libplanet.RocksDBStore/RocksDBStore.cs
  Libplanet.Tests/Action/Sys/RegistryTest.cs
  Libplanet.Tests/Blocks/BlockContentTest.cs
  Libplanet.Tests/Blocks/BlockMarshalerTest.cs
  Libplanet.Tests/Blocks/BlockTest.cs
  Libplanet.Tests/Fixtures/BlockContentFixture.cs
  Libplanet.Tests/TestUtils.cs
  Libplanet.Tests/TransactionExtensions.cs
  Libplanet.Tests/Tx/TransactionExtensionsTest.cs
  Libplanet.Tests/Tx/TransactionTest.cs
  Libplanet.Tests/Tx/TxActionListTest.cs
  Libplanet.Tests/Tx/TxCustomActionListTest.cs
  Libplanet.Tests/Tx/TxInvoiceTest.cs
  Libplanet.Tests/Tx/TxMarshalerTest.cs
  Libplanet.Tests/Tx/TxMetadataTest.cs
  Libplanet.Tests/Tx/TxSigningMetadataTest.cs
  Libplanet.Tests/Tx/TxSigningMetadataTest.ts
  Libplanet.Tests/Tx/TxSystemActionListTest.cs
  Libplanet.Tests/Tx/UnsignedTxTest.cs
  Libplanet/Action/ActionEvaluator.cs
  Libplanet/Action/ActionListJsonConverter.cs
  Libplanet/Action/Sys/Registry.cs
  Libplanet/Action/Sys/SysActionJsonConverter.cs
  Libplanet/AssemblyInfo.cs
  Libplanet/Blockchain/BlockChain.cs
  Libplanet/Blocks/BlockContent.cs
  Libplanet/Blocks/BlockMarshaler.cs
  Libplanet/Store/DefaultStore.cs
  Libplanet/Tx/ITransaction.cs
  Libplanet/Tx/ITxInvoice.cs
  Libplanet/Tx/ITxSigningMetadata.cs
  Libplanet/Tx/IUnsignedTx.cs
  Libplanet/Tx/InvalidTxException.cs
  Libplanet/Tx/Transaction.cs
  Libplanet/Tx/TransactionExtensions.cs
  Libplanet/Tx/TxActionList.cs
  Libplanet/Tx/TxCustomActionList.cs
  Libplanet/Tx/TxInvoice.cs
  Libplanet/Tx/TxMarshaler.cs
  Libplanet/Tx/TxMetadata.cs
  Libplanet/Tx/TxSigningMetadata.cs
  Libplanet/Tx/TxSystemActionList.cs
  Libplanet/Tx/UnsignedTx.cs
Labels: api, Extra Large

#3033 Skip `RocksDBStoreBlockChainTest` if RocksDB is unavailable
  Libplanet.RocksDBStore.Tests/RocksDBStoreBlockChainTest.cs
  Libplanet.Tests/Blockchain/BlockChainTest.Append.cs
  Libplanet.Tests/Blockchain/BlockChainTest.Internals.cs
  Libplanet.Tests/Blockchain/BlockChainTest.MineBlock.cs
  Libplanet.Tests/Blockchain/BlockChainTest.Stage.cs
  Libplanet.Tests/Blockchain/BlockChainTest.ValidateNextBlock.cs
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet.Tests/Blockchain/DefaultStoreBlockChainTest.cs
  global.json
Labels: bug, Large

#3035 fix: errata of planet cli
  Libplanet.Tools/download.mjs
Labels: Extra Small

#3036 🧹 Small logging fix for consistency
  Libplanet/Action/ActionEvaluator.cs
Labels: Extra Small
