Repository planetarium/libplanet, pull requests merged in 2023-02, with the labels that each got.

#2747 ⬆️ Bump dependencies
  CHANGES.md
  Libplanet.Explorer/Libplanet.Explorer.csproj
  Libplanet.Extensions.Cocona/Libplanet.Extensions.Cocona.csproj
  Libplanet/Libplanet.csproj
Labels: Extra Small

#2735 Port changes from 0.45.5 to 0.46-maintenance
  CHANGES.md
  Libplanet/KeyStore/Web3KeyStore.cs
Labels: Extra Small

#2760 fix/transport: `ProcessMessageHandler` consumes reference of message
  Libplanet.Net/Transports/NetMQTransport.cs
Labels: bug, network, Small

#2757 Fix `stateQuery`
  CHANGES.md
  Libplanet.Explorer/Queries/ExplorerQuery.cs
Labels: Extra Small

#2622 Add query types for `BlockCommit` and `Vote`
  CHANGES.md
  Libplanet.Explorer.Tests/GraphTypes/BlockCommitTypeTest.cs
  Libplanet.Explorer.Tests/GraphTypes/BlockTypeTest.cs
  Libplanet.Explorer.Tests/GraphTypes/VoteTypeTest.cs
  Libplanet.Explorer/GraphTypes/BlockCommitType.cs
  Libplanet.Explorer/GraphTypes/BlockType.cs
  Libplanet.Explorer/GraphTypes/VoteFlagType.cs
  Libplanet.Explorer/GraphTypes/VoteType.cs
Labels: explorer, Large, pbft

#2761 Fix incorrect uses of `FileMode.OpenOrCreate`
  CHANGES.md
  Libplanet.Extensions.Cocona/Commands/BlockCommand.cs
  Libplanet.Node/NodeUtils.cs
  Libplanet/Store/DefaultStore.cs
Labels: bug, storage, Extra Small

#2742 log/transport: alternative Identity for NetMQTransport log
  Libplanet.Net/Transports/NetMQTransport.cs
Labels: network, Extra Small, logging

#2759 ♻️ Removed nullability from `TrustedAppProtocolVersionSigners`
  CHANGES.md
  Libplanet.Net.Tests/Messages/MessageValidatorTest.cs
  Libplanet.Net.Tests/Protocols/TestTransport.cs
  Libplanet.Net.Tests/SwarmTest.AppProtocolVersion.cs
  Libplanet.Net/AppProtocolVersionOptions.cs
  Libplanet.Net/Messages/MessageValidator.cs
  Libplanet.Node/NetworkConfig.cs
Labels: Small

#2765 Renew copyright years
  Docs/docfx.json
Labels: docs, Extra Small

#2763 log/transport: add message type in NetMQTransport logger
  CHANGES.md
  Libplanet.Net/Messages/NetMQMessageCodec.cs
  Libplanet.Net/Transports/NetMQTransport.cs
Labels: network, Extra Small, logging

#2768 Upgrade docfx to 2.60.2
  .config/dotnet-tools.json
  Docs/build.ps1
Labels: docs, Small

#2769 🔧 Fix transport log
  CHANGES.md
  Libplanet.Net/Messages/NetMQMessageCodec.cs
  Libplanet.Net/Transports/NetMQTransport.cs
Labels: Small

#2770 fix/gossip/messageCache: message in cache is being modified from outside
  Libplanet.Net.Tests/Consensus/MessageCacheTest.cs
  Libplanet.Net/Consensus/Gossip.cs
  Libplanet.Net/Consensus/MessageCache.cs
  Libplanet.Net/Messages/NetMQMessageCodec.cs
  Libplanet.Net/Transports/NetMQTransport.cs
Labels: bug, network, Medium, pbft

#2773 Ignore too low length candidate
  Libplanet.Net/BlockCandidateTable.cs
  Libplanet.Net/Swarm.BlockCandidate.cs
Labels: bug, Extra Small

#2774 More friendly message on empty bootstrap seeds
  Libplanet.Net/Protocols/KademliaProtocol.cs
Labels: network, api, Extra Small

#2775 🚀 Release 0.46.1
  CHANGES.md
Labels: release

#2777 🚀 Prepare 0.46.2
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: release, Extra Small

#2779 🔀 Merge 0.46.1 to main
  CHANGES.md
  Libplanet.Net/BlockCandidateTable.cs
  Libplanet.Net/Messages/NetMQMessageCodec.cs
  Libplanet.Net/Protocols/KademliaProtocol.cs
  Libplanet.Net/Swarm.BlockCandidate.cs
  Libplanet.Net/Transports/NetMQTransport.cs
  Libplanet/KeyStore/Web3KeyStore.cs
Labels: Medium

#2781 Updated `DeriveAddress()` to be more stringent
  CHANGES.md
  Libplanet.Explorer/GraphTypes/AddressType.cs
  Libplanet.Tests/AddressTest.cs
  Libplanet/Address.cs
Labels: Small

#2780 Merge Libplanet.Crypto.Secp256k1 and publish it to NuGet
  .github/bin/constants.sh
  CHANGES.md
  CONTRIBUTING.md
  Docs/docfx.json
  Libplanet.Crypto.Secp256k1.Tests/Libplanet.Crypto.Secp256k1.Tests.csproj
  Libplanet.Crypto.Secp256k1.Tests/Secp256k1CryptoBackendTest.cs
  Libplanet.Crypto.Secp256k1/Libplanet.Crypto.Secp256k1.csproj
  Libplanet.Crypto.Secp256k1/Secp256k1CryptoBackend.cs
  Libplanet.sln
Labels: Large

#2778 ♻️ Introduce `IBencodable`
  CHANGES.md
  Libplanet.Net.Tests/BoundPeerTest.cs
  Libplanet.Net/BoundPeer.cs
  Libplanet.Net/Messages/NeighborsMsg.cs
  Libplanet.Net/Messages/NetMQMessageCodec.cs
  Libplanet.Net/Transports/CommunicationFailException.cs
  Libplanet.Net/Transports/InvalidMessageSignatureException.cs
  Libplanet.Net/Transports/SendMessageFailException.cs
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
  Libplanet.Tests/AddressTest.cs
  Libplanet.Tests/Common/Action/Attack.cs
  Libplanet.Tests/Common/Action/DetectRehearsal.cs
  Libplanet.Tests/Common/Action/DumbAction.cs
  Libplanet.Tests/Common/Action/RandomAction.cs
  Libplanet.Tests/Common/Action/SetStatesAtBlock.cs
  Libplanet/Action/InsufficientBalanceException.cs
  Libplanet/Action/Sys/Mint.cs
  Libplanet/Action/Sys/Transfer.cs
  Libplanet/Address.cs
  Libplanet/Blocks/InvalidBlockTxCountPerSignerException.cs
  Libplanet/Store/BaseStore.cs
  Libplanet/Tx/TxMetadata.cs
  Libplanet/Tx/TxSuccess.cs
Labels: Large

#2782 Use voting power instead of vote count when validating blockcommit
  Libplanet.Net.Tests/Consensus/Context/MessageLogTest.cs
  Libplanet.Tests/Blocks/BlockCommitTest.cs
  Libplanet/Blockchain/BlockChain.cs
  Libplanet/Blocks/BlockCommit.cs
Labels: Small, pbft

#2784 Fix `VolatileStagePolicy<T>`'s `Expired()`
  CHANGES.md
  Libplanet.Tests/Blockchain/Policies/VolatileStagePolicyTest.cs
  Libplanet/Blockchain/Policies/VolatileStagePolicy.cs
Labels: Extra Small

#2785 Release 0.47.0
  CHANGES.md
Labels: release, Extra Small

#2787 Add missing 0.47.0 release date
  CHANGES.md
Labels: bug, release, Extra Small

#2789 Optimized `ByteUtil.Hex()`
  Libplanet/ByteUtil.cs
Labels: Extra Small

#2791 Cherry pick from b1c6232389f7260340fd69946ecefd86102c626a
  Libplanet.Net/BlockCandidateTable.cs
  Libplanet.Net/Swarm.BlockCandidate.cs
Labels: Extra Small, pbft

#2793 Add test for validator power
  Libplanet.Net.Tests/SwarmTest.cs
  Libplanet.Tests/Blockchain/BlockChainTest.ValidateNextBlock.cs
  Libplanet.Tests/Fixtures/IntegerSet.cs
  Libplanet.Tests/TestUtils.cs
  Libplanet/Blockchain/BlockChain.cs
Labels: Small, pbft

#2792 pbft: Add `LastCommit` as `PreEvaluationHash` input
  CHANGES.md
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
  Libplanet.Tests/Blocks/BlockCommitTest.cs
  Libplanet.Tests/TestUtils.cs
  Libplanet/Blocks/BlockCommit.cs
  Libplanet/Blocks/BlockMetadata.cs
Labels: Extra Small, pbft

#2794 ♻️ Refactor `BlockCandidateTable`
  CHANGES.md
  Libplanet.Net.Tests/BlockCandidateTableTest.cs
  Libplanet.Net/BlockCandidateTable.cs
  Libplanet.Net/Swarm.BlockCandidate.cs
  Libplanet.Tests/Store/StoreFixture.cs
Labels: Medium

#2790 Optimized `ParseHex()`
  Libplanet.Node/NodeUtils.cs
  Libplanet.Tests/ByteUtilTest.cs
  Libplanet/ByteUtil.cs
Labels: Extra Small

#2795 ♻️ `IBencodable` `TxId`
  CHANGES.md
  Libplanet.Tests/AddressTest.cs
  Libplanet.Tests/TestUtils.cs
  Libplanet.Tests/Tx/TxIdTest.cs
  Libplanet/Address.cs
  Libplanet/Tx/TxExecution.cs
  Libplanet/Tx/TxFailure.cs
  Libplanet/Tx/TxId.cs
  Libplanet/Tx/TxSuccess.cs
Labels: Medium

#2798 ♻️ Revert to add `Serializabe` attribute back into `Address` and `BoundPeer`
  CHANGES.md
  Libplanet.Net.Tests/BoundPeerTest.cs
  Libplanet.Net/BoundPeer.cs
  Libplanet.Net/Transports/CommunicationFailException.cs
  Libplanet.Net/Transports/InvalidMessageSignatureException.cs
  Libplanet.Net/Transports/SendMessageFailException.cs
  Libplanet.Tests/AddressTest.cs
  Libplanet/Action/InsufficientBalanceException.cs
  Libplanet/Address.cs
  Libplanet/Blocks/BlockPolicyViolationException.cs
  Libplanet/Blocks/InvalidBlockTxCountPerSignerException.cs
Labels: Medium

#2801 🧹 Aligned identity with request id format
  Libplanet.Net/Swarm.MessageHandlers.cs
Labels: Extra Small

#2805 feat(@planetarium/tx): Support building unsigned transactions with custom actions
  @planetarium/tx/README.md
  @planetarium/tx/package.json
  @planetarium/tx/src/action.ts
  @planetarium/tx/src/index.ts
  @planetarium/tx/src/tx/index.ts
  @planetarium/tx/src/tx/unsigned.ts
  @planetarium/tx/test/tx/unsigned.test.ts
  CHANGES.md
Labels: Medium, js

#2806 🧹 Added contextual information to `BlockCandidate` logging
  Libplanet.Net/BlockCandidateTable.cs
Labels: Extra Small

#2807 🧹 Fixed logging mistake
  Libplanet.Net/BlockCandidateTable.cs
Labels: Extra Small

#2803 Reply with zero blocks when no corresponding blocks are found
  CHANGES.md
  Libplanet.Net/Swarm.MessageHandlers.cs
  Libplanet.Net/Swarm.cs
Labels: Extra Small

#2810 🚀 Release libplanet 0.48.0
  CHANGES.md
Labels: Extra Small

#2811 🔧 Prepare 0.48.1
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: Extra Small

#2812 🔧 Prepare 0.49.0
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: Extra Small

#2813 Revert temporal skippable tests
  Libplanet.Net.Tests/Transports/NetMQTransportTest.cs
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
  Libplanet.Tests/Blockchain/BlockChainTest.Append.cs
  Libplanet.Tests/Blockchain/BlockChainTest.Internals.cs
  Libplanet.Tests/Blockchain/BlockChainTest.MineBlock.cs
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet.Tests/Blockchain/Policies/StagePolicyTest.cs
  Libplanet.Tests/Blockchain/Renderers/AnonymousActionRendererTest.cs
  Libplanet.Tests/Blockchain/Renderers/AnonymousRendererTest.cs
  Libplanet.Tests/Blockchain/Renderers/DelayedActionRendererTest.cs
  Libplanet.Tests/Blockchain/Renderers/DelayedRendererTest.cs
  Libplanet.Tests/Blockchain/Renderers/LoggedActionRendererTest.cs
  Libplanet.Tests/Blockchain/Renderers/NonblockRendererTest.cs
  Libplanet.Tests/Blocks/BlockContentTest.cs
  Libplanet.Tests/Blocks/BlockTest.cs
  Libplanet.Tests/Blocks/PreEvaluationBlockTest.cs
  Libplanet.Tests/Store/BlockSetTest.cs
  Libplanet.Tests/Store/DefaultStoreTest.cs
Labels: Large

#2814 Prevent duplicated ProcessBlockDemand
  CHANGES.md
  Libplanet.Net.Tests/SwarmTest.Broadcast.cs
  Libplanet.Net/Swarm.BlockCandidate.cs
  Libplanet.Net/Swarm.cs
Labels: network, Small

#2815 Cherrypick 2814 to PBFT
  Libplanet.Net.Tests/SwarmTest.Broadcast.cs
  Libplanet.Net/Swarm.BlockCandidate.cs
  Libplanet.Net/Swarm.cs
Labels: network, Small, pbft

#2804 Get preload blocks when its needed
  Libplanet.Net/Swarm.BlockSync.cs
Labels: bug, network, Extra Small

#2818 🚀 Release 0.46.2
  CHANGES.md
Labels: release, Extra Small

#2819 🧹 Merge 0.46.2 to main
  CHANGES.md
  Libplanet.Net/Swarm.BlockSync.cs
Labels: release, Extra Small

#2820 ⬆️ Prepare 0.46.3
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: release, Extra Small

#2821 update action evaluator log level
  Libplanet/Action/ActionEvaluator.cs
Labels: Extra Small

#2822 Introduce `Branch<T>` for more context
  CHANGES.md
  Libplanet.Net.Tests/BlockCandidateTableTest.cs
  Libplanet.Net/BlockCandidateTable.cs
  Libplanet.Net/Swarm.BlockCandidate.cs
  Libplanet.Net/Swarm.BlockSync.cs
  Libplanet.Tests/Blockchain/BranchTest.cs
  Libplanet/Blockchain/Branch.cs
Labels: Medium

#2824 🧹 Scrubbed trailing periods
  Libplanet.Net.Tests/BlockCompletionTest.cs
  Libplanet.Net.Tests/Protocols/ProtocolTest.cs
  Libplanet.Net.Tests/Protocols/TestTransport.cs
  Libplanet.Net.Tests/SwarmTest.Broadcast.cs
  Libplanet.Net.Tests/SwarmTest.Fixtures.cs
  Libplanet.Net.Tests/SwarmTest.Preload.cs
  Libplanet.Net.Tests/SwarmTest.cs
  Libplanet.Net/BlockCompletion.cs
  Libplanet.Net/BlockDemandTable.cs
  Libplanet.Net/Protocols/KBucket.cs
  Libplanet.Net/Protocols/KBucketDictionary.cs
  Libplanet.Net/Protocols/KademliaProtocol.cs
  Libplanet.Net/Protocols/RoutingTable.cs
  Libplanet.Net/Swarm.BlockCandidate.cs
  Libplanet.Net/Swarm.BlockSync.cs
  Libplanet.Net/Swarm.MessageHandlers.cs
  Libplanet.Net/Swarm.cs
  Libplanet.Net/Transports/NetMQTransport.cs
  Libplanet.Net/TxCompletion.cs
  Libplanet.RocksDBStore/RocksDBStore.cs
  Libplanet.Stun/Stun/TurnClient.cs
  Libplanet/Action/ActionEvaluator.cs
  Libplanet/Blockchain/BlockChain.MineBlock.cs
  Libplanet/Blockchain/BlockChain.Swap.cs
  Libplanet/Blockchain/BlockChain.TxExecution.cs
  Libplanet/Blockchain/BlockChain.cs
  Libplanet/Blockchain/Policies/VolatileStagePolicy.cs
  Libplanet/Blockchain/Renderers/Debug/RecordingActionRenderer.cs
  Libplanet/Blockchain/Renderers/DelayedActionRenderer.cs
  Libplanet/Blockchain/Renderers/DelayedRenderer.cs
  Libplanet/Blockchain/Renderers/NonblockRenderer.cs
  Libplanet/Blocks/PreEvaluationBlock.cs
  Libplanet/KeyStore/Web3KeyStore.cs
  Libplanet/Store/BaseStore.cs
  Libplanet/Store/TrieStateStore.cs
Labels: Extra Large

#2817 Avoid unintended blocks on NetMQTransport
  CHANGES.md
  Libplanet.Net.Tests/Transports/BoundPeerExtensionsTest.cs
  Libplanet.Net/Transports/BoundPeerExtensions.cs
  Libplanet.Net/Transports/NetMQTransport.cs
Labels: network, Extra Small, Squash Needed

#2828 🧹 Changed method name logging for more consistency
  Libplanet.Net.Tests/SwarmTest.Preload.cs
  Libplanet.Net/Protocols/KademliaProtocol.cs
  Libplanet.Net/Swarm.BlockCandidate.cs
  Libplanet.Net/Swarm.BlockSync.cs
  Libplanet.Net/Swarm.cs
  Libplanet.Net/Transports/NetMQTransport.cs
  Libplanet.Net/TxCompletion.cs
  Libplanet.RocksDBStore/RocksDBStore.cs
  Libplanet.Stun/Stun/TurnClient.cs
  Libplanet/Blockchain/BlockChain.Swap.cs
  Libplanet/Store/TrieStateStore.cs
Labels: Medium

#2830 🧹 Elevated `NetMQTransport` log levels
  Libplanet.Net/Transports/NetMQTransport.cs
Labels: Small

#2832 🧹 Sanitized logging
  Libplanet.Net.Tests/BlockCompletionTest.cs
  Libplanet.Net.Tests/Protocols/ProtocolTest.cs
  Libplanet.Net.Tests/Protocols/TestTransport.cs
  Libplanet.Net.Tests/SwarmTest.Broadcast.cs
  Libplanet.Net.Tests/SwarmTest.Fixtures.cs
  Libplanet.Net.Tests/SwarmTest.Preload.cs
  Libplanet.Net.Tests/SwarmTest.cs
  Libplanet.Net/AppProtocolVersion.cs
  Libplanet.Net/BlockCompletion.cs
  Libplanet.Net/BlockDemandTable.cs
  Libplanet.Net/Protocols/KBucket.cs
  Libplanet.Net/Protocols/KBucketDictionary.cs
  Libplanet.Net/Protocols/KademliaProtocol.cs
  Libplanet.Net/Protocols/RoutingTable.cs
  Libplanet.Net/Swarm.BlockCandidate.cs
  Libplanet.Net/Swarm.BlockSync.cs
  Libplanet.Net/Swarm.MessageHandlers.cs
  Libplanet.Net/Swarm.cs
  Libplanet.Net/Transports/NetMQTransport.cs
  Libplanet.Net/TxCompletion.cs
  Libplanet.RocksDBStore/RocksDBStore.cs
  Libplanet.Stun/Stun/TurnClient.cs
  Libplanet.Tests/Blockchain/Renderers/LoggedActionRendererTest.cs
  Libplanet.Tests/Blockchain/Renderers/LoggedRendererTest.cs
  Libplanet/Action/ActionEvaluator.cs
  Libplanet/Blockchain/BlockChain.MineBlock.cs
  Libplanet/Blockchain/BlockChain.Swap.cs
  Libplanet/Blockchain/BlockChain.TxExecution.cs
  Libplanet/Blockchain/BlockChain.cs
  Libplanet/Blockchain/Policies/VolatileStagePolicy.cs
  Libplanet/Blockchain/Renderers/Debug/RecordingActionRenderer.cs
  Libplanet/Blockchain/Renderers/DelayedActionRenderer.cs
  Libplanet/Blockchain/Renderers/DelayedRenderer.cs
  Libplanet/Blockchain/Renderers/LoggedActionRenderer.cs
  Libplanet/Blockchain/Renderers/LoggedRenderer.cs
  Libplanet/Blockchain/Renderers/NonblockRenderer.cs
  Libplanet/Blocks/PreEvaluationBlock.cs
  Libplanet/KeyStore/Web3KeyStore.cs
  Libplanet/Store/BaseStore.cs
  Libplanet/Store/DefaultStore.cs
  Libplanet/Store/TrieStateStore.cs
Labels: Extra Large

#2827 update some log level from Debug to Information
  Libplanet.Net.Tests/Protocols/TestTransport.cs
  Libplanet.Net/Swarm.BlockCandidate.cs
  Libplanet.Net/Swarm.MessageHandlers.cs
  Libplanet.Net/Swarm.cs
  Libplanet.Net/TxCompletion.cs
  Libplanet/Blockchain/BlockChain.cs
  Libplanet/Blockchain/Policies/VolatileStagePolicy.cs
Labels: Medium

#2834 🚀 Release libplanet 0.49.0
  CHANGES.md
Labels: release, Extra Small

#2836 🔧 Prepare 0.50.0
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: Extra Small

#2835 🔧 Prepare 0.49.1
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: Extra Small

#2845 Ignore policy checks for genesis block
  CHANGES.md
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet/Blockchain/BlockChain.cs
  Libplanet/Blockchain/Policies/IBlockPolicy.cs
Labels: Medium

#2831 Separate `Message`'s content and make messages immutable
  CHANGES.md
  Libplanet.Net.Tests/Messages/BlockHashesTest.cs
  Libplanet.Net.Tests/Messages/MessageValidatorTest.cs
  Libplanet.Net.Tests/Messages/NetMQMessageCodecTest.cs
  Libplanet.Net.Tests/Protocols/TestMessage.cs
  Libplanet.Net.Tests/Protocols/TestTransport.cs
  Libplanet.Net.Tests/SwarmTest.Broadcast.cs
  Libplanet.Net.Tests/SwarmTest.cs
  Libplanet.Net.Tests/Transports/CommunicationFailExceptionTest.cs
  Libplanet.Net.Tests/Transports/NetMQTransportTest.cs
  Libplanet.Net.Tests/Transports/SendMessageFailExceptionTest.cs
  Libplanet.Net.Tests/Transports/TransportTest.cs
  Libplanet.Net/InvalidMessageContentException.cs
  Libplanet.Net/InvalidMessageException.cs
  Libplanet.Net/Messages/BlockHashesMsg.cs
  Libplanet.Net/Messages/BlockHeaderMsg.cs
  Libplanet.Net/Messages/BlocksMsg.cs
  Libplanet.Net/Messages/ChainStatusMsg.cs
  Libplanet.Net/Messages/DifferentVersionMsg.cs
  Libplanet.Net/Messages/FindNeighborsMsg.cs
  Libplanet.Net/Messages/GetBlockHashesMsg.cs
  Libplanet.Net/Messages/GetBlocksMsg.cs
  Libplanet.Net/Messages/GetChainStatusMsg.cs
  Libplanet.Net/Messages/GetTxsMsg.cs
  Libplanet.Net/Messages/IMessageCodec.cs
  Libplanet.Net/Messages/Message.cs
  Libplanet.Net/Messages/MessageContent.cs
  Libplanet.Net/Messages/MessageValidator.cs
  Libplanet.Net/Messages/NeighborsMsg.cs
  Libplanet.Net/Messages/NetMQMessageCodec.cs
  Libplanet.Net/Messages/PingMsg.cs
  Libplanet.Net/Messages/PongMsg.cs
  Libplanet.Net/Messages/TxIdsMsg.cs
  Libplanet.Net/Messages/TxMsg.cs
  Libplanet.Net/Protocols/KademliaProtocol.cs
  Libplanet.Net/Swarm.MessageHandlers.cs
  Libplanet.Net/Swarm.cs
  Libplanet.Net/Transports/CommunicationFailException.cs
  Libplanet.Net/Transports/ITransport.cs
  Libplanet.Net/Transports/NetMQTransport.cs
Labels: Extra Large

#2846 Merge/main to pbft 0.48.0
  @planetarium/tx/README.md
  @planetarium/tx/package.json
  @planetarium/tx/src/action.ts
  @planetarium/tx/src/index.ts
  @planetarium/tx/src/tx/index.ts
  @planetarium/tx/src/tx/unsigned.ts
  @planetarium/tx/test/tx/unsigned.test.ts
  CHANGES.md
  Libplanet.Net.Tests/BlockCandidateTableTest.cs
  Libplanet.Net.Tests/BoundPeerTest.cs
  Libplanet.Net/BlockCandidateTable.cs
  Libplanet.Net/BoundPeer.cs
  Libplanet.Net/Swarm.BlockCandidate.cs
  Libplanet.Net/Swarm.MessageHandlers.cs
  Libplanet.Net/Swarm.cs
  Libplanet.Net/Transports/CommunicationFailException.cs
  Libplanet.Net/Transports/InvalidMessageSignatureException.cs
  Libplanet.Net/Transports/SendMessageFailException.cs
  Libplanet.Node/NodeUtils.cs
  Libplanet.Tests/AddressTest.cs
  Libplanet.Tests/ByteUtilTest.cs
  Libplanet.Tests/Store/StoreFixture.cs
  Libplanet.Tests/TestUtils.cs
  Libplanet.Tests/Tx/TxIdTest.cs
  Libplanet/Action/InsufficientBalanceException.cs
  Libplanet/Address.cs
  Libplanet/Blocks/BlockPolicyViolationException.cs
  Libplanet/Blocks/InvalidBlockTxCountPerSignerException.cs
  Libplanet/ByteUtil.cs
  Libplanet/Libplanet.csproj
  Libplanet/Tx/TxExecution.cs
  Libplanet/Tx/TxFailure.cs
  Libplanet/Tx/TxId.cs
  Libplanet/Tx/TxSuccess.cs
Labels: Extra Large, pbft

#2849 Removed ConsumeBlockCandidates log
  CHANGES.md
  Libplanet.Net/Swarm.BlockCandidate.cs
  Libplanet.Net/Transports/NetMQTransport.cs
Labels: Extra Small

#2847 Prepare monorepo for typescript lib
  .editorconfig
  .gitattributes
  .github/bin/constants.sh
  .github/bin/dist-npm.sh
  .github/bin/dist-pack.sh
  .github/bin/dist-version.ps1
  .github/workflows/build.yaml
  .github/workflows/main.yml
  .github/workflows/yarn.yaml
  .gitignore
  .prettierignore
  .vscode/extensions.json
  .vscode/settings.json
  .yarn/plugins/@yarnpkg/plugin-typescript.cjs
  .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
  .yarn/releases/yarn-3.4.1.cjs
  .yarn/sdks/integrations.yml
  .yarn/sdks/typescript/lib/tsc.js
  .yarn/sdks/typescript/lib/tsserver.js
  .yarn/sdks/typescript/lib/tsserverlibrary.js
  .yarn/sdks/typescript/lib/typescript.js
  .yarn/sdks/typescript/package.json
  .yarnrc.yml
  @planetarium/.editorconfig
  @planetarium/.gitignore
  @planetarium/tx/.eslintrc.yaml
  @planetarium/tx/.gitignore
  @planetarium/tx/.prettierignore
  @planetarium/tx/.prettierrc.yaml
  @planetarium/tx/hooks/pre-commit
  @planetarium/tx/package.json
  @planetarium/tx/src/action.ts
  @planetarium/tx/src/address.ts
  @planetarium/tx/src/assets.ts
  @planetarium/tx/src/index.ts
  @planetarium/tx/src/tx/index.ts
  @planetarium/tx/src/tx/metadata.ts
  @planetarium/tx/src/tx/unsigned.ts
  @planetarium/tx/test/address.test.ts
  @planetarium/tx/tsconfig.json
  @planetarium/tx/vitest.config.ts
  CONTRIBUTING.md
  Libplanet.Tools/.gitignore
  Libplanet.Tools/bin/npm-test.ps1
  Libplanet.Tools/bin/npm-test.sh
  Libplanet.Tools/download.mjs
  Libplanet.Tools/package.json
  hooks/pre-commit
  package.json
  rome.json
  scripts/.editorconfig
  scripts/determine-version.js
  yarn.lock
Labels: Extra Large

#2851 CI: fix where obj/ directory is missing
  .github/workflows/build.yaml
Labels: Extra Small

#2850 🚀 Release 0.49.1
  CHANGES.md
Labels: Extra Small

#2853 🔀 Port 0.49.1 to main
  CHANGES.md
  Libplanet.Net/Swarm.BlockCandidate.cs
  Libplanet.Net/Transports/NetMQTransport.cs
Labels: Extra Small

#2855 CI: fix parameters
  .github/bin/dist-pack.sh
  scripts/determine-version.js
Labels: Extra Small

#2852 🔧 Prepare 0.49.2
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: Extra Small

#2857 ♻️ Refactor validate nonces
  Libplanet.Net/Swarm.BlockCandidate.cs
  Libplanet/Blockchain/BlockChain.cs
  Libplanet/Tx/InvalidTxNonceException.cs
Labels: Medium

#2859 🧹 Updated metric logging
  Libplanet.Net/Transports/NetMQTransport.cs
  Libplanet.Tests/EnumerableMeasurementTest.cs
  Libplanet/Action/ActionEvaluator.cs
  Libplanet/Blockchain/BlockChain.Swap.cs
  Libplanet/Blockchain/BlockChain.cs
  Libplanet/Store/TrieStateStore.cs
Labels: Small

#2861 🧹 Added info for transport logging
  Libplanet.Net/Transports/NetMQTransport.cs
Labels: Extra Small

#2862 🧹 Use ephemeral `IStateStore` for generating genesis block
  Libplanet.Tests/TestUtils.cs
Labels: Extra Small

#2858 Changed benchmark alert threshold to 200% (again)
  .github/workflows/benchmarks-pr.yml
Labels: Extra Small

#2856 Merge/main to pbft 0.49.0
  CHANGES.md
  Libplanet.Net.Tests/BlockCandidateTableTest.cs
  Libplanet.Net.Tests/BlockCompletionTest.cs
  Libplanet.Net.Tests/Consensus/ConsensusReactorTest.cs
  Libplanet.Net.Tests/Consensus/GossipTest.cs
  Libplanet.Net.Tests/HostOptionsTest.cs
  Libplanet.Net.Tests/Messages/NetMQMessageCodecTest.cs
  Libplanet.Net.Tests/Protocols/ProtocolTest.cs
  Libplanet.Net.Tests/Protocols/TestTransport.cs
  Libplanet.Net.Tests/SwarmTest.Broadcast.cs
  Libplanet.Net.Tests/SwarmTest.Fixtures.cs
  Libplanet.Net.Tests/SwarmTest.Preload.cs
  Libplanet.Net.Tests/SwarmTest.cs
  Libplanet.Net.Tests/TestUtils.cs
  Libplanet.Net.Tests/Transports/BoundPeerExtensionsTest.cs
  Libplanet.Net.Tests/Transports/TransportTest.cs
  Libplanet.Net/AppProtocolVersion.cs
  Libplanet.Net/BlockCandidateTable.cs
  Libplanet.Net/BlockCompletion.cs
  Libplanet.Net/BlockDemandTable.cs
  Libplanet.Net/Protocols/KBucket.cs
  Libplanet.Net/Protocols/KBucketDictionary.cs
  Libplanet.Net/Protocols/KademliaProtocol.cs
  Libplanet.Net/Protocols/RoutingTable.cs
  Libplanet.Net/Swarm.BlockCandidate.cs
  Libplanet.Net/Swarm.BlockSync.cs
  Libplanet.Net/Swarm.MessageHandlers.cs
  Libplanet.Net/Swarm.cs
  Libplanet.Net/Transports/BoundPeerExtensions.cs
  Libplanet.Net/Transports/NetMQTransport.cs
  Libplanet.Net/TxCompletion.cs
  Libplanet.Node.Tests/SwarmConfigTest.cs
  Libplanet.Node/InitConfig.cs
  Libplanet.RocksDBStore/RocksDBStore.cs
  Libplanet.Stun/Stun/TurnClient.cs
  Libplanet.Tests/Blockchain/BranchTest.cs
  Libplanet.Tests/Blockchain/Renderers/LoggedActionRendererTest.cs
  Libplanet.Tests/Blockchain/Renderers/LoggedRendererTest.cs
  Libplanet/Action/ActionEvaluator.cs
  Libplanet/Blockchain/BlockChain.MineBlock.cs
  Libplanet/Blockchain/BlockChain.Swap.cs
  Libplanet/Blockchain/BlockChain.TxExecution.cs
  Libplanet/Blockchain/BlockChain.cs
  Libplanet/Blockchain/Branch.cs
  Libplanet/Blockchain/Policies/VolatileStagePolicy.cs
  Libplanet/Blockchain/Renderers/Debug/RecordingActionRenderer.cs
  Libplanet/Blockchain/Renderers/DelayedActionRenderer.cs
  Libplanet/Blockchain/Renderers/DelayedRenderer.cs
  Libplanet/Blockchain/Renderers/LoggedActionRenderer.cs
  Libplanet/Blockchain/Renderers/LoggedRenderer.cs
  Libplanet/Blockchain/Renderers/NonblockRenderer.cs
  Libplanet/Blocks/PreEvaluationBlock.cs
  Libplanet/KeyStore/Web3KeyStore.cs
  Libplanet/Libplanet.csproj
  Libplanet/Store/BaseStore.cs
  Libplanet/Store/DefaultStore.cs
  Libplanet/Store/TrieStateStore.cs
Labels: Extra Large

#2843 Remove the deprecated class `ProposerSelector`
  Libplanet/Consensus/ProposerSelector.cs
Labels: Extra Small

#2865 🧹 Better logging
  Libplanet.Net/Transports/NetMQTransport.cs
  Libplanet.Tests/EnumerableMeasurementTest.cs
  Libplanet/Action/ActionEvaluator.cs
  Libplanet/Blockchain/BlockChain.Swap.cs
  Libplanet/Blockchain/BlockChain.cs
  Libplanet/Store/TrieStateStore.cs
Labels: Small

#2866 🚀 Release 0.50.0
  CHANGES.md
Labels: Extra Small

#2868 🧹 Added contexts for logging; additional metric logging
  Libplanet.Net/BlockCandidateTable.cs
  Libplanet/Blockchain/Policies/VolatileStagePolicy.cs
Labels: Extra Small

#2867 🔧 Prepare 0.51.0
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: Extra Small

#2848 Introduce @planetarium/account
  @planetarium/account/.gitignore
  @planetarium/account/README.md
  @planetarium/account/global.d.ts
  @planetarium/account/package.json
  @planetarium/account/src/Account.ts
  @planetarium/account/src/Address.ts
  @planetarium/account/src/Message.ts
  @planetarium/account/src/PublicKey.ts
  @planetarium/account/src/RawPrivateKey.ts
  @planetarium/account/src/Signature.ts
  @planetarium/account/src/index.ts
  @planetarium/account/test/Address.test.ts
  @planetarium/account/test/Message.test.ts
  @planetarium/account/test/PublicKey.test.ts
  @planetarium/account/test/RawPrivateKey.test.ts
  @planetarium/account/test/Signature.test.ts
  @planetarium/account/test/setup.ts
  @planetarium/account/test/utils.ts
  @planetarium/account/tsconfig.json
  @planetarium/account/vitest.config.ts
  CHANGES.md
  package.json
  yarn.lock
Labels: Extra Large

#2869 Add `@planetarium/account` to npm package list for CI
  .github/bin/constants.sh
Labels: Extra Small
