Repository planetarium/libplanet, pull requests merged in 2023-04, with the labels that each got.

#3038 🧹 Removed unnecessary logic
  Libplanet/Blockchain/BlockChain.MineBlock.cs
Labels: Extra Small

#3032 🔀 Merge 0.53.2 to main
  CHANGES.md
  Libplanet/Action/AccountStateDeltaImpl.cs
  Libplanet/Action/ActionContext.cs
  Libplanet/Action/ActionEvaluator.cs
  Libplanet/Action/IValidatorSupportStateDelta.cs
  Libplanet/Blockchain/BlockChain.cs
  Libplanet/Blockchain/BlockChainStates.cs
  Libplanet/Blockchain/ChainStateCache.cs
  Libplanet/Blockchain/KeyConverters.cs
  Libplanet/ByteUtil.cs
Labels: release, Large

#3040 🧹 Changelog formatting
  CHANGES.md
Labels: Extra Small

#3037 Refactor block evaluate related code
  CHANGES.md
  Libplanet.Net/Swarm.BlockSync.cs
  Libplanet.Tests/Action/AccountStateDeltaImplV0Test.cs
  Libplanet.Tests/Action/AccountStateDeltaTest.cs
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
  Libplanet.Tests/Blockchain/BlockChainTest.Internals.cs
  Libplanet.Tests/Blockchain/BlockChainTest.ValidateNextBlock.cs
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet.Tests/Blocks/PreEvaluationBlockTest.cs
  Libplanet.Tests/Fixtures/IntegerSet.cs
  Libplanet.Tests/Store/StoreFixture.cs
  Libplanet.Tests/Store/StoreTest.cs
  Libplanet.Tests/TestUtils.cs
  Libplanet/Blockchain/BlockChain.Evaluate.cs
  Libplanet/Blockchain/BlockChain.MineBlock.cs
  Libplanet/Blockchain/BlockChain.cs
  Libplanet/Blocks/PreEvaluationBlock.cs
Labels: Extra Large

#2996 fix: validate block content in PreVote step
  CHANGES.md
  Libplanet.Net.Tests/Consensus/Context/ContextNonProposerTest.cs
  Libplanet.Net.Tests/TestUtils.cs
  Libplanet.Net/Consensus/Context.Mutate.cs
  Libplanet.Net/Consensus/Context.cs
  Libplanet/Blockchain/BlockChain.cs
Labels: bug, Medium, pbft

#3043 🧹 Separate block validation related code
  Libplanet/Blockchain/BlockChain.Validate.cs
  Libplanet/Blockchain/BlockChain.cs
Labels: Large

#3046 Adjust consensus loggings
  CHANGES.md
  Libplanet.Net.Tests/Consensus/Context/MessageLogTest.cs
  Libplanet.Net/Consensus/ConsensusContext.cs
  Libplanet.Net/Consensus/Context.Async.cs
  Libplanet.Net/Consensus/Context.Mutate.cs
  Libplanet.Net/Consensus/Context.cs
  Libplanet.Net/Consensus/Gossip.cs
  Libplanet.Net/Consensus/MessageLog.cs
Labels: Medium

#3048 🔧 Prepare 0.53.4
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: Extra Small

#3051 🧹 Refactor block validate code
  Libplanet.Net/Consensus/Context.cs
  Libplanet/Blockchain/BlockChain.Validate.cs
  Libplanet/Blockchain/BlockChain.cs
Labels: Medium

#3052 Fix yarn package version resolve & tx export & Release 0.53.4
  .github/bin/dist-pack.sh
  @planetarium/tx/src/index.ts
  CHANGES.md
Labels: Extra Small

#3044 Implement TypeConverter for commonly used types
  CHANGES.md
  Libplanet.Explorer.Tests/Queries/StateQueryTest.cs
  Libplanet.Explorer/GraphTypes/PublicKeyType.cs
  Libplanet.Extensions.Cocona/Commands/ApvCommand.cs
  Libplanet.Extensions.Cocona/Commands/KeyCommand.cs
  Libplanet.Net.Tests/BoundPeerTest.cs
  Libplanet.Net/BoundPeer.cs
  Libplanet.Tests/AddressTest.cs
  Libplanet.Tests/Crypto/PublicKeyTest.cs
  Libplanet.Tests/HashDigestTest.cs
  Libplanet/Address.cs
  Libplanet/Crypto/PublicKey.cs
  Libplanet/FixedSizedQueue.cs
  Libplanet/HashDigest.cs
Labels: api, Large

#3056 🔨 Prepare 0.53.5
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: Extra Small

#3057 🔀 Port 0.53.3 to main
  CHANGES.md
  Libplanet.Net.Tests/Consensus/Context/MessageLogTest.cs
  Libplanet.Net/Consensus/ConsensusContext.cs
  Libplanet.Net/Consensus/Context.Async.cs
  Libplanet.Net/Consensus/Context.Mutate.cs
  Libplanet.Net/Consensus/Context.cs
  Libplanet.Net/Consensus/Gossip.cs
  Libplanet.Net/Consensus/MessageLog.cs
Labels: Medium

#3058 🔀 Port 0.53.4 to main
  .github/bin/dist-pack.sh
  @planetarium/tx/src/index.ts
  CHANGES.md
Labels: Extra Small

#3053 ♻️ Make validate methods throw exceptions instead of returning
  Libplanet.Net/Consensus/Context.cs
  Libplanet.Tests/Blockchain/BlockChainTest.ValidateNextBlock.cs
  Libplanet/Blockchain/BlockChain.Validate.cs
  Libplanet/Blockchain/BlockChain.cs
Labels: Medium

#3041 JSON serialization tests for tx types (post #2986)
  Libplanet.Tests/TestUtils.cs
  Libplanet.Tests/Tx/TransactionTest.cs
  Libplanet.Tests/Tx/TxActionListTest.cs
  Libplanet.Tests/Tx/TxInvoiceTest.cs
  Libplanet.Tests/Tx/TxSigningMetadataTest.cs
  Libplanet.Tests/Tx/UnsignedTxTest.cs
  Libplanet/Tx/TxActionList.cs
Labels: Medium

#3059 ♻️ Refactor block validate
  Libplanet.Net.Tests/Consensus/Context/ContextProposerTest.cs
  Libplanet.Net/Consensus/Context.cs
Labels: Medium

#3062 🧹 Remove tx execution update from `ProposeBlock()`
  Libplanet/Blockchain/BlockChain.ProposeBlock.cs
Labels: Extra Small

#3063 Replace newHeightDelay with contextMinInterval
  CHANGES.md
  Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextNonProposerTest.cs
  Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextTest.cs
  Libplanet.Net.Tests/Consensus/ConsensusReactorTest.cs
  Libplanet.Net.Tests/TestUtils.cs
  Libplanet.Net/Consensus/ConsensusContext.cs
  Libplanet.Net/Consensus/ConsensusReactor.cs
  Libplanet.Net/Consensus/Context.Async.cs
  Libplanet.Net/Consensus/Context.cs
Labels: Small

#3064 Fix local variable startTime to be assigned safely
  Libplanet.Net/Consensus/ConsensusContext.cs
Labels: Extra Small

#3060 Implement `Gossip.PublishMessage()`
  CHANGES.md
  Libplanet.Net.Tests/Consensus/GossipTest.cs
  Libplanet.Net/Consensus/ConsensusReactor.cs
  Libplanet.Net/Consensus/Gossip.cs
Labels: network, Medium, pbft

#3067 🧹 Remove mining
  CHANGES.md
  Libplanet.Tests/Blockchain/BlockChainTest.MineBlock.cs
  Libplanet.Tests/Blocks/BlockMetadataTest.cs
  Libplanet.Tests/HashcashTest.cs
  Libplanet.Tests/TestUtils.cs
  Libplanet/Blocks/BlockContent.cs
  Libplanet/Blocks/BlockMetadata.cs
  Libplanet/Hashcash.cs
  Libplanet/Nonce.cs
Labels: Medium

#3061 @planetarium/account-web3-secret-storage: `Web3Account` (deferred unlock) & asyncify `getPublicKey()`
  @planetarium/account-aws-kms/package.json
  @planetarium/account-aws-kms/src/AwsKmsAccount.ts
  @planetarium/account-aws-kms/test/AwsKmsKeyStore.test.ts
  @planetarium/account-web3-secret-storage/package.json
  @planetarium/account-web3-secret-storage/src/Web3Account.ts
  @planetarium/account-web3-secret-storage/src/Web3KeyStore.ts
  @planetarium/account-web3-secret-storage/src/index.ts
  @planetarium/account-web3-secret-storage/test/MockPassphraseEntry.ts
  @planetarium/account-web3-secret-storage/test/Web3Account.test.ts
  @planetarium/account-web3-secret-storage/test/Web3KeyStore.test.ts
  @planetarium/account-web3-secret-storage/test/__snapshots__/Web3Account.test.ts.snap
  @planetarium/account/src/Account.ts
  @planetarium/account/src/Address.ts
  @planetarium/account/src/RawPrivateKey.ts
  @planetarium/account/test/Account.test.ts
  @planetarium/account/test/Address.test.ts
  @planetarium/account/test/RawPrivateKey.test.ts
  @planetarium/tx/src/tx/signed.ts
  @planetarium/tx/test/tx/fixtures.ts
  CHANGES.md
  yarn.lock
Labels: api, Large, js

#3069 Move @planetarium/account to peerDependencies
  @planetarium/account-aws-kms/package.json
  @planetarium/account-web3-secret-storage/package.json
  @planetarium/tx/package.json
  CHANGES.md
  yarn.lock
Labels: Extra Small

#2613 Indexing in `Libplanet.Explorer`
  .github/bin/constants.sh
  CHANGES.md
  CONTRIBUTING.md
  Docs/docfx.json
  Libplanet.Explorer.Cocona.Tests/Commands/IndexCommandTest.cs
  Libplanet.Explorer.Cocona.Tests/Libplanet.Explorer.Cocona.Tests.csproj
  Libplanet.Explorer.Cocona/AssemblyInfo.cs
  Libplanet.Explorer.Cocona/Commands/IndexCommand.cs
  Libplanet.Explorer.Cocona/Libplanet.Explorer.Cocona.csproj
  Libplanet.Explorer.Executable/Program.cs
  Libplanet.Explorer.Tests/GeneratedBlockChainFixture.cs
  Libplanet.Explorer.Tests/GraphQLTestUtils.cs
  Libplanet.Explorer.Tests/GraphTypes/BlockTypeTest.cs
  Libplanet.Explorer.Tests/GraphTypes/TransactionTypeTest.cs
  Libplanet.Explorer.Tests/Indexing/BlockChainIndexFixture.cs
  Libplanet.Explorer.Tests/Indexing/BlockChainIndexTest.cs
  Libplanet.Explorer.Tests/Indexing/IBlockChainIndexFixture.cs
  Libplanet.Explorer.Tests/Indexing/RocksDbBlockChainIndexFixture.cs
  Libplanet.Explorer.Tests/Indexing/RocksDbBlockChainIndexTest.cs
  Libplanet.Explorer.Tests/Queries/MockBlockChainContext.cs
  Libplanet.Explorer.Tests/Queries/MockBlockChainContextWithIndex.cs
  Libplanet.Explorer.Tests/Queries/TransactionQueryGeneratedTest.cs
  Libplanet.Explorer.Tests/Queries/TransactionQueryGeneratedWithIndexTest.cs
  Libplanet.Explorer.Tests/Queries/TransactionQueryTest.cs
  Libplanet.Explorer.Tests/Queries/TransactionQueryWithIndexTest.cs
  Libplanet.Explorer.Tests/SimpleAction.cs
  Libplanet.Explorer/AssemblyInfo.cs
  Libplanet.Explorer/ExplorerStartup.cs
  Libplanet.Explorer/GraphTypes/BlockType.cs
  Libplanet.Explorer/GraphTypes/TransactionType.cs
  Libplanet.Explorer/Indexing/BlockChainIndexBase.cs
  Libplanet.Explorer/Indexing/IBlockChainIndex.cs
  Libplanet.Explorer/Indexing/IIndexingContext.cs
  Libplanet.Explorer/Indexing/IndexMismatchException.cs
  Libplanet.Explorer/Indexing/IndexingService.cs
  Libplanet.Explorer/Indexing/RocksDbBlockChainIndex.cs
  Libplanet.Explorer/Indexing/RocksDbIndexingContext.cs
  Libplanet.Explorer/Interfaces/IBlockChainContext.cs
  Libplanet.Explorer/Queries/ExplorerQuery.cs
  Libplanet.Explorer/Queries/TransactionQuery.cs
  Libplanet.Extensions.Cocona/Utils.cs
  Libplanet.sln
  Libplanet/AssemblyInfo.cs
Labels: Extra Large

#3073 Fix regression that `planet tx analyze` did not verify signature
  Libplanet.Explorer/Queries/TransactionQuery.cs
  Libplanet.Extensions.Cocona.Tests/Commands/TxCommandTest.cs
  Libplanet.Extensions.Cocona.Tests/Fixtures/invalid-tx.bin
  Libplanet.Extensions.Cocona.Tests/Fixtures/tx.bin
  Libplanet.Extensions.Cocona.Tests/Libplanet.Extensions.Cocona.Tests.csproj
  Libplanet.Extensions.Cocona/Commands/TxCommand.cs
  Libplanet.Tests/Tx/TransactionTest.cs
  Libplanet/Tx/Transaction.cs
  Libplanet/Tx/TransactionExtensions.cs
  Libplanet/Tx/TxMarshaler.cs
Labels: bug, tools

#3028 feat: cache evaluated actions in `Context<T>`
  CHANGES.md
  Libplanet.Net/Consensus/Context.Mutate.cs
  Libplanet.Net/Consensus/Context.cs
Labels: Small, pbft

#3074 Preserve order of `Transaction<T>.UpdatedAddresses`
  CHANGES.md
  Libplanet.Tests/Tx/AddressSetTest.cs
  Libplanet.Tests/Tx/TxMarshalerTest.cs
  Libplanet.Tools/Libplanet.Tools.csproj
  Libplanet.Tools/Program.cs
  Libplanet/Tx/AddressSet.cs
  Libplanet/Tx/TxInvoice.cs
  Libplanet/Tx/TxMarshaler.cs
Labels: bug, tools

#3080 Implement `query.stateQuery.states`
  CHANGES.md
  Libplanet.Explorer.Tests/Queries/StateQueryTest.cs
  Libplanet.Explorer/Queries/StateQuery.cs
Labels: explorer

#3071 @planetarium/account-web3-secret-storage: Optionally allow weak private keys shorter than 32 bytes and implement some utilites
  @planetarium/account-web3-secret-storage/package.json
  @planetarium/account-web3-secret-storage/src/KeyId.ts
  @planetarium/account-web3-secret-storage/src/Web3Account.ts
  @planetarium/account-web3-secret-storage/src/Web3KeyStore.ts
  @planetarium/account-web3-secret-storage/src/index.ts
  @planetarium/account-web3-secret-storage/test/KeyId.test.ts
  @planetarium/account-web3-secret-storage/test/MockPassphraseEntry.ts
  @planetarium/account-web3-secret-storage/test/Web3Account.test.ts
  @planetarium/account-web3-secret-storage/test/Web3KeyStore.test.ts
  @planetarium/account-web3-secret-storage/test/__snapshots__/Web3Account.test.ts.snap
  @planetarium/account-web3-secret-storage/test/fixtures/insufficient-lengthed-keys/UTC--2023-01-30T11-33-11Z--b35a2647-8581-43ff-a98e-6083dc952632
  @planetarium/account-web3-secret-storage/vitest.config.ts.timestamp-1681276750671.mjs
  @planetarium/account/src/Address.ts
  @planetarium/account/src/PublicKey.ts
  @planetarium/account/test/Address.test.ts
  @planetarium/account/test/PublicKey.test.ts
  CHANGES.md
  yarn.lock
Labels: api, js

#3084 @planetarium/account: `Account.getAddress()`
  @planetarium/account-aws-kms/src/AwsKmsAccount.ts
  @planetarium/account-aws-kms/test/AwsKmsKeyStore.test.ts
  @planetarium/account-web3-secret-storage/src/Web3Account.ts
  @planetarium/account-web3-secret-storage/src/Web3KeyStore.ts
  @planetarium/account-web3-secret-storage/test/Web3Account.test.ts
  @planetarium/account-web3-secret-storage/test/Web3KeyStore.test.ts
  @planetarium/account/src/Account.ts
  @planetarium/account/src/RawPrivateKey.ts
  @planetarium/account/test/Account.test.ts
  @planetarium/account/test/RawPrivateKey.test.ts
  CHANGES.md
Labels: api, js

#3088 Add initialize state for genesis block
  CHANGES.md
  Libplanet.Extensions.Cocona/Commands/BlockCommand.cs
Labels: tools

#3085 Support `query.stateQuery.balance(...)` with custom currencies instead of `currencyHash`
  CHANGES.md
  Libplanet.Explorer.Tests/GraphTypes/BlockPolicyTypeTest.cs
  Libplanet.Explorer.Tests/GraphTypes/CurrencyInputTypeTest.cs
  Libplanet.Explorer.Tests/GraphTypes/CurrencyTypeTest.cs
  Libplanet.Explorer.Tests/GraphTypes/TxResultTypeTest.cs
  Libplanet.Explorer.Tests/Queries/StateQueryTest.cs
  Libplanet.Explorer/GraphTypes/CurrencyInputType.cs
  Libplanet.Explorer/GraphTypes/CurrencyType.cs
  Libplanet.Explorer/Queries/StateQuery.cs
Labels: explorer

#3097 Release 1.0.0
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: release

#3082 Introduce `IActionEvaluator`
  CHANGES.md
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet.Tests/TestUtils.cs
  Libplanet/Action/ActionEvaluator.cs
  Libplanet/Action/IActionEvaluator.cs
  Libplanet/Blockchain/BlockChain.cs
Labels: api

#3102 Bump `Bencodex` to `0.9.0`
  CHANGES.md
  Libplanet.Explorer/Libplanet.Explorer.csproj
  Libplanet/Libplanet.csproj
Labels: dependencies

#3113 Update return type for `IActionEvaluator.Evaluate()` to `IReadOnlyList<IActionEvaluation>`
  Libplanet/Action/ActionEvaluator.cs
  Libplanet/Action/IActionEvaluator.cs
  Libplanet/Blockchain/BlockChain.Swap.cs
Labels: api

#3114 Correct typo
  CHANGES.md
Labels: bug, docs

#3115 test(@planetarium/tx): correct tx test data
  @planetarium/tx/test/tx/signed.test.ts
  @planetarium/tx/test/tx/unsigned.test.ts
Labels: js

#3068 Deprecate pow block fields query
  Libplanet.Explorer/GraphTypes/BlockType.cs
Labels: Extra Small

#3120 Exclude seed peer when heartbeat in `Gossip`
  Libplanet.Net.Tests/Consensus/GossipTest.cs
  Libplanet.Net.Tests/SwarmTest.cs
  Libplanet.Net/Consensus/Gossip.cs
Labels: network
