Repository planetarium/libplanet, pull requests merged in 2023-06, with the labels that each got.

#3202 🚀 Release 1.4.0
  CHANGES.md
Labels: Extra Small

#3165 Improve commit() perf on trie related APIs
  CHANGES.md
  Libplanet/HashDigest.cs
  Libplanet/Store/Trie/MerkleTrie.cs
Labels: storage, Small, Squash Needed

#3201 introduce: fee collector
  @planetarium/tx/src/assets.ts
  @planetarium/tx/src/tx/metadata.ts
  @planetarium/tx/test/tx/metadata.test.ts
  @planetarium/tx/test/tx/signed.test.ts
  @planetarium/tx/test/tx/unsigned.test.ts
  CHANGES.md
  Libplanet.Explorer.Tests/GeneratedBlockChainFixture.cs
  Libplanet.Extensions.Cocona.Tests/Commands/StoreCommandTest.cs
  Libplanet.Net.Tests/SwarmTest.Preload.cs
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
  Libplanet.Tests/Assets/CurrencyTest.cs
  Libplanet.Tests/Blockchain/BlockChainTest.Internals.cs
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet.Tests/Fixtures/IntegerSet.cs
  Libplanet.Tests/Store/StoreFixture.cs
  Libplanet.Tests/Store/StoreTest.cs
  Libplanet.Tests/Tx/TransactionTest.cs
  Libplanet.Tests/Tx/TxInvoiceTest.cs
  Libplanet.Tests/Tx/TxMetadataTest.cs
  Libplanet.Tests/Tx/UnsignedTxTest.cs
  Libplanet/Action/ActionContext.cs
  Libplanet/Action/ActionEvaluator.cs
  Libplanet/Action/FeeCollector.cs
  Libplanet/Action/GasMeter.cs
  Libplanet/Action/IActionContext.cs
  Libplanet/Action/IFeeCollector.cs
  Libplanet/Assets/Currency.cs
  Libplanet/Assets/FungibleAssetValue.cs
  Libplanet/Blockchain/BlockChain.cs
  Libplanet/Tx/ITxInvoice.cs
  Libplanet/Tx/Transaction.cs
  Libplanet/Tx/TxInvoice.cs
  Libplanet/Tx/TxMarshaler.cs
  Libplanet/Tx/UnsignedTx.cs
Labels: Extra Large

#3209 ♻️ Refactor `ActionContext`
  CHANGES.md
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
  Libplanet.Tests/Action/Sys/InitializeTest.cs
  Libplanet/Action/ActionContext.cs
  Libplanet/Action/ActionEvaluator.cs
  Libplanet/Action/IActionContext.cs
Labels: Extra Small

#3210 🚀 Release 2.0.0
  CHANGES.md
Labels: release, Extra Small

#3211 Fix typo on changelog
  CHANGES.md
Labels: release, Extra Small

#3213 🔧 Prepare 2.1.0
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: release, Extra Small

#3212 🔧 Prepare 2.0.1
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: release, Extra Small

#3218 Eager TotalUpdatedFungibles update
  CHANGES.md
  Libplanet/State/AccountStateDeltaImpl.cs
  Libplanet/State/AccountStateDeltaImplV0.cs
Labels: Small, Squash Needed

#3214 ♻️ Expand `IBlockChainStates`
  CHANGES.md
  Libplanet.Explorer.Tests/Queries/StateQueryTest.cs
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet/Blockchain/BlockChain.cs
  Libplanet/Blockchain/BlockChainStates.cs
  Libplanet/Blockchain/IBlockChainStates.cs
  Libplanet/Blockchain/IncompleteBlockStatesException.cs
  Libplanet/Blockchain/NullChainStates.cs
Labels: Large

#3215 ♻️ Remove null getters for `ActionEvaluator`
  CHANGES.md
  Libplanet.Tests/Action/AccountStateDeltaImplTest.cs
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet/Action/ActionEvaluator.cs
  Libplanet/State/AccountStateDeltaImpl.cs
Labels: Large

#3216 ✨ Introduce `IBlockStates`
  CHANGES.md
  Libplanet.Explorer.Tests/Queries/StateQueryTest.cs
  Libplanet/Action/ActionEvaluator.cs
  Libplanet/Blockchain/BlockChain.cs
  Libplanet/Blockchain/BlockChainStates.cs
  Libplanet/Blockchain/ChainStateCache.cs
  Libplanet/Blockchain/IBlockChainStates.cs
  Libplanet/Blockchain/NullChainStates.cs
  Libplanet/Blocks/BlockStates.cs
  Libplanet/Blocks/BlockStatesCache.cs
  Libplanet/Blocks/IBlockStates.cs
Labels: Large

#3224 🚀 Release 2.1.0
  CHANGES.md
Labels: Extra Small

#3226 🔧 Prepare 2.1.1
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: Extra Small

#3227 🔧 Prepare 2.2.0
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: Extra Small

#3228 ♻️ Added `BlockProtocolVersion` to `IActionContext`
  CHANGES.md
  Libplanet.Tests/Action/ActionContextTest.cs
  Libplanet.Tests/Action/ActionEvaluationTest.cs
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
  Libplanet.Tests/Action/Sys/InitializeTest.cs
  Libplanet.Tests/Blockchain/Renderers/AnonymousActionRendererTest.cs
  Libplanet.Tests/Blockchain/Renderers/LoggedActionRendererTest.cs
  Libplanet/Action/ActionContext.cs
  Libplanet/Action/ActionEvaluator.cs
  Libplanet/Action/IActionContext.cs
Labels: Extra Small

#3225 fix(@planetarium/tx): correct `Currency` serialization
  @planetarium/tx/src/action.ts
  @planetarium/tx/src/assets.ts
  @planetarium/tx/src/tx/unsigned.ts
  @planetarium/tx/test/__snapshots__/action.test.ts.snap
  @planetarium/tx/test/__snapshots__/assets.test.ts.snap
  @planetarium/tx/test/tx/signed.test.ts
  @planetarium/tx/test/tx/unsigned.test.ts
  CHANGES.md
Labels: bug, Small, js

#3229 ♻️ Explicit `IActionContext` dependency for `TransferAsset()`
  CHANGES.md
  Libplanet.Tests/Action/AccountStateDeltaImplTest.cs
  Libplanet.Tests/Action/AccountStateDeltaImplV0Test.cs
  Libplanet.Tests/Action/AccountStateDeltaTest.cs
  Libplanet.Tests/Action/ActionContextTest.cs
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet.Tests/Common/Action/DumbAction.cs
  Libplanet/Action/ActionContext.cs
  Libplanet/Action/ActionEvaluator.cs
  Libplanet/State/AccountStateDeltaImpl.cs
  Libplanet/State/AccountStateDeltaImplV0.cs
  Libplanet/State/IAccountStateDelta.cs
Labels: Extra Large

#3232 Release 2.0.1
  CHANGES.md
Labels: Extra Small

#3231 ♻️ Explicit `IActionContext` dependency for `MintAsset()` and `BurnAsset()`
  CHANGES.md
  Libplanet.Tests/Action/AccountStateDeltaImplTest.cs
  Libplanet.Tests/Action/AccountStateDeltaTest.cs
  Libplanet.Tests/Action/ActionContextTest.cs
  Libplanet.Tests/Action/ActionEvaluationTest.cs
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
  Libplanet.Tests/Action/Sys/InitializeTest.cs
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet.Tests/Blockchain/Renderers/AnonymousActionRendererTest.cs
  Libplanet.Tests/Blockchain/Renderers/LoggedActionRendererTest.cs
  Libplanet.Tests/Fixtures/IntegerSet.cs
  Libplanet/Action/ActionEvaluator.cs
  Libplanet/Action/FeeCollector.cs
  Libplanet/State/AccountStateDeltaImpl.cs
  Libplanet/State/IAccountStateDelta.cs
Labels: Medium

#3234 Port 2.0.1 to 2.1.1
  @planetarium/tx/src/action.ts
  @planetarium/tx/src/assets.ts
  @planetarium/tx/src/tx/unsigned.ts
  @planetarium/tx/test/__snapshots__/action.test.ts.snap
  @planetarium/tx/test/__snapshots__/assets.test.ts.snap
  @planetarium/tx/test/tx/signed.test.ts
  @planetarium/tx/test/tx/unsigned.test.ts
  CHANGES.md
Labels: Small

#3235 🚀 Release 2.1.1
  CHANGES.md
Labels: Extra Small

#3237 🔀 Port 2.1.1 to main
  @planetarium/tx/src/action.ts
  @planetarium/tx/src/assets.ts
  @planetarium/tx/src/tx/unsigned.ts
  @planetarium/tx/test/__snapshots__/action.test.ts.snap
  @planetarium/tx/test/__snapshots__/assets.test.ts.snap
  @planetarium/tx/test/tx/signed.test.ts
  @planetarium/tx/test/tx/unsigned.test.ts
  CHANGES.md
Labels: Small

#3238 🧹 Housekeeping
  CHANGES.md
  Libplanet.Tests/Action/AccountStateDeltaTest.cs
  Libplanet.Tests/Action/AccountStateDeltaV0Test.cs
  Libplanet.Tests/Action/AccountStateDeltaV1Test.cs
  Libplanet.Tests/Action/ActionEvaluationTest.cs
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
  Libplanet.Tests/Action/Sys/InitializeTest.cs
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet.Tests/Blockchain/Renderers/AnonymousActionRendererTest.cs
  Libplanet.Tests/Blockchain/Renderers/LoggedActionRendererTest.cs
  Libplanet.Tests/Fixtures/IntegerSet.cs
  Libplanet/Action/ActionEvaluator.cs
  Libplanet/State/AccountStateDelta.cs
Labels: Small

#3239 🧹 Removed `json` syntax highlighting in changelog
  CHANGES.md
Labels: Extra Small

#3240 🚀 Release 2.2.0
  CHANGES.md
Labels: Extra Small

#3242 🔧 Prepare 2.3.0
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: Extra Small

#3244 ♻️ Returned data structures for `IAccountStateDelta` changed for more consistency
  CHANGES.md
  Libplanet.Tests/Action/AccountStateDeltaTest.cs
  Libplanet.Tests/Action/AccountStateDeltaV1Test.cs
  Libplanet.Tests/Action/ActionContextTest.cs
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
  Libplanet/Action/ActionEvaluationsExtensions.cs
  Libplanet/Blockchain/BlockChain.TxExecution.cs
  Libplanet/State/AccountStateDelta.cs
  Libplanet/State/AccountStateDeltaExtensions.cs
  Libplanet/State/IAccountStateDelta.cs
Labels: Medium

#3230 fix(@planetarium/tx): remove separate actions
  @planetarium/tx/src/action.ts
  @planetarium/tx/src/index.ts
  @planetarium/tx/src/tx/index.ts
  @planetarium/tx/src/tx/signed.ts
  @planetarium/tx/src/tx/unsigned.ts
  @planetarium/tx/test/__snapshots__/action.test.ts.snap
  @planetarium/tx/test/action.test.ts
  @planetarium/tx/test/tx/signed.test.ts
  @planetarium/tx/test/tx/unsigned.test.ts
  CHANGES.md
Labels: bug, Large, js

#3245 ✨ Introduce `IAccountDelta`
  CHANGES.md
  Libplanet.Tests/Action/ActionContextTest.cs
  Libplanet/State/AccountDelta.cs
  Libplanet/State/AccountStateDelta.cs
  Libplanet/State/IAccountDelta.cs
  Libplanet/State/IAccountStateDelta.cs
Labels: Medium

#3247 ♻️ Remove `IValidatorSupportStateDelta`
  CHANGES.md
  Libplanet.Tests/Action/ActionContextTest.cs
  Libplanet/State/AccountStateDelta.cs
  Libplanet/State/IAccountStateDelta.cs
  Libplanet/State/IAccountStateView.cs
  Libplanet/State/IValidatorSupportStateDelta.cs
  Libplanet/State/ValidatorStateExtensions.cs
Labels: Extra Small

#3248 ♻️ API streamlining related to `IAccountStateDelta`
  CHANGES.md
  Libplanet.Tests/Action/AccountStateDeltaTest.cs
  Libplanet.Tests/Action/AccountStateDeltaV1Test.cs
  Libplanet.Tests/Action/ActionContextTest.cs
  Libplanet/Action/ActionEvaluationsExtensions.cs
  Libplanet/State/AccountStateDelta.cs
  Libplanet/State/AccountStateDeltaExtensions.cs
  Libplanet/State/IAccountStateDelta.cs
  Libplanet/Tx/TxSuccess.cs
Labels: Medium

#3250 ♻️ Rename `IAccountStateView` to `IAccountState`
  CHANGES.md
  Libplanet.Explorer.Tests/Queries/StateQueryTest.cs
  Libplanet/Blockchain/BlockChain.cs
  Libplanet/Blockchain/BlockChainStates.cs
  Libplanet/Blockchain/IBlockChainStates.cs
  Libplanet/Blockchain/NullChainStates.cs
  Libplanet/Blocks/BlockStates.cs
  Libplanet/Blocks/IBlockStates.cs
  Libplanet/State/AccountStateDelta.cs
  Libplanet/State/IAccountState.cs
  Libplanet/State/IAccountStateDelta.cs
  Libplanet/State/TotalSupplyNotTrackableException.cs
Labels: Extra Small

#3251 ♻️ Refactor `AccountStateDelta` internal API
  CHANGES.md
  Libplanet.Tests/Action/AccountStateDeltaTest.cs
  Libplanet.Tests/Action/ActionEvaluationTest.cs
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
  Libplanet.Tests/Action/Sys/InitializeTest.cs
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet.Tests/Blockchain/Renderers/AnonymousActionRendererTest.cs
  Libplanet.Tests/Blockchain/Renderers/LoggedActionRendererTest.cs
  Libplanet.Tests/Fixtures/IntegerSet.cs
  Libplanet.Tests/Mocks/MockAccountState.cs
  Libplanet/Action/ActionEvaluator.cs
  Libplanet/Blocks/BlockStates.cs
  Libplanet/Blocks/IBlockStates.cs
  Libplanet/State/AccountStateDelta.cs
Labels: Medium

#3252 🚀 Release 2.3.0
  CHANGES.md
Labels: Extra Small

#3255 🔧 Prepare 2.4.0
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: Extra Small

#3256 ✨ Added `IAccountDelta` sum and raw-delta
  CHANGES.md
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
  Libplanet.Tests/Blockchain/BlockChainTest.Internals.cs
  Libplanet.Tests/Store/StoreFixture.cs
  Libplanet/Action/ActionEvaluationsExtensions.cs
  Libplanet/Blockchain/BlockChain.Evaluate.cs
  Libplanet/Blockchain/BlockChain.cs
  Libplanet/Blocks/BlockStates.cs
  Libplanet/State/AccountDeltaExtensions.cs
  Libplanet/State/AccountStateDeltaExtensions.cs
  Libplanet/State/KeyConverters.cs
Labels: Medium

#3257 ♻️ Reroute `IAccountDelta` access
  CHANGES.md
  Libplanet.Tests/Action/AccountStateDeltaTest.cs
  Libplanet.Tests/Action/AccountStateDeltaV1Test.cs
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
  Libplanet/Action/ActionEvaluator.cs
  Libplanet/Blockchain/BlockChain.TxExecution.cs
  Libplanet/State/AccountStateDelta.cs
  Libplanet/State/IAccountStateDelta.cs
Labels: Medium
