Repository planetarium/libplanet, pull requests merged in 2023-08, with the labels that each got.

#3345 🧹 Remove offloading from MerkleTrie
  Libplanet.Store/Trie/MerkleTrie.cs
Labels: Medium

#3346 chore: update docstring and minor refactoring
  Libplanet.Action.Tests/Mocks/MockWorldState.cs
  Libplanet.Action.Tests/State/WorldTest.cs
  Libplanet.Action/State/IWorld.cs
  Libplanet.Action/State/IWorldDelta.cs
  Libplanet.Action/State/IWorldState.cs
  Libplanet.Action/State/World.cs
  Libplanet.Action/State/WorldDelta.cs
Labels: Extra Small

#3348 Remove nullable from `IWorld.GetAccount()`
  Libplanet.Action/State/IWorld.cs
  Libplanet.Action/State/IWorldState.cs
  Libplanet.Action/State/World.cs
Labels: Extra Small

#3347 ♻️ Cleanup and optimize `MerkleTrie.Get()`
  CHANGES.md
  Libplanet.Store/Trie/MerkleTrie.cs
Labels: Extra Small

#3349 🔧 Fix csproj
  Libplanet.Tests/Libplanet.Tests.csproj
Labels: Extra Small

#3353 fix: check block is in chain
  Libplanet.Net/Swarm.BlockSync.cs
Labels: bug, network, Extra Small

#3358 🧹 Removed Bencodex `Fingerprint` support
  Libplanet.Store/Trie/MerkleTrie.cs
  Libplanet.Tests/Store/TrieStateStoreTest.cs
Labels: Extra Small

#3357 🧹 Removed FungibleAssetsDelta and ExceptionMetadata
  CHANGES.md
  Libplanet.Explorer.Tests/GraphTypes/TxResultTypeTest.cs
  Libplanet.Explorer/GraphTypes/TxResult.cs
  Libplanet.Explorer/GraphTypes/TxResultType.cs
  Libplanet.Explorer/Queries/TransactionQuery.cs
  Libplanet.Store/BaseStore.cs
  Libplanet.Tests/Blockchain/BlockChainTest.Append.cs
  Libplanet.Tests/Blockchain/BlockChainTest.Internals.cs
  Libplanet.Tests/Store/StoreTest.cs
  Libplanet.Tests/Tx/TxSuccessTest.cs
  Libplanet.Types/Tx/TxSuccess.cs
  Libplanet/Blockchain/BlockChain.TxExecution.cs
Labels: Medium

#3359 ♻️ Added single `Get()` to `ITrie`
  CHANGES.md
  Libplanet.Store/Trie/ITrie.cs
  Libplanet.Store/Trie/MerkleTrie.cs
  Libplanet.Tests/Store/Trie/MerkleTrieTest.cs
Labels: Medium

#3360 Cherry-pick #3353 to 3.1.1 version
  CHANGES.md
  Libplanet.Net/Swarm.BlockSync.cs
Labels: bug, network, Extra Small

#3363 🚀 Release 3.1.1
  CHANGES.md
Labels: Extra Small

#3365 ⬆️ Bump Bencodex to 0.14.0
  CHANGES.md
  Libplanet.Action/Libplanet.Action.csproj
  Libplanet.Crypto/Libplanet.Crypto.csproj
  Libplanet.Store/Libplanet.Store.csproj
  Libplanet.Types/Libplanet.Types.csproj
  Libplanet/Libplanet.csproj
Labels: Extra Small

#3364 🔀 Merge 3.1.1 into main
  CHANGES.md
Labels: Extra Small

#3366 🔧 Prepare 3.1.2
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: Extra Small

#3367 🔀 ⬆️ Backport Bencodex bump to 0.14.0
  CHANGES.md
  Libplanet.Action/Libplanet.Action.csproj
  Libplanet.Crypto/Libplanet.Crypto.csproj
  Libplanet.Store/Libplanet.Store.csproj
  Libplanet.Store/Trie/MerkleTrie.cs
  Libplanet.Types/Libplanet.Types.csproj
  Libplanet/Libplanet.csproj
Labels: Medium

#3369 🚀 Release 3.1.2
  CHANGES.md
Labels: Extra Small

#3371 🔀 Port 3.1.2 to main
  CHANGES.md
Labels: Extra Small

#3370 🔧 Prepare 3.1.3
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: Extra Small

#3372 🚀 Release 3.2.0
  CHANGES.md
Labels: Extra Small

#3375 🔧 Prepare 3.3.0
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: Extra Small

#3376 🔧 Prepare 3.2.1
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: Extra Small

#3361 Introduce `VolatileKeyValueStore`
  CHANGES.md
  Libplanet.Explorer.Executable/Program.cs
  Libplanet.Store/IStateStore.cs
  Libplanet.Store/Trie/VolatileKeyValueStore.cs
  Libplanet.Store/TrieStateStore.cs
  Libplanet.Tests/Store/StateStoreTracker.cs
  Libplanet.Tests/Store/Trie/KeyValueStoreTest.cs
  Libplanet.Tests/Store/Trie/VolatileKeyValueStoreTest.cs
  Libplanet.Tests/Store/TrieStateStoreTest.cs
  Libplanet/Blockchain/BlockChainStates.cs
Labels: Medium

#3379 fix(ci): change macos resource
  .circleci/config.yml
Labels: ci & cd

#3381 fix(test): Cleaning Swarm when finish each tests
  Libplanet.Net.Tests/SwarmTest.Broadcast.cs
  Libplanet.Net.Tests/SwarmTest.Preload.cs
  Libplanet.Net.Tests/SwarmTest.cs
  Libplanet.Net/Transports/NetMQTransport.cs
Labels: bug, ci & cd, Large

#3382 fix: dispose rocksdb when finish tests
  Libplanet.Extensions.Cocona.Tests/Commands/StatsCommandTest.cs
  Libplanet.Extensions.Cocona.Tests/Commands/StoreCommandTest.cs
Labels: bug, Extra Small

#3385 fix(ci): ignore malicious tests
  .circleci/config.yml
Labels: Extra Small

#3387 fix: do not use codecov when running circle ci
  .circleci/config.yml
Labels: Extra Small

#3356 feat(#3354): support rocksdb read-only mode
  CHANGES.md
  Libplanet.RocksDBStore/RocksDBKeyValueStore.cs
  Libplanet.RocksDBStore/RocksDBStore.cs
  Libplanet.RocksDBStore/RocksDBUtils.cs
Labels: storage, Small

#3377 Fix node equality for `INode`
  CHANGES.md
  Libplanet.Store/Trie/Nodes/FullNode.cs
  Libplanet.Store/Trie/Nodes/HashNode.cs
  Libplanet.Store/Trie/Nodes/ShortNode.cs
  Libplanet.Store/Trie/Nodes/ValueNode.cs
Labels: bug, Small

#3390 ♻️ `MerkleTrie` overhaul
  CHANGES.md
  Libplanet.Store/Trie/MerkleTrie.Path.cs
  Libplanet.Store/Trie/MerkleTrie.cs
  Libplanet.Store/Trie/MerkleTrieExtensions.cs
  Libplanet.Store/Trie/Nodes/BaseNode.cs
  Libplanet.Store/Trie/Nodes/NodeDecoder.cs
  Libplanet.Store/Trie/Nodes/ShortNode.cs
  Libplanet.Tests/Store/Trie/MerkleTrieExtensionsTest.cs
  Libplanet.Tests/Store/Trie/MerkleTriePathCursorTest.cs
  Libplanet.Tests/Store/Trie/MerkleTrieTest.cs
  Libplanet.Tests/Store/Trie/TrieTest.cs
Labels: Large

#3392 introduce: `IRecordableTrie`
  CHANGES.md
  Libplanet.Action.Tests/ActionContextTest.cs
  Libplanet.Action.Tests/ActionEvaluationTest.cs
  Libplanet.Action.Tests/Mocks/MockAccount.cs
  Libplanet.Action.Tests/Mocks/MockAccountState.cs
  Libplanet.Action.Tests/Sys/InitializeTest.cs
  Libplanet.Action/ActionEvaluator.cs
  Libplanet.Action/State/Account.cs
  Libplanet.Action/State/AccountDelta.cs
  Libplanet.Action/State/BlockState.cs
  Libplanet.Action/State/BlockStateCache.cs
  Libplanet.Action/State/IAccount.cs
  Libplanet.Action/State/IBlockChainStates.cs
  Libplanet.Action/State/IBlockState.cs
  Libplanet.Explorer.Executable/Program.cs
  Libplanet.Explorer.Tests/Queries/StateQueryTest.cs
  Libplanet.Extensions.Cocona.Tests/Commands/MptCommandTest.cs
  Libplanet.Store/IStateStore.cs
  Libplanet.Store/StateStoreExtensions.cs
  Libplanet.Store/Trie/IRecordableTrie.cs
  Libplanet.Store/Trie/ITrie.cs
  Libplanet.Store/Trie/MerkleTrie.cs
  Libplanet.Store/Trie/TrieExtensions.cs
  Libplanet.Store/TrieStateStore.cs
  Libplanet.Tests/Action/AccountTest.cs
  Libplanet.Tests/Action/AccountV1Test.cs
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet.Tests/Blockchain/Renderers/AnonymousActionRendererTest.cs
  Libplanet.Tests/Blockchain/Renderers/LoggedActionRendererTest.cs
  Libplanet.Tests/Fixtures/IntegerSet.cs
  Libplanet.Tests/Store/StateStoreTracker.cs
  Libplanet.Tests/Store/Trie/MerkleTrieExtensionsTest.cs
  Libplanet.Tests/Store/Trie/MerkleTrieTest.cs
  Libplanet.Tests/Store/Trie/TrieTest.cs
  Libplanet.Tests/Store/TrieStateStoreTest.cs
  Libplanet/Blockchain/BlockChain.Evaluate.cs
  Libplanet/Blockchain/BlockChain.cs
  Libplanet/Blockchain/BlockChainStates.cs
  Libplanet/Blockchain/NullChainStates.cs
Labels: Extra Large

#3400 🧹 Removed unused `IKeyValueStore.Get()`
  CHANGES.md
  Libplanet.RocksDBStore/RocksDBKeyValueStore.cs
  Libplanet.Store/Trie/CacheableKeyValueStore.cs
  Libplanet.Store/Trie/DefaultKeyValueStore.cs
  Libplanet.Store/Trie/IKeyValueStore.cs
  Libplanet.Store/Trie/MemoryKeyValueStore.cs
  Libplanet.Tests/Store/Trie/KeyValueStoreTest.cs
Labels: Small

#3399 ✨ Introduce `Nibbles`
  CHANGES.md
  Libplanet.Store/Trie/MerkleTrie.Path.cs
  Libplanet.Store/Trie/MerkleTrie.cs
  Libplanet.Store/Trie/MerkleTrieExtensions.cs
  Libplanet.Store/Trie/Nibbles.cs
  Libplanet.Store/Trie/Nodes/NodeDecoder.cs
  Libplanet.Store/Trie/Nodes/ShortNode.cs
  Libplanet.Store/Trie/PathCursor.cs
  Libplanet.Tests/Store/Trie/NibblesTest.cs
  Libplanet.Tests/Store/Trie/Nodes/NodeDecoderTest.cs
  Libplanet.Tests/Store/Trie/Nodes/ShortNodeTest.cs
  Libplanet.Tests/Store/Trie/PathCursorTest.cs
Labels: Extra Large

#3402 🧹 Remove unnecessary `interface`s from `KeyBytes`
  CHANGES.md
  Libplanet.Store/Trie/KeyBytes.cs
  Libplanet.Tests/Store/Trie/KeyBytesTest.cs
Labels: Extra Small

#3401 ✨ Introduce `ITrie.GetNode()`
  CHANGES.md
  Libplanet.Store/Trie/ITrie.cs
  Libplanet.Store/Trie/MemoryKeyValueStore.cs
  Libplanet.Store/Trie/MerkleTrie.Path.cs
  Libplanet.Store/Trie/MerkleTrie.cs
  Libplanet.Store/Trie/PathCursor.cs
  Libplanet.Store/TrieStateStore.Commit.cs
  Libplanet.Tests/Store/Trie/MerkleTrieTest.cs
  Libplanet.Tests/Store/Trie/PathCursorTest.cs
Labels: storage, Medium

#3403 ♻️ Refactor `NodeDecoder`
  Libplanet.Store/Trie/MerkleTrie.cs
  Libplanet.Store/Trie/Nodes/NodeDecoder.cs
  Libplanet.Tests/Store/Trie/Nodes/NodeDecoderTest.cs
Labels: Medium
