Repository planetarium/libplanet, pull requests merged in 2023-09, with the labels that each got.

#3405 ✨ Introduce `ITrie.IterateValues()` and `ITrie.IterateNodes()`
  Libplanet.Extensions.Cocona/Commands/MptCommand.cs
  Libplanet.Store/Trie/ITrie.cs
  Libplanet.Store/Trie/MerkleTrie.cs
  Libplanet.Store/Trie/MerkleTrieExtensions.cs
  Libplanet.Tests/Store/Trie/MerkleTrieExtensionsTest.cs
  Libplanet.Tests/Store/Trie/MerkleTrieTest.cs
  Libplanet.Tests/Store/TrieStateStoreCommitTest.cs
Labels: Small

#3406 🧹 Changelog
  CHANGES.md
Labels: Extra Small

#3407 🧹 Remove `Secure` from `TrieStateStore`
  CHANGES.md
  Libplanet.RocksDBStore/RocksDBKeyValueStore.cs
  Libplanet.RocksDBStore/RocksDBStore.cs
  Libplanet.Store/DefaultStore.cs
  Libplanet.Store/MemoryStore.cs
  Libplanet.Store/Trie/DefaultKeyValueStore.cs
  Libplanet.Store/Trie/ITrie.cs
  Libplanet.Store/Trie/MemoryKeyValueStore.cs
  Libplanet.Store/Trie/MerkleTrie.cs
  Libplanet.Store/Trie/MerkleTrieExtensions.cs
  Libplanet.Store/Trie/PathCursor.cs
  Libplanet.Store/TrieStateStore.Commit.cs
  Libplanet.Store/TrieStateStore.cs
  Libplanet.Tests/Store/MemoryStoreTest.cs
  Libplanet.Tests/Store/StateStoreExtensionsTest.cs
  Libplanet.Tests/Store/StoreLoaderAttributeTest.cs
  Libplanet.Tests/Store/Trie/PathCursorTest.cs
  Libplanet.Tests/Store/TrieStateStoreTest.cs
Labels: Medium

#3408 🧹 More distinction/clarification for `Nibbles` creation
  Libplanet.Common/ByteUtil.cs
  Libplanet.Store/Trie/Nibbles.cs
  Libplanet.Store/Trie/PathCursor.cs
  Libplanet.Tests/Store/Trie/NibblesTest.cs
  Libplanet.Tests/Store/Trie/Nodes/ShortNodeTest.cs
  Libplanet.Tests/Store/Trie/PathCursorTest.cs
Labels: Small

#3412 ♻️ Refactor `Account`
  Libplanet.Action/State/Account.cs
Labels: Medium

#3410 ✨ Feature `ITrie.Diff()`
  CHANGES.md
  Libplanet.Extensions.Cocona.Tests/Commands/MptCommandTest.cs
  Libplanet.Extensions.Cocona/Commands/MptCommand.cs
  Libplanet.Store/Trie/ITrie.cs
  Libplanet.Store/Trie/MerkleTrie.Diff.cs
  Libplanet.Store/Trie/MerkleTrieExtensions.cs
  Libplanet.Tests/Store/Trie/MerkleTrieDiffTest.cs
  Libplanet.Tests/Store/Trie/MerkleTrieExtensionsTest.cs
  Libplanet.Tests/Store/Trie/MerkleTrieTest.cs
Labels: Large

#3411 🧹 Fix `BlockChain.DetermineStateRootHash`
  Libplanet.Store/StoreExtensions.cs
  Libplanet/Blockchain/BlockChain.Evaluate.cs
Labels: Extra Small

#3413 ♻️ Partial API rollback fork `IAccount`
  CHANGES.md
  Libplanet.Action.Tests/ActionContextTest.cs
  Libplanet.Action.Tests/ActionEvaluationTest.cs
  Libplanet.Action.Tests/Mocks/MockAccount.cs
  Libplanet.Action.Tests/Mocks/MockAccountState.cs
  Libplanet.Action.Tests/Sys/InitializeTest.cs
  Libplanet.Action/ActionEvaluator.cs
  Libplanet.Action/State/Account.cs
  Libplanet.Action/State/IAccount.cs
  Libplanet.Action/State/IAccountState.cs
  Libplanet.Action/State/IBlockChainStates.cs
  Libplanet.Explorer.Tests/Queries/StateQueryTest.cs
  Libplanet.Tests/Action/AccountTest.cs
  Libplanet.Tests/Blockchain/Renderers/AnonymousActionRendererTest.cs
  Libplanet.Tests/Blockchain/Renderers/LoggedActionRendererTest.cs
  Libplanet.Tests/Fixtures/IntegerSet.cs
  Libplanet/Blockchain/BlockChain.cs
  Libplanet/Blockchain/BlockChainStates.cs
  Libplanet/Blockchain/NullChainStates.cs
Labels: Large

#3415 Add .gitallowed for git secrets
  .gitallowed
Labels: Medium

#3416 Remove trie mutation from Account
  CHANGES.md
  Libplanet.Action.Tests/ActionContextTest.cs
  Libplanet.Action.Tests/ActionEvaluationTest.cs
  Libplanet.Action.Tests/Sys/InitializeTest.cs
  Libplanet.Action/ActionEvaluator.cs
  Libplanet.Action/State/Account.cs
  Libplanet.Action/State/AccountState.cs
  Libplanet.Action/State/AccountStateCache.cs
  Libplanet.Tests/Action/AccountTest.cs
  Libplanet.Tests/Blockchain/Renderers/AnonymousActionRendererTest.cs
  Libplanet.Tests/Blockchain/Renderers/LoggedActionRendererTest.cs
  Libplanet.Tests/Fixtures/IntegerSet.cs
  Libplanet/Blockchain/BlockChain.Evaluate.cs
  Libplanet/Blockchain/BlockChainStates.cs
  Libplanet/Blockchain/NullChainStates.cs
Labels: Large

#3417 🚀 Release 3.3.0
  CHANGES.md
Labels: Extra Small

#3419 🔧 Prepare 3.3.1
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: Extra Small

#3418 🔧 Prepare 3.4.0
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: Extra Small

#3420 🐛 Fix `ITrie.Get()`
  CHANGES.md
  Libplanet.Store/Trie/MerkleTrie.Path.cs
  Libplanet.Tests/Store/Trie/MerkleTrieTest.cs
Labels: Extra Small

#3421 🚀 Release 3.3.1
  CHANGES.md
Labels: Extra Small

#3423 🔀 Merge 3.3.1 to main
  CHANGES.md
  Libplanet.Store/Trie/MerkleTrie.Path.cs
  Libplanet.Tests/Store/Trie/MerkleTrieTest.cs
Labels: Extra Small

#3425 Added new GetAccountState() interface method
  CHANGES.md
  Libplanet.Action/State/IBlockChainStates.cs
  Libplanet.Explorer.Tests/Queries/StateQueryTest.cs
  Libplanet/Blockchain/BlockChain.cs
  Libplanet/Blockchain/BlockChainStates.cs
  Libplanet/Blockchain/NullChainStates.cs
Labels: Extra Small

#3427 ♻️ Refactor `IActionRenderer`
  CHANGES.md
  Libplanet.Action.Tests/Sys/InitializeTest.cs
  Libplanet.Action/ActionRenderContext.cs
  Libplanet.Action/IActionRenderContext.cs
  Libplanet.Action/State/IBlockChainStates.cs
  Libplanet.Explorer.Tests/Queries/StateQueryTest.cs
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
  Libplanet.Tests/Blockchain/BlockChainTest.Append.cs
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet.Tests/Blockchain/Renderers/AnonymousActionRendererTest.cs
  Libplanet.Tests/Blockchain/Renderers/LoggedActionRendererTest.cs
  Libplanet.Tests/Store/TrieStateStoreTest.cs
  Libplanet/Blockchain/BlockChain.Swap.cs
  Libplanet/Blockchain/BlockChain.cs
  Libplanet/Blockchain/BlockChainStates.cs
  Libplanet/Blockchain/NullChainStates.cs
  Libplanet/Blockchain/Renderers/AnonymousActionRenderer.cs
  Libplanet/Blockchain/Renderers/AtomicActionRenderer.cs
  Libplanet/Blockchain/Renderers/Debug/RecordingActionRenderer.cs
  Libplanet/Blockchain/Renderers/Debug/RenderRecord.cs
  Libplanet/Blockchain/Renderers/Debug/ValidatingActionRenderer.cs
  Libplanet/Blockchain/Renderers/IActionRenderer.cs
  Libplanet/Blockchain/Renderers/LoggedActionRenderer.cs
Labels: Large

#3424 Initial implementation of AccountDiff
  CHANGES.md
  Libplanet.Action/State/AccountDiff.cs
  Libplanet.Tests/Action/AccountDiffTest.cs
Labels: Large

#3428 ♻️ Cleanup `TxSuccess` and `TxFailure`
  CHANGES.md
  Libplanet.Store/BaseStore.cs
  Libplanet.Tests/Blockchain/BlockChainTest.Append.cs
  Libplanet.Tests/Blockchain/BlockChainTest.Internals.cs
  Libplanet.Tests/Store/StoreTest.cs
  Libplanet.Tests/Tx/TxFailureTest.cs
  Libplanet.Tests/Tx/TxSuccessTest.cs
  Libplanet.Types/Tx/TxExecution.cs
  Libplanet.Types/Tx/TxFailure.cs
  Libplanet.Types/Tx/TxSuccess.cs
Labels: Medium

#3429 ♻️ `TxExecution` overhaul
  CHANGES.md
  Libplanet.Explorer.Tests/GraphTypes/TxResultTypeTest.cs
  Libplanet.Explorer.Tests/Queries/TransactionQueryGeneratedTest.cs
  Libplanet.Explorer/GraphTypes/TxResult.cs
  Libplanet.Explorer/GraphTypes/TxResultType.cs
  Libplanet.Explorer/Queries/TransactionQuery.cs
  Libplanet.Explorer/Store/LiteDBRichStore.cs
  Libplanet.Explorer/Store/MySQLRichStore.cs
  Libplanet.RocksDBStore/RocksDBStore.cs
  Libplanet.Store/BaseStore.cs
  Libplanet.Store/DefaultStore.cs
  Libplanet.Store/IStore.cs
  Libplanet.Store/MemoryStore.cs
  Libplanet.Tests/Blockchain/BlockChainTest.Append.cs
  Libplanet.Tests/Blockchain/BlockChainTest.Internals.cs
  Libplanet.Tests/Blockchain/BlockChainTest.ProposeBlock.cs
  Libplanet.Tests/Store/ProxyStore.cs
  Libplanet.Tests/Store/StoreTest.cs
  Libplanet.Tests/Store/StoreTracker.cs
  Libplanet.Tests/Tx/TxExecutionTest.cs
  Libplanet.Tests/Tx/TxFailureTest.cs
  Libplanet.Tests/Tx/TxSuccessTest.cs
  Libplanet.Types/Tx/TxExecution.cs
  Libplanet.Types/Tx/TxFailure.cs
  Libplanet.Types/Tx/TxSuccess.cs
  Libplanet/Blockchain/BlockChain.TxExecution.cs
Labels: Extra Large

#3430 🧹 Remove unnecessary clutter
  Libplanet/Blockchain/BlockChain.Swap.cs
Labels: Extra Small

#3431 ♻️ Commit once for `IActionEvaluation`s
  CHANGES.md
  Libplanet.Action/ActionContext.cs
  Libplanet.Action/CommittedActionContext.cs
  Libplanet.Action/CommittedActionEvaluation.cs
  Libplanet.Action/ICommittedActionContext.cs
  Libplanet.Action/ICommittedActionEvaluation.cs
  Libplanet.Action/Random.cs
  Libplanet.Net/Consensus/Context.cs
  Libplanet.Tests/Blockchain/BlockChainTest.Append.cs
  Libplanet.Tests/Blockchain/Renderers/AnonymousActionRendererTest.cs
  Libplanet.Tests/Blockchain/Renderers/LoggedActionRendererTest.cs
  Libplanet/Blockchain/BlockChain.Evaluate.cs
  Libplanet/Blockchain/BlockChain.Swap.cs
  Libplanet/Blockchain/BlockChain.TxExecution.cs
  Libplanet/Blockchain/BlockChain.Validate.cs
  Libplanet/Blockchain/BlockChain.cs
  Libplanet/Blockchain/Renderers/AnonymousActionRenderer.cs
  Libplanet/Blockchain/Renderers/AtomicActionRenderer.cs
  Libplanet/Blockchain/Renderers/Debug/RecordingActionRenderer.cs
  Libplanet/Blockchain/Renderers/Debug/RenderRecord.cs
  Libplanet/Blockchain/Renderers/Debug/ValidatingActionRenderer.cs
  Libplanet/Blockchain/Renderers/IActionRenderer.cs
  Libplanet/Blockchain/Renderers/LoggedActionRenderer.cs
Labels: Large

#3433 🧹 Docs fix
  Libplanet.Store/IStore.cs
Labels: No Changes

#3432 Migrate to `ITrie`
  CHANGES.md
  Libplanet.Action.Tests/Sys/InitializeTest.cs
  Libplanet.Action/ActionContext.cs
  Libplanet.Action/CommittedActionContext.cs
  Libplanet.Action/CommittedActionEvaluation.cs
  Libplanet.Action/ICommittedActionContext.cs
  Libplanet.Action/ICommittedActionEvaluation.cs
  Libplanet.Action/Random.cs
  Libplanet.Action/State/AccountDiff.cs
  Libplanet.Explorer.Tests/GraphTypes/TxResultTypeTest.cs
  Libplanet.Explorer.Tests/Queries/StateQueryTest.cs
  Libplanet.Explorer.Tests/Queries/TransactionQueryGeneratedTest.cs
  Libplanet.Explorer/GraphTypes/TxResult.cs
  Libplanet.Explorer/GraphTypes/TxResultType.cs
  Libplanet.Explorer/Queries/TransactionQuery.cs
  Libplanet.Explorer/Store/LiteDBRichStore.cs
  Libplanet.Explorer/Store/MySQLRichStore.cs
  Libplanet.Net/Consensus/Context.cs
  Libplanet.RocksDBStore/RocksDBStore.cs
  Libplanet.Store/BaseStore.cs
  Libplanet.Store/DefaultStore.cs
  Libplanet.Store/IStore.cs
  Libplanet.Store/MemoryStore.cs
  Libplanet.Tests/Action/AccountDiffTest.cs
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
  Libplanet.Tests/Blockchain/BlockChainTest.Append.cs
  Libplanet.Tests/Blockchain/BlockChainTest.Internals.cs
  Libplanet.Tests/Blockchain/BlockChainTest.ProposeBlock.cs
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet.Tests/Blockchain/Renderers/AnonymousActionRendererTest.cs
  Libplanet.Tests/Blockchain/Renderers/LoggedActionRendererTest.cs
  Libplanet.Tests/Store/ProxyStore.cs
  Libplanet.Tests/Store/StoreTest.cs
  Libplanet.Tests/Store/StoreTracker.cs
  Libplanet.Tests/Store/TrieStateStoreTest.cs
  Libplanet.Tests/Tx/TxExecutionTest.cs
  Libplanet.Tests/Tx/TxFailureTest.cs
  Libplanet.Tests/Tx/TxSuccessTest.cs
  Libplanet.Types/Tx/TxExecution.cs
  Libplanet.Types/Tx/TxFailure.cs
  Libplanet.Types/Tx/TxSuccess.cs
  Libplanet/Blockchain/BlockChain.Evaluate.cs
  Libplanet/Blockchain/BlockChain.Swap.cs
  Libplanet/Blockchain/BlockChain.TxExecution.cs
  Libplanet/Blockchain/BlockChain.Validate.cs
  Libplanet/Blockchain/BlockChain.cs
  Libplanet/Blockchain/Renderers/AnonymousActionRenderer.cs
  Libplanet/Blockchain/Renderers/AtomicActionRenderer.cs
  Libplanet/Blockchain/Renderers/Debug/RecordingActionRenderer.cs
  Libplanet/Blockchain/Renderers/Debug/RenderRecord.cs
  Libplanet/Blockchain/Renderers/Debug/ValidatingActionRenderer.cs
  Libplanet/Blockchain/Renderers/IActionRenderer.cs
  Libplanet/Blockchain/Renderers/LoggedActionRenderer.cs
Labels: Extra Large

#3434 🚀 Release 3.4.0
  CHANGES.md
Labels: Extra Small

#3422 🔧 Prepare 3.3.2
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: Extra Small

#3435 🔧 Prepare 3.5.0
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: Extra Small
