Repository planetarium/libplanet, pull requests merged in 2023-07, with the labels that each got.

#3259 ♻️ General name changes
  CHANGES.md
  Libplanet.Analyzers.Tests/ActionAnalyzerTest.cs
  Libplanet.Analyzers/rules/LAA1001.md
  Libplanet.Analyzers/rules/LAA1002.md
  Libplanet.Explorer.Tests/Queries/StateQueryTest.cs
  Libplanet.Explorer.Tests/SimpleAction.cs
  Libplanet.Extensions.Cocona/Utils.cs
  Libplanet.Net.Tests/SwarmTest.cs
  Libplanet.Tests/Action/ActionContextTest.cs
  Libplanet.Tests/Action/ActionEvaluationExtensions.cs
  Libplanet.Tests/Action/ActionEvaluationTest.cs
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
  Libplanet.Tests/Action/Sys/InitializeTest.cs
  Libplanet.Tests/Blockchain/BlockChainTest.Append.cs
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet.Tests/Common/Action/Attack.cs
  Libplanet.Tests/Common/Action/DelayAction.cs
  Libplanet.Tests/Common/Action/DetectRehearsal.cs
  Libplanet.Tests/Common/Action/DumbAction.cs
  Libplanet.Tests/Common/Action/MinerReward.cs
  Libplanet.Tests/Common/Action/RandomAction.cs
  Libplanet.Tests/Common/Action/SetStatesAtBlock.cs
  Libplanet.Tests/Common/Action/SetValidator.cs
  Libplanet.Tests/Common/Action/Sleep.cs
  Libplanet.Tests/Common/Action/ThrowException.cs
  Libplanet.Tests/Fixtures/Arithmetic.cs
  Libplanet.Tests/Store/StoreTest.cs
  Libplanet/Action/ActionContext.cs
  Libplanet/Action/ActionEvaluation.cs
  Libplanet/Action/ActionEvaluationsExtensions.cs
  Libplanet/Action/ActionEvaluator.cs
  Libplanet/Action/IAction.cs
  Libplanet/Action/IActionContext.cs
  Libplanet/Action/IActionEvaluation.cs
  Libplanet/Action/NullAction.cs
  Libplanet/Action/Sys/Initialize.cs
  Libplanet/Blockchain/BlockChain.Swap.cs
  Libplanet/Blockchain/BlockChain.TxExecution.cs
  Libplanet/Blockchain/BlockChain.cs
  Libplanet/Blockchain/BlockChainStates.cs
  Libplanet/Blockchain/IBlockChainStates.cs
  Libplanet/Blockchain/NullChainStates.cs
  Libplanet/Blockchain/Renderers/IActionRenderer.cs
  Libplanet/Blocks/BlockState.cs
  Libplanet/Blocks/BlockStateCache.cs
  Libplanet/Blocks/IBlockState.cs
Labels: Large

#3261 🧹 Removed unnecessary test code
  Libplanet.Tests/Action/ActionContextTest.cs
Labels: Small

#3260 Update gossip to forget only with NewRound
  CHANGES.md
  Libplanet.Net.Tests/Consensus/ConsensusContextNonProposerTest.cs
  Libplanet.Net.Tests/Consensus/ConsensusContextTest.cs
  Libplanet.Net.Tests/Consensus/ContextNonProposerTest.cs
  Libplanet.Net.Tests/Consensus/ContextProposerTest.cs
  Libplanet.Net.Tests/Consensus/ContextProposerValidRoundTest.cs
  Libplanet.Net.Tests/Consensus/ContextTest.cs
  Libplanet.Net.Tests/Consensus/GossipTest.cs
  Libplanet.Net.Tests/Consensus/MessageCacheTest.cs
  Libplanet.Net.Tests/SwarmTest.cs
  Libplanet.Net.Tests/TestUtils.cs
  Libplanet.Net/Consensus/ConsensusContext.Event.cs
  Libplanet.Net/Consensus/ConsensusContext.cs
  Libplanet.Net/Consensus/ConsensusReactor.cs
  Libplanet.Net/Consensus/Context.Async.cs
  Libplanet.Net/Consensus/Context.Event.cs
  Libplanet.Net/Consensus/Context.Mutate.cs
  Libplanet.Net/Consensus/Context.cs
  Libplanet.Net/Consensus/Gossip.cs
  Libplanet.Net/Consensus/GossipConsensusMessageCommunicator.cs
  Libplanet.Net/Consensus/HeightVoteSet.cs
  Libplanet.Net/Consensus/IConsensusMessageCommunicator.cs
  Libplanet.Net/Consensus/MessageCache.cs
  Libplanet.Net/Messages/ConsensusPreCommitMsg.cs
  Libplanet.Net/Messages/ConsensusPreVoteMsg.cs
  Libplanet.Net/Messages/ConsensusProposalMsg.cs
  Libplanet.Net/Messages/ConsensusVoteMsg.cs
Labels: Extra Large

#3263 🚀 Release 2.4.0
  CHANGES.md
Labels: release

#3264 🔧 Prepare 2.4.1
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: release, Extra Small

#3265 🔧 Prepare 2.5.0
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: release

#3267 🧹 Remove `ActionTypeAttribute.ValueOf()`
  CHANGES.md
  Libplanet.Tests/Action/ActionTypeAttributeTest.cs
  Libplanet/Action/ActionTypeAttribute.cs
  Libplanet/Action/Loader/TypedActionLoader.cs
Labels: Extra Small

#3206 Replace proposal when +2/3 valid votes are collected
  CHANGES.md
  Libplanet.Net.Tests/Consensus/ConsensusContextTest.cs
  Libplanet.Net.Tests/Consensus/ContextTest.cs
  Libplanet.Net.Tests/Messages/NetMQMessageCodecTest.cs
  Libplanet.Net/Consensus/ConsensusContext.cs
  Libplanet.Net/Consensus/ConsensusReactor.cs
  Libplanet.Net/Consensus/Context.Mutate.cs
  Libplanet.Net/Consensus/Context.cs
  Libplanet.Net/Consensus/Gossip.cs
  Libplanet.Net/Messages/ConsensusMaj23Msg.cs
  Libplanet.Net/Messages/ConsensusProposalClaimMsg.cs
  Libplanet.Net/Messages/ConsensusVoteSetBitsMsg.cs
  Libplanet.Net/Messages/MessageContent.cs
  Libplanet.Net/Messages/NetMQMessageCodec.cs
  Libplanet.Tests/Consensus/Maj23Test.cs
  Libplanet.Tests/Consensus/ProposalClaimMetadataTest.cs
  Libplanet.Tests/Consensus/ProposalClaimTest.cs
  Libplanet.Tests/Consensus/VoteSetBitsMetadataTest.cs
  Libplanet.Tests/Consensus/VoteSetBitsTest.cs
  Libplanet/Consensus/ProposalClaim.cs
  Libplanet/Consensus/ProposalClaimMetadata.cs
  Libplanet/Consensus/VoteSetBits.cs
  Libplanet/Consensus/VoteSetBitsMetadata.cs
Labels: Extra Large, pbft

#3273 Add spam filter logic on communicator #3271
  CHANGES.md
  Libplanet.Net.Tests/Consensus/GossipConsensusMessageCommunicatorTest.cs
  Libplanet.Net.Tests/Consensus/GossipTest.cs
  Libplanet.Net/Consensus/Gossip.cs
  Libplanet.Net/Consensus/GossipConsensusMessageCommunicator.cs
Labels: Large

#3272 🔧 Evaluate all `IAction`s regardless of errors
  CHANGES.md
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
  Libplanet.Tests/Fixtures/IntegerSet.cs
  Libplanet/Action/ActionEvaluator.cs
Labels: Extra Small

#3274 Expose `Logs` for `ActionContext`
  CHANGES.md
  Libplanet.Explorer/GraphTypes/TxResult.cs
  Libplanet.Tests/Action/ActionContextTest.cs
  Libplanet.Tests/Store/StoreTest.cs
  Libplanet.Tests/Tx/TxFailureTest.cs
  Libplanet.Tests/Tx/TxSuccessTest.cs
  Libplanet/Action/ActionContext.cs
  Libplanet/Action/ActionEvaluation.cs
  Libplanet/Action/ActionEvaluator.cs
  Libplanet/Action/IActionContext.cs
  Libplanet/Action/IActionEvaluation.cs
  Libplanet/Store/BaseStore.cs
  Libplanet/Tx/TxExecution.cs
  Libplanet/Tx/TxFailure.cs
  Libplanet/Tx/TxSuccess.cs
Labels: Small

#3275 ⚡ Use `Array.Empty`
  Libplanet.Benchmarks/Store.cs
  Libplanet.Crypto.Secp256k1.Tests/Secp256k1CryptoBackendTest.cs
  Libplanet.Net.Tests/Messages/NetMQMessageCodecTest.cs
  Libplanet.Net.Tests/SwarmTest.cs
  Libplanet.Net/Swarm.MessageHandlers.cs
  Libplanet.RocksDBStore/RocksDBStore.cs
  Libplanet.Tests/Blockchain/BlockChainTest.ProposeBlock.cs
  Libplanet/Blockchain/BlockChain.cs
  Libplanet/ByteUtil.cs
  Libplanet/HashDigest.cs
  Libplanet/Tx/TxMarshaler.cs
Labels: Extra Small

#3277 🧹 Rename for consistency
  Libplanet/Blockchain/BlockChain.cs
Labels: Extra Small

#3278 ♻️ Better `MockAccountState`
  Libplanet.Tests/Action/AccountStateDeltaTest.cs
  Libplanet.Tests/Action/AccountStateDeltaV0Test.cs
  Libplanet.Tests/Action/AccountStateDeltaV1Test.cs
  Libplanet.Tests/Action/ActionEvaluationTest.cs
  Libplanet.Tests/Fixtures/IntegerSet.cs
  Libplanet.Tests/Mocks/MockAccountState.cs
Labels: Large

#3276 Catch when RoundVoteSet not found
  Libplanet.Net/Consensus/Context.cs
  Libplanet.Net/Consensus/GossipConsensusMessageCommunicator.cs
  Libplanet.Net/Consensus/HeightVoteSet.cs
  Libplanet.Net/Consensus/VoteSet.cs
Labels: Medium

#3279 ♻️ Refactor `Evaluate`
  Libplanet.Tests/Action/ActionContextTest.cs
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
  Libplanet/Action/ActionEvaluator.cs
Labels: Large

#3283 🧹 Removed `IFeeCalculator`
  CHANGES.md
  Libplanet.Benchmarks/AppendBlock.cs
  Libplanet.Benchmarks/BlockChain.cs
  Libplanet.Benchmarks/ProposeBlock.cs
  Libplanet.Explorer.Executable/Program.cs
  Libplanet.Explorer.Tests/GeneratedBlockChainFixture.cs
  Libplanet.Extensions.Cocona/Commands/BlockCommand.cs
  Libplanet.Net.Tests/Consensus/ConsensusReactorTest.cs
  Libplanet.Net.Tests/SwarmTest.Broadcast.cs
  Libplanet.RocksDBStore.Tests/RocksDBStoreTest.cs
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
  Libplanet.Tests/Blockchain/BlockChainTest.Append.cs
  Libplanet.Tests/Blockchain/BlockChainTest.ProposeBlock.cs
  Libplanet.Tests/Blockchain/BlockChainTest.ValidateNextBlock.cs
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet.Tests/Blockchain/Policies/BlockPolicyTest.cs
  Libplanet.Tests/Blockchain/Policies/StagePolicyTest.cs
  Libplanet.Tests/Blocks/PreEvaluationBlockTest.cs
  Libplanet.Tests/Fixtures/IntegerSet.cs
  Libplanet.Tests/Store/StoreFixture.cs
  Libplanet.Tests/Store/StoreTest.cs
  Libplanet.Tests/TestUtils.cs
  Libplanet/Action/ActionEvaluator.cs
  Libplanet/Action/IFeeCalculator.cs
  Libplanet/Blockchain/Policies/BlockPolicy.cs
  Libplanet/Blockchain/Policies/IBlockPolicy.cs
  Libplanet/Blockchain/Policies/NullBlockPolicy.cs
Labels: Medium

#3282 Removed all getters
  CHANGES.md
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
  Libplanet/State/AccountBalanceGetter.cs
  Libplanet/State/AccountStateDelta.cs
  Libplanet/State/AccountStateGetter.cs
  Libplanet/State/TotalSupplyGetter.cs
  Libplanet/State/ValidatorSetGetter.cs
Labels: Medium

#3286 Fix `HandleVoteSetBits` test
  Libplanet.Net.Tests/Consensus/ConsensusContextTest.cs
Labels: Extra Small

#3287 🧹 Nullable crypto
  Libplanet/Crypto/CryptoConfig.cs
Labels: Extra Small

#3281 Add preEvaluationHash field to BlockType
  CHANGES.md
  Libplanet.Explorer.Tests/GraphTypes/BlockTypeTest.cs
  Libplanet.Explorer/GraphTypes/BlockType.cs
Labels: explorer, api, Extra Small, Squash Needed

#3288 Add `Context.VoteSetModified` event handler
  CHANGES.md
  Libplanet.Net.Tests/Consensus/ConsensusContextTest.cs
  Libplanet.Net/Consensus/Context.Event.cs
  Libplanet.Net/Consensus/Context.Mutate.cs
  Libplanet.Net/Consensus/VoteSet.cs
Labels: Extra Small

#3291 🧹 Removed ActionsLogsList from TxExecution
  CHANGES.md
  Libplanet.Explorer.Tests/GraphTypes/TxResultTypeTest.cs
  Libplanet.Explorer/GraphTypes/TxResult.cs
  Libplanet.Explorer/GraphTypes/TxResultType.cs
  Libplanet.Explorer/Queries/TransactionQuery.cs
  Libplanet.Tests/Blockchain/BlockChainTest.Internals.cs
  Libplanet.Tests/Store/StoreTest.cs
  Libplanet.Tests/Tx/TxFailureTest.cs
  Libplanet.Tests/Tx/TxSuccessTest.cs
  Libplanet/Blockchain/BlockChain.TxExecution.cs
  Libplanet/Store/BaseStore.cs
  Libplanet/Tx/TxExecution.cs
  Libplanet/Tx/TxFailure.cs
  Libplanet/Tx/TxSuccess.cs
Labels: Medium

#3292 🧹 Removed `Logs` from `IActionContext` and `IActionEvaluation`
  CHANGES.md
  Libplanet.Tests/Action/ActionContextTest.cs
  Libplanet/Action/ActionContext.cs
  Libplanet/Action/ActionEvaluation.cs
  Libplanet/Action/ActionEvaluator.cs
  Libplanet/Action/IActionContext.cs
  Libplanet/Action/IActionEvaluation.cs
Labels: Extra Small

#3290 Log empty block demand as success on `PullBlocksAsync`
  Libplanet.Net/Swarm.BlockSync.cs
Labels: Extra Small

#3284 Fix `Currency` backward compability broken bug
  CHANGES.md
  Libplanet/Assets/Currency.cs
Labels: bug, Extra Small

#3243 ci(gh-actions): check typos
  .github/workflows/lint.yml
  CHANGES.md
  Libplanet.Net.Tests/Consensus/ConsensusContextProposerTest.cs
  Libplanet.Net.Tests/Consensus/ContextNonProposerTest.cs
  Libplanet.Net/Consensus/Context.cs
  Libplanet.Net/Swarm.BlockSync.cs
  Libplanet.Net/Transports/ITransport.cs
  Libplanet.RocksDBStore/RocksDBStore.cs
  Libplanet.Stun.Tests/Stun/Messages/BindingRequestSuccessTest.cs
  Libplanet.Stun/Stun/TurnClient.cs
  Libplanet.Tests/Store/StoreTest.cs
  Libplanet/Blockchain/BlockChain.Evaluate.cs
  Libplanet/Blockchain/BlockChain.ProposeBlock.cs
  Libplanet/Blockchain/BlockChain.Validate.cs
  Libplanet/Blocks/BlockCommit.cs
  Libplanet/Blocks/BlockMarshaler.cs
  Libplanet/Blocks/BlockMetadata.cs
  Libplanet/ByteUtil.cs
Labels: Small

#3294 🚀 Release 2.5.0
  CHANGES.md
Labels: Extra Small

#3295 🔧 Prepare 2.6.0
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: Extra Small

#3298 ⚡ `RocksDBStore` Concat optimization
  CHANGES.md
  Libplanet.RocksDBStore/RocksDBStore.cs
Labels: Medium

#3297 ⚡ Faster `Hex` for netstandard2.1 and up
  CHANGES.md
  Libplanet/ByteUtil.cs
Labels: Extra Small

#3302 ⬆️ Bump Bencodex to 0.11.0
  CHANGES.md
  Libplanet.Explorer/Libplanet.Explorer.csproj
  Libplanet/Libplanet.csproj
Labels: Extra Small

#3305 🚀 Release 2.4.1
  CHANGES.md
Labels: Extra Small

#3296 🔧 Prepare 2.5.1
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: Extra Small

#3308 🔀 Merge 2.4.1 to main
  CHANGES.md
  Libplanet.Common/ByteUtil.cs
  Libplanet.Explorer/Libplanet.Explorer.csproj
  Libplanet.RocksDBStore/RocksDBStore.cs
  Libplanet/Libplanet.csproj
Labels: Medium

#3304 🧹 Removed `ExtractableException`
  CHANGES.md
  Libplanet.Common/Types/Tx/ExtractableException.cs
  Libplanet.Common/Types/Tx/IExtractableException.cs
  Libplanet.Common/Types/Tx/TxFailure.cs
  Libplanet.Tests/Action/ExtractableExceptionTest.cs
  Libplanet.Tests/Blockchain/BlockChainTest.Append.cs
  Libplanet.Tests/Blockchain/BlockChainTest.Internals.cs
  Libplanet.Tests/Store/StoreTest.cs
  Libplanet.Tests/Tx/TxFailureTest.cs
  Libplanet/Action/ExtractableException.cs
  Libplanet/Action/IExtractableException.cs
  Libplanet/Store/BaseStore.cs
Labels: Medium

#3313 Fix flaky test `GossipConsensusMessageCommunicatorTest`
  CHANGES.md
  Libplanet.Net.Tests/Consensus/GossipConsensusMessageCommunicatorTest.cs
  Libplanet.Net/Consensus/Gossip.cs
Labels: Extra Small

#3316 🚀 Release 3.0.0
  CHANGES.md
Labels: release, Extra Small

#3317 Release 3.0.0
  Libplanet/Libplanet.csproj
Labels: Extra Small

#3318 🔧 Prepare 3.1.0
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: release, Extra Small

#3319 🔧 Prepare 3.0.1
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: release, Extra Small

#3320 🧹 Edited `csproj`
  Libplanet.Action/Libplanet.Action.csproj
  Libplanet.Action/State/AccountDeltaExtensions.cs
  Libplanet.Action/State/BlockState.cs
  Libplanet.Action/State/IBlockChainStates.cs
  Libplanet.Action/State/InsufficientBalanceException.cs
  Libplanet.Action/State/TotalSupplyNotTrackableException.cs
Labels: Extra Small

#3322 🔧 Simple test fix
  Libplanet.Action.Tests/DuplicateActionTypeIdentifierExceptionTest.cs
Labels: Extra Small

#3324 docs: fix docfx toc configuration
  Docs/api/index.md
  Docs/toc.yml
Labels: bug, docs, Extra Small

#3325 🧹 Remove single use extensions
  CHANGES.md
  Libplanet.Action/ActionEvaluator.cs
  Libplanet.Common/EnumerableMeasurement.cs
  Libplanet.Common/KeyValuePairExtensions.cs
  Libplanet.Tests/EnumerableMeasurementTest.cs
  Libplanet.Tests/KeyValuePairExtensionsTest.cs
  Libplanet.Tests/Tx/TxSuccessTest.cs
Labels: Medium

#3321 ⚡ Optimize `KeyBytes` derivation
  CHANGES.md
  Libplanet.Action.Tests/State/KeyConvertersTest.cs
  Libplanet.Action/ActionEvaluationsExtensions.cs
  Libplanet.Action/State/AccountDeltaExtensions.cs
  Libplanet.Action/State/AccountStateDeltaExtensions.cs
  Libplanet.Action/State/BlockState.cs
  Libplanet.Action/State/KeyConverters.cs
  Libplanet.Store/StateStoreExtensions.cs
  Libplanet.Tests/Fixtures/IntegerSet.cs
  Libplanet.Tests/Store/StateStoreExtensionsTest.cs
  Libplanet.Tests/Store/TrieStateStoreTest.cs
  Libplanet/Blockchain/BlockChain.Evaluate.cs
Labels: Large

#3326 🔨 Fix tests and builds
  CHANGES.md
  Docs/api/index.md
  Docs/toc.yml
  Libplanet.Action.Tests/DuplicateActionTypeIdentifierExceptionTest.cs
  Libplanet.Action/Libplanet.Action.csproj
  Libplanet.Action/State/AccountDeltaExtensions.cs
  Libplanet.Action/State/BlockState.cs
  Libplanet.Action/State/IBlockChainStates.cs
  Libplanet.Action/State/InsufficientBalanceException.cs
  Libplanet.Action/State/TotalSupplyNotTrackableException.cs
Labels: Extra Small

#3327 🚀 Release 3.0.1
  CHANGES.md
Labels: Extra Small

#3330 🔀 Merge 3.0.1 to main
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: Extra Small

#3331 🔧 Prepare 3.0.2
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: Extra Small

#3329 ci(gh-actions): check typos over all files
  .github/workflows/lint.yml
  @planetarium/account-web3-secret-storage/test/TtyPassphraseEntry.test.ts
  Libplanet.Action.Tests/Common/DumbAction.cs
  Libplanet.Explorer.Tests/GraphQLTestUtils.cs
  Libplanet.Explorer.ruleset
  Libplanet.Explorer/GraphTypes/ActionType.cs
  Libplanet.Net/Consensus/GossipConsensusMessageCommunicator.cs
  Libplanet.Net/Transports/NetMQTransport.cs
  Libplanet.Tests.ruleset
  Libplanet.Tests/KeyStore/Kdfs/KdfTest.cs
  Libplanet.ruleset
  _typos.toml
Labels: ci & cd, Extra Small

#3328 🧹 Refactor to use `KeyBytes` instead of `string`s in general
  CHANGES.md
  Libplanet.Action.Tests/State/KeyConvertersTest.cs
  Libplanet.Extensions.Cocona.Tests/Commands/MptCommandTest.cs
  Libplanet.Extensions.Cocona/Commands/MptCommand.cs
  Libplanet.Store/StateStoreExtensions.cs
  Libplanet.Store/Trie/KeyBytes.cs
  Libplanet.Store/Trie/TrieExtensions.cs
  Libplanet.Tests/Store/StateStoreExtensionsTest.cs
  Libplanet.Tests/Store/Trie/KeyBytesTest.cs
  Libplanet.Tests/Store/TrieStateStoreTest.cs
Labels: Medium

#3335 ⬆️ Bump bencodex to 0.12.0
  CHANGES.md
  Libplanet.Action/Libplanet.Action.csproj
  Libplanet.Crypto/Libplanet.Crypto.csproj
  Libplanet.Store/Libplanet.Store.csproj
  Libplanet.Types/Libplanet.Types.csproj
  Libplanet/Libplanet.csproj
Labels: Extra Small

#3336 🚀 Release 3.1.0
  CHANGES.md
Labels: Extra Small

#3338 🔧 Prepare 3.2.0
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: Extra Small

#3340 🔧 Prepare 3.1.1
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: Extra Small

#3341 🧹 Fix `csproj` files
  Libplanet.Explorer.Executable/Libplanet.Explorer.Executable.csproj
  Libplanet.RocksDBStore/Libplanet.RocksDBStore.csproj
  Libplanet.Tests/Libplanet.Tests.csproj
  Libplanet.Types/Blocks/BlockPerception.cs
Labels: Extra Small

#3337 Rename `IAccountStateDelta` as `IAccount`
  CHANGES.md
  Libplanet.Action.Tests/ActionContextTest.cs
  Libplanet.Action.Tests/ActionEvaluationTest.cs
  Libplanet.Action.Tests/Common/Attack.cs
  Libplanet.Action.Tests/Common/BaseAction.cs
  Libplanet.Action.Tests/Common/DelayAction.cs
  Libplanet.Action.Tests/Common/DetectRehearsal.cs
  Libplanet.Action.Tests/Common/DumbAction.cs
  Libplanet.Action.Tests/Common/ExecuteRecord.cs
  Libplanet.Action.Tests/Common/MinerReward.cs
  Libplanet.Action.Tests/Common/RandomAction.cs
  Libplanet.Action.Tests/Common/SetStatesAtBlock.cs
  Libplanet.Action.Tests/Common/SetValidator.cs
  Libplanet.Action.Tests/Common/Sleep.cs
  Libplanet.Action.Tests/Common/ThrowException.cs
  Libplanet.Action.Tests/Sys/InitializeTest.cs
  Libplanet.Action/AccountMetrics.cs
  Libplanet.Action/ActionContext.cs
  Libplanet.Action/ActionEvaluation.cs
  Libplanet.Action/ActionEvaluator.cs
  Libplanet.Action/FeeCollector.cs
  Libplanet.Action/IAction.cs
  Libplanet.Action/IActionContext.cs
  Libplanet.Action/IActionEvaluation.cs
  Libplanet.Action/IFeeCollector.cs
  Libplanet.Action/NullAction.cs
  Libplanet.Action/State/Account.cs
  Libplanet.Action/State/AccountDeltaExtensions.cs
  Libplanet.Action/State/AccountExtensions.cs
  Libplanet.Action/State/CurrencyPermissionException.cs
  Libplanet.Action/State/IAccount.cs
  Libplanet.Action/State/InsufficientBalanceException.cs
  Libplanet.Action/State/SupplyOverflowException.cs
  Libplanet.Action/Sys/Initialize.cs
  Libplanet.Analyzers.Tests/ActionAnalyzerTest.cs
  Libplanet.Explorer.Tests/SimpleAction.cs
  Libplanet.Extensions.Cocona/Utils.cs
  Libplanet.Net.Tests/SwarmTest.cs
  Libplanet.Tests/Action/AccountTest.cs
  Libplanet.Tests/Action/AccountV0Test.cs
  Libplanet.Tests/Action/AccountV1Test.cs
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet.Tests/Blockchain/Renderers/AnonymousActionRendererTest.cs
  Libplanet.Tests/Blockchain/Renderers/LoggedActionRendererTest.cs
  Libplanet.Tests/Fixtures/Arithmetic.cs
  Libplanet.Tests/Fixtures/IntegerSet.cs
  Libplanet.Tests/Store/StoreTest.cs
  Libplanet.Types/Assets/Currency.cs
  Libplanet/Blockchain/BlockChain.TxExecution.cs
  Libplanet/Blockchain/Renderers/AnonymousActionRenderer.cs
  Libplanet/Blockchain/Renderers/AtomicActionRenderer.cs
  Libplanet/Blockchain/Renderers/Debug/RecordingActionRenderer.cs
  Libplanet/Blockchain/Renderers/Debug/RenderRecord.cs
  Libplanet/Blockchain/Renderers/Debug/ValidatingActionRenderer.cs
  Libplanet/Blockchain/Renderers/IActionRenderer.cs
  Libplanet/Blockchain/Renderers/LoggedActionRenderer.cs
Labels: Extra Large

#3342 Use @noble/hashes/scrypt instead of scrypt-js
  @planetarium/account-web3-secret-storage/package.json
  @planetarium/account-web3-secret-storage/src/Web3Account.ts
  @planetarium/account-web3-secret-storage/test/Web3Account.test.ts
  yarn.lock
Labels: bug, Extra Small, js
