Repository planetarium/libplanet, pull requests merged in 2023-12, with the labels that each got.

#3528 Restore `BlockChainState`
  CHANGES.md
  Libplanet.Explorer.Executable/Program.cs
  Libplanet.Tests/Blockchain/BlockChainTest.Append.cs
  Libplanet.Tests/Blockchain/BlockChainTest.ProposeBlock.cs
  Libplanet.Tests/Blockchain/BlockChainTest.ValidateNextBlock.cs
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet.Tests/TestUtils.cs
  Libplanet/Blockchain/BlockChain.States.cs
  Libplanet/Blockchain/BlockChain.cs
  Libplanet/Blockchain/BlockChainStates.cs
Labels: Medium

#3512 @planetarium/tx: Remove useless template variable
  @planetarium/tx/src/tx/signed.ts
  CHANGES.md
Labels: Extra Small, js

#3520 ♻️ `ITrie` based `IAccount`
  CHANGES.md
  Libplanet.Action.Tests/ActionEvaluationExtensions.cs
  Libplanet.Action/ActionEvaluationsExtensions.cs
  Libplanet.Action/ActionEvaluator.cs
  Libplanet.Action/State/Account.cs
  Libplanet.Action/State/AccountDeltaExtensions.cs
  Libplanet.Action/State/AccountExtensions.cs
  Libplanet.Action/State/AccountState.cs
  Libplanet.Action/State/IAccount.cs
  Libplanet.Tests/Action/AccountDiffTest.cs
  Libplanet.Tests/Action/AccountTest.cs
  Libplanet.Tests/Action/AccountV1Test.cs
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
  Libplanet.Tests/Blockchain/BlockChainTest.cs
Labels: Extra Large

#3535 🧹 Remove `IAccountDelta`
  CHANGES.md
  Libplanet.Action/State/Account.cs
  Libplanet.Action/State/AccountDelta.cs
  Libplanet.Action/State/IAccount.cs
  Libplanet.Action/State/IAccountDelta.cs
  Libplanet.Explorer.Tests/Queries/StateQueryTest.cs
Labels: Small

#3537 🧹 Remove internal tracking of amounts for `TotalUpdatedFungibleAssets`
  CHANGES.md
  Libplanet.Action/ActionEvaluator.cs
  Libplanet.Action/State/Account.cs
Labels: Extra Small

#3538 🚀 Release 3.9.0
  CHANGES.md
Labels: Extra Small

#3540 Add metadata for tries
  CHANGES.md
  Libplanet.Action.Tests/State/AccountBaseStateTest.cs
  Libplanet.Action.Tests/State/WorldBaseStateTest.cs
  Libplanet.Action/ActionEvaluator.cs
  Libplanet.Action/IActionEvaluator.cs
  Libplanet.Action/State/AccountBaseState.cs
  Libplanet.Action/State/TrieExtensions.cs
  Libplanet.Action/State/TrieMetadata.cs
  Libplanet.Action/State/TrieType.cs
  Libplanet.Action/State/WorldBaseState.cs
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
  Libplanet.Tests/Blockchain/BlockChainTest.Append.cs
  Libplanet/Blockchain/BlockChain.Evaluate.cs
  Libplanet/Blockchain/BlockChain.Swap.cs
Labels: Large

#3542 ✨ Added `TxStatus.INCLUDED`
  CHANGES.md
  Libplanet.Explorer.Tests/GeneratedBlockChainFixture.cs
  Libplanet.Explorer.Tests/GraphTypes/TxResultTypeTest.cs
  Libplanet.Explorer.Tests/Queries/TransactionQueryGeneratedTest.cs
  Libplanet.Explorer/GraphTypes/TxStatusType.cs
  Libplanet.Explorer/Queries/TransactionQuery.cs
Labels: Large

#3543 🚀 Release 3.9.1
  CHANGES.md
Labels: Extra Small

#3544 🔧 Prepare 3.9.2
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: Extra Small

#3534 Replace <T> with IActionLoader param
  Libplanet.Explorer.Tests/Queries/TransactionQueryTest.cs
  Libplanet.Net.Tests/Consensus/ConsensusContextNonProposerTest.cs
  Libplanet.Net.Tests/Consensus/ConsensusContextProposerTest.cs
  Libplanet.Net.Tests/Consensus/ConsensusContextTest.cs
  Libplanet.Net.Tests/Consensus/ContextNonProposerTest.cs
  Libplanet.Net.Tests/Consensus/ContextTest.cs
  Libplanet.Net.Tests/Messages/NetMQMessageCodecTest.cs
  Libplanet.Net.Tests/SwarmTest.Broadcast.cs
  Libplanet.Net.Tests/SwarmTest.Fixtures.cs
  Libplanet.Net.Tests/SwarmTest.Preload.cs
  Libplanet.Net.Tests/SwarmTest.cs
  Libplanet.Net.Tests/TestUtils.cs
  Libplanet.Net.Tests/Transports/BoundPeerExtensionsTest.cs
  Libplanet.Tests/Action/AccountTest.cs
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
  Libplanet.Tests/Blockchain/BlockChainTest.Append.cs
  Libplanet.Tests/Blockchain/BlockChainTest.ValidateNextBlock.cs
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet.Tests/Blockchain/Policies/BlockPolicyTest.cs
  Libplanet.Tests/TestUtils.cs
Labels: Large

#3547 🔀 Port 3.9.1 to 4.0.0
  CHANGES.md
  Libplanet.Explorer.Tests/GeneratedBlockChainFixture.cs
  Libplanet.Explorer.Tests/GraphTypes/TxResultTypeTest.cs
  Libplanet.Explorer.Tests/Queries/TransactionQueryGeneratedTest.cs
  Libplanet.Explorer/GraphTypes/TxStatusType.cs
  Libplanet.Explorer/Queries/TransactionQuery.cs
  Libplanet.Tests/Action/AccountTest.cs
Labels: Large

#3551 ♻️ Allow to choose output format of `BencodexValueType`
  CHANGES.md
  Libplanet.Explorer.Tests/Queries/StateQueryTest.cs
  Libplanet.Explorer/GraphTypes/BencodexValueType.cs
Labels: Small

#3553 feat: new argument for `RocksDBKeyValueStore.ctor`
  Libplanet.RocksDBStore/RocksDBKeyValueStore.cs
Labels: Extra Small

#3555 ♻️ Additional error logging for better debugging
  Libplanet.Action/ActionEvaluator.cs
Labels: Extra Small

#3556 ⏪ Revert all incompatible api changes
  CHANGES.md
  Libplanet.Explorer.Tests/GraphTypes/AddressTypeTest.cs
  Libplanet.Explorer.Tests/GraphTypes/BlockHashTypeTest.cs
  Libplanet.Explorer.Tests/GraphTypes/HashDigestTypeTest.cs
  Libplanet.Explorer.Tests/GraphTypes/PublicKeyTypeTest.cs
  Libplanet.Explorer.Tests/GraphTypes/TxIdTypeTest.cs
  Libplanet.Explorer.Tests/Queries/StateQueryTest.cs
  Libplanet.Explorer/GraphTypes/AddressType.cs
  Libplanet.Explorer/GraphTypes/BencodexValueType.cs
  Libplanet.Explorer/GraphTypes/BlockCommitType.cs
  Libplanet.Explorer/GraphTypes/BlockHashType.cs
  Libplanet.Explorer/GraphTypes/BlockType.cs
  Libplanet.Explorer/GraphTypes/CurrencyType.cs
  Libplanet.Explorer/GraphTypes/HashDigestSHA256Type.cs
  Libplanet.Explorer/GraphTypes/HashDigestType.cs
  Libplanet.Explorer/GraphTypes/PublicKeyType.cs
  Libplanet.Explorer/GraphTypes/TransactionType.cs
  Libplanet.Explorer/GraphTypes/TxIdType.cs
  Libplanet.Explorer/GraphTypes/TxResultType.cs
  Libplanet.Explorer/Queries/BlockQuery.cs
  Libplanet.Explorer/Queries/StateQuery.cs
  Libplanet.Explorer/Queries/TransactionQuery.cs
Labels: Extra Large

#3557 🚀 Release 3.9.2
  CHANGES.md
Labels: Extra Small

#3558 🔧 Prepare 3.9.3
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: Extra Small

#3560 ♻️ Allow to choose output format of `BencodexValueType`
  CHANGES.md
  Libplanet.Explorer.Tests/Queries/StateQueryTest.cs
  Libplanet.Explorer/GraphTypes/BencodexValueType.cs
Labels: Small

#3554 🧹 Removed `IBlockPolicy` as generic type parameter for `StateQuery`
  Libplanet.Explorer.Tests/Queries/StateQueryTest.cs
  Libplanet.Explorer/Queries/ExplorerQuery.cs
  Libplanet.Explorer/Queries/StateQuery.cs
Labels: Small

#3561 ✨ QoL GraphQL queries
  CHANGES.md
  Libplanet.Explorer.Tests/Queries/HelperQueryTest.cs
  Libplanet.Explorer/Queries/ExplorerQuery.cs
  Libplanet.Explorer/Queries/HelperQuery.cs
Labels: Small

#3562 ♻️ Removed updated addresses from `IRichStore`
  CHANGES.md
  Libplanet.Explorer.Tests/Queries/TransactionQueryGeneratedTest.cs
  Libplanet.Explorer/Queries/ExplorerQuery.cs
  Libplanet.Explorer/Queries/TransactionQuery.cs
  Libplanet.Explorer/Store/IRichStore.cs
  Libplanet.Explorer/Store/LiteDBRichStore.cs
  Libplanet.Explorer/Store/MySQLRichStore.cs
Labels: Medium

#3563 🧹 Remove unnecessary usings
  Libplanet.Action/ActionContext.cs
  Libplanet.Analyzers.Tests/Helpers/DiagnosticResult.cs
  Libplanet.Benchmarks/AppendBlock.cs
  Libplanet.Benchmarks/BlockChain.cs
  Libplanet.Benchmarks/Program.cs
  Libplanet.Benchmarks/ProposeBlock.cs
  Libplanet.Crypto.Secp256k1.Tests/Secp256k1CryptoBackendTest.cs
  Libplanet.Crypto.Secp256k1/Secp256k1CryptoBackend.cs
  Libplanet.Explorer.Tests/GraphQLTestUtils.cs
  Libplanet.Explorer.Tests/GraphTypes/FungibleAssetValueTypeTest.cs
  Libplanet.Explorer.Tests/GraphTypes/HashDigestTypeTest.cs
  Libplanet.Explorer.Tests/Indexing/RocksDbBlockChainIndexTest.cs
  Libplanet.Explorer.Tests/Queries/MockBlockChainContext.cs
  Libplanet.Explorer.Tests/Queries/StateQueryTest.cs
  Libplanet.Explorer.Tests/Queries/TransactionQueryGeneratedWithIndexTest.cs
  Libplanet.Explorer.Tests/Queries/TransactionQueryTest.cs
  Libplanet.Explorer/GraphTypes/BoundPeerType.cs
  Libplanet.Explorer/Interfaces/IBlockChainContext.cs
  Libplanet.Explorer/Queries/ExplorerQuery.cs
  Libplanet.Extensions.Cocona.Tests/BlockPolicyParamsTest.cs
  Libplanet.Extensions.Cocona/BlockPolicyParams.cs
  Libplanet.Extensions.Cocona/Utils.cs
  Libplanet.Net/Consensus/Context.Mutate.cs
  Libplanet.Store/MemoryStore.cs
  Libplanet.Store/Trie/PathCursor.cs
  Libplanet.Tests/Blockchain/BlockChainTest.Append.cs
  Libplanet.Tests/Blockchain/BlockChainTest.Internals.cs
  Libplanet.Tests/Crypto/SymmetricKeyTest.cs
  Libplanet.Types/Consensus/ValidatorSet.cs
  Libplanet/Blockchain/BlockChain.TxExecution.cs
Labels: Extra Small

#3564 🧹 Remove `IRichStore`
  CHANGES.md
  Libplanet.Explorer.Executable/Options.cs
  Libplanet.Explorer.Executable/Program.cs
  Libplanet.Explorer/Queries/ExplorerQuery.cs
  Libplanet.Explorer/Store/AddressRefDoc.cs
  Libplanet.Explorer/Store/IRichStore.cs
  Libplanet.Explorer/Store/LiteDBRichStore.cs
  Libplanet.Explorer/Store/MySQLRichStore.cs
  Libplanet.Explorer/Store/MySQLRichStoreOptions.cs
  Libplanet.Explorer/Store/TxRefDoc.cs
Labels: Extra Large

#3567 ♻️ Refactor tx gas policy
  CHANGES.md
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
  Libplanet.Tests/Tx/TxInvoiceTest.cs
  Libplanet.Types/Tx/ITxInvoice.cs
  Libplanet.Types/Tx/TxInvoice.cs
Labels: Medium

#3572 ♻️ Refactor `ShortNode`
  CHANGES.md
  Libplanet.Store/Trie/Nodes/NodeDecoder.cs
  Libplanet.Store/Trie/Nodes/ShortNode.cs
Labels: Extra Small

#3573 ⚡ ♻️ Slightly optimized `FullNode`
  CHANGES.md
  Libplanet.Store/Trie/MerkleTrie.cs
  Libplanet.Store/Trie/Nodes/FullNode.cs
  Libplanet.Tests/Store/Trie/Nodes/NodeDecoderTest.cs
Labels: Extra Small

#3574 ♻️ Changed `FullNode` to no longer inherit `BaseNode`
  CHANGES.md
  Libplanet.Store/Trie/Nodes/BaseNode.cs
  Libplanet.Store/Trie/Nodes/FullNode.cs
Labels: Extra Small

#3575 ♻️ 🧹 Minor code cleanup.
  Libplanet.Store/Trie/MerkleTrie.Insert.cs
  Libplanet.Store/Trie/MerkleTrie.cs
Labels: Medium
