Repository planetarium/libplanet, pull requests merged in 2024-02, with the labels that each got.

#3644 Removal of '#nullable disable' from the Libplanet.Store project
  CHANGES.md
  Libplanet.Explorer.Tests/Queries/TransactionQueryGeneratedTest.cs
  Libplanet.Explorer/Indexing/BlockChainIndexBase.cs
  Libplanet.Explorer/Queries/ExplorerQuery.cs
  Libplanet.Store/BaseIndex.cs
  Libplanet.Store/BaseStore.cs
  Libplanet.Store/BlockSet.cs
  Libplanet.Store/DefaultStore.cs
  Libplanet.Store/IStore.cs
  Libplanet.Store/MemoryStore.cs
  Libplanet.Store/StoreExtensions.cs
Labels: Medium

#3648 🔊 Added which string caused an APV parsing error to log
  CHANGES.md
  Libplanet.Net/AppProtocolVersion.cs
Labels: Extra Small

#3649 📝 Updated graphql schema
  CHANGES.md
  Libplanet.Explorer/schema.graphql
Labels: Large

#3652 🚀 Release 4.0.2
  CHANGES.md
Labels: Extra Small

#3653 🔧 Prepare 4.0.3
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: Extra Small

#3654 🔀 Merge 4.0.2 to main
  .github/workflows/check-changelog.yml
  CHANGES.md
  Libplanet.Explorer/schema.graphql
  Libplanet.Net/AppProtocolVersion.cs
Labels: Large

#3657 ⏪ Revert graphql type changes
  CHANGES.md
  Libplanet.Explorer/GraphTypes/BlockCommitType.cs
  Libplanet.Explorer/GraphTypes/BlockType.cs
  Libplanet.Explorer/GraphTypes/CurrencyType.cs
  Libplanet.Explorer/GraphTypes/HashDigestSHA256Type.cs
  Libplanet.Explorer/GraphTypes/TransactionType.cs
  Libplanet.Explorer/GraphTypes/TxResultType.cs
  Libplanet.Explorer/Queries/BlockQuery.cs
  Libplanet.Explorer/Queries/StateQuery.cs
  Libplanet.Explorer/Queries/TransactionQuery.cs
Labels: Medium

#3661 ⬇️ Downgrade xUnit packages to fix CI
  Libplanet.Action.Tests/Libplanet.Action.Tests.csproj
  Libplanet.Analyzers.Tests/Libplanet.Analyzers.Tests.csproj
  Libplanet.Crypto.Secp256k1.Tests/Libplanet.Crypto.Secp256k1.Tests.csproj
  Libplanet.Explorer.Cocona.Tests/Libplanet.Explorer.Cocona.Tests.csproj
  Libplanet.Explorer.Tests/Libplanet.Explorer.Tests.csproj
  Libplanet.Extensions.Cocona.Tests/Libplanet.Extensions.Cocona.Tests.csproj
  Libplanet.Net.Tests/Consensus/ConsensusContextTest.cs
  Libplanet.Net.Tests/Consensus/ContextProposerTest.cs
  Libplanet.Net.Tests/Libplanet.Net.Tests.csproj
  Libplanet.RocksDBStore.Tests/Libplanet.RocksDBStore.Tests.csproj
  Libplanet.Stun.Tests/Libplanet.Stun.Tests.csproj
  Libplanet.Tests/Libplanet.Tests.csproj
Labels: Extra Small, no changelog

#3660 🔀 Merge 4.0.3 to main
  CHANGES.md
  Libplanet.Explorer/GraphTypes/BlockCommitType.cs
  Libplanet.Explorer/GraphTypes/BlockType.cs
  Libplanet.Explorer/GraphTypes/CurrencyType.cs
  Libplanet.Explorer/GraphTypes/HashDigestSHA256Type.cs
  Libplanet.Explorer/GraphTypes/TransactionType.cs
  Libplanet.Explorer/GraphTypes/TxResultType.cs
  Libplanet.Explorer/Queries/BlockQuery.cs
  Libplanet.Explorer/Queries/StateQuery.cs
  Libplanet.Explorer/Queries/TransactionQuery.cs
Labels: Medium

#3662 Fixed an issue that caused an error when testing dotnet
  Libplanet.Action.Tests/Libplanet.Action.Tests.csproj
  Libplanet.Analyzers.Tests/Libplanet.Analyzers.Tests.csproj
  Libplanet.Crypto.Secp256k1.Tests/Libplanet.Crypto.Secp256k1.Tests.csproj
  Libplanet.Explorer.Cocona.Tests/Libplanet.Explorer.Cocona.Tests.csproj
  Libplanet.Explorer.Tests/Libplanet.Explorer.Tests.csproj
  Libplanet.Extensions.Cocona.Tests/Libplanet.Extensions.Cocona.Tests.csproj
  Libplanet.Net.Tests/Libplanet.Net.Tests.csproj
  Libplanet.RocksDBStore.Tests/Libplanet.RocksDBStore.Tests.csproj
  Libplanet.Stun.Tests/Libplanet.Stun.Tests.csproj
  Libplanet.Tests/Libplanet.Tests.csproj
Labels: Extra Small, no changelog

#3663 ⏪ Revert query argument type to be compatible with legacy queries
  CHANGES.md
  Libplanet.Explorer/Queries/TransactionQuery.cs
Labels: Extra Small

#3664 🚀 Release 4.0.4
  CHANGES.md
Labels: Extra Small

#3651 Removal of '#nullable disable' from the Libplanet.RocksDBStore project
  CHANGES.md
  Libplanet.RocksDBStore/RocksDBStore.cs
Labels: Extra Small

#3665 🔧 Prepare 4.0.5
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: Extra Small

#3669 Removal of '#nullable disable' from the Libplanet.Net project (etc)
  CHANGES.md
  Libplanet.Net.Tests/BlockCandidateTableTest.cs
  Libplanet.Net/AppProtocolVersion.cs
  Libplanet.Net/AssemblyInfo.cs
  Libplanet.Net/BlockCompletion.cs
  Libplanet/Blockchain/Branch.cs
Labels: Small

#3675 ♻️ ⚡ Optimized action evaluator
  CHANGES.md
  Libplanet.Action/ActionEvaluator.cs
Labels: Extra Small

#3676 🚀 Release 4.0.5
  CHANGES.md
Labels: Extra Small

#3677 🔧 Prepare 4.0.6
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: Extra Small

#3678 🔀 Merge 4.0.5 to main
  CHANGES.md
  Libplanet.Action/ActionEvaluator.cs
Labels: Extra Small

#3680 Fix Mortgage not to clean TotalUpdatedFungibleAssets
  CHANGES.md
  Libplanet.Action/FeeCollector.cs
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
Labels: Extra Small

#3681 🚀 Release 4.0.6
  CHANGES.md
Labels: release, Extra Small

#3682 🔧 Prepare 4.0.7
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: release, Extra Small

#3683 🔀 Merge 4.0.6 to main
  CHANGES.md
  Libplanet.Action/FeeCollector.cs
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
Labels: Small

#3687 ⚡ Optimized `ITrie.IterateNodes()`
  CHANGES.md
  Libplanet.Store/Trie/MerkleTrie.cs
Labels: Extra Small

#3686 Remove BaseIndex class.
  CHANGES.md
  Libplanet.Store/BaseIndex.cs
  Libplanet.Store/BlockSet.cs
  Libplanet.Tests/Store/BlockSetTest.cs
  Libplanet/Blockchain/BlockChain.cs
Labels: Medium
