Repository planetarium/libplanet, pull requests merged in 2024-07, with the labels that each got.

#3857 reduce cache size
  src/Libplanet.Store/HashNodeCache.cs
Labels: no changelog

#3854 🚀 Release 5.0.0
  CHANGES.md
Labels: release

#3858 🔧 Prepare 5.1.0
  CHANGES.md
  src/Libplanet/Libplanet.csproj
Labels: release

#3864 Fix github-release script error
  .github/bin/dist-github-release.sh
Labels: no changelog

#3866 🔧 Prepare 5.1.0
  CHANGES.md
  src/Libplanet/Libplanet.csproj
Labels: release

#3865 🔧Prepare 5.0.1
  CHANGES.md
  src/Libplanet/Libplanet.csproj
Labels: release

#3867 Remove `IFeeCollector` and its implementation
  Libplanet.Action/ActionEvaluator.cs
  Libplanet.Action/FeeCollector.cs
  Libplanet.Action/IFeeCollector.cs
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
Labels: no changelog

#3869 🧹 Remove unnecessary `null` checks
  src/Libplanet.Net/Swarm.BlockCandidate.cs
Labels: no changelog

#3871 Fix CI errors
  .github/workflows/benchmarks-merged.yml
  .github/workflows/check-build.yaml
  CONTRIBUTING.md
  Dockerfile.explorer
  tools/Libplanet.Explorer/run.ps1
Labels: no changelog

#3878 add pyroscope
  src/Libplanet.Action/Libplanet.Action.csproj
  src/Libplanet.Action/State/AccountState.cs
  src/Libplanet.Action/State/WorldBaseState.cs
  src/Libplanet.Net/Libplanet.Net.csproj
  src/Libplanet.Net/Transports/NetMQTransport.cs
  src/Libplanet/Blockchain/BlockChainStates.cs
  src/Libplanet/Libplanet.csproj
Labels: no changelog

#3881 🔀 Port pyroscope from main to 5.1.2
  src/Libplanet.Action/Libplanet.Action.csproj
  src/Libplanet.Action/State/AccountState.cs
  src/Libplanet.Action/State/WorldBaseState.cs
  src/Libplanet.Net/Libplanet.Net.csproj
  src/Libplanet.Net/Transports/NetMQTransport.cs
  src/Libplanet/Blockchain/BlockChainStates.cs
  src/Libplanet/Libplanet.csproj
Labels: no changelog

#3890 fix: correct typo
  src/Libplanet.Action/State/IAccount.cs
  src/Libplanet.Action/State/IWorld.cs
Labels: bug, docs, no changelog

#3896 Add SHA value to RepositoryUrl in nuget package
  .github/bin/dist-pack.sh
  .github/workflows/build.yaml
Labels: no changelog

#3901 🧹 Fixed mistakes for arguments when throwing an `ArgumentOutOfRangeException`
  src/Libplanet.Net/Protocols/KBucket.cs
  src/Libplanet.Net/Protocols/KBucketDictionary.cs
  src/Libplanet.Net/Protocols/RoutingTable.cs
  src/Libplanet.Types/Evidence/EvidenceBase.cs
  src/Libplanet.Types/Evidence/EvidenceId.cs
  src/Libplanet.Types/Tx/TxActionList.cs
  src/Libplanet.Types/Tx/TxSigningMetadata.cs
  src/Libplanet/Blockchain/BlockLocator.cs
Labels: no changelog

#3905 🧹 Cleaned up `BlockChain.FindNextHashes()`
  src/Libplanet/Blockchain/BlockChain.cs
Labels: no changelog

#3906 🧹 Removed null check for Tip
  src/Libplanet.Net/Swarm.BlockSync.cs
  src/Libplanet.Net/Swarm.cs
Labels: no changelog
