Repository planetarium/libplanet, pull requests merged in 2024-03, with the labels that each got.

#3689 Fixed a test failure due to resource sharing between threads.
  Libplanet.Net.Tests/NullableSemaphoreTest.cs
Labels: Extra Small, no changelog

#3690 🔀 ci: use large runner
  .github/workflows/benchmarks-merged.yml
  .github/workflows/benchmarks-pr.yml
Labels: Extra Small, no changelog

#3688 ✨ introduce: Libplanet.Store.Remote
  .github/bin/constants.sh
  CHANGES.md
  CONTRIBUTING.md
  Docs/docfx.json
  Libplanet.Store.Remote.Tests/Helpers/LoggerHelper.cs
  Libplanet.Store.Remote.Tests/Helpers/RemoteKeyValueServiceExtensions.cs
  Libplanet.Store.Remote.Tests/Helpers/TestServerCallContextHelper.cs
  Libplanet.Store.Remote.Tests/Integrations/ServiceIntegration.cs
  Libplanet.Store.Remote.Tests/Libplanet.Store.Remote.Tests.csproj
  Libplanet.Store.Remote.Tests/Units/ServiceUnit.cs
  Libplanet.Store.Remote.Tests/Units/StoreUnit.cs
  Libplanet.Store.Remote.Tests/Usings.cs
  Libplanet.Store.Remote/Client/RemoteKeyValueStore.cs
  Libplanet.Store.Remote/Extensions/ByteStringExtensions.cs
  Libplanet.Store.Remote/Extensions/KeyBytesExtensions.cs
  Libplanet.Store.Remote/Extensions/ProtoMessageExtensions.cs
  Libplanet.Store.Remote/Libplanet.Store.Remote.csproj
  Libplanet.Store.Remote/Protos/Requests/key_value_requests.proto
  Libplanet.Store.Remote/Protos/Responses/key_value_responses.proto
  Libplanet.Store.Remote/Protos/Types/pair.proto
  Libplanet.Store.Remote/Protos/kvstore.proto
  Libplanet.Store.Remote/README.md
  Libplanet.Store.Remote/Server/RemoteKeyValueService.cs
  Libplanet.Store.Remote/Server/Startup.cs
  Libplanet.sln
Labels: Extra Large

#3691 🚀 release: 4.1.0
  CHANGES.md
Labels: release, Extra Small

#3692 🚀 prepare: 4.2.0
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: release, Extra Small

#3685 Split changes.md by major version
  CHANGES.md
  Docs/docfx.json
  changes/v0.md
  changes/v1.md
  changes/v2.md
  changes/v3.md
Labels: Extra Large, no changelog

#3697 Move FAV related operations from `IAccount` to `IWorld`
  CHANGES.md
  Libplanet.Action.Tests/Common/DumbAction.cs
  Libplanet.Action.Tests/Common/DumbModernAction.cs
  Libplanet.Action.Tests/Mocks/MockWorldState.cs
  Libplanet.Action/ActionEvaluator.cs
  Libplanet.Action/AssemblyInfo.cs
  Libplanet.Action/FeeCollector.cs
  Libplanet.Action/State/Account.cs
  Libplanet.Action/State/AccountDiff.cs
  Libplanet.Action/State/AccountState.cs
  Libplanet.Action/State/CurrencyPermissionException.cs
  Libplanet.Action/State/IAccount.cs
  Libplanet.Action/State/IAccountState.cs
  Libplanet.Action/State/IWorld.cs
  Libplanet.Action/State/IWorldState.cs
  Libplanet.Action/State/InsufficientBalanceException.cs
  Libplanet.Action/State/SupplyOverflowException.cs
  Libplanet.Action/State/TotalSupplyNotTrackableException.cs
  Libplanet.Action/State/World.cs
  Libplanet.Action/State/WorldBaseState.cs
  Libplanet.Action/State/WorldExtensions.cs
  Libplanet.Explorer.Tests/GeneratedBlockChainFixture.cs
  Libplanet.Explorer.Tests/Queries/StateQueryTest.Mocks.cs
  Libplanet.Explorer/Queries/StateQuery.cs
  Libplanet.Tests/Action/AccountDiffTest.cs
  Libplanet.Tests/Action/AccountTest.cs
  Libplanet.Tests/Action/AccountV0Test.cs
  Libplanet.Tests/Action/AccountV1Test.cs
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
  Libplanet.Tests/Action/WorldTest.cs
  Libplanet.Tests/Action/WorldV0Test.cs
  Libplanet.Tests/Action/WorldV1Test.cs
  Libplanet.Tests/Blockchain/BlockChainTest.Append.cs
Labels: Extra Large

#3699 🧹 Removed unnecessary methods and properties from `IWorldDelta`
  CHANGES.md
  Libplanet.Action/ActionEvaluator.cs
  Libplanet.Action/State/IWorldDelta.cs
  Libplanet.Action/State/WorldDelta.cs
Labels: Extra Small

#3702 🚚 Move `Validator` related methods from `IAccount` to `IWorld`
  CHANGES.md
  Libplanet.Action.Tests/Common/DumbAction.cs
  Libplanet.Action.Tests/Common/DumbModernAction.cs
  Libplanet.Action.Tests/Common/SetValidator.cs
  Libplanet.Action.Tests/Mocks/MockWorldState.cs
  Libplanet.Action.Tests/Sys/InitializeTest.cs
  Libplanet.Action/State/Account.cs
  Libplanet.Action/State/IAccount.cs
  Libplanet.Action/State/IAccountState.cs
  Libplanet.Action/State/IWorld.cs
  Libplanet.Action/State/IWorldState.cs
  Libplanet.Action/State/World.cs
  Libplanet.Action/State/WorldBaseState.cs
  Libplanet.Action/Sys/Initialize.cs
  Libplanet.Explorer.Tests/Queries/StateQueryTest.Mocks.cs
  Libplanet.Explorer/Queries/StateQuery.cs
  Libplanet.Net.Tests/Consensus/ContextTest.cs
  Libplanet.Net.Tests/TestUtils.cs
  Libplanet.Net/Consensus/ConsensusContext.cs
  Libplanet.Tests/Action/AccountDiffTest.cs
  Libplanet.Tests/Action/AccountTest.cs
  Libplanet.Tests/Action/WorldTest.cs
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet/Blockchain/BlockChain.Validate.cs
Labels: Medium

#3704 ♻️ Docs cleanup
  Libplanet.Action/State/Account.cs
  Libplanet.Action/State/World.cs
  Libplanet.Action/State/WorldBaseState.cs
  Libplanet.Action/State/WorldDelta.cs
Labels: docs, no changelog

#3705 🧹 Removed unnecessary test code
  Libplanet.Tests/Action/AccountTest.cs
  Libplanet.Tests/Action/AccountV0Test.cs
  Libplanet.Tests/Action/AccountV1Test.cs
Labels: Small, no changelog

#3706 🧹 Changelog formatting
  CHANGES.md
Labels: Extra Small

#3642 ✨ Mocks
  .github/bin/constants.sh
  CHANGES.md
  CONTRIBUTING.md
  Docs/docfx.json
  Libplanet.Action.Tests/ActionContextTest.cs
  Libplanet.Action.Tests/ActionEvaluationTest.cs
  Libplanet.Action.Tests/Libplanet.Action.Tests.csproj
  Libplanet.Action.Tests/Mocks/MockAccountState.cs
  Libplanet.Action.Tests/Mocks/MockWorldState.cs
  Libplanet.Action.Tests/Sys/InitializeTest.cs
  Libplanet.Action/AssemblyInfo.cs
  Libplanet.Explorer.Tests/Libplanet.Explorer.Tests.csproj
  Libplanet.Explorer.Tests/Queries/StateQueryTest.Legacy.cs
  Libplanet.Explorer.Tests/Queries/StateQueryTest.Mocks.cs
  Libplanet.Explorer.Tests/Queries/StateQueryTest.cs
  Libplanet.Mocks/Libplanet.Mocks.csproj
  Libplanet.Mocks/MockUtil.cs
  Libplanet.Mocks/MockWorldState.cs
  Libplanet.Tests/Action/AccountTest.cs
  Libplanet.Tests/Action/WorldTest.cs
  Libplanet.Tests/Blockchain/Renderers/AnonymousActionRendererTest.cs
  Libplanet.Tests/Blockchain/Renderers/LoggedActionRendererTest.cs
  Libplanet.Tests/Libplanet.Tests.csproj
  Libplanet.sln
Labels: Extra Large

#3707 🚀 Release 4.2.0
  CHANGES.md
Labels: Extra Small

#3708 🔧 Prepare 4.3.0
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: Extra Small

#3700 Introduce `ConsensusCryptoBackend`, `Proof`, `Lot`
  CHANGES.md
  Libplanet.Crypto/CryptoConfig.cs
  Libplanet.Crypto/DefaultConsensusCryptoBackend.cs
  Libplanet.Crypto/IConsensusCryptoBackend.cs
  Libplanet.Crypto/InvalidProofException.cs
  Libplanet.Crypto/PrivateKey.cs
  Libplanet.Crypto/Proof.cs
  Libplanet.Crypto/PublicKey.cs
  Libplanet.Tests/Consensus/LotMetadataTest.cs
  Libplanet.Tests/Consensus/LotTest.cs
  Libplanet.Tests/Crypto/PrivateKeyTest.cs
  Libplanet.Tests/Crypto/ProofTest.cs
  Libplanet.Tests/Crypto/PublicKeyTest.cs
  Libplanet.Types/Consensus/ILot.cs
  Libplanet.Types/Consensus/ILotMetadata.cs
  Libplanet.Types/Consensus/Lot.cs
  Libplanet.Types/Consensus/LotMetadata.cs
Labels: Extra Large

#3711 🔧 Prepare 4.2.1
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: Extra Small

#3710 chore: fix typos
  changes/v0.md
  changes/v2.md
Labels: Extra Small, no changelog

#3701 Introduce Begin / End block action
  CHANGES.md
  Libplanet.Action.Tests/Common/UpdateValueAction.cs
  Libplanet.Action/ActionEvaluator.cs
  Libplanet.Action/PolicyBlockActionGetter.cs
  Libplanet.Action/PolicyBlockActionsGetter.cs
  Libplanet.Benchmarks/AppendBlock.cs
  Libplanet.Benchmarks/BlockChain.cs
  Libplanet.Benchmarks/ProposeBlock.cs
  Libplanet.Explorer.Executable/Program.cs
  Libplanet.Explorer.Tests/GeneratedBlockChainFixture.cs
  Libplanet.Extensions.Cocona.Tests/BlockPolicyParamsTest.cs
  Libplanet.Extensions.Cocona/BlockPolicyParams.cs
  Libplanet.Extensions.Cocona/Commands/BlockCommand.cs
  Libplanet.Net.Tests/Consensus/ConsensusReactorTest.cs
  Libplanet.Net.Tests/Consensus/ContextNonProposerTest.cs
  Libplanet.Net.Tests/Consensus/ContextTest.cs
  Libplanet.Net.Tests/Consensus/HeightVoteSetTest.cs
  Libplanet.Net.Tests/SwarmTest.Broadcast.cs
  Libplanet.Net.Tests/SwarmTest.Fixtures.cs
  Libplanet.Net.Tests/SwarmTest.Preload.cs
  Libplanet.Net.Tests/SwarmTest.cs
  Libplanet.Net.Tests/TestUtils.cs
  Libplanet.RocksDBStore.Tests/RocksDBStoreBlockChainTest.cs
  Libplanet.RocksDBStore.Tests/RocksDBStoreFixture.cs
  Libplanet.RocksDBStore.Tests/RocksDBStoreTest.cs
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
  Libplanet.Tests/Blockchain/BlockChainTest.Append.cs
  Libplanet.Tests/Blockchain/BlockChainTest.ProposeBlock.cs
  Libplanet.Tests/Blockchain/BlockChainTest.ValidateNextBlock.cs
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet.Tests/Blockchain/DefaultStoreBlockChainTest.cs
  Libplanet.Tests/Blockchain/Policies/BlockPolicyTest.cs
  Libplanet.Tests/Blockchain/Policies/StagePolicyTest.cs
  Libplanet.Tests/Blocks/PreEvaluationBlockTest.cs
  Libplanet.Tests/Fixtures/IntegerSet.cs
  Libplanet.Tests/Store/DefaultStoreFixture.cs
  Libplanet.Tests/Store/MemoryStoreFixture.cs
  Libplanet.Tests/Store/StoreFixture.cs
  Libplanet.Tests/Store/StoreTest.cs
  Libplanet.Tests/TestUtils.cs
  Libplanet/Blockchain/BlockChain.Evaluate.cs
  Libplanet/Blockchain/Policies/BlockPolicy.cs
  Libplanet/Blockchain/Policies/IBlockPolicy.cs
  Libplanet/Blockchain/Policies/NullBlockPolicy.cs
Labels: Extra Large

#3713 ✨ ♻️ Added `Txs` property to `IActionContext`
  CHANGES.md
  Libplanet.Action/ActionContext.cs
  Libplanet.Action/ActionEvaluator.cs
  Libplanet.Action/IActionContext.cs
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
Labels: Small

#3714 🧹 Removed `TotalUpdatedFungibleAssets` from `IWorld`
  CHANGES.md
  Libplanet.Action/ActionEvaluator.cs
  Libplanet.Action/State/IWorld.cs
  Libplanet.Action/State/World.cs
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
  Libplanet.Tests/Action/WorldV1Test.cs
Labels: Medium

#3715 ♻️ 🚚 Moved `Currency` and `Validator` related methods from `IWorldState` and `IWorld` to an extension `class`
  CHANGES.md
  Libplanet.Action/ActionEvaluator.cs
  Libplanet.Action/State/IWorld.cs
  Libplanet.Action/State/IWorldExtensions.cs
  Libplanet.Action/State/IWorldState.cs
  Libplanet.Action/State/World.cs
  Libplanet.Action/State/WorldBaseState.cs
  Libplanet.Mocks/MockWorldState.cs
Labels: Extra Large

#3716 🧹 Cleanup `DumbAction`
  Libplanet.Action.Tests/Common/DumbAction.cs
  Libplanet.Action.Tests/Common/DumbModernAction.cs
  Libplanet.Net.Tests/SwarmTest.Fixtures.cs
  Libplanet.Tests/Blockchain/BlockChainTest.cs
Labels: no changelog

#3717 🧹 Minor cleanup
  Libplanet.Action.Tests/Common/DumbAction.cs
  Libplanet.Action.Tests/Common/DumbModernAction.cs
Labels: Extra Small, no changelog
