Repository planetarium/libplanet, pull requests merged in 2024-04, with the labels that each got.

#3718 ♻️ Overhaul `DumbAction`
  Libplanet.Action.Tests/ActionEvaluationTest.cs
  Libplanet.Action.Tests/Common/DumbAction.cs
  Libplanet.Action.Tests/Common/DumbModernAction.cs
  Libplanet.Action.Tests/Loader/IndexedActionLoaderTest.cs
  Libplanet.Action.Tests/Sys/RegistryTest.cs
  Libplanet.Benchmarks/AppendBlock.cs
  Libplanet.Benchmarks/ProposeBlock.cs
  Libplanet.Net.Tests/SwarmTest.Broadcast.cs
  Libplanet.Net.Tests/SwarmTest.Fixtures.cs
  Libplanet.Net.Tests/SwarmTest.Preload.cs
  Libplanet.Net.Tests/SwarmTest.cs
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
  Libplanet.Tests/Action/WorldTest.cs
  Libplanet.Tests/Action/WorldV0Test.cs
  Libplanet.Tests/Action/WorldV1Test.cs
  Libplanet.Tests/Blockchain/BlockChainTest.Append.cs
  Libplanet.Tests/Blockchain/BlockChainTest.ProposeBlock.cs
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet.Tests/Tx/TransactionExtensionsTest.cs
  Libplanet.Tests/Tx/TransactionTest.cs
  Libplanet.Tests/Tx/TxActionListTest.cs
  Libplanet.Tests/Tx/TxInvoiceTest.cs
  Libplanet.Tests/Tx/UnsignedTxTest.cs
Labels: no changelog

#3719 ♻️ Changed `AssertBytesEqual()` overloads and use more hex representation
  Libplanet.Net.Tests/Protocols/RoutingTableTest.cs
  Libplanet.Tests/Blocks/BlockTest.cs
  Libplanet.Tests/Crypto/PublicKeyTest.cs
  Libplanet.Tests/TestUtils.cs
  Libplanet.Tests/Tx/TransactionTest.cs
  Libplanet.Tests/Tx/TxMarshalerTest.cs
Labels: no changelog

#3720 ♻️ Refactor `DumbAction`
  Libplanet.Action.Tests/ActionEvaluationTest.cs
  Libplanet.Action.Tests/Common/DumbAction.cs
  Libplanet.Action.Tests/Common/DumbModernAction.cs
  Libplanet.Net.Tests/SwarmTest.Fixtures.cs
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
  Libplanet.Tests/Blockchain/BlockChainTest.Append.cs
  Libplanet.Tests/Blockchain/BlockChainTest.ProposeBlock.cs
  Libplanet.Tests/Blockchain/BlockChainTest.Stage.cs
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet.Tests/TestUtils.cs
  Libplanet.Tests/Tx/TransactionTest.cs
  Libplanet.Tests/Tx/TxActionListTest.cs
  Libplanet.Tests/Tx/TxInvoiceTest.cs
  Libplanet.Tests/Tx/UnsignedTxTest.cs
Labels: Large, no changelog

#3721 ♻️ Add mint and burn functionality to `DumbAction`
  Libplanet.Action.Tests/ActionEvaluationTest.cs
  Libplanet.Action.Tests/Common/DumbAction.cs
  Libplanet.Action.Tests/Common/DumbModernAction.cs
  Libplanet.Action.Tests/Loader/IndexedActionLoaderTest.cs
  Libplanet.Action.Tests/Sys/RegistryTest.cs
  Libplanet.Benchmarks/AppendBlock.cs
  Libplanet.Benchmarks/ProposeBlock.cs
  Libplanet.Net.Tests/SwarmTest.Broadcast.cs
  Libplanet.Net.Tests/SwarmTest.Fixtures.cs
  Libplanet.Net.Tests/SwarmTest.Preload.cs
  Libplanet.Net.Tests/SwarmTest.cs
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
  Libplanet.Tests/Action/WorldTest.cs
  Libplanet.Tests/Action/WorldV0Test.cs
  Libplanet.Tests/Action/WorldV1Test.cs
  Libplanet.Tests/Blockchain/BlockChainTest.Append.cs
  Libplanet.Tests/Blockchain/BlockChainTest.ProposeBlock.cs
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet.Tests/Tx/TransactionExtensionsTest.cs
  Libplanet.Tests/Tx/TransactionTest.cs
  Libplanet.Tests/Tx/TxActionListTest.cs
  Libplanet.Tests/Tx/TxInvoiceTest.cs
  Libplanet.Tests/Tx/UnsignedTxTest.cs
Labels: no changelog

#3722 ♻️ Changed `RandomAction` to `ContextRecordingAction`
  Libplanet.Action.Tests/Common/ContextRecordingAction.cs
  Libplanet.Action.Tests/Common/RandomAction.cs
  Libplanet.Action.Tests/Loader/IndexedActionLoaderTest.cs
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
  Libplanet.Tests/Blocks/BlockTest.cs
Labels: Medium, no changelog

#3723 🧹 Removed RecordRandom from DumbAction
  Libplanet.Action.Tests/Common/DumbAction.cs
  Libplanet.Action.Tests/Common/DumbModernAction.cs
Labels: Extra Small, no changelog

#3724 🧹 More descriptive currency ticker and documentation for easier testing
  Libplanet.Action.Tests/Common/DumbAction.cs
  Libplanet.Action.Tests/Common/DumbModernAction.cs
  Libplanet.Tests/Action/WorldTest.cs
  Libplanet.Tests/Action/WorldV1Test.cs
Labels: Extra Small, no changelog

#3726 ♻️ Shared `Currencies` for testing
  Libplanet.Action.Tests/Common/Currencies.cs
  Libplanet.Tests/Action/WorldTest.cs
Labels: Medium, no changelog

#3727 🩹 Added missing information in Exception
  Libplanet/Blockchain/BlockChain.cs
Labels: no changelog

#3728 ♻️ Removed negative balance feature
  CHANGES.md
  Libplanet.Action.Tests/Common/DumbAction.cs
  Libplanet.Action.Tests/Common/DumbModernAction.cs
  Libplanet.Action/State/IWorldExtensions.cs
  Libplanet.Net.Tests/SwarmTest.Preload.cs
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
  Libplanet.Tests/Action/WorldTest.cs
  Libplanet.Tests/Action/WorldV0Test.cs
  Libplanet.Tests/Action/WorldV1Test.cs
  Libplanet.Tests/Blockchain/BlockChainTest.Append.cs
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet.Tests/TestUtils.cs
Labels: Large

#3730 Introduce `IAccount.SetValidatorSet()` method
  CHANGES.md
  Libplanet.Action/State/Account.cs
  Libplanet.Action/State/IAccount.cs
  Libplanet.Tests/Action/AccountTest.cs
Labels: Extra Small

#3729 ⬆️ Bump Litedb to 5.0.15
  CHANGES.md
  Libplanet.Explorer.Executable/Program.cs
  Libplanet.Store/DefaultStore.cs
  Libplanet.Store/Libplanet.Store.csproj
Labels: Small

#3732 🚀 Release 4.3.0
  CHANGES.md
Labels: Extra Small

#3733 🔧 Prepare 4.4.0
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: Extra Small

#3734 🔧 Prepare 4.3.1
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: Extra Small

#3736 ♻️ Changed constant reference block protocol versions
  CHANGES.md
  Libplanet.Action/ActionEvaluator.cs
  Libplanet.Store/BlockSet.cs
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
  Libplanet.Tests/Blockchain/BlockChainTest.Append.cs
  Libplanet.Tests/Blocks/PreEvaluationBlockHeaderTest.cs
  Libplanet.Tests/TestUtils.cs
  Libplanet.Types/Blocks/BlockHeader.cs
  Libplanet.Types/Blocks/BlockMetadata.cs
  Libplanet.Types/Blocks/PreEvaluationBlockHeader.cs
  Libplanet/Blockchain/BlockChain.Validate.cs
  Libplanet/Blockchain/BlockChain.cs
Labels: Extra Small

#3738 ♻️ Refactor `TrieMetadata`
  CHANGES.md
  Libplanet.Store/Trie/TrieMetadata.cs
  Libplanet.Tests/Store/Trie/TrieMetadataTest.cs
Labels: Extra Small

#3740 🧹 Fixed changelog typo
  CHANGES.md
Labels: Extra Small

#3739 ♻️ Added `Version` property to `IWorldState`
  CHANGES.md
  Libplanet.Action/State/IWorldState.cs
  Libplanet.Action/State/World.cs
  Libplanet.Action/State/WorldBaseState.cs
  Libplanet.Mocks/MockWorldState.cs
Labels: Extra Small

#3743 ♻️ Refactor `IWorld` tests
  Libplanet.Tests/Action/WorldTest.cs
  Libplanet.Tests/Action/WorldV0Test.cs
  Libplanet.Tests/Action/WorldV1Test.cs
  Libplanet.Tests/Action/WorldV5Test.cs
Labels: no changelog

#3737 Implement Vote Power
  CHANGES.md
  Libplanet.Action.Tests/ActionContextTest.cs
  Libplanet.Action.Tests/ActionEvaluationTest.cs
  Libplanet.Action.Tests/Sys/InitializeTest.cs
  Libplanet.Benchmarks/Commit.cs
  Libplanet.Explorer.Tests/GeneratedBlockChainFixture.cs
  Libplanet.Explorer.Tests/GraphTypes/BlockCommitTypeTest.cs
  Libplanet.Explorer.Tests/GraphTypes/BlockTypeTest.cs
  Libplanet.Explorer.Tests/GraphTypes/VoteTypeTest.cs
  Libplanet.Explorer.Tests/Indexing/BlockChainIndexTest.cs
  Libplanet.Explorer/GraphTypes/VoteType.cs
  Libplanet.Net.Tests/Consensus/ConsensusContextNonProposerTest.cs
  Libplanet.Net.Tests/Consensus/ConsensusContextProposerTest.cs
  Libplanet.Net.Tests/Consensus/ConsensusContextTest.cs
  Libplanet.Net.Tests/Consensus/ContextNonProposerTest.cs
  Libplanet.Net.Tests/Consensus/ContextProposerTest.cs
  Libplanet.Net.Tests/Consensus/ContextProposerValidRoundTest.cs
  Libplanet.Net.Tests/Consensus/ContextTest.cs
  Libplanet.Net.Tests/Consensus/GossipConsensusMessageCommunicatorTest.cs
  Libplanet.Net.Tests/Consensus/HeightVoteSetTest.cs
  Libplanet.Net.Tests/Consensus/VoteSetTest.cs
  Libplanet.Net.Tests/Messages/MessageTest.cs
  Libplanet.Net.Tests/Messages/NetMQMessageCodecTest.cs
  Libplanet.Net.Tests/SwarmTest.Preload.cs
  Libplanet.Net.Tests/SwarmTest.cs
  Libplanet.Net.Tests/TestUtils.cs
  Libplanet.Net/Consensus/Context.cs
  Libplanet.Net/Consensus/HeightVoteSet.cs
  Libplanet.Net/Consensus/VoteSet.cs
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
  Libplanet.Tests/Blockchain/BlockChainTest.ProposeBlock.cs
  Libplanet.Tests/Blockchain/BlockChainTest.ValidateNextBlock.cs
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet.Tests/Blocks/BlockCommitTest.cs
  Libplanet.Tests/Blocks/BlockFixture.cs
  Libplanet.Tests/Blocks/BlockMetadataTest.cs
  Libplanet.Tests/Blocks/BlockTest.cs
  Libplanet.Tests/Consensus/ValidatorSetTest.cs
  Libplanet.Tests/Consensus/VoteMetadataTest.cs
  Libplanet.Tests/Consensus/VoteTest.cs
  Libplanet.Tests/Store/StoreFixture.cs
  Libplanet.Tests/Store/StoreTest.cs
  Libplanet.Tests/TestUtils.cs
  Libplanet.Types/Blocks/BlockCommit.cs
  Libplanet.Types/Blocks/PreEvaluationBlockHeader.cs
  Libplanet.Types/Consensus/IVoteMetadata.cs
  Libplanet.Types/Consensus/ValidatorSet.cs
  Libplanet.Types/Consensus/Vote.cs
  Libplanet.Types/Consensus/VoteMetadata.cs
Labels: Extra Large
