Repository planetarium/libplanet, pull requests merged in 2024-10, with the labels that each got.

#3957 fix: add zero padding to version timestamp
  scripts/determine-version.js
Labels: Squash Needed, no changelog

#3961 🔧 fix: use `Assert` instead of exception
  test/Libplanet.Net.Tests/SwarmTest.Evidence.cs
Labels: no changelog

#3972 Update ProposeGenesis in TestUtils to remove redundant Initialize()
  test/Libplanet.Net.Tests/Messages/MessageTest.cs
  test/Libplanet.Tests/Action/ActionEvaluatorTest.cs
  test/Libplanet.Tests/TestUtils.cs
Labels: hacktoberfest, no changelog

#3976 Raise exception on libplanet for zero byte prive key
  src/Libplanet.Crypto/PrivateKey.cs
  test/Libplanet.Tests/Crypto/PrivateKeyTest.cs
Labels: hacktoberfest, no changelog
