Repository planetarium/libplanet, pull requests merged in 2024-01, with the labels that each got.

#3576 ✨ Add `Trie.Remove()`
  CHANGES.md
  Libplanet.Store/Trie/ITrie.cs
  Libplanet.Store/Trie/MerkleTrie.Remove.cs
  Libplanet.Store/Trie/MerkleTrie.cs
  Libplanet.Store/Trie/Nodes/FullNode.cs
  Libplanet.Tests/Store/Trie/MerkleTrieTest.cs
Labels: Large

#3577 ✨ Add `IAccount.RemoveState()`
  CHANGES.md
  Libplanet.Action/State/Account.cs
  Libplanet.Action/State/IAccount.cs
  Libplanet.Explorer.Tests/Queries/StateQueryTest.cs
  Libplanet.Tests/Action/AccountTest.cs
Labels: Extra Small

#3579 ♻️ ⏪ Revert changes for old queries
  CHANGES.md
  Libplanet.Explorer.Tests/Queries/StateQueryTest.cs
  Libplanet.Explorer/GraphTypes/LegacyBencodexValueType.cs
  Libplanet.Explorer/Queries/StateQuery.cs
Labels: Small

#3570 ✨ New state querying scheme
  CHANGES.md
  Libplanet.Explorer.Tests/Queries/StateQueryTest.cs
  Libplanet.Explorer/GraphTypes/AccountStateType.cs
  Libplanet.Explorer/Queries/StateQuery.cs
Labels: Extra Large

#3584 🚀 Release 3.9.3
  CHANGES.md
Labels: Extra Small

#3585 🔧 Prepare 3.9.4
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: Extra Small

#3583 Refactor `IBlockChainStates` interface
  CHANGES.md
  Libplanet.Action/State/IBlockChainStates.cs
  Libplanet.Explorer.Tests/Queries/StateQueryTest.cs
  Libplanet.Tests/Action/AccountTest.cs
  Libplanet.Tests/Action/AccountV0Test.cs
  Libplanet.Tests/Action/AccountV1Test.cs
  Libplanet/Blockchain/BlockChain.States.cs
  Libplanet/Blockchain/BlockChainStates.cs
Labels: api, Medium

#3587 🔀 Merge 3.9.2 to main
  CHANGES.md
  Libplanet.Action/ActionEvaluator.cs
  Libplanet.RocksDBStore/RocksDBKeyValueStore.cs
Labels: Extra Small

#3581 ci(gh-actions): bump tj-actions/changed-files action
  .github/workflows/yarn.yaml
Labels: ci & cd, Extra Small

#3590 🧹 Leaner `IBlockChainStates`
  CHANGES.md
  Libplanet.Action/State/IBlockChainStates.cs
  Libplanet.Explorer.Tests/Queries/StateQueryTest.Mocks.cs
  Libplanet/Blockchain/BlockChain.States.cs
  Libplanet/Blockchain/BlockChainStates.cs
Labels: Small

#3586 Fix GossipConsensusMessageCommunicator
  Libplanet.Net.Tests/Consensus/GossipConsensusMessageCommunicatorTest.cs
  Libplanet.Net/Consensus/GossipConsensusMessageCommunicator.cs
Labels: Small

#3591 🧹 Remove direct access to lower level data in `IBlockChainStates`
  Libplanet.Action/State/IBlockChainStates.cs
  Libplanet.Net.Tests/Consensus/ContextTest.cs
  Libplanet.Net.Tests/TestUtils.cs
  Libplanet.Net/Consensus/ConsensusContext.cs
  Libplanet.Tests/Action/AccountTest.cs
  Libplanet.Tests/Action/AccountV0Test.cs
  Libplanet.Tests/Action/AccountV1Test.cs
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet/Blockchain/BlockChain.States.cs
  Libplanet/Blockchain/BlockChain.Validate.cs
  Libplanet/Blockchain/BlockChainStates.cs
Labels: Medium

#3593 🧹 Clutter removal
  Libplanet.Action/State/WorldBaseState.cs
Labels: Extra Small

#3599 🧹 Updated changelog
  CHANGES.md
Labels: Extra Small

#3598 ♻️ Refactor `IWorldState` to be read-only
  Libplanet.Action.Tests/Mocks/MockWorldState.cs
  Libplanet.Action/State/AccountState.cs
  Libplanet.Action/State/IAccountState.cs
  Libplanet.Action/State/IWorld.cs
  Libplanet.Action/State/IWorldState.cs
  Libplanet.Action/State/World.cs
  Libplanet.Action/State/WorldBaseState.cs
  Libplanet.Action/State/WorldExtensions.cs
  Libplanet.Explorer.Tests/Queries/StateQueryTest.Mocks.cs
  Libplanet.Explorer/GraphTypes/WorldStateType.cs
  Libplanet.Explorer/Queries/StateQuery.cs
  Libplanet.Net.Tests/Consensus/ContextTest.cs
  Libplanet.Net.Tests/SwarmTest.Preload.cs
  Libplanet.Net.Tests/SwarmTest.cs
  Libplanet.Net.Tests/TestUtils.cs
  Libplanet.Net/Consensus/ConsensusContext.cs
  Libplanet.Tests/Action/AccountTest.cs
  Libplanet.Tests/Action/AccountV0Test.cs
  Libplanet.Tests/Action/AccountV1Test.cs
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
  Libplanet.Tests/Blockchain/BlockChainTest.Append.cs
  Libplanet.Tests/Blockchain/BlockChainTest.ProposeBlock.cs
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet.Tests/Blocks/PreEvaluationBlockTest.cs
  Libplanet.Tests/Fixtures/IntegerSet.cs
  Libplanet/Blockchain/BlockChain.Validate.cs
Labels: Extra Large

#3600 ⏪ Roll back some internal name changes
  CHANGES.md
  Libplanet.Explorer/GraphTypes/AccountStateType.cs
  Libplanet.Explorer/GraphTypes/ActionType.cs
  Libplanet.Explorer/GraphTypes/AddressType.cs
  Libplanet.Explorer/GraphTypes/BencodexValueType.cs
  Libplanet.Explorer/GraphTypes/BlockHashType.cs
  Libplanet.Explorer/GraphTypes/BlockType.cs
  Libplanet.Explorer/GraphTypes/BoundPeerType.cs
  Libplanet.Explorer/GraphTypes/IValueType.cs
  Libplanet.Explorer/GraphTypes/LegacyBencodexValueType.cs
  Libplanet.Explorer/GraphTypes/NodeStateType.cs
  Libplanet.Explorer/GraphTypes/PublicKeyType.cs
  Libplanet.Explorer/GraphTypes/TransactionType.cs
  Libplanet.Explorer/GraphTypes/TxIdType.cs
  Libplanet.Explorer/GraphTypes/TxResultType.cs
  Libplanet.Explorer/GraphTypes/ValidatorType.cs
  Libplanet.Explorer/Queries/HelperQuery.cs
  Libplanet.Explorer/Queries/StateQuery.cs
Labels: Medium

#3601 🚀 Release 3.9.4
  CHANGES.md
Labels: Extra Small

#3602 🔧 Prepare 3.9.5
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: Extra Small

#3604 🔀 Merge 3.9.4 to main
  CHANGES.md
  Libplanet.Explorer/GraphTypes/AccountStateType.cs
  Libplanet.Explorer/GraphTypes/ActionType.cs
  Libplanet.Explorer/GraphTypes/AddressType.cs
  Libplanet.Explorer/GraphTypes/BencodexValueType.cs
  Libplanet.Explorer/GraphTypes/BlockHashType.cs
  Libplanet.Explorer/GraphTypes/BlockType.cs
  Libplanet.Explorer/GraphTypes/BoundPeerType.cs
  Libplanet.Explorer/GraphTypes/IValueType.cs
  Libplanet.Explorer/GraphTypes/LegacyBencodexValueType.cs
  Libplanet.Explorer/GraphTypes/NodeStateType.cs
  Libplanet.Explorer/GraphTypes/PublicKeyType.cs
  Libplanet.Explorer/GraphTypes/TransactionType.cs
  Libplanet.Explorer/GraphTypes/TxIdType.cs
  Libplanet.Explorer/GraphTypes/TxResultType.cs
  Libplanet.Explorer/GraphTypes/ValidatorType.cs
  Libplanet.Explorer/Queries/HelperQuery.cs
  Libplanet.Explorer/Queries/StateQuery.cs
Labels: Medium

#3605 🧹 Minor cleanup for `IWorldState`
  Libplanet.Action/ActionEvaluator.cs
  Libplanet.Action/State/World.cs
Labels: Extra Small

#3606 🧹 Removed unnecessary code
  Libplanet.Action/State/World.cs
  Libplanet.Action/State/WorldBaseState.cs
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
Labels: Extra Small

#3609 ⏪ Revert changes to `IActionEvaluator` interface
  CHANGES.md
  Libplanet.Action/ActionEvaluator.cs
  Libplanet.Action/IActionEvaluator.cs
  Libplanet.Tests/Action/ActionEvaluatorTest.cs
  Libplanet.Tests/Blockchain/BlockChainTest.Append.cs
  Libplanet/Blockchain/BlockChain.Evaluate.cs
  Libplanet/Blockchain/BlockChain.Swap.cs
Labels: Medium

#3610 🐛 Fixed `IStateStore.Commit()`
  CHANGES.md
  Libplanet.Store/IStateStore.cs
  Libplanet.Store/Trie/MerkleTrie.Diff.cs
  Libplanet.Store/Trie/MerkleTrie.Insert.cs
  Libplanet.Store/TrieStateStore.Commit.cs
  Libplanet.Tests/Store/TrieStateStoreCommitTest.cs
Labels: Extra Small

#3614 ♻️ 🧹 Removed `IStateStore.PruneStates()`
  CHANGES.md
  Libplanet.Explorer.Executable/Program.cs
  Libplanet.Store/IStateStore.cs
  Libplanet.Store/TrieStateStore.cs
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet.Tests/Store/StateStoreTracker.cs
  Libplanet.Tests/Store/TrieStateStoreTest.cs
Labels: Small

#3615 🚀 Release 3.9.5
  CHANGES.md
Labels: Extra Small

#3617 🔀 Merge 3.9.5 to main
  CHANGES.md
  Libplanet.Explorer.Executable/Program.cs
  Libplanet.Store/IStateStore.cs
  Libplanet.Store/Trie/MerkleTrie.Diff.cs
  Libplanet.Store/Trie/MerkleTrie.Insert.cs
  Libplanet.Store/Trie/MerkleTrie.cs
  Libplanet.Store/TrieStateStore.Commit.cs
  Libplanet.Store/TrieStateStore.cs
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet.Tests/Store/StateStoreTracker.cs
  Libplanet.Tests/Store/TrieStateStoreCommitTest.cs
  Libplanet.Tests/Store/TrieStateStoreTest.cs
Labels: Large

#3616 🔧 Prepare 3.9.6
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: Extra Small

#3618 🧹 Removed unnecessary extension method
  Libplanet.Store/Trie/TrieExtensions.cs
  Libplanet.Tests/Fixtures/IntegerSet.cs
Labels: Extra Small

#3619 ♻️ Refactor `TrieStateStore.CopyStates()`
  Libplanet.Store/TrieStateStore.cs
  Libplanet.Tests/Store/TrieStateStoreTest.cs
Labels: Small

#3624 ♻️ Move `TrieMetadata` to `Libplanet.Store`
  CHANGES.md
  Libplanet.Action/State/TrieMetadata.cs
  Libplanet.Store/Trie/TrieExtensions.cs
  Libplanet.Store/Trie/TrieMetadata.cs
  Libplanet.Tests/Store/TrieStateStoreTest.cs
Labels: Small

#3626 ♻️ 🧹 Removed `EnumerableExtensions`
  CHANGES.md
  Libplanet.Common/EnumerableExtensions.cs
  Libplanet.Net/Swarm.cs
Labels: Small

#3627 🚀 Release 4.0.0
  CHANGES.md
Labels: Extra Small

#3629 🔧 Prepare 4.1.0
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: Extra Small

#3628 🔧 Prepare 4.0.1
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: Extra Small

#3622 Remove the '#nullable disable' keyword from 3 projects(Action, Common, Explorer)
  Libplanet.Action/IAction.cs
  Libplanet.Action/IRandom.cs
  Libplanet.Action/RandomExtensions.cs
  Libplanet.Common/FixedSizedQueue.cs
  Libplanet.Common/Serialization/SerializationInfoExtensions.cs
  Libplanet.Explorer/GraphTypes/ActionType.cs
  Libplanet.Explorer/GraphTypes/ByteStringType.cs
  Libplanet.Explorer/GraphTypes/NodeStateType.cs
  Libplanet.Explorer/GraphTypes/VoteFlagType.cs
  Libplanet.Explorer/Interfaces/IBlockChainContext.cs
  Libplanet.Explorer/Queries/BlockQuery.cs
  Libplanet.Explorer/Queries/ExplorerQuery.cs
  Libplanet.Explorer/Queries/TransactionQuery.cs
Labels: Small

#3633 ♻️ More strict `IWorld.SetAccount()` behavior
  CHANGES.md
  Libplanet.Action/State/AccountState.cs
  Libplanet.Action/State/IWorld.cs
  Libplanet.Action/State/World.cs
  Libplanet.Action/State/WorldDelta.cs
  Libplanet.Tests/Action/AccountTest.cs
Labels: Extra Small

#3634 ⚡ Optimize `TrieStateStore.CopyStates()`
  CHANGES.md
  Libplanet.Store/Trie/MerkleTrie.cs
Labels: Extra Small

#3635 🚀 Release 3.9.6
  CHANGES.md
Labels: Extra Small

#3636 🔧 Prepare 3.9.7
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: Extra Small

#3637 🔀 Merge 3.9.6 to 4.0-maintenance
  CHANGES.md
  Libplanet.Store/Trie/MerkleTrie.cs
Labels: Extra Small

#3638 🧹 Fix changelog
  CHANGES.md
Labels: Extra Small

#3639 🚀 Release 4.0.1
  CHANGES.md
Labels: Extra Small

#3641 🔀 Merge 4.0.1 to main
  CHANGES.md
  Libplanet.Action/State/AccountState.cs
  Libplanet.Action/State/IWorld.cs
  Libplanet.Action/State/World.cs
  Libplanet.Action/State/WorldDelta.cs
  Libplanet.Store/Trie/MerkleTrie.cs
  Libplanet.Tests/Action/AccountTest.cs
Labels: Small

#3640 🔧 Prepare 4.0.2
  CHANGES.md
  Libplanet/Libplanet.csproj
Labels: Extra Small

#3643 🧹 Remove unnecessary test code
  Libplanet.Tests/Blockchain/BlockChainTest.Stage.cs
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet.Tests/Store/StoreFixture.cs
Labels: Extra Small
