Repository planetarium/libplanet, pull requests merged in 2024-06, with the labels that each got.

#3809 chore: fix some comments
  Docs/articles/overview.md
  Libplanet.Mocks/MockWorldState.cs
Labels: no changelog

#3820 ✏️ Fixed version prefix
  Libplanet/Libplanet.csproj
Labels: no changelog

#3823 👷 Changed to more elaborate version matching
  Libplanet.Tools/bin/npm-test.sh
Labels: no changelog

#3822 📝 Added some clarifications
  Libplanet.Net/Consensus/ConsensusContext.cs
Labels: no changelog

#3831 Fix ci installation test error
  Libplanet.Tools/bin/npm-test.ps1
Labels: good first issue, no changelog

#3832 Remove duplicated NSRH generation on BlockChain.Create()
  Libplanet/Blockchain/BlockChain.cs
Labels: no changelog

#3835 🧹 Minor cleanup for #3832
  Libplanet/Blockchain/BlockChain.cs
Labels: no changelog

#3836 ✨ ci: introduce ai-code-reviewer
  .github/workflows/ai-code-reviewer.yaml
Labels: ci & cd, no changelog

#3838 fix: use pull_request_target
  .github/workflows/ai-code-reviewer.yaml
Labels: no changelog

#3834 ♻️ Stricter `Swap()` condition
  Libplanet.Net.Tests/SwarmTest.Preload.cs
  Libplanet.Net/Swarm.BlockCandidate.cs
  Libplanet.Tests/Blockchain/BlockChainTest.cs
  Libplanet/Blockchain/BlockChain.Swap.cs
Labels: no changelog

#3840 🔧 Fixed `BlockChain.EvaluateBlock()`
  Libplanet/Blockchain/BlockChain.Evaluate.cs
Labels: no changelog

#3827 Use `buffer` dependency for browser environment
  @planetarium/account/package.json
  @planetarium/account/src/Address.ts
  @planetarium/account/src/PublicKey.ts
  @planetarium/account/src/RawPrivateKey.ts
  yarn.lock
Labels: js, no changelog

#3847 Fix dist-nuget script running error
  .github/bin/dist-nuget.sh
Labels: no changelog

#3850 🔧 Added timeout to `async` tests
  test/Libplanet.Net.Tests/Consensus/ConsensusContextTest.cs
Labels: no changelog
