Repository planetarium/libplanet, pull requests merged in 2025-01, with the labels that each got.

#4018 typo fix ActionEvaluator.cs
  src/Libplanet.Action/ActionEvaluator.cs
Labels: no changelog

#4023 🚀 Release 5.5.0
  CHANGES.md
Labels: release

#4025 Update docs and workflows required for Libplanet.Node
  .github/bin/constants.sh
  CONTRIBUTING.md
  hooks/check-projects
  sdk/node/Libplanet.Node/README.md
Labels: docs, github_actions, no changelog

#4029 Node.Executable and Explorer.Executable from executables in constants.sh
  .github/bin/constants.sh
Labels: ci & cd, no changelog

#4021 chore: fix 404 status URL
  changes/v2.md
Labels: no changelog
